### ISSUE TITLE
AUTHORISED_CHATS and SUDO_USERS has no effect

### ISSUE THREAD

**Issue by NoobyProg** [anasty17/mirror-leech-telegram-bot#1004]
**Describe the bug**
Updating or adding new group or chat ids in either AUTHORISED_CHATS or SUDO_USERS does not work and does not give the chat or the user access to the bot when running in a docker container using docker-compose.

**To Reproduce**
1. Host and Build the Bot on a VPS using docker-compose
2. Edit the config.env file and add chat id to AUTHORISED_CHATS

**Expected behavior**
The chat and users should get access to using the bot

**Screenshots**
![Telegram Group](https://user-images.githubusercontent.com/54892329/187176923-81d78f1f-ae91-4155-8fa9-573f079d4d4a.png)
![config.env](https://user-images.githubusercontent.com/54892329/187176586-efb9ce87-fd29-4017-aad9-745c097aded7.png)

**Additional context**

**Comment by anasty17** [comment]
Use /users

**Comment by anasty17** [comment]
Maybe ur config.env not updated! What u r using to add config.env gists ? If yes then make sure u have removed the commit id from link
