### ISSUE TITLE
Add Colab Notebook support

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1007]
Hi,

İf you like the idea sir. Could you maybe consider to make the bot work on Google Colab? I Thank you for your great work btw.👍

The Storage is 70GB.

**Comment by hitesh920-1** [comment]
google colab is not for hosting stuff..

**Comment by erickyun** [comment]
I know but could it not bu used as a vps? 
Also if we considered the speed and storage it could be a good alternative for heroku.
