### ISSUE TITLE
Cant use commands for mega

### ISSUE THREAD

**Issue by soni0212** [anasty17/mirror-leech-telegram-bot#1008]
**Describe the bug**
Can't use any commands for mega links.. The progress gets stuck for indefinite period of time

**To Reproduce**
1. I followed all the steps from description and launched it via Heroku branch
2. ![image](https://user-images.githubusercontent.com/32086892/187230306-c9947dbc-e5ab-4e10-8091-787d92598648.png)
3. ![image](https://user-images.githubusercontent.com/32086892/187230508-25eac5ab-d426-4d1b-ab6b-64eb00503883.png)

**Expected behavior**
My other bot can mirror/leech mega links with no problem. I made it last year December but this one I made today.

**Comment by anasty17** [comment]
On heroku u should deploy heroku branch read readme!!
