### ISSUE TITLE
Auto cancel slow downloads?

### ISSUE THREAD

**Issue by MinorX** [anasty17/mirror-leech-telegram-bot#1009]
Hey Anas ,

Is there any way to automatically cancel slow torrents. For now only dead torrents can get cancelled but slow torrents are also an big issue. I've searched on Google and found 1 or 2 GitHub repo's related to this. I really don't know if I'm even right on this. 

For eg :- A torrent with download speed lower than 500 kb/s for more than 5 minutes would result in auto cancel. 

It would be great if you could add this. IF IT'S POSSIBLE.

THANKS , REGARDS.

**Comment by anasty17** [comment]
Just cancel it manually bruh! In qBittorrent u can enable Queueing and add edit slow speed threshold but it will lead to queue the download to start other download. And we can implement this in qBittorrent to stop download if speed is slow, but in aria2c it's more complicated. And all this not worth. But KNOW that i don't support groups features and U still asking for it!
