### ISSUE TITLE
Path of Download_Dir

### ISSUE THREAD

**Issue by ShangWangNUST** [anasty17/mirror-leech-telegram-bot#101]
Dear sir,

I have encountered two problems. First, I use the VPS of buyvm, so I have a 256G hard disk mounted with the path: /mount, and the installation path of my mirrorbot is: /root/mirrorbot.
**Problem 1: Mirrorbot can't recognize my mounted hard disk.** 
```
> Bot Uptime: 12h32m44s
> Total Disk Space: 9.78GB
> Used: 6.7GB |  Free: 2.56GB
> Upload: 3.18GB> Download: 3.94GB
> CPU: 0.0%> RAM: 63.1%> DISK: 72.4%
> Physical Cores: 1
> Total Cores: 1
> SWAP: 1024.0MB | Used: 21.3%
> memory total: 477.91mb 
> memory free: 176.46mb 
> memory used: 287.49mb 
```

**Problem  2:** 
I changed the download path download _ dir = "/usr/src/app/downloads"  to **download _ dir = "/mount/gdrive/downloads"**
I don't know if it can't be downloaded to the set folder because of the first question, and I can't find it in/usr/src/app/downloads.

In addition, thank you for developing this great tool!

**Comment by anasty17** [comment]
@ShangWangNUST First this not related to code ... or to bot  .... create ur vps well 
2nd u can't find files .... bcz in docker container... not in home files

**Comment by ShangWangNUST** [comment]
> @ShangWangNUST First this not related to code ... or to bot .... create ur vps well 2nd u can't find files .... bcz in docker container... not in home files

Understand. Thank you.

**Comment by erickyun** [comment]
> Dear sir,
> 
> I have encountered two problems. First, I use the VPS of buyvm, so I have a 256G hard disk mounted with the path: /mount, and the installation path of my mirrorbot is: /root/mirrorbot. **Problem 1: Mirrorbot can't recognize my mounted hard disk.**
> 
> ```
> > Bot Uptime: 12h32m44s
> > Total Disk Space: 9.78GB
> > Used: 6.7GB |  Free: 2.56GB
> > Upload: 3.18GB> Download: 3.94GB
> > CPU: 0.0%> RAM: 63.1%> DISK: 72.4%
> > Physical Cores: 1
> > Total Cores: 1
> > SWAP: 1024.0MB | Used: 21.3%
> > memory total: 477.91mb 
> > memory free: 176.46mb 
> > memory used: 287.49mb 
> ```
> 
> In addition, thank you for developing this great tool!

Hi, I'm having the same problem. Were you able to use your mounted disk? İf yes could you please tell me how?

**Comment by anasty17** [comment]
https://stackoverflow.com/questions/24309526/how-to-change-the-docker-image-installation-directory

**Comment by erickyun** [comment]
> https://stackoverflow.com/questions/24309526/how-to-change-the-docker-image-installation-directory

Thank you very much :) 👍
