### ISSUE TITLE
Error on large file clone Google Drive

### ISSUE THREAD

**Issue by a0v0** [anasty17/mirror-leech-telegram-bot#1013]
I am trying to clone a 2.1TB file to Shared Drive but am getting this error

```
 Error.
('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```

**Comment by anasty17** [comment]
Send full logs

**Comment by ketela7** [comment]
> I am trying to clone a 2.1TB file to Shared Drive but am getting this error
> 
> ```
>  Error.
> ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
> ```

target link to clone is not public, maybe

**Comment by anasty17** [comment]
Don't send logs like this. Send link for logs my browser hanged

**Comment by ketela7** [comment]
![Screenshot_2022-08-30-18-32-51-629_com android chrome](https://user-images.githubusercontent.com/103868701/187426443-d727da62-5a90-4a04-9bea-74a5265bab96.jpg)
this???

**Comment by anasty17** [comment]
Seems u have deleted the sa from project

**Comment by anasty17** [comment]
Use /log and upload the file!

**Comment by anasty17** [comment]
> [log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9457668/log.txt)

Ok i only see userRateLimitExceeded. What is the problem with that!
