### ISSUE TITLE
ytdlleech Issue

### ISSUE THREAD

**Issue by AsuranJ** [anasty17/mirror-leech-telegram-bot#1016]
Stream output not come ytdlleech

Using leechset as media.. But no stream output

**Comment by anasty17** [comment]
Logs and link to test!

**Comment by AsuranJ** [comment]
Sorry for that.. Some old zee5 links only send output of in document format.. Latest episode links working fine

**Comment by anasty17** [comment]
This shouldn't happen! Send link plz

**Comment by AsuranJ** [comment]
> This shouldn't happen! Send link plz

https://www.zee5.com/tv-shows/details/yaaradi-nee-mohini/0-6-338/yaaradi-nee-mohini/0-1-85250
