### ISSUE TITLE
Aria2 download never stops on listdir, when the download is complete

### ISSUE THREAD

**Issue by eyMarv** [anasty17/mirror-leech-telegram-bot#1017]
**Describe the bug**

**To Reproduce**
1. Download from any link with aria2
2. After the download, status is stuck on 100%
3. Check logs, to see the error,

**Expected behavior**
The file is getting uploaded.

**Additional context**
app_1  | bot - INFO - https://speed.hetzner.de/10GB.bin
app_1  | bot - INFO - onDownloadStarted: 10GB.bin - Gid: 41e0e22da91e6fb2
app_1  | bot - INFO - Aria2Download started: 41e0e22da91e6fb2
app_1  | bot - INFO - onDownloadComplete: 10GB.bin - Gid: 41e0e22da91e6fb2
app_1  | bot - INFO - Download completed: 10GB.bin
app_1  | Exception in thread Thread-11 (__onDownloadComplete):
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
app_1  |     self.run()
app_1  |   File "/usr/lib/python3.10/threading.py", line 946, in run
app_1  |     self._target(*self._args, **self._kwargs)
app_1  |   File "/usr/src/mcap/bot/helper/mirror_utils/download_utils/aria2_download.py", line 116, in __onDownloadComplete
app_1  |     dl.listener().onDownloadComplete()
app_1  |   File "/usr/src/mcap/bot/modules/listener.py", line 103, in onDownloadComplete
app_1  |     name = listdir(f"{self.dir}")[-1]
app_1  | FileNotFoundError: [Errno 2] No such file or directory: 'downloads/410'

**Comment by anasty17** [comment]
? Why deployed heroku branch on vps ?

**Comment by anasty17** [comment]
No such an issue btw. U edit in code!

**Comment by eyMarv** [comment]
> No such an issue btw. U edit in code!

No... is original.

**Comment by anasty17** [comment]
NOT MY DOCKER!!!

**Comment by anasty17** [comment]
Don't open issue again. Otherwise block
