### ISSUE TITLE
Deploy with workflow not working

### ISSUE THREAD

**Issue by Hossein-Habibi-2004** [anasty17/mirror-leech-telegram-bot#1029]
hey, today when I want to deploy the bot again, the workflow doesn't work.

it's given me below error:
![image](https://user-images.githubusercontent.com/68292834/188271887-efebf0b9-bab5-4597-a5b9-39a09fdb2f0d.png)

**Comment by anasty17** [comment]
Don't deploy again and again! Just deploy once or wait btw deploys Don't spam
