### ISSUE TITLE
Filename is different from caption name when file is splitted using leech module if more than 2gb: leech, zip

### ISSUE THREAD

**Issue by lokomartin** [anasty17/mirror-leech-telegram-bot#103]
Please make filename same as caption name or atleast theres an extension and part number on the filename because I had to rename every files downloaded when unzipping or combining files or else files corrupted and not joining. Thank you

![1](https://user-images.githubusercontent.com/94389621/144004994-baac2aa1-585f-4f94-9330-92f7a28facc0.JPG)

![2](https://user-images.githubusercontent.com/94389621/144005275-b5bf88cb-550f-4067-ab2d-550b83033b65.jpg)

**Comment by anasty17** [comment]
@lokomartin How caption related to combine !! And the only difference btw caption and filename is the extension... i peft the difference to know that the extension has been changed from the one in caption(original) to fake one ... this process only to make it Streamable on telegram... that's it

**Comment by anasty17** [comment]
@lokomartin U should combine the zip parts ... don't extract and combine!!!

**Comment by lokomartin** [comment]
I cannot combine the zip parts when downloaded. I had to rename the zip parts in order to combine please refer to 1st pic. there was no extension on the filename

**Comment by anasty17** [comment]
@lokomartin Are u sure this is my repo that your using ?

**Comment by anasty17** [comment]
@lokomartin Send link to test

**Comment by lokomartin** [comment]
yes your repo

https://archive.org/download/my.-husband.-my.-lover.-2021/My.Husband.My.Lover.2021.1080p.VMAX.WEB-DL.AAC2.0.H264-MSQ.mkv

**Comment by anasty17** [comment]
@lokomartin I will test, if there any problem i will fix as soon as possible

**Comment by anasty17** [comment]
@lokomartin Got it .. Telegram change dot to underscore... will try to fix this by adding _partxx instead of .partxx and for zip will try to find solution... thanks for reporting

**Comment by lokomartin** [comment]
oh. thank you
