### ISSUE TITLE
Link support possible

### ISSUE THREAD

**Issue by AsuranJ** [anasty17/mirror-leech-telegram-bot#1031]
https://abra--a2376523.api.frosty-night.buzz/0e5c3b69dc10390538a80406db1f36ecd1691abe/Fall%20(2022)%20%5B720p%5D%20%5BWEBRip%5D%20%5BYTS.MX%5D%2FFall.2022.720p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4~tc/Fall.2022.720p.WEBRip.x264.AAC-%5BYTS.MX%5D.mp4~mtrc/v0-480.m3u8?user-id=a3e93e7049d4e3c219b87526d94d7e01&download-id=00c61bc8aecb66711b40db05a32f7fd5&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudCI6Ik1vemlsbGEvNS4wIChMaW51eDsgQW5kcm9pZCAxMTsgUE9DTyBNMiBQcm8pIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS8xMDQuMC41MTEyLjk3IE1vYmlsZSBTYWZhcmkvNTM3LjM2IiwicmVtb3RlQWRkcmVzcyI6IjgzLjE0My4yNDUuMjMwIiwiZG9tYWluIjoieXRzLm14IiwiZXhwIjoxNjYyODM5MDIwLCJzZXNzaW9uSUQiOiJaMi05N0NUdTRhU1lnaDhhemhzVy14OUUwWUJFSnQ2RiIsInJhdGUiOiIxME0iLCJyb2xlIjoibm9ib2R5In0.XTu4FxfjR1VH-u9yFDF5VF0-RSGBgNu9uChDaq_aQCU&api-key=8acbcf1e-732c-4574-a3bf-27e6a85b86f1

This link not support to download.. It's shows file name  too long

**Comment by anasty17** [comment]
Use rename feature! /help and  read first line
