### ISSUE TITLE
Multiple Teamdrive Option for Mirroring and Cloning

### ISSUE THREAD

**Issue by vishansh** [anasty17/mirror-leech-telegram-bot#1033]
Can we have multiple teamdrive option like adding multiple ids and when mirroring and clone we can select diff ids /mirror id1, id2  magnet and /clone id1, id 2 link this can make bot for multiple use purpose personal drive work drive

**Comment by anasty17** [comment]
Okay

**Comment by vishansh** [comment]
Bro y u close the issue have you completed it or skipping it
