### ISSUE TITLE
Bot not responding

### ISSUE THREAD

**Issue by Not098** [anasty17/mirror-leech-telegram-bot#1034]
I didn't get any errors in bot log but bot is not responding

Please help me to fix this I deployed in workflow
![Screenshot_2022-09-04-18-06-07-129_com android chrome](https://user-images.githubusercontent.com/88423723/188314042-172d8d0e-06b8-4c34-8762-f7e3b17ff748.png)

**Comment by anasty17** [comment]
I can't know! But other deploying normally so it's not bug

**Comment by Not098** [comment]
Can you help me fix bot not responding
