### ISSUE TITLE
Organizing TV Shows

### ISSUE THREAD

**Issue by ciniexpress** [anasty17/mirror-leech-telegram-bot#1037]
Hello, 

I have a request is it possible to get the tv shows to be organized in a proper way.

Example: Lets take Game of thrones
it has 8 seasons and each season have 15 episodes min lets says,

 if we are using a rss feed from a torrent website can it move the files to their parent folder automatically when ever new episode is released.

Thanks

**Comment by anasty17** [comment]
This is not tv shows organisation bot! No u r going so far from bot purpose
