### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Jarvis991** [anasty17/mirror-leech-telegram-bot#1039]
Can you add option to

-  select Team Drive / folder in that drive before uploading

- Rclone encrypted remote upload instead of using credentials in addition to select which remote to upload like ex

1. Animation: (rclone remote for gdrive ex)
2. Edu : (rclone remote dropbox)
3. Encrypted Movies : (Rclone remote)
so before uploading it should ask which remote to upload using qbit or aira or mega ..

Like this
![image](https://user-images.githubusercontent.com/97823396/188330958-41df68e1-ebb9-4b86-88d7-531096a706aa.png)

Would be very useful
[SAMPLE](https://graph.org/file/84708c84e2dfb73da052e.mp4)

**Comment by anasty17** [comment]
Many users like me don't like to press too many buttons before download. So..
1. I will make default des_id, and with using prefix (t) then u can show up the buttons to select des_id. Also for user settings i check what i can do.
2. No need for rclone we can done almost everything from google api lib.

**Comment by Jarvis991** [comment]
Thanks

**Comment by Jarvis991** [comment]
> Many users like me don't like to press too many buttons before download. So..
> 
> 1. I will make default des_id, and with using prefix (t) then u can show up the buttons to select des_id. Also for user settings i check what i can do.
> 2. No need for rclone we can done almost everything from google api lib.

Thanks

**Comment by anasty17** [comment]
> > Many users like me don't like to press too many buttons before download. So..
> > 
> > 1. I will make default des_id, and with using prefix (t) then u can show up the buttons to select des_id. Also for user settings i check what i can do.
> > 2. No need for rclone we can done almost everything from google api lib.
> 
> Thanks

Btw why fake github account u can use ur main, i don't eat people!

**Comment by Jarvis991** [comment]
Nah that individual is different..i just forwarded his req

**Comment by anasty17** [comment]
No i mean the sample!

**Comment by Jarvis991** [comment]
> Oh u just forwarded it, ok. But who opened that issue is fake account look at the sample
I see 🙂
