### ISSUE TITLE
Remove thumb command

### ISSUE THREAD

**Issue by Brirringo** [anasty17/mirror-leech-telegram-bot#1040]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
— Yes, it is impossible to delete a thumbnail while in anonymous mode in a group

**Describe the solution you'd like**
— A command like `/setthumb`, but to remove the thumbnail

**Describe alternatives you've considered**
— Could be /rmvthumb

**Additional context**
— When trying to delete the thumbnail via `/leechset`, a popup appears saying "No Yours!" as the settings are for @GroupAnonymousBot

I know the solution would be to not use anonymous mode, but I don't want to stop using it.

**Comment by anasty17** [comment]
Soon i will remove setthumb it will be merged with userset.
And also query will not work ... all queries will not work with anonymous! So sure NO
