### ISSUE TITLE
Telegram File Mirror Not Working

### ISSUE THREAD

**Issue by peru194** [anasty17/mirror-leech-telegram-bot#1048]
The File Which Is In Telegram I can't mirror to drive. bot is not replying

![image](https://user-images.githubusercontent.com/101878848/188764938-36a5a23f-1149-4f37-8151-31b3bf070460.png)

![image](https://user-images.githubusercontent.com/101878848/188765268-c70e9c9a-44d1-4495-96f9-efad95ae23dc.png)

**Comment by anasty17** [comment]
Promote the bot as admin!
