### ISSUE TITLE
Btsel command

### ISSUE THREAD

**Issue by LeoBonharts** [anasty17/mirror-leech-telegram-bot#1051]
**Describe the bug**
When using /btsel command with /qbmirror after that download selected files are complete bot cannot upload to the google drive it just upload one file named " .8142c7341cdf161c1cf9a2fad47809bda93fb6eb.parts"

**To Reproduce**
1. Used this Command with this link or file.
2. Before/after/while Upload ..
3. Check logs

**Expected behavior**

**Screenshots**

**Additional context**
The torrent file that i am using is this "https://nyaa.si/download/1458908.torrent" i wanted to download 150 files on each mirror when completed i downloaded first 150 files with /btsel for the 150 files after this problem appears and i restearted the bot but se problem. Log file is below.

[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9505111/log.txt)

**Comment by anasty17** [comment]
Yeah i forget this, I will fix soon 👍

**Comment by LeoBonharts** [comment]
Thank you so much.

**Comment by anasty17** [comment]
Fixed thanks for reporting
