### ISSUE TITLE
Yt-dlp issue 

### ISSUE THREAD

**Issue by Ajay0916** [anasty17/mirror-leech-telegram-bot#1053]
I am getting this issue while leeching instagram using /
![Screenshot_2022-09-08-12-59-18-91_469d9a8fb01100be319306c44b95b80a](https://user-images.githubusercontent.com/94453305/189062887-5c5c12f8-b927-479d-a553-7d66aef97817.jpg)
yl cammand

**Comment by anasty17** [comment]
Send link

**Comment by Ajay0916** [comment]
https://www.instagram.com/reel/CiPX9hkJn80/?igshid=YmMyMTA2M2Y=

**Comment by anasty17** [comment]
I got this error 

@anas_tayyar ERROR: CiNGzp7Kpy5: An extractor error has occurred. (caused by KeyError('config')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by anasty17** [comment]
Problem in extractor, report to yt-dlp

**Comment by anasty17** [comment]
I'm trying with another bot, yeah something wrong let me check

**Comment by anasty17** [comment]
Format_id is too long for instagram and we have limits for buttons. I will fix this maybe in 3 days

**Comment by Ajay0916** [comment]
Ohk ohk....

**Comment by anasty17** [comment]
Fixed https://github.com/anasty17/mirror-leech-telegram-bot/commit/b6e3917c3630581e1ff08b51e5f270245f746d47
