### ISSUE TITLE
Dead torrent!

### ISSUE THREAD

**Issue by Dekad11** [anasty17/mirror-leech-telegram-bot#106]
Sir how to apply this feature on /mirror command
![IMG_20211201_023820](https://user-images.githubusercontent.com/91631500/144128622-2c532b35-4e08-4df2-849b-33a7e6bac5d3.jpg)

**Comment by anasty17** [comment]
For aria2c check timeout in aria.sh replace zero by number of sec
For qBittorrent edit those 999999 in sec

1. https://github.com/anasty17/mirror-leech-telegram-bot/blob/8347421da7e023e08e0be011cd1e5a385d985702/bot/helper/mirror_utils/download_utils/qbit_downloader.py#L192
2. https://github.com/anasty17/mirror-leech-telegram-bot/blob/8347421da7e023e08e0be011cd1e5a385d985702/bot/helper/mirror_utils/download_utils/qbit_downloader.py#L141
First one while stalled download and 2nd wjile downloading meta data

**Comment by Dekad11** [comment]
I have already changed it but it works only qbmirror command, it is not work in mirror command
![IMG_20211201_114645](https://user-images.githubusercontent.com/91631500/144183511-721f3704-a479-4aea-89ae-b2de5e1039c7.jpg)

**Comment by anasty17** [comment]
U update with restart command?

**Comment by Dekad11** [comment]
What update

**Comment by anasty17** [comment]
@Dekad11 Show me ur aria.sh

**Comment by Dekad11** [comment]
![IMG_20211201_121843](https://user-images.githubusercontent.com/91631500/144185797-85fcf3cc-fc85-451c-aa4f-1adbb6205368.jpg)

**Comment by anasty17** [comment]
@anasty17 I told u to edit timeout in  aria.sh ... --stop-timeout in sec

**Comment by Dekad11** [comment]
Thanks it's working
