### ISSUE TITLE
Max parallel number of tasks.

### ISSUE THREAD

**Issue by Lucif3rHun1** [anasty17/mirror-leech-telegram-bot#1061]
**Is your feature request related to a problem? Please describe.**
Max number of parallel number of tasks at a time.

**Describe the solution you'd like**
Like I want the bot to stop responding to messages when its already running lets say like 20 tasks at a time. And once it finishes 1 and its 19 add 1 after it to make it 20 again.

**Describe alternatives you've considered**
None

**Additional context**
Just a suggestion, as I like to leech in bulk so if it leech too using /l command bot stops responding as too heavy and am lazy to do make small chunks and do.

**Comment by anasty17** [comment]
Manage it by ur self!
