### ISSUE TITLE
Ytdl Issue

### ISSUE THREAD

**Issue by adamjasan** [anasty17/mirror-leech-telegram-bot#1062]
Stream output not  came in /yl cmd

Link is

https://www.voot.com/shows/mithuna-raashi/1/747148/suraksha-tries-to-influence-raashi/756777

**Comment by anasty17** [comment]
What do u mean ?

**Comment by anasty17** [comment]
![Screenshot_20220910-013842_Plus](https://user-images.githubusercontent.com/77075674/189454956-d23458a4-acc7-4655-accd-afe7b8120440.jpg)
