### ISSUE TITLE
Multiple ZIP Files

### ISSUE THREAD

**Issue by Saafracs** [anasty17/mirror-leech-telegram-bot#1067]
I have these 13 Episodes split in 17 different parts (different ZIP files), so how can I download them, extract them, and the upload them to the shared drive using the bot? Thanks 😀

![image](https://user-images.githubusercontent.com/68617893/189503344-89d6754e-8bbb-44c7-8135-2ee4a02056ec.png)
![image](https://user-images.githubusercontent.com/68617893/189503346-d0fdd86e-a7b3-4973-b977-01190df4266e.png)

**Comment by anasty17** [comment]
Not yet, i will add this soon! Join official channel for updates
