### ISSUE TITLE
Torrents getting stopped after selection

### ISSUE THREAD

**Issue by Nobody12541** [anasty17/mirror-leech-telegram-bot#1072]
So i have been having this problem after some commit i don't what commit actually caused this. But the torrents get cancelled or stopped as soon as the bot upload the files.  Note that this happens only when i use the "select" feature when i want only some files from a specific torrent because the size is so big like 1TB. 

So i select the files and the bot starts leeching then upload it. And as soon as the bot upload it and start to seed it  i get the following message : "your download has been stopped due to: No enough space for this torrent on device"

And it happens even when i select only 5GB of files from the torrent. 

The bot logs : 
2022-09-11T16:15:31.615004+00:00 app[web.1]: 2022-09-11 16:15:31,614 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Uploaded To G-Drive: Star Trek： Voyager 1995 48xDVD9
2022-09-11T16:15:31.615149+00:00 app[web.1]: 2022-09-11 16:15:31,615 - bot - INFO - Done Uploading Star Trek： Voyager 1995 48xDVD9
2022-09-11T16:15:31.840247+00:00 app[web.1]: 2022-09-11 16:15:31,840 - bot - INFO - Seeding started: Star Trek： Voyager 1995 48xDVD9 - Hash: 5038cb10c8ff6fb8d46a751510890f0778ef4c88
2022-09-11T16:15:31.842896+00:00 app[web.1]: 2022-09-11 16:15:31,842 - bot - INFO - Cancelling Download: Star Trek： Voyager 1995 48xDVD9
2022-09-11T16:15:32.145303+00:00 app[web.1]: 2022-09-11 16:15:32,145 - bot - INFO - Cleaning Download: /usr/src/app/downloads/2204

Can you please look into this?

**Comment by Nobody12541** [comment]
I don't reselect again. I pm'ed the torrent on telegram. Check it.

**Comment by anasty17** [comment]
Disable checkingup on complete in qBittorrent.conf. maybe bug from qBittorrent i didn't try on 4.3.9, i only tried on 4.4.5 heroku branch will try soon on vps.

**Comment by anasty17** [comment]
I have tried master branch no issues. So issue in qBittorrent 4.4.4. U can use vps with master branch or disable checkup on complete as i said in previous comment. Heroku and h-code branch will not receive updates anymore

**Comment by Nobody12541** [comment]
Alright thanks! 
Btw this is unrelated but i wanted to ask this for some time. How do i remove or add another tracker url in the torrent? I saw there is an option but to do that if you can tell me?
![Screenshot_2022_0912_023556](https://user-images.githubusercontent.com/101923792/189548907-cfa33ea4-fa4d-42a9-adcb-2c50fb61bb66.png)

How do i add or remove the tracker url after adding the torrent?

**Comment by anasty17** [comment]
It's not good option in qBittorrent t add trackers it will lag alot if u added many trackers. I will send to u previous commit. But u can't add from bot u need to edit in code.

**Comment by Nobody12541** [comment]
Okay i can do that. I will only add one tracker. Can you send me that commit and tell me where do i edit it?

**Comment by Nobody12541** [comment]
> It's not good option in qBittorrent t add trackers it will lag alot if u added many trackers. I will send to u previous commit. But u can't add from bot u need to edit in code.

Hi did you forget about it? Dropping another reply just in case.

**Comment by anasty17** [comment]
Ohh sure i forget, soon i will reply for answer

**Comment by Nobody12541** [comment]
> Ohh sure i forget, soon i will reply for answer

Okay

**Comment by Nobody12541** [comment]
> Ohh sure i forget, soon i will reply for answer

Did you forget again? Dropping another message just in case. Can you please it this time? I have been checking again and again if you replied lol

**Comment by Nobody12541** [comment]
> > Ohh sure i forget, soon i will reply for answer
> 
> Did you forget again? Dropping another message just in case. Can you please send it this time? I have been checking again and again if you replied lol

**Comment by anasty17** [comment]
Sorry i forget, do u want to add tracker for all torrents or specific torrent ?

**Comment by Nobody12541** [comment]
I want to add tracker for specific torrent.

**Comment by anasty17** [comment]
First for all torrents (add this in init.py)

trackers = check_output(["curl -Ns https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt https://ngosang.github.io/trackerslist/trackers_all_http.txt https://newtrackon.com/api/all | awk '$0'"], shell=True).decode('utf-8')
trackerslist = set(trackers.split("\n"))trackerslist.remove("")
trackerslist = "\n\n".join(trackerslist)
get_client().application.set_preferences({"add_trackers": f"{trackerslist}"})

2nd for specific torrent using eval:

/eval from bot import get_client 
client = get_client()
client.torrents_add_trackers(torrent_hash={HASH}, urls="")

**Comment by Nobody12541** [comment]
I a sorry i have no idea where do need to edit it can you please tell me the full location?

**Comment by anasty17** [comment]
No
