### ISSUE TITLE
YTDL: "best video" does not work

### ISSUE THREAD

**Issue by eyMarv** [anasty17/mirror-leech-telegram-bot#1077]
**Describe the bug**
The "best video" option does not work and throws an unhandled exception.

**To Reproduce**
1. Use /ytdl for this video: http://www.youtube.com/watch?v=2sFvGqTjlxM (others also affected)
2. Select "best video"
3. Check logs

**Expected behavior**
Selection should pass and the ytdl process should begin.

**Additional context**
logs:

022-09-12 17:47:41,059 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/utils/promise.py", line 96, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/usr/src/app/bot/modules/ytdlp.py", line 255, in select_format
    b_name, tbr = qual.split("|")
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by anasty17** [comment]
Ohh that's right i will fix it

**Comment by anasty17** [comment]
Fixed https://github.com/anasty17/mirror-leech-telegram-bot/commit/92197154e4b1940f6c01fd314bb25ac0e21d3581
