### ISSUE TITLE
ERROR: Service 'app' failed to build: The command '/bin/sh -c pip3 install --no-cache-dir -r requirements.txt' returned a non-zero code: 137

### ISSUE THREAD

**Issue by nicolerralph** [anasty17/mirror-leech-telegram-bot#108]
Issue while building with docker-compose

**Comment by anasty17** [comment]
@nicolerralph Which vps ? And what it's architecture

**Comment by nicolerralph** [comment]
> @nicolerralph Which vps ? And what it's architecture

Azure Standard B1s

x86_64 architecture

Was working two days ago. Then git pulled and rebuilded the app image and got this error.

**Comment by anasty17** [comment]
@nicolerralph U edit anything.. cz i have already tested it on azure, if no show me all docker logs

**Comment by nicolerralph** [comment]
> @nicolerralph U edit anything.. cz i have already tested it on azure, if no show me all docker logs

Issue fixed thanks for helping(re-did everything)

Just a personal request can you unblock me in telegram?
(t.me/none_xd) 😅
