### ISSUE TITLE
Ytdlp Playlist Leech Not working 

### ISSUE THREAD

**Issue by GautamSaini1834** [anasty17/mirror-leech-telegram-bot#1081]
Hi there @anasty17 

Thak you for your hard work btw I appreciate it

When I try to leech YouTube playlist links eg :

```https://youtube.com/playlist?list=RDQMgEzdN5RuCXE&playnext=1``` it sends the following error in log 

```2022-09-15 22:49:13,035 - bot - ERROR - Button_data_invalid```

Didn't modfiy the bot or any codes the bot doesn't reply when passing this playlist link...

Thank you 

Waiting for your reply kindly....

**Comment by anasty17** [comment]
Latest commit ?

**Comment by GautamSaini1834** [comment]
Thank you for noting
