### ISSUE TITLE
I can't download any youtube videos using /ytdl

### ISSUE THREAD

**Issue by mr-m85** [anasty17/mirror-leech-telegram-bot#1101]
Hi,
Thanks for your hard work I try use cookies or without same msg appear 
/ytdl https://www.youtube.com/watch?v=8Jl6FuFohXk
**your download has been stopped due to: ERROR: [download] Got error:  urlopen error _ssl.c:1114: The handshake operation timed out**
I can't download any youtube videos
Can help me please.

**Comment by anasty17** [comment]
No issues here! Update ur code and deploy again to get latest version of yt-dlp
