### ISSUE TITLE
Bot isn't leeching nor uploading.

### ISSUE THREAD

**Issue by akshzyx** [anasty17/mirror-leech-telegram-bot#1103]
Bot isn't downloading files from google drive.

![google file - bot](https://user-images.githubusercontent.com/73602335/193194589-e4a4d62b-f9a0-4a2f-8db1-1a5dfe0f563a.png)
It's stuck like this every time, or the speed is just in few kb sometimes.

Also this index file was around 1.6gb but bot isn't downloading it either. Instead of leeching 1.6gb file bot uploads 8kb file.

![index file leech - bot](https://user-images.githubusercontent.com/73602335/193194741-9fbc772b-50ad-46e7-a8e8-c424f09ea913.png)

I tried restarting bot from telegram and even from github actions but still no luck.
How to solve this problem?

**Comment by anasty17** [comment]
Read issue guide lines and follow it to understand you. Ur issue is not clear

**Comment by akshzyx** [comment]
> Read issue guide lines and follow it to understand you. Ur issue is not clear

I'm saying bot isn't downloading files from google drive. Download doesn't start. How to solve this?

**Comment by anasty17** [comment]
Read issue guide lines and write the issue! FOLLOW THE GUIDE LINES
