### ISSUE TITLE
No module named 'pymongo'

### ISSUE THREAD

**Issue by mjain234** [anasty17/mirror-leech-telegram-bot#1106]
I was trying to redploy my bot and caught with this error:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 13, in <module>
    from .helper.ext_utils.db_handler import DbManger
  File "/usr/src/app/bot/helper/ext_utils/db_handler.py", line 2, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

**Comment by anasty17** [comment]
If u r using docker-compose so use the build arg read readme. In short Deploy again!

**Comment by sp003** [comment]
It's a silly issue . 
Added RUN pip3 install pymongo dnspython in dockerfile .

**Comment by anasty17** [comment]
> It's a silly issue . Add RUN pip3 install pymongo dnspython in dockerfile .

No need for ur suggestion cz also no need! He want to pull the latest code and deploy again with silly edits in docker!

**Comment by mjain234** [comment]
I already figured out the way before you call the question "Noob"😅 , also its my mistake as I opened the issue in a hurry without waiting to solve it by myself!
