### ISSUE TITLE
/sleep command is not working? Bot is not idling?

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1109]
**Describe the bug**
/sleep command is not working? Bot is not idling After I execute /sleep

**Expected behavior**
Bot will idle after I execute `/sleep`

[log (3).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9689998/log.3.txt)

**Comment by anasty17** [comment]
No more support for heroku! Where u r living heroku will stop soon!

**Comment by erickyun** [comment]
No I have heard that heroku free will end on november but I didn't know you would cease to support heroku because of that reason? This is sad news for me.🙁

Thank you for your support on heroku until now.👍

**Comment by anasty17** [comment]
If u r ready to pay then get a paid vps, it's cheaper then heroku!

**Comment by anasty17** [comment]
I will remove it because people acting weird about heroku they want updates until 28 nov!
