### ISSUE TITLE
Qbittorrent webui not working

### ISSUE THREAD

**Issue by sp003** [anasty17/mirror-leech-telegram-bot#1111]
Qbittorrent gives unauthorised error on web ui . 

 You specified port 80 in tutorial . It's not webui .

Qbittorrent webui port is 8090 as mentioned in qbittorrent.conf

I forwarded 8090 from docker container and it gives unauthorized error .

 Rest is fine

**Comment by sp003** [comment]
I found the solution . Add these lines in qBittorrent/config/qBittorrent.conf
to solve unauthorized.

`WebUI\HostHeaderValidation=false
WebUI\Address=*
WebUI\ServerDomains=*`

& forward webui port from docker container 
`docker run -p 80:8090 mirror-bot` [not 80:80]

**Comment by anasty17** [comment]
Who said this for qbitorrent webui ?! Sever port only for selecting files from Torrents added in aria2c and qbittorrent! Nothing related to webui!
