### ISSUE TITLE
YTDL is fixed, right?

### ISSUE THREAD

**Issue by Coolboyrajat** [anasty17/mirror-leech-telegram-bot#1113]
I'm using repo that was push on **Sep 30, 2022** In one of your commit, you mention that the conversion of ytdl links are fixed on **Sep 13, 2022**, but still I'm getting mkv as result

Here is a small clip that I would like you to watch 

https://user-images.githubusercontent.com/67316346/193445914-616bdac6-76ec-4146-a8b4-689379d29f20.mp4

**Comment by anasty17** [comment]
Heroku ?

**Comment by Rust-Mode** [comment]
Yes

**Comment by Coolboyrajat** [comment]
Yes

**Comment by Coolboyrajat** [comment]
Yes

**Comment by anasty17** [comment]
U didn't notice that h-code branch not getting any more updates! If u r noob to this level so u shouldn't think about opening issue!
