### ISSUE TITLE
Heroku deply error

### ISSUE THREAD

**Issue by akshzyx** [anasty17/mirror-leech-telegram-bot#1126]
I am trying to deploy on heroku but this error keeps showing

```Error: Command failed: heroku container:push web --app *** 
 ›   Warning: heroku update available from 7.63.4 to 7.64.0.
manifest for anasty17/mltb:heroku not found: manifest unknown: manifest unknown
 ▸    Error: docker build exited with Error: 1```

**Comment by tania010** [comment]
i'm also getting this error after updating

**Comment by anasty17** [comment]
No support for heroku! It will end soon STOP TALKING ABOUT IT!

**Comment by kyash4** [comment]
why are you ending support for heroku?

**Comment by anasty17** [comment]
I'm not ending it! Free service will stop soon and not worth to update h-code! And people still asking for h-code updates! I have removed it so people can stop talking about but seems i was wrong now all of u kids spamming why why! Error ! Bug! Not deploying! Just fuck off
