### ISSUE TITLE
Error: Resource not found

### ISSUE THREAD

**Issue by tania010** [anasty17/mirror-leech-telegram-bot#1127]
**Describe the bug**
When trying to mirror multiple direct links, bot gives error: your download has been stopped due to: Resource not found

**To Reproduce**

1. Used /mirror with 
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X01%20ARROW%20-%20HD%201080p%20MKV.mkv
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X02%20ARROW%20-%20HD%201080p%20MKV.mkv
3. does not start upload, gives error
4. logs
`bot - INFO - Download Error: Resource not found
2022-10-07 14:38:28,593 - bot - INFO - http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X01%20ARROW%20-%20HD%201080p%20MKV.mkv
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X02%20ARROW%20-%20HD%201080p%20MKV.mkv
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X03%20ARROW%20-%20HD%201080p%20MKV.mkv
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X04%20ARROW%20-%20HD%201080p%20MKV.mkv
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X05%20ARROW%20-%20HD%201080p%20MKV.mkv
2022-10-07 14:38:28,627 - bot - INFO - No Direct link function found for http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X01%20ARROW%20-%20HD%201080p%20MKV.mkv
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X02%20ARROW%20-%20HD%201080p%20MKV.mkv
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X03%20ARROW%20-%20HD%201080p%20MKV.mkv
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X04%20ARROW%20-%20HD%201080p%20MKV.mkv
http://54.39.52.63/SERIES2/Series%20Espa%c3%b1ol%20Castellano/A/ARROW/TEMPORADA%201/1X05%20ARROW%20-%20HD%201080p%20MKV.mkv
2022-10-07 14:38:28,637 - bot - INFO - onDownloadStarted: 1X05%20ARROW%20-%20HD%201080p%20MKV.mkv`

**Expected behavior**
For the bot to start downloading the file one-by-one or at the same time. 

**Screenshots**

**Additional context**
replying to the links one by one starts the download, it's only when replying to a list of links is when it throws the error. 
![save](https://user-images.githubusercontent.com/51423213/194673616-bdcf1e4e-954c-4dc5-b190-664d4a4c1225.PNG)

**Comment by anasty17** [comment]
Multi link doesn't work like this!
Send each link alone then reply to first link with the number of links! Use /help!
