### ISSUE TITLE
Error: Command failed: heroku container:push web --app ***

### ISSUE THREAD

**Issue by Ahmadali322** [anasty17/mirror-leech-telegram-bot#1129]
I made a bot once and it did ran but unfortunatlly a bad file was added so my Team Drive was banned or closed so I tried to make the bot once again so I deleted the app from heroku and did the process again but deployment was failed I tried making a new account and tried starting all over again but still not deploying everytime it shows the same error

"Error: Error: Command failed: heroku container:push web --app *** 
 ›   Warning: heroku update available from 7.63.4 to 7.64.0.
manifest for anasty17/mltb:heroku not found: manifest unknown: manifest unknown
 ▸    Error: docker build exited with Error: 1

manifest for anasty17/mltb:heroku not found: manifest unknown: manifest unknown
 ▸    Error: docker build exited with Error: 1"

please if you have solution then do let me know.

**Comment by junedkh** [comment]
No More Heroku

**Comment by Ahmadali322** [comment]
so what are we supposed to do @junedkh ? can we still make this mirror leech bot?
