### ISSUE TITLE
Error. RetryError[Future at 0x7f8b18264340 state=finished raised HttpError]

### ISSUE THREAD

**Issue by mine-nandha** [anasty17/mirror-leech-telegram-bot#113]
![IMG_20211202_110335](https://user-images.githubusercontent.com/86552361/144363787-19431fa7-3f21-4244-8db7-60d3b7e341fd.jpg)

**Comment by anasty17** [comment]
@mine-nandha If the link is public, send it

**Comment by mine-nandha** [comment]
Uh.. actually that link isn't public. It's from someone's TD. Cloning works fine if they're my own files(From my own td, personal drive). Couldn't clone from others TD now. It was working fine till yesterday.

**Comment by anasty17** [comment]
@mine-nandha So the problem from ur side ...

**Comment by anasty17** [comment]
@mine-nandha Everything working fine with me

**Comment by mine-nandha** [comment]
😶

**Comment by anasty17** [comment]
@mine-nandha U edit last commit manually?

**Comment by mine-nandha** [comment]
I did. A day back. But then I even fetched upstream then redeployed the app.

**Comment by anasty17** [comment]
@mine-nandha I need to test by myself if u can give access to that td and let me try

**Comment by mine-nandha** [comment]
U mean the one it failed to clone?

**Comment by mine-nandha** [comment]
http://groups.google.com/forum/#!forum/hm-drive

**Comment by anasty17** [comment]
@mine-nandha Ok bro send link please

**Comment by mine-nandha** [comment]
Sent already ig

**Comment by anasty17** [comment]
@mine-nandha File link ...

**Comment by mine-nandha** [comment]
https://drive.google.com/u/0/open?id=1vRHzNo9lp7vMoGT76_2rMb3DyhrVof-V

**Comment by anasty17** [comment]
@mine-nandha Ok bro wait for fix

**Comment by anasty17** [comment]
@anasty17 Fixed thanks for reporting
