### ISSUE TITLE
/ytdl MX Player link fails with 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by gagantk** [anasty17/mirror-leech-telegram-bot#1131]
/ytdl command with MX Player video link fails with 'NoneType' object is not subscriptable. This error appears during video information gets extracted.

1. Used this Command:
    /ytdl https://www.mxplayer.in/show/watch-the-promise-hindi-dubbed/season-1/episode-1-online-fda49f7c6102b06315b020fab186d9af
2. Bot replies 'NoneType' object is not subscriptable

Expected behavior
I have verified the same link using yt-dlp on Windows separately. It does not fail and is able to extract data and download the video.
![image](https://user-images.githubusercontent.com/41661218/194764987-eb7244f5-42e6-4e77-b692-f951eb5aca5f.png)

**Comment by anasty17** [comment]
https://user-images.githubusercontent.com/77075674/194769420-dc550f5e-7bb6-4f44-b8b3-926d424307a2.mp4

**Comment by anasty17** [comment]
Mostly hist location issue not related to code.

**Comment by gagantk** [comment]
Oh okay, thanks for your clarification!
