### ISSUE TITLE
0.0.0.0 port 80 change?

### ISSUE THREAD

**Issue by carolynsteeves1** [anasty17/mirror-leech-telegram-bot#1149]
WARNING: Image for service app was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating mirror-leech-telegram-bot_app_1 ...
Creating mirror-leech-telegram-bot_app_1 ... error

ERROR: for mirror-leech-telegram-bot_app_1  Cannot start service app: driver failed programming external connectivity on endpoint mirror-leech-telegram-bot_app_1 (3491c8fdbc226952fd8759ddd96dc868b35892c1838b86480): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

ERROR: for app  Cannot start service app: driver failed programming external connectivity on endpoint mirror-leech-telegram-bot_app_1 (3491c8fdbc226952fd8759ddd96dc868b35892c1838b86480): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

---

Is there an way to change this to not use port 80 on 0.0.0.0? I host my other projects on my vps as well

**Comment by anasty17** [comment]
Seems u didn't read readme or looked to config.env

**Comment by carolynsteeves1** [comment]
i did try change server port, but it didnt fix the issue

**Comment by anasty17** [comment]
Learn how to open port in ur instance
