### ISSUE TITLE
bot is not downloading torrent but able to download direct links.

### ISSUE THREAD

**Issue by rishabh-modi2** [anasty17/mirror-leech-telegram-bot#115]
i deployed bot to heroku.
first clone and done git checkout heroku
then copied my cred. token.pickel file
then followed you given by you
pushed and added following configs

# REQUIRED CONFIG
BOT_TOKEN = ""
GDRIVE_FOLDER_ID = ""
OWNER_ID =
DOWNLOAD_DIR = "/usr/src/app/downloads"
DOWNLOAD_STATUS_UPDATE_INTERVAL = 7
AUTO_DELETE_MESSAGE_DURATION = 20
IS_TEAM_DRIVE = ""
TELEGRAM_API =
TELEGRAM_HASH = ""
BASE_URL_OF_BOT = ""  # Web Link, Required for (Heroku) to avoid sleep or use worker

when i use /leech or /mirror with magnet links
it stuck at collecting metadata

is there anything i missed
please help

**Comment by anasty17** [comment]
@rishabh-modi2 Use qbitorrent or mirror ubuntu torrent to initiate aria2c then cancel after while then add ur torrent

**Comment by rishabh-modi2** [comment]
thanks for solving my issue. 
such a good work 
stared the repo

**Comment by anasty17** [comment]
@rishabh-modi2 U wlc
