### ISSUE TITLE
Using the bot as a "download manager"

### ISSUE THREAD

**Issue by Velosofy** [anasty17/mirror-leech-telegram-bot#1150]
**Is your feature request related to a problem? Please describe.**
Save the downloaded files locally, by disabling upload

**Describe the solution you'd like**
Is it possible to configure the bot to only save the files locally in the hosted machine?
I'd like to use it as a "download manager", by disabling gdrive/tg uploading feature.

**Comment by anasty17** [comment]
Search for another bot for this purpose!
