### ISSUE TITLE
Not Uploading file to telegram

### ISSUE THREAD

**Issue by Master-Mind-007** [anasty17/mirror-leech-telegram-bot#1161]
![Screenshot_20221024-000330_Plus](https://user-images.githubusercontent.com/87894877/197409705-912c1765-0b04-40c8-bdc3-b9bd08b9682c.jpg)
![Screenshot_20221024-000651_Chrome](https://user-images.githubusercontent.com/87894877/197409712-4e3cf303-8cf7-48de-b328-3bc360ebf720.jpg)

I don't know what's going wrong here, but the bot is not uploading file to telegram. It can mirror, but not leech because it's not able to upload file on telegram

**Comment by anasty17** [comment]
No issues here!
