### ISSUE TITLE
error  ModuleNotFoundError: No module named 'megasdkrestclient'

### ISSUE THREAD

**Issue by mbahmunz** [anasty17/mirror-leech-telegram-bot#1172]
app_1  | warning: no common commits
app_1  | 2022-10-27 04:23:14,500 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
app_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
app_1  |   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
app_1  |     return _get_module_details(pkg_main_name, error)
app_1  |   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
app_1  |     __import__(pkg_name)
app_1  |   File "/usr/src/app/bot/__init__.py", line 16, in <module>
app_1  |     from megasdkrestclient import MegaSdkRestClient, errors as mega_err
app_1  | ModuleNotFoundError: No module named 'megasdkrestclient'
app_1  | warning: no common commits
app_1  | 2022-10-27 04:23:17,450 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
app_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
app_1  |   File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
app_1  |     return _get_module_details(pkg_main_name, error)
app_1  |   File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
app_1  |     __import__(pkg_name)
app_1  |   File "/usr/src/app/bot/__init__.py", line 16, in <module>
app_1  |     from megasdkrestclient import MegaSdkRestClient, errors as mega_err
app_1  | ModuleNotFoundError: No module named 'megasdkrestclient'
.

how to solve this error??

**Comment by junedkh** [comment]
Repo no more support for heroku

**Comment by mbahmunz** [comment]
> Repo no more support for heroku

I use my own vps not heroku
