### ISSUE TITLE
google drive not upload/all steps follow and permisson Access

### ISSUE THREAD

**Issue by daneeshak** [anasty17/mirror-leech-telegram-bot#1173]
HttpError 404 when requesting https://www.googleapis.com/drive/v3/files?supportsAllDrives=true&alt=json returned "File not found: .". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: .', 'locationType': 'parameter', 'location': 'fileId'}]"

**Comment by anasty17** [comment]
Update ur config.env. check the sample
