### ISSUE TITLE
BASE_URL doesn't work

### ISSUE THREAD

**Issue by DanyTPG** [anasty17/mirror-leech-telegram-bot#1174]
With the latest commit, the `BASE_URL_OF_BOT` was changed to `BASE_URL`. I tried both of them in the config file and neither work. the bot says  `BASE_URL not provided!` which results in qbittorrent web selection not being able to bind.

**Comment by DanyTPG** [comment]
`CONFIG_FILE_URL` variable doesn't work either.

**Comment by anasty17** [comment]
Change it from bot settings if u added database.
CONFIG_FILE_URL removed. And no support for heroku.
