### ISSUE TITLE
Task Limit

### ISSUE THREAD

**Issue by tunsuriya** [anasty17/mirror-leech-telegram-bot#1175]
How to limit Tasks, Sir?
not STATUS_LIMIT, TASK_LIMIT

**Comment by junedkh** [comment]
Why ?

**Comment by tunsuriya** [comment]
> Why ?

I'm sharing my low-cost VPS bot with my friends. But one of them raped the bot by Many Tasks, so the bot is DOWN and I can't even connect my VPS. So I want to limit tasks, but I didn't find that feature.

**Comment by Saafracs** [comment]
Can I ask which VPS are you using?

**Comment by junedkh** [comment]
> > Why ?
> 
> I'm sharing my low-cost VPS bot with my friends. But one of them raped the bot by Many Tasks, so the bot is DOWN and I can't even connect my VPS. So I want to limit tasks, but I didn't find that feature.

are you using bot from group ?

**Comment by anasty17** [comment]
> > Why ?
> 
> I'm sharing my low-cost VPS bot with my friends. But one of them raped the bot by Many Tasks, so the bot is DOWN and I can't even connect my VPS. So I want to limit tasks, but I didn't find that feature.

Bruh u can't lie here! Just tell ur friend to use in proper way IF HE IS UR FRIEND! No group features here u can use junedkh repo for group features
