### ISSUE TITLE
Gdrive not uploading any file 

### ISSUE THREAD

**Issue by sp003** [anasty17/mirror-leech-telegram-bot#1177]
Changed config.env from GDRIVE_FOLDER_ID to GDRIVE_ID but error not fixed .

Upstream set as this repo .

 HttpError 404 when requesting None returned "File not found: .". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: .', 'locationType': 'parameter', 'location': 'fileId'}]"

**Comment by sp003** [comment]
[_mirror-leech-telegram-bot_app_1_logs.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9885688/_mirror-leech-telegram-bot_app_1_logs.txt)

**Comment by sp003** [comment]
also tried with new credentials.json & token.pickle , new Teamdrive with manager access . not resolved

**Comment by anasty17** [comment]
Update ur config.env. check the sample var names have been changed

**Comment by anasty17** [comment]
> Changed config.env from GDRIVE_FOLDER_ID to GDRIVE_ID but error not fixed .
> 
> Upstream set as this repo .
> 
> HttpError 404 when requesting None returned "File not found: .". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: .', 'locationType': 'parameter', 'location': 'fileId'}]"

If u changed it then u have added wrong Id.

**Comment by sp003** [comment]
Got it . I changed it locally in config.env .

But in database , /bsetting gdrive_id was empty , so that was causing problems . Working fine after setting it from the bot . 

 can you add tutorial on flushing the database  ?

Also , if I don't set database_url , /bsetting will change local config.env file ??

**Comment by sp003** [comment]
Done thanks
