### ISSUE TITLE
Upload speed limitation

### ISSUE THREAD

**Issue by daneeshak** [anasty17/mirror-leech-telegram-bot#1180]
upload speed is differ than earlier... If i send 2 files upload speed will (20mbsx2=40mbs) But if I send one file the upload speed will be the same (20mbs) .My question is why the maximum speed(40mbs) does not upload in single upload? I use indian High performance oracle vps

**Comment by anasty17** [comment]
It's like multi part download. We don't have this feature yet. Maybe in future.
