### ISSUE TITLE
[May not a bug], but can't get the running successfully after following the guide.

### ISSUE THREAD

**Issue by mobilelifeful** [anasty17/mirror-leech-telegram-bot#1197]
**Describe the bug**
fail to upload
app_1  | 2022-11-04 13:26:23,829 - google_auth_httplib2 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2.
app_1  | 2022-11-04 13:26:27,076 - google_auth_httplib2 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2.
app_1  | 2022-11-04 13:26:31,263 - google_auth_httplib2 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2.
app_1  | 2022-11-04 13:26:31,348 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Total Attempts: 3
app_1  | 2022-11-04 13:26:31,348 - bot - INFO - Cleaning Download: /usr/src/app/downloads/14

**To Reproduce**
1. in tg bog chat: 
    /y https://www.youtube.com/watch?v=IUmq1paCiHI&feature=youtu.be
2. While uploading, got the error message as stated above.
3. app_1  | 2022-11-04 13:26:23,829 - google_auth_httplib2 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2.
app_1  | 2022-11-04 13:26:27,076 - google_auth_httplib2 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2.
app_1  | 2022-11-04 13:26:31,263 - google_auth_httplib2 - INFO - Refreshing credentials due to a 401 response. Attempt 1/2.
app_1  | 2022-11-04 13:26:31,348 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Total Attempts: 3
app_1  | 2022-11-04 13:26:31,348 - bot - INFO - Cleaning Download: /usr/src/app/downloads/14

**Expected behavior**
upload the video to the google drive account, the one created  OAuth Client ID and Drive API

**Screenshots**

**Additional context**
Flowed guide as:
1. git clone https://github.com/anasty17/mirror-leech-telegram-bot mirrorbot/ && cd mirrorbot
2. sudo apt install python3 python3-pip
3. cp config_sample.env config.env (filled all the required fields)
4. Deploying on VPS Using docker-compose:
   ubuntu@ubuntu-tg2od:~/mirrorbot$ pwd
   /home/ubuntu/mirrorbot

-     sudo apt install docker-compose
-     sudo docker-compose up

**Comment by anasty17** [comment]
Did u published the app ?

**Comment by anasty17** [comment]
Make sure u have published ur app and update ur code
