### ISSUE TITLE
no module named 'telegraph'

### ISSUE THREAD

**Issue by white-devil-00** [anasty17/mirror-leech-telegram-bot#1201]
I even install the telegraph module manually.
I don't know why it's showing 

![Screenshot_2022-11-10-06-45-56-37_9e8df3d0c7c1f50248b6ee043a653d26](https://user-images.githubusercontent.com/102788535/200976655-c78b4fad-1ac6-4f6f-bc11-c47237abf9aa.jpg)

**Comment by anasty17** [comment]
Join official channel on tg
