### ISSUE TITLE
Feature Req: Replace Filters concept with DB

### ISSUE THREAD

**Issue by dishapatel010** [anasty17/mirror-leech-telegram-bot#121]
**Replace Filters** : replace the specific set of word with the new word via filter while leeching /mirror (only for single file now)

ex- `[xyzXD] qwe.mp3 changes to [abcd] qwe.mp3`. here added replace filter to change words i.e. xyzXD to abcd

example working repo to [help](https://github.com/yash-dk/Mesh-RenameBot)

_### OR_ 

Add something to change specific words from file while leeching

**Comment by anasty17** [comment]
Yt-dlp already like this ... tg files no but can do this .... direct links can't

**Comment by anasty17** [comment]
Bro this is not rename bot ... many extras features added for simple use ... rename like u want it's not feature it project

**Comment by dishapatel010** [comment]
> Bro this is not rename bot ... many extras features added for simple use ... rename like u want it's not feature it project

mm nvm none
