### ISSUE TITLE
Command Customization did not work

### ISSUE THREAD

**Issue by sflores16-twu** [anasty17/mirror-leech-telegram-bot#122]
I gave custom commands in /bot/helper/telegram_helper/bot_commands.py but still the Bot took the default commands

What to do?

**Comment by dinesh-0602** [comment]
@sflores16-twu Use master branch and Don't fill UPSTREAM_REPO

**Comment by sflores16-twu** [comment]
I did it Bro.
Actually I am deploying it to VPS.

**Comment by sflores16-twu** [comment]
![image](https://user-images.githubusercontent.com/84863624/144714232-415e09b6-9af0-4115-ab33-9aceb68a1508.png)

**Comment by anasty17** [comment]
@sflores16-twu U need to build again after changing the commands... build then run

**Comment by sflores16-twu** [comment]
@anasty17 I had deployed it after changing the commands only but still did not work

**Comment by anasty17** [comment]
@sflores16-twu Should use master branch and don't fill UPSTREAM_REPO var

**Comment by sflores16-twu** [comment]
@anasty17 I am checking Sir
