### ISSUE TITLE
HttpError 404 when requesting None returned "File not found

### ISSUE THREAD

**Issue by Maol-commits** [anasty17/mirror-leech-telegram-bot#1223]
**Describe the bug**
im getting this every time the bot try to upload something to the drive:

`HttpError 404 when requesting None returned "File not found: .". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: .', 'locationType': 'parameter', 'location': 'fileId'}]"`

**To Reproduce**
1. Any /m link

**Screenshots**
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/10917426/202554486-07a0f38e-c8b0-4133-aa69-5dcfcd7f52c5.png">

**Additional context**
It was working fine just 2 days ago

**Comment by anasty17** [comment]
Ur td nuked or ur permission revoked. In short u don't have upload permission to this ID
