### ISSUE TITLE
Feature Request : Seed till certain Ratio

### ISSUE THREAD

**Issue by 4r3t** [anasty17/mirror-leech-telegram-bot#123]
As a lot of us are on private trackers, we often end up leeching because it's convenient to use the bot to upload to TDs.
When running on VPS, it would be nice if we have a seed command with the required ratio as an argument so that we don't end up doing a  'Hit and Run'.
It is a niche feature, so don't expect you to work on it at all.
But given it might be directly possible through qbit api, I hope it would relatively easier to implement.

**Comment by anasty17** [comment]
Will add this... but only for qBittorrent

**Comment by 4r3t** [comment]
> Will add this... but only for qBittorrent

Yes!
Qbit only needed!
Aria is banned anyway and it's peer discovery is inferior to qbit anyway.
Thank you so much!

**Comment by anasty17** [comment]
Done
