### ISSUE TITLE
Add rclone support

### ISSUE THREAD

**Issue by sobuj53** [anasty17/mirror-leech-telegram-bot#1230]
**Is your feature request related to a problem? Please describe.**
This repo is only missing out rclone support capabilities. Would be very helpful if we could transfer files to other storage provider, say OneDrive instead of Gdrive. 

**Describe the solution you'd like**
Rclone support would definitely fix the issue.

**Describe alternatives you've considered**

**Additional context**
Thank you for your time and consideration.

**Comment by anasty17** [comment]
I will not say NO now, but let me finish the todo list first.
It's not important not all people can get storage easily on onedrive or other clouds.

**Comment by rinrinx2** [comment]
@anasty17 https://github.com/Sam-Max/rclone-mirror-leech-telegram-bot bro add same this

**Comment by anasty17** [comment]
Kanger with rclone support in very weird way. He also removed ptb lib. With many weird modules. I can't see what new features he added in readme. I only see mine!

**Comment by rinrinx2** [comment]
much more advanced features have been added, I'll show you soon

**Comment by rinrinx2** [comment]
![Screenshot_20221120_201006_Telegram](https://user-images.githubusercontent.com/58888200/202915711-a0f320e9-4c3a-4e75-961c-406083bbe652.jpg)
![Uploading Screenshot_20221120_201028_Telegram.jpg…]()

**Comment by rinrinx2** [comment]
![IMG_20221120_202355_675](https://user-images.githubusercontent.com/58888200/202916462-6bc85f6e-1f4c-4f2b-87de-9f158c342529.jpg)

**Comment by anasty17** [comment]
> ![IMG_20221120_202355_675](https://user-images.githubusercontent.com/58888200/202916462-6bc85f6e-1f4c-4f2b-87de-9f158c342529.jpg)

So it's only rclone!

**Comment by rinrinx2** [comment]
@anasty17 yes sir  Aria rclone qbit and other

**Comment by seman01** [comment]
rclone most advance tools for cloud storage,hope it get implemented soon.
if people can buy vps to deploy mirror bot they should no problem for them to buy cloud storage.

**Comment by TrollGithub** [comment]
Totally pyrogram bruh

**Comment by tawayaka** [comment]
> I will not say NO now, but let me finish the todo list first. It's not important not all people can get storage easily on onedrive or other clouds.

sorry but some shared drives are no longer working due to new google policy
https://www.reddit.com/r/DataHoarder/comments/zfshkw/google_workspace_for_education_new_100gb_limit/
![image](https://user-images.githubusercontent.com/30314539/209103586-70c3d5a7-cd66-49b4-839b-5f945e81ce97.png)

**Comment by kuesttman** [comment]
You can see the possibility of using gclone instead of rclone. I think the implementation is easier...
https://github.com/l3v11/gclone

Like this Caduceus bot... which uses Gclone and lists the Drives that Service Accounts have access to...

https://github.com/TheCaduceus/CloneBot_V2

**Comment by CevreMuhendisi** [comment]
rclone support please

**Comment by anasty17** [comment]
Almost done
