### ISSUE TITLE
RSS filtering fails

### ISSUE THREAD

**Issue by Niffy-the-conqueror** [anasty17/mirror-leech-telegram-bot#1240]
**Describe the bug**
Bot fails to send the leech RSS link to RSS Channel when filters are enable

**To Reproduce**
1. Send /rsssub nyaa https://nyaa.si/?page=rss&q=1080p&c=0_0&f=0 f: Erai-raws or SubsPlease or Yameii or LostYears or Reza or DB
2. Nothing happens when RSS is updated
3. Logs return
```
2022-11-26 05:18:32,385 - bot - ERROR - __enter__
2022-11-26 05:18:38,750 - bot - INFO - Feed Name: nyaa
2022-11-26 05:18:38,751 - bot - INFO - Last item: https://nyaa.si/download/1606801.torrent
```

**Expected behavior**
Should send /leech along with the RSS link and start leeching 

**Screenshots**

**Additional context**

**Comment by Niffy-the-conqueror** [comment]
Also CMD_PERFIX doesn't work
I added it in config.env and did /restart but it didn't work /help still shows the normal commands and so also the bot respond to commands without the prefix and ignores the command with prefix

**Comment by anasty17** [comment]
I will check this error.. after adding database u should change the variables from bot settings use /bsetting

**Comment by Niffy-the-conqueror** [comment]
> I will check this error.. after adding database u should change the variables from bot settings use /bsetting

Adding RSS leech command is impossible since bot interprets it as an actual command 
Workaround is to add a random command prefix, restart, add RSS leech command , reset or add previous command prefix, restart.

**Comment by anasty17** [comment]
Fixed

**Comment by anasty17** [comment]
> > I will check this error.. after adding database u should change the variables from bot settings use /bsetting
> 
> Thanks that worked
> 
> BTW Adding RSS leech command is impossible since bot interprets it as an actual command Workaround is to add a random command prefix, restart, add RSS leech command , reset or add previous command prefix, restart.

I didn't understood!
