### ISSUE TITLE
Clear guide for deploying on VPS

### ISSUE THREAD

**Issue by wanderlusttt** [anasty17/mirror-leech-telegram-bot#1246]
**Is your feature request related to a problem? Please describe.**
No. Please do update clear guide on depolying to VPS. It is not possible to get it working with the steps mentioned herein.

**Describe the solution you'd like**
Update the steps on "Deploying to VPS"

**Describe alternatives you've considered**
Nope.

**Additional context**
--

**Comment by anasty17** [comment]
Watch the tutorial! And nothing more to explain its very simple! U want me to explain how to connect vps with terminal! Go and google it!

**Comment by anasty17** [comment]
And watch follow the steps from beginning don't go directly to deploying on vps i will change this totle soon but no new step!
