### ISSUE TITLE
ERROR - 'NoneType' object has no attribute 'id' Path: /usr/src/app/downloads/10984/

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1247]
**Describe the bug**
My /yl leeched file from youtube gets not uploaded to telegram instead I get this error `Files Corrupted. Check logs` 

**To Reproduce**
1. Used this Command with this link or file. `/yl`
2. while Upload .. I receive error `Files Corrupted. Check logs`
3. Check logs `ERROR - 'NoneType' object has no attribute 'id' Path: /usr/src/app/downloads/10984/`

**Expected behavior**
Execute /yl and video gets uploaded to telegram

[log (9).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10101983/log.9.txt)

**Additional context**
When I `/restart` the bot the file gets uploaded to telegram and I am not receiving this problem but this is only a temporary fix! when I try again /yl I am getting the same problem again!

Also this error doesn't occur only on one specific link.

**Comment by anasty17** [comment]
U added dump chat id ?

**Comment by erickyun** [comment]
> U added dump chat id ? If yes, did u read the description for this var in readme?

No dump chat id is empty.

**Comment by anasty17** [comment]
User session from same account that u r using ?

**Comment by erickyun** [comment]
> User session from same account that u r using ?

Yes

**Comment by erickyun** [comment]
> > User session from same account that u r using ?
> 
> Yes

Mirror works. İssue only occurs with /yl leeching.
[log (10).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10103001/log.10.txt)


Edit1: I Noticed also a different problem don't know if it is relevant but

When /yl leeching works after I try /restart a couple of times the bot does reply to a different cmd which isn't relevant!

Example.
cmd 1 /yl url-abc (Executed on September)
cmd 2 /yl url-bca (Executed on October)
cmd 3 /yl url-cba (Executed on November today)

cmd 3 does download/leech the video to telegram but
İt does not reply to cmd 3 but to a relevant cmd!!! Which is example cmd 1 or cmd 2? Which was executed one or two months back?

**Comment by anasty17** [comment]
Have u delete the command message ?
