### ISSUE TITLE
option for view current thumbnail in /usetting

### ISSUE THREAD

**Issue by hitesh920** [anasty17/mirror-leech-telegram-bot#1251]
**Is your feature request related to a problem? Please describe.**
no option to view current thumbnail, sometimes i had to set same thumbnail again and again just to be make sure its the correct one.

**Describe the solution you'd like**
add "View Thumbnail" option in /usettings, if we click on it then bot should send the thumbnail (u can also auto delete that sent thumbnail).

**Comment by anasty17** [comment]
I will add it to usetting directly

**Comment by anasty17** [comment]
> I will add it to usetting directly

Adding thumbnails to user settings is not good to manage if thumbnail removed need to delete the msg and resend another or incase u try to add option using the handler then also need to delete msg and add another we can't edit msg from media msg to non media msg

Pushed
