### ISSUE TITLE
rename for ytdl links with .m3u8 not working i guess

### ISSUE THREAD

**Issue by hitesh920** [anasty17/mirror-leech-telegram-bot#1252]
**Describe the bug**
normal ytdl isworking but ytdl with rename not working

**To Reproduce**
use this link :- https://djnn525lc63jq.cloudfront.net/live_streams/institute/forumias/courses/live-classes/6046/video_960x540.m3u8
if you check ytdl is working but renaming with ytdl not working

**Screenshots**
![image](https://user-images.githubusercontent.com/71580009/204499008-ccfd3d89-c9c8-474d-a90b-e8054428c279.png)
![image](https://user-images.githubusercontent.com/71580009/204499353-038dbf7f-72d5-452a-b5ca-ed9aa764162b.png)
first one i tried with normal ytdl, its downloading 
second one is ytdlleech with rename

**Additional context**
i dont know why its happing.

**Comment by anasty17** [comment]
Next time try first with rename. Check what 403 status code means

**Comment by hitesh920** [comment]
but bro normal ytdl, ytdl leech working fine with that link

**Comment by anasty17** [comment]
Update ur code and try

**Comment by hitesh920** [comment]
fixed thx

**Comment by anasty17** [comment]
> fixed thx

Thanks for reporting
