### ISSUE TITLE
having some problems with telegram downloads

### ISSUE THREAD

**Issue by hitesh920** [anasty17/mirror-leech-telegram-bot#1253]
**Describe the bug**
i am having same serious problems while downloading telegram files
i am using user session string with dump chat var
getting really slow speed when downloading "some" telegram files (dm me in telegram ill send you those files https://t.me/hitesh920)
when i leech a file with dump chat id, after leech if i forward those files from the dump channel to bot pm for mirror, bot not responding to that file
even i have "some" telegram files where bot not responding if trying to mirror in bot's pm but if forwarded to group then bot responding to that file

**To Reproduce**
try with dump chat var (i am using user session string also)
leech a file 
after leech forward that file from dump chat to bot's pm
and try mirror
for "some" files to try in bot's dm, msg me in telegram https://t.me/hitesh920 ill forward those files to you

**Expected behavior**
bot should mirror those files

**Screenshots**
![image](https://user-images.githubusercontent.com/71580009/204562138-ec3a69d5-df04-4837-9a7b-f2ddbfdb6f63.png)
![image](https://user-images.githubusercontent.com/71580009/204562234-2213fd11-2559-44fc-ae8b-59d95ef07e25.png)

**Additional context**
None

**Comment by hitesh920** [comment]
![image](https://user-images.githubusercontent.com/71580009/204588489-2452cff9-1965-4d61-a519-c7d8d9e6cdfc.png)

same error 
AttributeError: 'NoneType' object has no attribute 'document'

**Comment by anasty17** [comment]
U can use user session string only in supergroup
