### ISSUE TITLE
Stuck On Creating Telegraph Account

### ISSUE THREAD

**Issue by devabdulharis** [anasty17/mirror-leech-telegram-bot#1258]
docker-compose --env-file /mnt/usb/Mirror/mltb/mltb/config.env up
Creating mltb_app_1 ... done
Attaching to mltb_app_1
app_1  | 2022-12-01 09:29:07,632 - root - INFO - Creating client from BOT_TOKEN
app_1  | 2022-12-01 09:29:07,636 - root - WARNING - MEGA API KEY not provided!
app_1  | 2022-12-01 09:29:07,637 - root - WARNING - MEGA Credentials not provided!
app_1  | 2022-12-01 09:29:07,638 - root - WARNING - BASE_URL not provided!
app_1  | 2022-12-01 09:29:08,844 - root - INFO - Initializing Aria2c
app_1  | 2022-12-01 09:29:13,261 - bot - INFO - Creating Telegraph Account

**Comment by anasty17** [comment]
What is the vps location?

**Comment by devabdulharis** [comment]
VPS indonesia

> What is the vps location?

**Comment by devabdulharis** [comment]
VPS Indonesia

**Comment by anasty17** [comment]
Try this

/eval from requests import get
r = get("https://graph.org/")
print(r.status_code)

**Comment by devabdulharis** [comment]
returned 200.
