### ISSUE TITLE
Got: userRateLimitExceeded

### ISSUE THREAD

**Issue by carolynsteeves1** [anasty17/mirror-leech-telegram-bot#1259]
app_1  | 2022-12-01 19:16:09,894 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Got: userRateLimitExceeded, Trying Again.
app_1  | 2022-12-01 19:16:10,141 - googleapiclient.http - WARNING - Encountered 403 Forbidden with reason "userRateLimitExceeded"
app_1  | 2022-12-01 19:16:10,141 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Switching to 54.json service account
app_1  | 2022-12-01 19:16:10,141 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 54.json service account
app_1  | 2022-12-01 19:16:10,321 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Got: userRateLimitExceeded, Trying Again.
app_1  | 2022-12-01 19:16:10,626 - googleapiclient.http - WARNING - Encountered 403 Forbidden with reason "userRateLimitExceeded"
app_1  | 2022-12-01 19:16:10,627 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Switching to 55.json service account

------

This problem only happens when deploying on oracle. Token.pickle is uploaded. Just tried creating new sas accounts with new google account + new shared drive, and still the same

**Comment by anasty17** [comment]
Not code issue

**Comment by carolynsteeves1** [comment]
yes it is or else its something new, since this hasnt been happening before

**Comment by anasty17** [comment]
Not related token.pickle not related to code this from google api. Check shared drive limits

**Comment by anasty17** [comment]
U guys don't know anything about what r u using and asking stupid questions and no one want to read. Read about service accounts in readme maybe u will understand more about clone there a limit from file creator also. READ ! DON'T REPLY TO THIS COMMENT PLZ

**Comment by carolynsteeves1** [comment]
.

**Comment by anasty17** [comment]
I think u r stupid which have a keyboard. I said "READ ! DON'T REPLY TO THIS COMMENT PLZ".
I said also:
"there is a limit from file creator also". Focus on this stupid. Even if create 1k new service account will get the same result that because u r stupid and u don't want to read.
