### ISSUE TITLE
How can I create .netrc

### ISSUE THREAD

**Issue by Dekad11** [anasty17/mirror-leech-telegram-bot#126]
How can I create netrc file? I'm generate youtube cookies but i am unable to generate netrc file please help

![IMG_20211205_163627](https://user-images.githubusercontent.com/91631500/144743990-5adb068e-6281-424c-b934-905083a0582a.jpg)

**Comment by anasty17** [comment]
@Dekad11 Check readme

**Comment by Dekad11** [comment]
I have seen readme but am not able to create this netrc file Where is this file hidden? Can you tell me little the easy way

**Comment by anasty17** [comment]
Create file !! And name it .netrc ... google search how to create file

**Comment by anasty17** [comment]
Show hidden files .... already written also!!! Google search how to show hidden files on ur os
