### ISSUE TITLE
Docker deployment failing 

### ISSUE THREAD

**Issue by Niffy-the-conqueror** [anasty17/mirror-leech-telegram-bot#1264]
**Describe the bug**
Deployment failed with docker.

**To Reproduce**
1. Fill env
2. docker build . -t mtlb && docker run mtlb
3. Log (everything goes fine till telegraph):
```2022-12-04 11:32:43,858 - bot - INFO - Creating Telegraph Account
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 18, in <module>
    from .modules import authorize, list, cancel_mirror, mirror_status, mirror_leech, clone, ytdlp, \
  File "/usr/src/app/bot/modules/search.py", line 259, in <module>
    initiate_search_tools()
  File "/usr/src/app/bot/modules/search.py", line 24, in initiate_search_tools
    src_plugins = jsonloads(SEARCH_PLUGINS)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
**Expected behavior**
Bot should deploy without issues 

**Screenshots**

**Additional context**

**Comment by anasty17** [comment]
Check search plugins var value

**Comment by Niffy-the-conqueror** [comment]
Well I changed the search plugins value using /bsetting (like you said previously when I mentioned the rss issue) and redeployment with the same database URL causes this
Well it seems like a bug with the bot

**Comment by Niffy-the-conqueror** [comment]
Think I found the issue
I never set SEARCH_PLUGINS var on first deployment
But I did after deployment using bsetting 
Which is why I never noticed  the telegraph issue ;it happens everytime on the server I think it's the server issue 
--------
1. I have a suggestion give a method to clear problematic variables from database since bot no longer reads from config.env
2. Add an exception catcher for telegraph to enable it continue deploying on error

**Comment by anasty17** [comment]
> Think I found the issue I never set SEARCH_PLUGINS var on first deployment But I did after deployment using bsetting Which is why I never noticed the telegraph issue ;it happens everytime on the server I think it's the server issue
> 
> Got 2 Suggestions
> 
> 1. give a method to clear problematic variables from database since bot no longer reads from config.env
> 2. Add an exception catcher for telegraph to enable it continue deploying on error

Read readme to know how to fill the settings! Make sure from u had done in settings before restart. U can edit database data from mango database official site. U r the bug! READ BEFORE USING!

**Comment by anasty17** [comment]
It's not like rss! That was a bug but when u enter fill the variable wrong then its ur problem and u should edit it from Database. Or if u don't use database then edit config.env. I can't handle all people mistakes!

**Comment by Niffy-the-conqueror** [comment]
> Read readme to know how to fill the settings! Make sure from what u had done in settings before restart. U can edit database data from mango database official site. U r the bug! READ BEFORE USING!

Resetting the variable to none worked

**Comment by Niffy-the-conqueror** [comment]
The issue is from me (or at least the current vps) I have it deployed locally elsewhere no issues
