### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by nareshmodi8520** [anasty17/mirror-leech-telegram-bot#1268]
I am getting this error "[Errno 32] Broken pipe" at the time of uploading. Some times its not comming but most of the times its there.
Problem started 15 hrs ago.
Please Help

![Screenshot 2022-12-08 110625](https://user-images.githubusercontent.com/119057373/206365491-0ee3fea1-b687-4020-87b2-98e9036f69e1.jpeg)

**Comment by anasty17** [comment]
Connection issues

**Comment by a0v0** [comment]
@nareshmodi8520 is your problem fixed?
