### ISSUE TITLE
[Errno 32] Broken pipe

### ISSUE THREAD

**Issue by Ustad-Op** [anasty17/mirror-leech-telegram-bot#1274]
Hey Sir
Whenever I'm trying to mirror any file from telegram or external link
Bot Downloading file properly but not uploading it and getting "@USERNAME [Errno 32] Broken pipe" this is replied message

**Comment by anasty17** [comment]
Connections issues

**Comment by a0v0** [comment]
@Ustad-Op is your problem fixed?
