### ISSUE TITLE
Qbittorrent Upload Speed Issue

### ISSUE THREAD

**Issue by vishansh** [anasty17/mirror-leech-telegram-bot#1275]
In qbittorrent it is uploading (seeding) file during downloading can we limit upload speed to 10-100Kb/s coz it's using credit in vps very fast any solution?

**Comment by anasty17** [comment]
Yes u can from bot settings if u addee database or edit qBittorrent.conf if u didn't add database.

BUT if u add limit for uploading while downloading this will effect the download speed also. And this not an issue open discussion next time
