### ISSUE TITLE
Feature request: - bypass limits

### ISSUE THREAD

**Issue by rahul112kapoor** [anasty17/mirror-leech-telegram-bot#128]
Brother pls add feature to bypass all limits i.e. clone limit, mega limit, direct zip unzip limit for owner and sudo users

**Comment by anasty17** [comment]
@rahul112kapoor Yeah bro will add all group features soon in separated branch for groups ... and from master i will remove all groups features... but need time to finish major updates

**Comment by rahul112kapoor** [comment]
Nice bro that will be great having a seperate branch for group users ....
All the best bro
Waiting for those major updates ...

**Comment by ghostmirrorlab** [comment]
epic move

> @rahul112kapoor Yeah bro will add all group features soon in separated branch for groups ... and from master i will remove all groups features... but need time to finish major updates



> @rahul112kapoor Yeah bro will add all group features soon in separated branch for groups ... and from master i will remove all groups features... but need time to finish major updates

epic move

**Comment by ghostmirrorlab** [comment]
🙄 may I know why u deleted my comment?

**Comment by anasty17** [comment]
@ghostmirrorlab Sorry bro by wrong also closed the issue by wrong 🤦‍♂

**Comment by ghostmirrorlab** [comment]
> @ghostmirrorlab Sorry bro by wrong also closed the issue by wrong 🤦‍♂

Ahh lol okay
