### ISSUE TITLE
Gdrive Uploading Error (Error 104) 

### ISSUE THREAD

**Issue by sennoncap** [anasty17/mirror-leech-telegram-bot#1280]
i have an error with code of Errno 104] Connection reset by peer....
its occour when uploading to google drive and 
most of around 500MB is ok and over 1GB failed like this..

is it gdrive server error or others ?

**Comment by anasty17** [comment]
Show logs

**Comment by sennoncap** [comment]
Sir i am using Azure VPS before and now i am changing to oracle free that is slow speed compare with AZURE VPS.
but There is no errors on Oracle Free VPS...
sorry for logs ... i delete that instance sir..

**Comment by anasty17** [comment]
This related to vps location. If ur vps is india so it's very bad. Connection error nothing else

**Comment by sennoncap** [comment]
Thanks for everything sir. thanks so much
