### ISSUE TITLE
Add .m3u8 link support 

### ISSUE THREAD

**Issue by Cinichi** [anasty17/mirror-leech-telegram-bot#1289]
I had try to leech m3u8 link using ytdl command
But got this error 
(@ri_pan your download has been stopped due to: ERROR: [generic] yftj8f7kq8kkq7r3bqgngsg2g2Zf223qvyvjg485wgvlbqk11srwm: Requested format is not available. Use --list-formats for a list of available formats)
So please add m3u8 link support

**Comment by Cinichi** [comment]
Sorry I had put value on ytdl quality that why I got this error

**Comment by anasty17** [comment]
No this problem from yt-dlp. It was working good with select quality before in old versions. I will report soon.
