### ISSUE TITLE
Heroku Deployment Support 

### ISSUE THREAD

**Issue by goldenevil47** [anasty17/mirror-leech-telegram-bot#1304]
Hello there dear dev

Idk why you have removed heroku branch and I can't deploy it using heroku and GitHub workflow. Please add heroku support back or guide me through the process to add heroku support myself.

**Comment by khainee** [comment]
Use WZML

**Comment by khainee** [comment]
Use [WZML](https://github.com/weebzone/WZML)

**Comment by goldenevil47** [comment]
> Use [WZML](https://github.com/weebzone/WZML)

I have been using it for about 2 months now but recently it's not working anymore, while uploading a file it always throws following error:

@xUltimateNoobx HttpError 403 when requesting None returned "User rate limit exceeded.". Details: "[{'domain': 'usageLimits', 'reason': 'userRateLimitExceeded', 'message': 'User rate limit exceeded.'}]"

I have tried with multiple Shared Drives but always same error

**Comment by khainee** [comment]
Change
[UPSTREAM_REPO = "https://github.com/anasty17/mirror-leech-telegram-bot"
UPSTREAM_BRANCH = "h-code"]
in your config

**Comment by goldenevil47** [comment]
> Change [UPSTREAM_REPO = "https://github.com/anasty17/mirror-leech-telegram-bot" UPSTREAM_BRANCH = "h-code"] in your config in wzml heroku branch

Ok thanks, I'll try and report ASAP

**Comment by goldenevil47** [comment]
> Change [UPSTREAM_REPO = "https://github.com/anasty17/mirror-leech-telegram-bot" UPSTREAM_BRANCH = "h-code"] in your config in wzml heroku branch

I tried it but still same error. Tried with 2 different drives
