### ISSUE TITLE
/btsel ERROR not responding?

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1306]
**Describe the bug**
Hi, when execute /btsel bot does not respond?

Also I'm getting `your download has been stopped due to: No enough space for this torrent on device` ERROR

**Expected behavior**
Bot does respond when /btsel gets executed.

[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10300585/log.txt)

**Comment by anasty17** [comment]
/btsel fixed
2nd error because storage not enough. Use args `s` while adding torrent. /btsel incase u forget to select while adding the torrent or if u have changed ur mind. But better to use arg   s. Check /qm for more notes

**Comment by erickyun** [comment]
Thank you very much :)

**Comment by erickyun** [comment]
> 2nd error because storage not enough. 

My second error still persist sadly?
Even though I have enough storage I'm getting `No Enough Storage` Error? 

I have 14GB free storage on my vps. My torrent size is 1.8GB and I am getting no enough storage error?
When I download different file in the same torrent that has higher storage size 3.8GB there is no error! I also tried with a different torrent that has 5.35GB and there was no error! 
But for only those specific files I get error? (I select that files with /qm s since my max storage is 14GB and complete torrent is 16GB) 

[log_for-2nd-error.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10300650/log.txt)

**Comment by anasty17** [comment]
Send the torrent u are trying to mirror

**Comment by erickyun** [comment]
> Send the torrent u are trying to mirror https://t.me/mltb_official_group Join the group and report there

My friend says the torrent is from 1337x "wednesday qxr ghost" 16.1 GB 
[log (for-first-error).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10318576/log.22.txt)
And 
Also for "Black Christmas Unrated qxr Ghost" he got namefrommovie.mkv.!qB the `.!qB` was not removed when it was uploaded to gdrive he says! 
[log (for-second-error).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10318551/log.23.txt)
He says that problem mostly happens on 1337x?

Ofcourse I told my friend that he should stop downloading immediately these torrents.

**Comment by anasty17** [comment]
Let him write there please. I made the group gor purpose
