### ISSUE TITLE
Maximum Recursion depth error

### ISSUE THREAD

**Issue by SoloLeveling7seven** [anasty17/mirror-leech-telegram-bot#1307]
**Describe the bug**

**To Reproduce**
1. /mirror to magnet link
2. On uploading time it gives error
3. Check logs
![Screenshot_2022-12-25-21-48-36-013_org telegram messenger](https://user-images.githubusercontent.com/109235836/209494755-f4118388-96e5-4870-ae12-b1d1bd06dbdc.jpg)

**Expected behavior**

> **Screenshots**
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10301322/log.txt)

![Screenshot_2022-12-25-21-48-36-013_org telegram messenger](https://user-images.githubusercontent.com/109235836/209494831-d06666a1-496b-4369-811e-a21515fa2fde.jpg)

**Additional context**
My telegram tag @ShadowYtt77 please message me i need help

**Comment by anasty17** [comment]
First update ur repo. And if u r up to date then this means u have added too many service accounts.  
Main problem in edu teamdrives. We can't upload anything to it.
