### ISSUE TITLE
Support debrid-link, real-debrid, and alldebrid?

### ISSUE THREAD

**Issue by bidbiz** [anasty17/mirror-leech-telegram-bot#1309]
Can the bot support debrid because if you use it, it can support multiple hosters?
I saw an example implementation in this repo https://github.com/jlnsrk/debridlink , can you add it to the bot? Thank you in advance.

**Comment by harissoot** [comment]
> Can the bot support debrid because if you use it, it can support multiple hosters? I saw an example implementation in this repo https://github.com/jlnsrk/debridlink , can you add it to the bot? Thank you in advance.

u know what problem?most debrid block vps ip/dedicated ip

**Comment by FHulayyil** [comment]
> > Can the bot support debrid because if you use it, it can support multiple hosters? I saw an example implementation in this repo https://github.com/jlnsrk/debridlink , can you add it to the bot? Thank you in advance.
> 
> u know what problem?most debrid block vps ip/dedicated ip

You can route the container through a vpn and it'll work. I did it with gluetun & mullvad and Real-Debrid worked fine on jdownloader2
