### ISSUE TITLE
YouTube video download problem

### ISSUE THREAD

**Issue by Dekadas1** [anasty17/mirror-leech-telegram-bot#131]
**Why I am faced error?**
![IMG_20211207_131049](https://user-images.githubusercontent.com/95675552/144988469-c49373c3-493c-4456-ae4a-bcbf245f7c3c.jpg)
![IMG_20211207_131401](https://user-images.githubusercontent.com/95675552/144988643-f6bb83a5-b31c-40d7-aded-ff416069f2fb.jpg)
![IMG_20211207_131616](https://user-images.githubusercontent.com/95675552/144988679-aba0e050-47eb-49bb-b685-e287f6a09a5a.jpg)

**Comment by anasty17** [comment]
Remove auth from .netrc .... why using both of cookies and .netrc ... u need only one method to login ... and youtube only works with cookies so remove them from .netrc

**Comment by Dekadas1** [comment]
![IMG_20211207_135120](https://user-images.githubusercontent.com/95675552/144992933-18a3f17f-05c6-46ad-b69e-b5940afed49a.jpg)
I have removed .netrc but still not working

**Comment by Dekadas1** [comment]
https://youtu.be/lFX_15NRpmw, https://youtu.be/y4FiCl-tUJc, https://youtu.be/8_Cw99SiHvc

Video link

**Comment by anasty17** [comment]
@Dekadas1 yeah only for that kind video that only has image along video. Maybe issue from yt-dlp report to yt-dlp dev

**Comment by anasty17** [comment]
@Dekadas1 Mostly geo restriction not bug

**Comment by Dekadas1** [comment]
So how to fix this

**Comment by anasty17** [comment]
Change bot location! (Ip) ... u don't have many options

**Comment by Doramon3** [comment]
😔

**Comment by Dekadas1** [comment]
😔

**Comment by Dekadas1** [comment]
I changed the bot IP location like you said It's working Thanks bro👍

**Comment by Dekadas1** [comment]
Will there be any problem if I use Europe region on heroku?

**Comment by anasty17** [comment]
@Dekadas1 Sure no problem

**Comment by Dekadas1** [comment]
Ok thanks again
