### ISSUE TITLE
Deploy Mirror Telegram Bot in Render.com (Heroku Alternatives)

### ISSUE THREAD

**Issue by Namlee123** [anasty17/mirror-leech-telegram-bot#1310]
Hello Bro!
Thank you for creating a great tool.
Render is almost the same as Heroku, and in my opinion it is even better, free account, up to 750 hours/month runtime.

I tried to run your old code on "Render" platform, by heroku branch.
I found it compatible and the BOT works, but it still has some errors, I don't understand the code like you, so I can't fix it.
I think, if you spend a few hours, a "Mirror Bot" implementation on "Render" (replacing Heroku) is possible. Because no one understands it better than the person who created it.

I quote a video someone made on Render:
https://www.youtube.com/watch?app=desktop&v=FlUb5HnRRm8

The error I get is that it generates two or three identical "BOT Mirrors" on the same BOT ID Telegram.
After downloading, switch to Upload but get an error: EOF occurs due to protocol violation (_ssl.c:2396)
Finally, I wish you a lot of health and happiness with your family in the new year.

**Comment by anasty17** [comment]
No support for any platform. Github will suspend my repo
