### ISSUE TITLE
Bulk Download

### ISSUE THREAD

**Issue by Gapemaster6** [anasty17/mirror-leech-telegram-bot#1311]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to download list of links from a txt file that I got from linkgrabber such as 1DM or IDM. Mirror command only works with links separated in a new message, however I want to send all links in one message or txt file. 

**Describe the solution you'd like**
I want the bot to be able to download all the links from the list (in one message) or txt file.

**Describe alternatives you've considered**
Please refer to this https://github.com/X-Gorn/BulkLoader.

**Additional context**
These are some screenshot from the bot above
![image](https://user-images.githubusercontent.com/121523855/210123042-4db2947f-7272-4014-a5e3-03d67c22b575.png)

with zip support if desired
![image](https://user-images.githubusercontent.com/121523855/210123101-255d9a72-ccb4-4337-8b77-e28d7d561a58.png)
 
all links in one message
![image](https://user-images.githubusercontent.com/121523855/210123592-06cae39a-a5b1-48e6-b154-68b3bd58f8f9.png)

**Comment by anasty17** [comment]
I remember i have post smal script for this before. I will find it and post it in channel. Check it soon
