### ISSUE TITLE
config_dict is not defined

### ISSUE THREAD

**Issue by sennoncap** [anasty17/mirror-leech-telegram-bot#1315]
i am facing an issue with config_dict is not defined error .. and cannot mirror anymore sir

**Comment by junedkh** [comment]
Fixed

**Comment by sennoncap** [comment]
is it need to reinstall docker image sir?

**Comment by sennoncap** [comment]
old repo support directlinks of Megaup ..
But new repo not support directlinks 
is that right sir ?

**Comment by anasty17** [comment]
> is it need to reinstall docker image sir?

No, u only need to restart after update. Or incase we added new requirement in requirements.txt

**Comment by anasty17** [comment]
> old repo support directlinks of Megaup .. But new repo not support directlinks is that right sir ?

Same repo. What r u talking about! This is wrong

**Comment by sennoncap** [comment]
i cannot mirror directlinks of megaup sir.....
i donot why? sir

**Comment by anasty17** [comment]
Who told u that i know what r u talking about! What megaup!?

**Comment by sennoncap** [comment]
sorry sir,
megaup .net sir and it doesnot show directlink automatically but your mirror bot support many of directlinks before sir.
thanks for replying sir...

**Comment by anasty17** [comment]
I never saw this before! There was no megaup.net direct link generator before!

**Comment by sennoncap** [comment]
This is original links sir >>> https://megaup .net/19o9y/Real.Fake.S01E01.1080p.CM.mp4

This is Direct Link that support by your bot sir >>>https://f72.megaup .net/19o9y/Real.Fake.S01E01.1080p.CM.mp4?download_token=b66a028ec7191d4bab9837fceb2720427704bfa7fd00313136ad18842c3a1b6f

this working before and not working sir

**Comment by anasty17** [comment]
Then u was using a modified repo

**Comment by sennoncap** [comment]
yes sir ,, its working before sir 
not woking in latest repo sir .
