### ISSUE TITLE
[Feature Request] Add RSSSUB and RSS_COMMAND for every user

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1320]
**Is your feature request related to a problem? Please describe.**

Hi,

İn user settings `/usetting` it would be great if every user could add its own `RSS_COMMAND` and it `own RSS feed` to subscribe. 

Hope you can add this in your TODO list sir?
And thank you for your great work btw keep it up.👍🙂

**Comment by anasty17** [comment]
Okay but no eta
Many things todo especially after asyncio in ptb

**Comment by erickyun** [comment]
> Okay but no eta Many things todo especially after asyncio in ptb

Thank you very much looking forward to it. ☺️👍

**Comment by anasty17** [comment]
Done

**Comment by erickyun** [comment]
> Done

Thank you very much sir. 👍👍
I greatly appreciate the work you do here.
