### ISSUE TITLE
Problem with unzipping RAR files

### ISSUE THREAD

**Issue by Tommitony** [anasty17/mirror-leech-telegram-bot#1326]
When tried to using unzipmirror command on rar file bot will not unzip and upload the folder, it will upload directly the rar file without unzipping it.
There is not other unrar command separately to unrar the rar files.. please add new unrar cmd or embed it in unzip cmd please

**Comment by anasty17** [comment]
What if i won't to extract the compressed file inside rar ?
Do it twice

**Comment by Tommitony** [comment]
Making clear it's not having a rar file inside the rar file to mirror twice!!
It is not able to unzip on the first rar itself...I will be adding the pic..
![Screenshot_20230108-105222_Telegram](https://user-images.githubusercontent.com/119886999/211181849-55c31a2f-b6d0-481d-9b38-6526ccaaba51.jpg)

See it uploaded as rar file itself...even if I used unzipmirror cmd!!

**Comment by anasty17** [comment]
Then why all explanation. Say extract not working! 
Send the link! And send logs! Maybe issue from the file!

**Comment by Tommitony** [comment]
Log_file link - [here](https://tgdl.eu.org/fast/1/BQACAgUAAxkBAAEINHljulxcu3K_yKwUZfSuikOPqH7x7gACEAcAAuEn0VXwdlciJrPzNR4E/log.txt) 

Rar file link - [here](https://drive.google.com/file/d/124CfyogvzYVwSB4p-eYENkzHehDe85PW/view?usp=drivesdk) 

In the log file at 11th line you can "unable to extract"...

**Comment by anasty17** [comment]
Yeah try any other rar. If extraction worked then problem in file which means corrupted!
