### ISSUE TITLE
Selection of favorite folders

### ISSUE THREAD

**Issue by kuesttman** [anasty17/mirror-leech-telegram-bot#1327]
**Is your feature request related to a problem? Please describe.**

Hi everyone,

Could add support for selecting favorite drive folders for mirroring. Instead of informing a single ID in the bot's settings, you could inform several IDs or have a selection menu of available folders that the bot can use to mirror.
It's possible?

**Comment by anasty17** [comment]
I will think about it

**Comment by anasty17** [comment]
In todo soon but not favorite folders
