### ISSUE TITLE
Cant booting

### ISSUE THREAD

**Issue by CevreMuhendisi** [anasty17/mirror-leech-telegram-bot#1328]
![image](https://user-images.githubusercontent.com/59526034/211480329-44af7f6f-7d22-42b9-ba86-58f5e9ff3d2f.png)

İ need help, i cant booting my mirror bot

**Comment by anasty17** [comment]
Use my docker

**Comment by CevreMuhendisi** [comment]
> Use my docker

i cant booting your docker imaje, can you help me ?

**Comment by anasty17** [comment]
Why u can't. And no i can't help without my docker
