### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by CevreMuhendisi** [anasty17/mirror-leech-telegram-bot#1329]
Docker imaje has no internet

![image](https://user-images.githubusercontent.com/59526034/211500895-5358050d-5083-41f9-9dcf-339b753fa97e.png)

i need help. im using armv7 device

**Comment by anasty17** [comment]
Well this not docker. This repo clone and issue in ur connection.
![Screenshot_20230110-164327_Chrome](https://user-images.githubusercontent.com/77075674/211581875-2362b305-be60-4250-a191-487cb7036ea9.jpg)
