### ISSUE TITLE
[Error] bot sometimes uploads unfinished torrent with /qm

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1335]
**Describe the bug**
Sometimes bot uploads unfinished torrent! And this does not Happen on a specific torrent file.

When I look at gdrive I see the uploaded torrent has still `.!qB` in its name!

 I do a crc32 hash check on the file and see the uploaded file has not the same hash as the original .mkv video file! So The uploaded torrent is uploaded without finishing completely I think.

**To Reproduce**
1. When I use `/qm` 
2. Before/after/while Upload ..
3. Check logs I see `.!qB` in its name

**Expected behavior**
Bot finishes downloading torrent file completely, before uploading to gdrive. 
And has no  `.!qB` in File Name.

[unfinished-torrent-error-log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10417100/unfinished-torrent-error-log.txt)

**Comment by anasty17** [comment]
Ok this will get fixed soon. Known rarely issue.

**Comment by erickyun** [comment]
> Ok this will get fixed soon. Known rarely issue.

Thanks 🙂👍👍

**Comment by askfriends** [comment]
+1

**Comment by Ignite191919** [comment]
+1

**Comment by anasty17** [comment]
Fixed
