### ISSUE TITLE
[Error] while leeching terabox link 

### ISSUE THREAD

**Issue by sourabhbeni** [anasty17/mirror-leech-telegram-bot#1337]
**Describe the bug**
Terabox link has been changed from terabox.com to nephobox.com

**Comment by anasty17** [comment]
@junedkh

**Comment by junedkh** [comment]
Okay I'll fix it 👍

**Comment by anasty17** [comment]
https://github.com/anasty17/mirror-leech-telegram-bot/commit/c7ba3766f7556c38739efe9cacd591a82d6f28fe

**Comment by askfriends** [comment]
can u share sample terabox cookies tx file?

**Comment by nanami157** [comment]
Terabox links not working. It says need to verify. I've provided terabox cookie (terabox.txt).
![Screenshot 2024-06-01 225231](https://github.com/anasty17/mirror-leech-telegram-bot/assets/155349961/6f996a64-89cc-44f4-886f-bb6248a7695e)
[terabox[1].txt](https://github.com/user-attachments/files/15522590/terabox.1.txt)

**Comment by nanami157** [comment]
![Screenshot 2024-06-01 at 23-04-02 Credentials – APIs   Services – EMON – Google Cloud console](https://github.com/anasty17/mirror-leech-telegram-bot/assets/155349961/4d511db8-5fbf-47a4-8939-6eb82e94c1c5)
[terabox.txt](https://github.com/user-attachments/files/15522657/terabox.txt)
