### ISSUE TITLE
ERROR occurs during leech

### ISSUE THREAD

**Issue by kuesttman** [anasty17/mirror-leech-telegram-bot#1338]
**Describe the bug**
an error occurs during leech, I try to upload a telegram file to the drive using /mirror and it shows the error below in the log.
An error occurs also during leech to telegram.

app_1  | Exception in thread Thread-11:
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
app_1  |     self.run()
app_1  |   File "/usr/lib/python3.8/threading.py", line 870, in run
app_1  |     self._target(*self._args, **self._kwargs)
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/telegram_downloader.py", line 92, in add_download
app_1  |     media = _dmsg.document or _dmsg.video or _dmsg.audio or None
app_1  | AttributeError: 'NoneType' object has no attribute 'document'

**Comment by anasty17** [comment]
Restart ur bot. Pyrogram is not stable nowadays or maybe issues in ur connection
