### ISSUE TITLE
Add some Download option for bulk download to ytdlp links

### ISSUE THREAD

**Issue by niranjantechofficial** [anasty17/mirror-leech-telegram-bot#1339]
*

**Additional context**

Hi brother, 

I have some ytdlp support links... Every time i can't give links manually to bot...i need support like yt playlist download...all links add in Que and download One by One...
![Uploading Screenshot_2023-01-16-11-44-31-608_com.mi.android.globallauncher.jpg…]()

Like this i stored links in text file in this format {Name:url} can you give support to download bulk request... Like if we sent links using txt file to bot.. Bot need to fetch that text file and download video's in Que

I can give links manually to bot.. But now i have 100 links i can't give it manually... Do something

Please respond me 
Thank you

**Comment by anasty17** [comment]
Set yt-dlp default quality and use multi link. And before thise check channel howbtot extarct links from txt file.

Next time try to write more clear sentences and wait the photo to upload

**Comment by niranjantechofficial** [comment]
Brother i need bulk download... Ytdlp support links... 

Every time i given links like this👇👇👇
But i have 100+ links.. I can't send all links separately 

![Screenshot_2023-01-16-11-57-07-627_org telegram messenger](https://user-images.githubusercontent.com/61946705/212612343-fbb17f4d-6a6f-48a2-a87c-b9ba8935d875.jpg)


I have more links like this.. 👇👇 how to download this link like playlist download... Or bulk download in theared

![Screenshot_2023-01-16-11-57-33-417_bin mt plus](https://user-images.githubusercontent.com/61946705/212612456-9d099178-f7c9-4aad-a6a6-d11b7fb82256.jpg)

**Comment by dfslammirror** [comment]
![IMG_20230129_144244.jpg](https://user-images.githubusercontent.com/96507199/215317161-2ca1859f-6776-46d8-ab3e-1218d958462c.jpg)

Showing this error, did I miss anything? Need help. Thanks in advance...

**Comment by edwardtucci01** [comment]
![IMG_20230129_144244](https://user-images.githubusercontent.com/123895021/215345837-77c9b8bb-b0bf-41cf-86d8-f447e2f4340b.jpg)
Bro, what mistake did I do here? It is not working. Need your help.
