### ISSUE TITLE
Adding support for scalingo

### ISSUE THREAD

**Issue by Krish241** [anasty17/mirror-leech-telegram-bot#134]
scalingo.com is a very good alternative for heroku

**Comment by tiararosebiezetta** [comment]
I have known and used scalingo for a year now. 

That will need so many changes as it doesn't support deployment with Docker. Only using python buildpack and Procfile will sure be hard for installating dependencies. 

Well, I don't think the effort will be that worth it as scalingo only offers 30 days trial (temp mail can be used though actually) and 512MB RAM free plan is not much (it's different from heroku free tier, they give 512MB RAM but they allow you to utilize 2x of the RAM you're given).

Just my opinion though, I'm not the developer 😅

**Comment by anasty17** [comment]
> I have known and used scalingo for a year now.
> 
> That will need so many changes as it doesn't support deployment with Docker. Only using python buildpack and Procfile will sure be hard for installating dependencies.
> 
> Well, I don't think the effort will be that worth it as scalingo only offers 30 days trial (temp mail can be used though actually) and 512MB RAM free plan is not much (it's different from heroku free tier, they give 512MB RAM but they allow you to utilize 2x of the RAM you're given).
> 
> Just my opinion though, I'm not the developer 😅

Thank u
