### ISSUE TITLE
Cant Load .env From VPS

### ISSUE THREAD

**Issue by lyco-wangy** [anasty17/mirror-leech-telegram-bot#1341]
I Have fill the Env BASE_URL,CMD_SUFFIX,GDRIVE_ID,

but if i start the bot

Log is BASE_URL is not provided
& I try run /m command 
I got reply GDRIVE _ID
is not Exist & The suffix
not effect

**Comment by lyco-wangy** [comment]
yep,i add DATABASE_URL
but not for UPSTREAM_REPO

**Comment by anasty17** [comment]
So edit from botsetting! Read readme
