### ISSUE TITLE
getting error : binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by Nobody12541** [anasty17/mirror-leech-telegram-bot#1343]
I am trying to deploy the bot but getting this error again and again.
I don't know where the problem is. 

![Capture](https://user-images.githubusercontent.com/101923792/213750586-566becb8-73db-45c7-86e0-994a14d7100b.PNG)

I have spent 6 hours trying to get to work but no luck. please help me.

**Comment by anasty17** [comment]
Not my repo. Why reporting to me!
