### ISSUE TITLE
mirroring or leeching to drive not work

### ISSUE THREAD

**Issue by Manssizz** [anasty17/mirror-leech-telegram-bot#1347]
**Describe the bug**
leeching file to telegram working. but  mirroring or leeching with gdrive. bot replied with `GDRIVE_ID not Provided!`

**To Reproduce**
1. 2 Method i try
- Change value `GDRIVE_ID` with teamdrive
- Use id drive folder.
2. VPS logs not show any error

**Screenshots**
Proof
![image](https://user-images.githubusercontent.com/23637327/213975595-65e03453-898b-44b3-b2f8-7f9a75331538.png)

config.env
![image](https://user-images.githubusercontent.com/23637327/213975383-ccea7d03-ef94-479e-b12e-723a188464d7.png)

docker logs
![image](https://user-images.githubusercontent.com/23637327/213975440-5decd76d-74b7-4e7f-b115-8dd9581a521b.png)

**Comment by anasty17** [comment]
If DATABASE_URL added then u should edit it grom botsettings using /bsetting

**Comment by Manssizz** [comment]
thanks!
