### ISSUE TITLE
[noob] Using service account

### ISSUE THREAD

**Issue by Manssizz** [anasty17/mirror-leech-telegram-bot#1348]
how to use service account? i try using SA but my drive quota still cutting.

folder structure
![image](https://user-images.githubusercontent.com/23637327/214010385-7b4370d2-cb8f-492f-8e8b-21c9aa14260a.png)

config.env
```
IS_TEAM_DRIVE = "True"
USE_SERVICE_ACCOUNTS = "True"
```

Cut off quota storage
![image](https://user-images.githubusercontent.com/23637327/214011098-5c4036d8-dc87-48a2-a78c-c40532a027dc.png)

**Comment by anasty17** [comment]
Read about database. Once u added DATABASE_URL and start the bot then all vars should be edit from bot only.
