### ISSUE TITLE
cant dl terabox folders

### ISSUE THREAD

**Issue by askfriends** [anasty17/mirror-leech-telegram-bot#1349]
**Describe the bug**
Im getting KBs file while downloading terabox folder link, seems like folder dl isnt supported yet 

**To Reproduce**
1. /mirror teraboxFolderUrl
2. after..
3. getting file in kbs

**Expected behavior**
It should mirror folder link as it should

**Screenshots**
![tera](https://user-images.githubusercontent.com/2517219/214024817-02a650f5-3a63-46dc-a9de-93c5b774be47.png)

**Additional context**

**Comment by junedkh** [comment]
folder download not support for now
