### ISSUE TITLE
Feature request "Batch Download"

### ISSUE THREAD

**Issue by mohamedkaissi** [anasty17/mirror-leech-telegram-bot#1352]
Batch download.
Like i send a txt file has multiple links , and the bot mirror them.
This feature is available here https://github.com/Sam-Max/rclone-mirror-leech-telegram-bot

**Comment by anasty17** [comment]
I will add from text have more than one link and from file

**Comment by jiusheng6** [comment]
> 
Is it possible to add a batch decompression upload?

**Comment by anasty17** [comment]
U mean extract?
If yes then sure when i add this feature then it will be available for archive and extract

**Comment by jiusheng6** [comment]
> U mean extract? If yes then sure when i add this feature then it will be available for archive and extract

Yes, look forward to the addition of new features

**Comment by anasty17** [comment]
In todo list
