### ISSUE TITLE
Add support for devuploads

### ISSUE THREAD

**Issue by zYxDevs** [anasty17/mirror-leech-telegram-bot#1359]
Can you add support download from devuploads.com

Thanks you!

**Comment by anasty17** [comment]
Maybe @junedkh can do this. I don't have time to add direct link support for all people need

**Comment by FollowNaim** [comment]
yes. we need this.

**Comment by anasty17** [comment]
Owner know us 😂 maybe later to keep his eyes on

**Comment by junedkh** [comment]
> Owner know us 😂 maybe later to keep his eyes on

i grab link but it need cookies i guess for start download in aria2c
i am thinking write own downloader in future so we can download from gofiles etc..
i found this cli [library ](https://github.com/Jules-WinnfieldX/CyberDropDownloader) i asked them make useable as module but they rejected 😒

**Comment by zYxDevs** [comment]
> Owner know us 😂 maybe later to keep his eyes on

hope they just dont care it:)

**Comment by anasty17** [comment]
> > Owner know us 😂 maybe later to keep his eyes on
> 
> i grab link but it need cookies i guess for start download in aria2c i am thinking write own downloader in future so we can download from gofiles etc.. i found this cli [library ](https://github.com/Jules-WinnfieldX/CyberDropDownloader) i asked them make useable as module but they rejected 😒

You can get the scrappers only. Not complex repo
