### ISSUE TITLE
qbmirror select before downloading

### ISSUE THREAD

**Issue by mmjason** [anasty17/mirror-leech-telegram-bot#136]
it is not working

**Comment by anasty17** [comment]
@mmjason How not working? Explain

**Comment by mmjason** [comment]
its just downloading not asking which files to select

**Comment by anasty17** [comment]
@mmjason Hit /help in ur bot and read how selection works after press other commands... from telegraph page

**Comment by mmjason** [comment]
for ex = /qbmirror s magnet:?xt=urn:bti II  i am using it not working somehow , by the way thanks for this great repo

**Comment by anasty17** [comment]
@mmjason https://t.me/mltbBugsReport join this group and try the test bot
