### ISSUE TITLE
download hotstar videos

### ISSUE THREAD

**Issue by promuserhu** [anasty17/mirror-leech-telegram-bot#1360]
![Screenshot_2023-02-15-02-38-00-32](https://user-images.githubusercontent.com/120303140/218863984-6baa8b84-fded-4725-8b2c-99fd0cdd28bd.jpg)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anasty17** [comment]
Bruh use indian vps
