### ISSUE TITLE
Bot  /rss menu `Subscriptions` shows only page 0 there is no clickable page 1 Error

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1365]
**Describe the bug**
 /rss menu `Subscriptions` shows only page 0 there is no page 1? I can't see every subscribed rss feed?

**Expected behavior**
To see every subscribed rss feed and see a clickable page 1 or 2.

**Comment by erickyun** [comment]
Also I know it is not related but /rss menu `Subscriptions` shows only page 0 there is no page 1? I can't see every subscribed rss feed?

**Comment by anasty17** [comment]
I will fix it

**Comment by anasty17** [comment]
Fixed
