### ISSUE TITLE
Error rss auto downloading not working

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1366]
**Describe the bug**
I did generate session string using python3 generate_string_session.py after mounting repo folder for sure. But bot won't auto download rss feed?
I did check logs and saw 
`ERROR - 'NoneType' object has no attribute 'id'`

**To Reproduce**
1. Used this Command rss menu
2. Check logs
[Log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10760925/Log.2.txt)

**Expected behavior**
bot auto download rss feed.

**Comment by anasty17** [comment]
Read readme

**Comment by anasty17** [comment]
Message is clear use supergroup

**Comment by anasty17** [comment]
Don't mix issues please u didn't tell if u r using supergroup or not!

**Comment by anasty17** [comment]
RSS_CHAT_ID is group or channel id ?

**Comment by anasty17** [comment]
Got the none type error. I will fix it soon

**Comment by anasty17** [comment]
But try to not use channel if u r using user session string

**Comment by anasty17** [comment]
I have pushed incomplete commit. I will fix rss for channel tomorrow.

**Comment by erickyun** [comment]
> Don't mix issues please u didn't tell if u r using supergroup or not! And regarding ur last question: yes. Leeching working well u should provide error

> I'm getting Use SuperGroup to leech with User! Error in group?

İn group I'm using group sir! Sorry if I was not clear enough.

**Comment by anasty17** [comment]
Yeah u also using channel for rss ?

**Comment by anasty17** [comment]
Fixed. I will add unpin for message soon

**Comment by erickyun** [comment]
> Fixed. I will add unpin for message soon

Thanks
