### ISSUE TITLE
IS_PREMIUM_USER: False ERROR

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1367]
**Describe the bug**
I did generate session string using python3 generate_string_session.py after mounting repo folder for sure. But bot won't upload file with a size of 2.5GB 
Even though I have Telegram premium account?

I noticed that
İf I generate session string 
With my **phone number** `IS_PREMIUM_USER: True` and Leech Split Size is 4194304000
But when I try to /leech something I'm getting `Use SuperGroup to leech with User! Error` in group?
I'm using group!

İf I generate session string with my **Bot token** /leeching does work but `IS_PREMIUM_USER: False`
and Leech Split Size is 2097152000 ?

Here is log of error.
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10762297/log.txt)

**Expected behavior**
Upload file with a greater size than 2GB with a premium account.

**Comment by anasty17** [comment]
Is it supergroup?

**Comment by erickyun** [comment]
> Is it supergroup?

Yes supergroup

**Comment by anasty17** [comment]
Should be fixed try

**Comment by erickyun** [comment]
Thank you it woks
