### ISSUE TITLE
ytdll

### ISSUE THREAD

**Issue by 320cuneyt** [anasty17/mirror-leech-telegram-bot#1368]
Youtube videos not downloading

ERROR: [youtube] VLG3if2NtvE: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by erickyun** [comment]
The "Unable to extract uploader id" problem is a yt-dlp problem not bot fault. 

https://github.com/anasty17/mirror-leech-telegram-bot/issues/1362#issuecomment-1433358294

Fixed it with 
```/shell python3 -m pip install --force-reinstall --no-cache-dir https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz``` and then restart bot.

**Comment by 320cuneyt** [comment]
thanks.

**Comment by anasty17** [comment]
This proper solution to install from master.

**Comment by erickyun** [comment]
> Not a proper solution to install always from master.

İt was a temporary fix! ytdlp has already fixed this issue on yt-dlp 2023.02.17 stable release.
