### ISSUE TITLE
rss auto download Error 'utf-8' codec can't decode byte 0xf9 in position 515: invalid start byte

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1369]
**Describe the bug**
Hi,
I'm using rss for group right now until there is fix for rss channel . 
Bot is auto downloading in supergroup from rss there is no problem there
But I did get a error in **Tag** with my **username** I think? Since my name has "ı" latin letter in it.

Bot did send error to telegram

`'utf-8' codec can't decode byte 0xf9 in position 515: invalid start byte`

`d%C4%B1n`

**To Reproduce**
1. Generated user string session and rsschatid is supergroup
2. Check logs and bot sends error only to telegram

I think since my username has `dın` in its name bot can't read latin letter **"ı"** am I right sır?

 I can just change my name just to "din" .

And it is not that urgent but I would appreciate a fix sır if possible.

**Comment by anasty17** [comment]
Ur usersname shown in rss download message ? So it take write it but can't read?
I will add support for sender_chat now, so u can use channel and i will add unpin directly if the message is pinned.

**Comment by anasty17** [comment]
Explain more about this when the error show up ?

**Comment by anasty17** [comment]
![Screenshot_20230218-010305_Plus](https://user-images.githubusercontent.com/77075674/219813691-da25afa2-be87-4de3-81a7-b1c2202f9d35.jpg)

**Comment by anasty17** [comment]
I guess u mean ur name contains that character and not ur username. Cz username can't accept those character. I was trying. So problem in html mention ?

**Comment by erickyun** [comment]
> I guess u mean ur name contains that character and not ur username. Cz username can't accept those character. I was trying. So problem in html mention ?

Yes sir I did mean my name.

> Explain more about this when the error show up ?

So I did set rsschatid to group and when new torrent was available torrent was send to group like this

`/qm https://randomsite/download/torrent
Tag: Namedın 88888888`

And then bot sends another two separate messages like  

`'utf-8' codec can't decode byte 0xf9 in position 515: invalid start byte`

`Named%C4%B1n`

But auto downloading works!

**Comment by anasty17** [comment]
Manually mean u added the name hyperlink right ?

**Comment by erickyun** [comment]
> Manually mean u added the name hyperlink right ?

Yes I did forward same message with hyperlink that give me a error.
