### ISSUE TITLE
/rss filter Error `Title Link inf: 1080` is filtered like `[['1'], ['0'], ['8'], ['0']]`

### ISSUE THREAD

**Issue by kendim2chiii** [anasty17/mirror-leech-telegram-bot#1370]
**Describe the bug**
Hi,
My repo is uptodate and today I tried to use /rss filter like
`Title Link inf: 1080`
But when I checked my subscriptions in rss menu I did see that the bot saved the filter like this `[['1'], ['0'], ['8'], ['0']]`

**To Reproduce**
1. Used this Command /rss menu 
2. Clicked subscribe button

**Expected behavior**
/rss filter gets saved like `[[1080]]`

**Screenshots**
![IMG_20230218_123902](https://user-images.githubusercontent.com/112317009/219853350-426c8cd4-78a7-4914-88ba-711607e657e6.jpg)

Also same error with letters `Title Link inf: /episode-` 
İs saved like `[['/'], ['e'], ['p'], ['i'], ['s'], ['o'], ['d'], ['e'], ['-']]`

**Comment by anasty17** [comment]
Opps lol

**Comment by anasty17** [comment]
Fixed thanks for reporting
