### ISSUE TITLE
Bot always send `Not added` message when rss send auto download

### ISSUE THREAD

**Issue by kendim2chiii** [anasty17/mirror-leech-telegram-bot#1371]
**Describe the bug**
Hi,
Sir I found out that when rss send auto download to channel then group Bot always send message to telegram? Even if download/upload finishes?

`Not added, maybe it will took time and u should remove it manually using eval!`

Downloading works there is no problem there.
But bot always send same message when rss send auto download?

**To Reproduce**
1. Used this Command rss menu
2. after/while downloading ..
3. Check logs
Nothing to see only message is send to telegram.

**Comment by anasty17** [comment]
What is that message?

**Comment by anasty17** [comment]
Well it's 60. Can u send link to test?

**Comment by kendim2chiii** [comment]
> This from qbitorrent. Torrent is too large ? Maybe i need to added more time to wait torrent to get added.

Torrent is not large sir 702MiB only and I have tested with different torrents with even lower size same thing happens with all of them.

And there is not any problem with torrent getting downloaded and uploaded! 
Auto Mirroring works fine! Only problem is bot sends message to telegram?

Btw `/qm` works fine bot sends this message only with auto mirroring.

**Comment by anasty17** [comment]
Send link from rss that give this message please.

**Comment by kendim2chiii** [comment]
> Send link from rss that give this message please.

`Error from above` https://pastebin.com/raw/sCPbCbNd

Also `New Error`! if it is not a directly download link but magnet torrent I get two error message like this.

`This is an unsupported/invalid link.`

`local variable 'ext_hash' referenced before assignment`

Bot send cmd like this:
`
/qm d:1.0:50 magnetlink
Tag: Name 11111111
`

Link of magnet link from new Error: https://pastebin.com/raw/Z5NsXyyZ

**Comment by anasty17** [comment]
I will fix tonight thanks for reporting

**Comment by anasty17** [comment]
The direct link is not valid and not added not shown with the magnet link.

**Comment by ProTogen11** [comment]
Tabbsv back javelin candy Han javelin anabolic an bagel sofa have hyena nap jugs Hyundai and the kids are going be
