### ISSUE TITLE
Torrent Search Magnet not showing

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#138]
Earlier it used to show magnets in torrent search results, but now it doesn't show
before
![image](https://user-images.githubusercontent.com/68769346/145278169-ece9397f-ef08-4ddc-801d-0dfb647c8625.png)
now
![image](https://user-images.githubusercontent.com/68769346/145278287-28c9ab48-5fa9-4eab-bb2f-4fd2c5b5fa91.png)
please add this feature back

**Comment by anasty17** [comment]
@rajput-hemant Press share to telegram and choose chat to forward the magnet to it .. by this way we can takebless bytes in each page ... means less pages for same results number
