### ISSUE TITLE
Auto downloading from channel to group doesn't seem to work after repo update?

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1381]
**Describe the bug**
Hi sir,
İt seems after repo update auto downloading rss feed doesn't seem to work bot won't respond(start downloading) to new rss feed from channel to group?
İt did seem to work fine monday but today it won't respond to channel anymore?

Edit:
İt seems /ping /help do work from channel but /qm  /ql /y /yl /m /l won't work?

**To Reproduce**
1. Used this Command /rss menu user_string channel to group.
2. Check logs
Nothing to see?
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10806300/log.txt)

**Expected behavior**
Bot will respond to channel commands. Send from rss feed.

**Comment by anasty17** [comment]
Aha wait let me test

**Comment by anasty17** [comment]
It's working with both bot and USER_SESSION_STRING no problem in both message sent to channel then to group then bot started to leech/mirror

**Comment by erickyun** [comment]
I'm sorry for the trouble sir.

I figured it out. I did need to give bot "Pin Messages" rights.

**Comment by anasty17** [comment]
It's ok don't hesitate to report any bug. Thank you
