### ISSUE TITLE
yt-dlp bug, please update yt-dlp 2023.02.17

### ISSUE THREAD

**Issue by sahilkundu** [anasty17/mirror-leech-telegram-bot#1383]
**Describe the bug**
Unable to extract uploader id;

**Comment by erickyun** [comment]
Look for if a similar issue is opened from before please! This a dublicate from https://github.com/anasty17/mirror-leech-telegram-bot/issues/1368#issuecomment-1434245583 y
You can close issue now its a fixed ytdlp error.
