### ISSUE TITLE
Error while zipping file. Bot creates 3 copies from same file `ERROR - name 'uploaded_doc' is not defined.`

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1384]
**Describe the bug**
Hi sir,
When I try to zip photo, document or ytdl link Bot creates 3 zip files from same file? Both are copies from each other not splitted. And file size is not high only 301.69KB

**To Reproduce**
1. Used this Command zip command for mirror, leech and ytdl
2. Check logs saw this error
`ERROR - name 'uploaded_doc' is not defined.`

[log (1).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10811944/log.1.txt)

**Expected behavior**
Bot creates only one zip from file.

**Comment by anasty17** [comment]
I have pushed temp fix for this. I will do it different way soon

**Comment by erickyun** [comment]
Thank you
