### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by GarouTheDevil** [anasty17/mirror-leech-telegram-bot#1387]
I Always Use Ffmpeg In Shell On Mirrorbot, From Few Days I Am Facing This Error A Lot I Dont Know Why, Fix Please

**Comment by anasty17** [comment]
You (must) provide logs and explain how to produce the error

**Comment by GarouTheDevil** [comment]
https://pastebin.com/kznnUafw
See This (I Was Muxing With Using Ffmpeg As Always But Its Showing "The Segmentation fault (core dumped)" From Past Few Days

**Comment by anasty17** [comment]
Where is the bot logs! And how to produce!! What r u doing!

**Comment by GarouTheDevil** [comment]
Bot Log : https://vfhk6-my.sharepoint.com/:t:/g/personal/garouthsemonster_vfhk6_onmicrosoft_com/EZJ_KdnF0AJLvroR7xZPR8wBDdrpW31Wh_DuQQ0eY_AnKw?download=1
Screenshot Of What I Did : https://telegra.ph/Screenshot-bot-error-02-24

Context :
As I Said, I Use Always Shell Mostly For Muxing Videos With Custom Audios With The Help Of Ffmpeg And Mkvmerge. But I Dont Know Why From These Days By Past I Facing Segmentation fault Error Most Of The Time From Ffmpeg

**Comment by GarouTheDevil** [comment]
And Also Yes, I Deleted Docker File For To Get Latest Ffmpeg Normal But That Have Nothing To Do With This Error

**Comment by anasty17** [comment]
Not my repo

**Comment by GarouTheDevil** [comment]
> Not my repo

But I Faced The Same In Your Repo And As Because Of Bugs I Was Shifted To Another Repo
And May I Know How Can I Get Rid Of This ?
