### ISSUE TITLE
Error when trying to zip media send from channel `AttributeError: 'NoneType' object has no attribute 'is_bot'`

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1389]
**Describe the bug**
Hi sir,
When I try to zip a media video send from channel, in group Bot won't respond?
Bot won't zip video file if it is send from channel?
I tried to forward video from channel to group and tried to zip forwarded video it worked?

**To Reproduce**
1. Used this Command zip
2. Check logs
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10834749/log.2.txt)

``AttributeError: 'NoneType' object has no attribute 'is_bot`

**Expected behavior**
Bot does zip video send from channel.

**Comment by anasty17** [comment]
I know this not bug. There is no support for chat_sender i just added for rss

**Comment by erickyun** [comment]
> I know this not bug. There is no support for chat_sender i just added for rss

I understand sir. Thank you for your response.
