### ISSUE TITLE
Can you enable torrent uploading to fight with HNR in private trackers?

### ISSUE THREAD

**Issue by askfriends** [anasty17/mirror-leech-telegram-bot#139]
Hi;
Bro currently torrent uploading is disabled while we download any torrent, so private trackers have implemented HNR system which ban accounts which download only and doesn't upload, So can you enable it until and unless torrent is being downloaded?
Thanks

**Comment by dinesh-0602** [comment]
@askfriends You can't seed without the file in ur storage. So Impossible

**Comment by anasty17** [comment]
@askfriends Use qbittorrent, uploading while downloading and u can enable qb_seed for specific ratio or time after download and upload to drive finished

**Comment by askfriends** [comment]
> @askfriends Use qbittorrent, uploading while downloading and u can enable qb_seed for specific ratio or time after download and upload to drive finished

Thank u so much for this feature, i just updated my bot and it really works.
Thanks a ton!!!!!

**Comment by anasty17** [comment]
@askfriends U wlc
