### ISSUE TITLE
[Feature Request] Add Queue System for qBittorent and Archive

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1390]
**Describe the solution you'd like**
Hi,
İt would be nice if there was a Queue System for qBittorrent and Archive.

I thank you sincerely for your great work sir.
And I would appreciate it if you could consider adding this feature if you like the idea?

**Comment by anasty17** [comment]
Qbittorrent and Aria2c have their own queue system with more options. You can check qBittorrent.conf/aria.sh or bsetting.

Regarding archive idk why it's important? You still can use download queue or all, any action before the upload will be in download or all queue except aria2c and qbittorrent. Hard to manage them in queue with status. Another way can use but without showing it in status.

Explain more about ur purpose

**Comment by erickyun** [comment]
> Qbittorrent and Aria2c have their own queue system with more options. You can check qBittorrent.conf/aria.sh or bsetting.

Thank you for your response. I will close this issue now since it was just a suggestion of mine. 
 I will do the queue for them like you just explained sir.
