### ISSUE TITLE
Add File to Link Streaming Option

### ISSUE THREAD

**Issue by m-hoseyny** [anasty17/mirror-leech-telegram-bot#1391]
Hi,
It would be great if you could add the file to link the streaming option to the project. 
In this project, you can find a suitable solution for it. 
https://github.com/avipatilpro/FileStreamBot

As both projects use Pyrogram, I believe it would be easy to integrate it into the project. This project needs to add a filter to get files from users, show options for leeching or streaming, and after that give the user a permanent or temporary HTTP link.

**Comment by anasty17** [comment]
This repo is dead, i will make my own. Check todo listin channel
