### ISSUE TITLE
Bug Bot won't start seeding torrent after latest repo update

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1392]
**Describe the bug**
Hi sir,
After latest repo update `commit 6b2fb2d` bot won't start seeding with neither qBittorrent or Aria2 ?

**To Reproduce**
1. Used this Command: reply to torrent with `/l d:1.0:50` or `/ql d:1.0:50`
2. Check logs:
Nothing to see no error? Bot finishes torrent with
` Leech Completed:` and `Cleaning download:`

**Expected behavior**
Bot start seeding torrent when d:1.0:50 is executed.

**Comment by erickyun** [comment]
Thank you 🙂

**Comment by anasty17** [comment]
> Thank you 🙂

Thqnks for reporting
