### ISSUE TITLE
[Bug] /ytdlleech sends Unfinished youtube video

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1396]
**Describe the bug**
Hi sir,

When I try to execute /yl on a link bot sends/uploads not completed video file?
Bot sends `part-frag7.part` file?

I'm up to date with latest repo `commit 999df74` .

**To Reproduce**
1. Check Logs
[log (4).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10929149/log.4.txt)

**Expected behavior**
Bot sends completed video file when executing /yl

**Comment by anasty17** [comment]
Send link so i can test

**Comment by erickyun** [comment]
> I will check. But why u don't join the telegram group?
I am in your group sir. I do send bugs there sometimes but I didn't though that it matters. From now on I will try to send from there.

> Send link so i can test

İt is in the log sir. `https://www.youtube.com/watch?v=0XmM7YZjPSc`

**Comment by anasty17** [comment]
Mostly the issue from yt-dlp. But i will leave this issue open until i can produce the error

**Comment by anasty17** [comment]
ERROR - ERROR: 
[download] Got error: Downloaded 163840 bytes, expected 8353290 bytes

Download corrupted
