### ISSUE TITLE
Aria2 select inactive torrent file (/mirror s)

### ISSUE THREAD

**Issue by Namlee123** [anasty17/mirror-leech-telegram-bot#1397]
Hello Bro!
I tried using the "/Mirror s" command to select the torrent file, but it doesn't pause, doesn't show the selection.
It directly executes the download command in the BOT Status.
Hope you can fix this in the future.

**Comment by hitesh920** [comment]
fill BASE_URL in config.env

**Comment by anasty17** [comment]
> Hello Bro! I tried using the "/Mirror s" command to select the torrent file, but it doesn't pause, doesn't show the selection. It directly executes the download command in the BOT Status. Hope you can fix this in the future.

Fix what ? U added bas_url ?

**Comment by Namlee123** [comment]
Yes, of course.
if using "/qm s" it works properly.
I re-ran your old repo (several months ago) it still works with "/mirror s".
But since you updated add:
(async, await) in module (bot/helper/mirror_utils/download_utils/aria2_download.py)
It encountered this error.
But I'm not sure if it's caused by (async, await) or not!

**Comment by hitesh920** [comment]
bro for selecting you must use qb , selection with aria will not work (this is not a error thats how it suppose to be.)

**Comment by Namlee123** [comment]
> bro for selecting you must use qb , selection with aria will not work (this is not a error thats how it suppose to be.)

The file selection function using Aria2 was added a long time ago by the owner.
Here is an image using Anas' "Old Repo".
I just redeployed the Repo yesterday, the "/mirror s" function doesn't work, it directly downloads the same as the "/mirror" command without the "s".
![Capture](https://user-images.githubusercontent.com/92989894/224959938-6eaa1317-b981-46fd-8544-aaf42d23c1a7.PNG)

**Comment by hitesh920** [comment]
> > bro for selecting you must use qb , selection with aria will not work (this is not a error thats how it suppose to be.)
> 
> The file selection function using Aria2 was added a long time ago by the owner. Here is an image using Anas' "Old Repo". I just redeployed the Repo yesterday, the "/mirror s" function doesn't work, it directly downloads the same as the "/mirror" command without the "s". ![Capture](https://user-images.githubusercontent.com/92989894/224959938-6eaa1317-b981-46fd-8544-aaf42d23c1a7.PNG)

dude i already said you must use qb for selection in the latest repo
"/m s" will no longer work

**Comment by Namlee123** [comment]
@hitesh920 ,
I see what you mean, use qb instead of Aria2.
I want to report this issue to the owner because he doesn't have time to check all Repo functionality is stable or is there any other bug?
Only users will accidentally discover some minor bugs.
If I am indifferent (not reporting) then really sorry to the creator of the Repo.
If he has some free time, hopefully he can fix them.

**Comment by anasty17** [comment]
@hitesh920 u don't know about aria2c selection?

**Comment by anasty17** [comment]
> > > bro for selecting you must use qb , selection with aria will not work (this is not a error thats how it suppose to be.)
> > 
> > 
> > The file selection function using Aria2 was added a long time ago by the owner. Here is an image using Anas' "Old Repo". I just redeployed the Repo yesterday, the "/mirror s" function doesn't work, it directly downloads the same as the "/mirror" command without the "s". ![Capture](https://user-images.githubusercontent.com/92989894/224959938-6eaa1317-b981-46fd-8544-aaf42d23c1a7.PNG)
> 
> dude i already said you must use qb for selection in the latest repo "/m s" will no longer work

Why no longer work ?

**Comment by anasty17** [comment]
> Hello Bro! I tried using the "/Mirror s" command to select the torrent file, but it doesn't pause, doesn't show the selection. It directly executes the download command in the BOT Status. Hope you can fix this in the future.

Got it thanks for reporting. I will not leave waiting for rclone commit. I will fix it very soon

**Comment by hitesh920** [comment]
> > > > bro for selecting you must use qb , selection with aria will not work (this is not a error thats how it suppose to be.)
> > > 
> > > 
> > > The file selection function using Aria2 was added a long time ago by the owner. Here is an image using Anas' "Old Repo". I just redeployed the Repo yesterday, the "/mirror s" function doesn't work, it directly downloads the same as the "/mirror" command without the "s". ![Capture](https://user-images.githubusercontent.com/92989894/224959938-6eaa1317-b981-46fd-8544-aaf42d23c1a7.PNG)
> > 
> > 
> > dude i already said you must use qb for selection in the latest repo "/m s" will no longer work
> 
> Why no longer work ? I'm wondering who told u it's not working anymore! It's a bug

so you saying 
/m s and /qb s both works?
wow its been so many "months"  
i though actually "we" though selection only works when using qb

**Comment by anasty17** [comment]
> > > > > bro for selecting you must use qb , selection with aria will not work (this is not a error thats how it suppose to be.)
> > > > 
> > > > 
> > > > The file selection function using Aria2 was added a long time ago by the owner. Here is an image using Anas' "Old Repo". I just redeployed the Repo yesterday, the "/mirror s" function doesn't work, it directly downloads the same as the "/mirror" command without the "s". ![Capture](https://user-images.githubusercontent.com/92989894/224959938-6eaa1317-b981-46fd-8544-aaf42d23c1a7.PNG)
> > > 
> > > 
> > > dude i already said you must use qb for selection in the latest repo "/m s" will no longer work
> > 
> > 
> > Why no longer work ? I'm wondering who told u it's not working anymore! It's a bug
> 
> so you saying /m s and /qb s both should be working? wow its been so many "months" i though actually "we" though selection only works when using qb

This added since 1 year i guess

**Comment by hitesh920** [comment]
> > > > > > bro for selecting you must use qb , selection with aria will not work (this is not a error thats how it suppose to be.)
> > > > > 
> > > > > 
> > > > > The file selection function using Aria2 was added a long time ago by the owner. Here is an image using Anas' "Old Repo". I just redeployed the Repo yesterday, the "/mirror s" function doesn't work, it directly downloads the same as the "/mirror" command without the "s". ![Capture](https://user-images.githubusercontent.com/92989894/224959938-6eaa1317-b981-46fd-8544-aaf42d23c1a7.PNG)
> > > > 
> > > > 
> > > > dude i already said you must use qb for selection in the latest repo "/m s" will no longer work
> > > 
> > > 
> > > Why no longer work ? I'm wondering who told u it's not working anymore! It's a bug
> > 
> > 
> > so you saying /m s and /qb s both should be working? wow its been so many "months" i though actually "we" though selection only works when using qb
> 
> This added since 1 year i guess

ik ik but littreally we all though for selecting we must use qbit "/qm s" thats why no one reported it xDD
