### ISSUE TITLE
Renaming Torrents with qBit and Aria doesn't work?

### ISSUE THREAD

**Issue by kendim2chiii** [anasty17/mirror-leech-telegram-bot#1398]
**Describe the bug**
Hi,
My bot is up to date I tried to rename torrent with /ql n: newname or /l n: newname but wirh both torrent name won't change?

**To Reproduce**
1. Check logs
Nothing to see?

**Expected behavior**
Bot changes torrent name

**Comment by anasty17** [comment]
Read readme

**Comment by kendim2chiii** [comment]
> Read readme

My bad I apologize

**Comment by anasty17** [comment]
In readme written torrent can't be renamed

**Comment by kendim2chiii** [comment]
> In readme written torrent can't be renamed I will add it in notes also but this thing should be known if u read readme

Yes you're absolutely right sir. I'm sincerely sorry about that.
