### ISSUE TITLE
`/m rcd` won't let me select config, remote and path

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1400]
**Describe the bug**
Hi,
I did deploy my bot to latest `commit 885f9d9` .
Today I tried /m rcd and with /qm to select from rclone.conf but bot won't let me select remote? it directly uploads to gdrive.
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/10989224/log.txt)

Edit: 
Also `/m mrcc:dropbox-encrypt:test.zip` doesn't work? it uploads to gdrive.

**To Reproduce**
1. Uploaded rclone.conf to /usettings
2. Used this Command `/m rcd` reply to link or telegram file

**Expected behavior**
Bot let me select from rclone.conf when I execute /m rcd

**Comment by anasty17** [comment]
Just tell me who said i added rclone for upload. I worte in commit title rclone download!!!!

**Comment by anasty17** [comment]
Join the channel
