### ISSUE TITLE
[Bug] rclone upload not working with reply and torrent links

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1405]
**Describe the bug**
Hi,
I have updated bot to latest `commit 1fbdc1b` today.
When I try `/m reply up: rcl` bot won't upload with Rclone it gives me a error.
Also with torrents `/m Link up: rcl` Bot also wont upload with rclone getting error.
 

[log (1).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11020922/log.1.txt)
[log (2).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11020923/log.2.txt)

**Comment by anasty17** [comment]
Upload rclone! There are two ways! Chat in group

**Comment by LoveThisWorld002** [comment]
> Upload rclone! There are two ways! Chat in group

I did upload rclone sir and did redeploy on ubuntu vps but I'm still getting error?

**Comment by anasty17** [comment]
U have two ways.
U can from bsetting which is for all users
And from usetting  for only u and when u write path manually u should add mrcc: before any path i gave example in mcd notes

**Comment by LoveThisWorld002** [comment]
> U have two ways. U can from bsetting which is for all users And from usetting for only u and when u write path manually u should add mrcc: before any path i gave example in cmd notes

Yes thank you very much sir right now torrent uploading works.

But I'm still getting error with uploading telegram files with rclone?
[log (8).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11022063/log.8.txt)


I found a error with dropbox upload Telegram says: [400 BUTTON_URL_INVALID] 
[log (4).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11021560/log.4.txt)


Edit:
directory not found error while trying to choose dropbox upload folder? With `/m Link up: rcl `
[log (7).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11021943/log.7.txt)

**Comment by LoveThisWorld002** [comment]
> 1st error u did something wrong show me the cmd 2nd invalid link because rclone can't create link im all cases i didn't find solution for this yet 3rd i don't why with google drive works but with dropbox doesn't! If u can provide to me dropbox config so i can test

1st error `/m up: rcl` reply to upload photo on telegram
3rd error https://pastebin.com/NFmCv6sM

**Comment by LoveThisWorld002** [comment]
> 1st error u did something wrong show me the cmd 2nd invalid link because rclone can't create link im all cases i didn't find solution for this yet 3rd i don't why with google drive works but with dropbox doesn't! If u can provide to me dropbox config so i can test

1st error `/m up: rcl` reply to upload photo on telegram
3rd https://pastebin.com/NFmCv6sM

**Comment by anasty17** [comment]
I forget the tg file part so it will not work if u r trying to mirror tg files

**Comment by LoveThisWorld002** [comment]
> I forget the tg file part so it will not work if u r trying to mirror tg files

Any eta for tg file sir? Will you add it later?

And did you check pastebin?

**Comment by LoveThisWorld002** [comment]
> 2nd invalid link because rclone can't create link im all cases i didn't find solution for this yet 

I found out that if folder path is specified like this `/m up: dropbox:Folder/` there is no error! I get dropbox link.
But if no folder path is specified like this `/m up: dropbox:` I get [400 BUTTON_URL_INVALID] error?

**Comment by 320cuneyt** [comment]
> 1. hata yanlış bir şey yaptın bana cmd'yi göster 2. geçersiz bağlantı çünkü rclone tüm durumlarda bağlantı oluşturamıyor bunun için henüz bir çözüm bulamadım 3. neden google drive ile çalışıyor ama dropbox ile çalışmıyor! Test edebilmem için bana dropbox yapılandırması sağlayabilirseniz

/l drive:downloads ✅ 
/l drive:/downloads ✅ 
/l dropbox:downloads ✅ 
/l dropbox:/downloads ❌
