### ISSUE TITLE
Dropbox upload ERROR - while getting link. Failed to link: path/not_found/.

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1408]
**Describe the bug**
Hi,
I tried to upload torrent to dropbox with `/qm up: rcl` but got **Failed to link: path/not_found/.** Error? I got this error after download was completed and uploaded reached 100% after that bot won't finish task(it does upload the file btw) it is stuck in 100% percentage?
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11057096/log.txt)

With `/m up: rcl` also getting error?
[log (1).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11057127/log.1.txt)

Can't cancel when this error occurs only way to stop it is to restart bot. 
[log (2).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11057139/log.2.txt)

## EDİTED ABOVE

**Comment by anasty17** [comment]
I will fix this tomorrow

**Comment by LoveThisWorld002** [comment]
> I will fix this tomorrow

**bot does upload the file btw but it won't finish task it is stuck in 100% percentage?**

I want to edit that part sir.

**Comment by anasty17** [comment]
Edit what! I said i will fix this.

**Comment by anasty17** [comment]
Mostly fixed try and open new issue if problem exists
