### ISSUE TITLE
i have an issue called "No Module named  cloudscraper:"

### ISSUE THREAD

**Issue by noncapturesen** [anasty17/mirror-leech-telegram-bot#1413]
<<<LOG>>>>

pyrogram.session.session - INFO - Session started
2023-03-28 19:01:00,536 - pyrogram.session.session - INFO - PingTask started
2023-03-28 19:01:01,827 - pyrogram.dispatcher - INFO - Started 6 HandlerTasks
2023-03-28 19:01:04,381 - bot - INFO - Creating Telegraph Account
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/bot/__main__.py", line 21, in <module>
    from .modules import authorize, gd_clone, gd_count, gd_delete, gd_list, cancel_mirror, mirror_leech, status, torrent_search, torrent_select, ytdlp, rss, shell, eval, users_settings, bot_settings
  File "/usr/src/app/bot/modules/gd_clone.py", line 16, in <module>
    from bot.helper.mirror_utils.download_utils.direct_link_generator import direct_link_generator
  File "/usr/src/app/bot/helper/mirror_utils/download_utils/direct_link_generator.py", line 21, in <module>
    from cloudscraper import create_scraper
ModuleNotFoundError: No module named 'cloudscraper'

**Comment by erickyun** [comment]
İt is mentioned on [commit 911b8f8](https://github.com/anasty17/mirror-leech-telegram-bot/commit/911b8f809e33b5cc02d0889222cde49a227f88d5) you should read them.

Fix it with executing `/shell pip3 install cloudscraper`

**Comment by sennoncap** [comment]
i already did it sir, but not fix
how to deploy it again sir (i am using with sudo docker run -p 80:80 mltb)

is it right?

**Comment by erickyun** [comment]
> i already did it sir, but not fix how to deploy it again sir (i am using with sudo docker run -p 80:80 mltb)
> 
> is it right?

İt says in readme [here](https://github.com/anasty17/mirror-leech-telegram-bot#build-and-run-the-docker-image-using-official-docker-commands)

To stop
```
sudo docker ps

sudo docker stop id
```

To build image
```
sudo docker build . -t mltb
```

İf it still wont work try pruning image and build again

```
sudo docker images
sudo docker image prune -a
```

**Comment by sennoncap** [comment]
yep sir 
i will try it

**Comment by erickyun** [comment]
> yep sir i will try it

First

`git clone https://github.com/anasty17/mirror-leech-telegram-bot`

Clone repo again delete old one
