### ISSUE TITLE
GDrive ID rss path upload

### ISSUE THREAD

**Issue by undeadmecha0** [anasty17/mirror-leech-telegram-bot#1419]
**Is your feature request related to a problem? Please describe.**
rss upload using driveid instead of rclone

**Describe the solution you'd like**
its faster to just add gdrive id than using remotes

**Comment by undeadmecha0** [comment]
Have you considered using gclone (rclone mod) instead of rclone? It's also updated to the latest rclone version
https://github.com/dogbutcat/gclone

gclone supports SA rotation you just need to add accounts in root plus it supports gdrive id for cloning/moving instead of making remotes and adding it in rclone.conf for each td or folder

I think this would help in the RSS upload path

**Comment by anasty17** [comment]
In todo list
