### ISSUE TITLE
how to seed after downloading?

### ISSUE THREAD

**Issue by Nobita-o** [anasty17/mirror-leech-telegram-bot#142]
how to seed after downloading? can anyone explain me please?

**Comment by snehitap** [comment]
@Nobita-o Use qbmirror it will seed after downloading

**Comment by Nobita-o** [comment]
after downloading it's uploaded on gdrive without seeding. 
should i enable any options to seed ?
I'm tried from 1337x magnet link

**Comment by a092devs** [comment]
@Nobita-o check if you have added QB_SEED = "True" in config.env

**Comment by anasty17** [comment]
@Nobita-o Check QB_SEED VAR in readme and u will know without asking
