### ISSUE TITLE
(DMCA) complaint detected by vps

### ISSUE THREAD

**Issue by sennoncap** [anasty17/mirror-leech-telegram-bot#1420]
(DMCA) complaint detected by vps when using qbzipmirror with MLTB bots on Oracle VPS.
i really don't know this is oracle or Mltb error .
if admin have bypass method , please tell me sir.

**Comment by anasty17** [comment]
this depending on what u r downloading not related to my repo.

**Comment by oktest145** [comment]
Yes when you download games it will takedown like it happened with me when someone mirroring fit girl.
