### ISSUE TITLE
[bug] `TypeError:` when executing /yl opt: fragment_retries:inf

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1423]
**Describe the bug**
Hi,

I would appreciate sir if you could please help with this error.

When I try to execute `/yl opt: fragment_retries:inf` bot gives type error?
Bot won't download link, it does get stuck on status can't cancell it! After this error the only way to cancel is /restart bot.
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11147168/log.txt)

**Expected behavior**
Bot downloads link when `opt: fragment_retries:inf` is used.

### Edit:
İt seems `opt: 'fragment_retries': inf` works but `opt: fragment_retries:inf` doesn't work? So does this mean it is not a bug sir? Shall I close the issue?

**Comment by anasty17** [comment]
Mostly issue from yt-dlp it only accept int which is bug it should accept str

**Comment by anasty17** [comment]
Will fix this soon i didn't know about this possible value in yt-dlp

**Comment by anasty17** [comment]
Fixed try /yl2 opt: fragment_retries:^inf

**Comment by LoveThisWorld002** [comment]
> 

Thank you very much sir. 👍
