### ISSUE TITLE
JSONDecodeError when `/l rcl` is executed, rclone download won't work

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1424]
**Describe the bug**
Hi,

When I try to execute `/l rcl` bot won't download? Bot gives error in logs. 
[log (9).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11159695/log.9.txt)

Also when I try to execute `/l n: token.pickle` to rename the file, the bot gives `WARNING - Get Document Type ` in logs. But file gets uploaded successfully.

**Expected behavior**
Rclone download works when `/l rcl` is executed.

**Comment by anasty17** [comment]
Ignore the warning

**Comment by LoveThisWorld002** [comment]
Thank you
