### ISSUE TITLE
Docker File not Found

### ISSUE THREAD

**Issue by abhinavkakku** [anasty17/mirror-leech-telegram-bot#1427]
The docker file is not found so cannot eun the docker build or compose up

docker.io/anasty17/ - NOT found
 

FROM anasty17/mltb:dev

WORKDIR /usr/src/app
RUN chmod 777 /usr/src/app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

CMD ["bash", "start.sh"]

**Comment by anasty17** [comment]
Yeah update ur repo
