### ISSUE TITLE
Is there an issue with botcommands.py?

### ISSUE THREAD

**Issue by BruhYouKiddingMe** [anasty17/mirror-leech-telegram-bot#143]
Hello. I have 3 bots, all using this repo. But I updated one bot yesterday, everything seems to work fine except the commands. Because I have multiple bots, I had tweaked the commands a little. Just added numbers like 1,2,3 to differentiate between them. Old bots seem wot work fine but the new doesn't. It only takes default commands. Like /start, while I had set it to /start1. Please take a look into this. It was working perfectly before the Qbit update. Thanks.

**Comment by a092devs** [comment]
@BruhYouKiddingMe You need to change upstream_repo to your fork, read README.md to know more

**Comment by anasty17** [comment]
@BruhYouKiddingMe If heroku branch add UPSTREAM_REPO then edit in that repo
