### ISSUE TITLE
Documentation for "Generate Database" is missing

### ISSUE THREAD

**Issue by ChvckN0rri5** [anasty17/mirror-leech-telegram-bot#1431]
Long time listener,
first time caller.

**Describe the bug**
Clicking the link in the documentation takes the user to a folder within the repository.

**To Reproduce**
1. Click on "Generate Database" link in documentation

**Expected behavior**
A link to the Generate Database Documentation was expected.

Thank you for this awesome project y'all 🫡

**Comment by anasty17** [comment]
it's working!!!!
