### ISSUE TITLE
Add Global Limit Size 

### ISSUE THREAD

**Issue by m-hoseyny** [anasty17/mirror-leech-telegram-bot#1432]
I believe in the first version of this repo (or parent), there was a setting in config.env that we can set a global limit for file size. For example, if there was a 4 GB limit for global size, files with more than this size will ignore. 
Could you please add it to this repo too? Files with more than a specific size would not leech or mirror.

Thanks

**Comment by anasty17** [comment]
Use juned repo for public groups
