### ISSUE TITLE
Please add delete links feature as other repo has it already

### ISSUE THREAD

**Issue by paulper2** [anasty17/mirror-leech-telegram-bot#1434]
**Is your feature request related to a problem? Please describe.**
Please add delete links option as it links fill up my group

**Describe the solution you'd like**
If this feature is added my group would look less messy as its filled with links so after it has started downloading the torrent then the link should get delete

**Comment by anasty17** [comment]
Use junedkh repo

**Comment by paulper2** [comment]
I was refering that repo only but his repo is not provinding links after leech upload like your repo does so that's why i need this feature in your repo
