### ISSUE TITLE
upload to local storage?

### ISSUE THREAD

**Issue by thzamn** [anasty17/mirror-leech-telegram-bot#1436]
More of a question than a feature request, but it's not an issue. Just installed the bot on docker, and it's running very well. I'm just wondering, is it possible to send files to local storage like a connected usb? If so, how do I do that? It only seems to upload mirrors to google drive and rclone. I'm running on linux, if it matters.

**Comment by thzamn** [comment]
wrong area

**Comment by anasty17** [comment]
Why using mirror bot! Download to local directory

**Comment by thzamn** [comment]
> Why using mirror bot! Download to local directory 

this is the only telegram bot to download I found that works 😂 can you tell me where the downloaded files are temporarily stored?

**Comment by anasty17** [comment]
In downloads folder and nothing localy all in docker container but if u edit tobstop upload u can export copy file from container to local system

**Comment by thzamn** [comment]
yes i modified the leech command to save the file to ssd outside of docker, and to also still upload the file to telegram chat, without deleting the file on the ssd for "dual upload." It was a pain to mod the second path variable in the telegram_download.py file but Im all good now, thanks.

**Comment by thzamn** [comment]
for anyone wondering, the loop outside of the docker image is as follows:

sudo docker run -p 80:80 -p 8080:8080 -v {dir outside of docker}:/usr/src/app/{dir inside docker} mltb
