### ISSUE TITLE
Not uploading files

### ISSUE THREAD

**Issue by basavaadarsh5** [anasty17/mirror-leech-telegram-bot#1440]
HttpError 404 when requesting None returned "File not found: 0APdtQQDIGJsZUk9PVA.". Details: "[{'message': 'File not found: 0APdtQQDIGJsZUk9PVA.', 'domain': 'global', 'reason': 'notFound', 'location': 'fileId', 'locationType': 'parameter'}]"
Elapsed: 9m58s
Upload: Drive

Getting this error while uploading the files to gdrive in telegram bot.please help me

**Comment by basavaadarsh5** [comment]
Please help me to solve this ereor

**Comment by anasty17** [comment]
Don't open issue again and join the group
