### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by seega** [anasty17/mirror-leech-telegram-bot#1441]
I would like to thank the developer for such a powerful tool. I use it for probably 1% of all the possibilities for downloading files from a site that is speed limited and only 1 active connection is allowed (using /leech), so I have to send each link after the previous one is downloaded, I set up queues, but when I send a new link to while the download is already in progress, the bot creates a connection, as I understand it, to request the file size and, accordingly, receives an error, because. the server forbids more than 1 connection. I would like to know how to organize the work of such a queue, now I'm just doing a delayed sending of the command via telegram.

**Comment by anasty17** [comment]
Queue system that i have added not for all tools yet. Aria2c which download direct links and torrents and qbittorrent are not added to queue system yet. BUT ARIA2C and qbittorrent already have their own queue system in Aria2c options which is concurrent downloads and in qbittorrent its enable queuing. So u need to set concurrent downloads to 1

**Comment by anasty17** [comment]
Open discussion or ask in group next time i will close this issue
