### ISSUE TITLE
yt-dlp referer not working?

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1442]
**Describe the bug**
Hi,
I'm trying to download a video with `/yzl https://myspacecat.pictures/bonyuu-chan-wa-dashitai/4k/E03.webm opt: http_headers: {'Referer': 'https://oppai.stream/'}` 
But the bot seems not to use referer I get HttpError 403? İt did work fine two weeks ago but now it doesn't? When downloading localy with yt-dlp using bot vps network executing `yt-dlp https://myspacecat.pictures/bonyuu-chan-wa-dashitai/4k/E03.webm --referer https://oppai.stream/` it works fine but with the bot /yl it doesn't work? 

The bot does download with aira2c`/m` ! I did use aria2 referer command to download and it did work. I did this with adding new key in bsettings.
But /yl it doesn't work? I would appreciate if you could please help me with this sir?

**To Reproduce**
1. Check logs Nothing to See
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11297987/log.txt)

**Expected behavior**
Bot downloads video when using opt referer cmd.

**Screenshots**
![IMG_20230421_202108](https://user-images.githubusercontent.com/112317009/233698288-e23cee76-d838-494b-8b74-85b450c24156.jpg)

**Comment by anasty17** [comment]
Is there  `http_headers` option? I don't know it! And i didn't find it while searching!

**Comment by LoveThisWorld002** [comment]
> Is there `http_headers` option? I don't know it! And i didn't find it while searching!

```
import yt_dlp

def cli_to_api(*opts):
    default = yt_dlp.parse_options([]).ydl_opts
    diff = {k: v for k, v in yt_dlp.parse_options(opts).ydl_opts.items() if default[k] != v}
    if 'postprocessors' in diff:
        diff['postprocessors'] = [pp for pp in diff['postprocessors'] if pp not in default['postprocessors']]
    return diff
    
from pprint import pprint

pprint(cli_to_api('--referer', 'https://oppai.stream/'))  # Change according to your need
```

Yes there is sir, that is what [CLI to API](https://github.com/anasty17/mirror-leech-telegram-bot/issues/1423#issuecomment-1496032649) script gives as output. This is the output the script gives:

```
{'http_headers': {'Referer': 'https://oppai.stream/'}}
```

This working fine until now sir?

**Comment by anasty17** [comment]
Yes i will fix it. This the first step of getting info i remove the option from it. I will push fix for it. Thanks for reporting

**Comment by anasty17** [comment]
![Screenshot_20230421-232603_Plus](https://user-images.githubusercontent.com/77075674/233728482-db44b52d-fe30-47b3-a3c4-f301180e45d5.jpg)
I will push in minutes

**Comment by LoveThisWorld002** [comment]
> ![Screenshot_20230421-232603_Plus](https://user-images.githubusercontent.com/77075674/233728482-db44b52d-fe30-47b3-a3c4-f301180e45d5.jpg) I will push in minutes

Thank you sir for the fix.
