### ISSUE TITLE
Extract part files.

### ISSUE THREAD

**Issue by pachax001** [anasty17/mirror-leech-telegram-bot#1445]
Assume there are multiple rar files like this.
ugly.alert.s1.web.48-pahe.li.part1.rar
ugly.alert.s1.web.48-pahe.li.part2.rar
ugly.alert.s1.web.48-pahe.li.part3.rar
ugly.alert.s1.web.48-pahe.li.part4.rar
ugly.alert.s1.web.48-pahe.li.part5.rar
ugly.alert.s1.web.48-pahe.li.part6.rar
ugly.alert.s1.web.48-pahe.li.part7.rar
When uploading or leeching these kind of files , some parts of the files gets corrupted.
So it will be good to check if the filename has part** and ask user to send the all file parts or direct links of the files and extract them in the directory and upload them.

**Comment by anasty17** [comment]
U have samedir feature already. U can do this if u read!
/m and read the cmd help message
