### ISSUE TITLE
Can you add one more alist-like index button

### ISSUE THREAD

**Issue by ITtest1** [anasty17/mirror-leech-telegram-bot#1446]
I tried adding it myself but it didn't work, it would be great if you could add it.  Or can you simply tell me where I am going wrong and how to do it.

            for file in response.get('files', []):
                mime_type = file.get('mimeType')
                if mime_type == "application/vnd.google-apps.folder":
                    furl = f"https://drive.google.com/drive/folders/{file.get('id')}"
                    msg += f"\U0001f4c1 <code>{file.get('name')}<br>(folder)</code><br>"
                    msg += f"<b><a href={furl}>Drive Link</a></b>"
                    if index_url:
                        if isRecur:
                            url_path = "/".join([rquote(n, safe='')
                                                for n in self.__get_recursive_list(file, dir_id)])
                        else:
                            url_path = rquote(f'{file.get("name")}', safe='')
                        url = f'{index_url}/{url_path}/'
                        msg += f' <b>| <a href="{url}">Index Link</a></b>'
                    if alist_url:
                        if isRecur:
                            url_path = "/".join(rquote(n, safe='') 
                                                for n in self.__get_recursive_list(file, dir_id))
                        else:
                            url_path = rquote(f'{file.get("name")}', safe='')
                        url = f'{alist_url}/{url_path}'
                        msg += f' <b>| <a href="{url}">AList Link</a></b>'  
                elif mime_type == 'application/vnd.google-apps.shortcut':
                    furl = f"https://drive.google.com/drive/folders/{file.get('id')}"
                    msg += f"\u204d<a href='https://drive.google.com/drive/folders/{file.get('id')}'>{file.get('name')}" \
                            f"</a> (shortcut)"
                else:
                    furl = f"https://drive.google.com/uc?id={file.get('id')}&export=download"
                    msg += f"\U0001f4c4 <code>{file.get('name')}<br>({get_readable_file_size(int(file.get('size', 0)))})</code><br>"
                    msg += f"<b><a href={furl}>Drive Link</a></b>"
                    if index_url:
                        if isRecur:
                            url_path = "/".join(rquote(n, safe='')
                                                for n in self.__get_recursive_list(file, dir_id))
                        else:
                            url_path = rquote(f'{file.get("name")}', safe='')
                        url = f'{index_url}/{url_path}'
                        msg += f' <b>| <a href="{url}">Index Link</a></b>'
                        if config_dict['VIEW_LINK']:
                            urlv = f'{index_url}/{url_path}?a=view'
                            msg += f' <b>| <a href="{urlv}">View Link</a></b>'
                    if alist_url:
                        if isRecur:
                            url_path = "/".join(rquote(n, safe='') 
                                                for n in self.__get_recursive_list(file, dir_id))
                        else:
                            url_path = rquote(f'{file.get("name")}', safe='')
                        url = f'{alist_url}/{url_path}'
                        msg += f' <b>| <a href="{url}">AList Link</a></b>'           
                msg += '<br><br>'
                contents_no += 1
                if len(msg.encode('utf-8')) > 39000:
                    telegraph_content.append(msg)
                    msg = ''
            if noMulti:
                break

        if msg != '':
            telegraph_content.append(msg)

        return telegraph_content, contents_no

**Comment by anasty17** [comment]
What do u mran by alist-like?

**Comment by ITtest1** [comment]
https://github.com/alist-org/alist
I hope that after the task is over, one more button is a hyperlink of alist, just like the index_link button hyperlinks to index

**Comment by anasty17** [comment]
soon all this will not be available... check channel. we will use file to create index because i will support for different upload destination.

**Comment by anasty17** [comment]
but we can add for rclone only

**Comment by anasty17** [comment]
@junedkh do u have any idea about this ?
check the repo that he sent

**Comment by ITtest1** [comment]
![Screenshot_20230424-194341_Telegram](https://user-images.githubusercontent.com/87193498/233997441-90ff7165-27d2-45b8-a098-a03be9be66f6.jpg)
I mean I want one more button like this. I know you may have a better way, but I still want to suggest that you can try to use alist, such as using rclone to specify that the task upload location is one-divre: td1/abc  /abc.mp4 , then alist's button will hyperlink to https://alist/one-divre/td1/abc/abc.mp4.  {alist_url}/{rclone_remote}/{url_path}, the former is a preview and the direct download is {alist_url}/d/{rclone_remote}/{url_path}.
