### ISSUE TITLE
Rclone serve is not running

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1450]
**Describe the bug**
Hi,
Rclone serve is not running? I did setup RCLONE_SERVE_URL http://myip:8080 RCLONE_SERVE_PORT 8080 .
İt was working fine for me but now it won't? I get ERR_CONNECTION_REFUSED can't access this site.
I would appreciate if you could please fix this sir?

Nothing to see in logs no error

**Comment by anasty17** [comment]
Issue from ur side
