### ISSUE TITLE
Bittorrent Selection error

### ISSUE THREAD

**Issue by Namlee123** [anasty17/mirror-leech-telegram-bot#1455]
Hello Anasty
I use "/m s" (/qm s) to select files.
Everything is working fine, but when I hit the "Submit" button I get this problem.
Torrent link to check: https://nyaa.si/download/1667401.torrent
NOTE:
I have problems only with torrents with too many small files, about 2000 or more files.
![Capture2](https://user-images.githubusercontent.com/92989894/236635806-94f981b5-3f9e-4743-9be6-4c634a68c6df.PNG)

After pressing the submit button:
![Capture](https://user-images.githubusercontent.com/92989894/236635817-88510534-2f0a-4af3-af89-856422a3cc79.PNG)

**Comment by anasty17** [comment]
I have tested it and no issue with aria2c and qbittorrent

**Comment by LoveThisWorld002** [comment]
> I have tested it and no issue with aria2c and qbittorrent

I'm also having the same problem sir.
Ubuntu 20.04.5 VPS 1GB Ram Buyvm.

**Comment by anasty17** [comment]
I have tried and no issues. Explain exactly how to produce the error

**Comment by LoveThisWorld002** [comment]
> I have tried and no issues. Explain exactly how to produce the error

Firstly sir I Select in sequently order 1-6 
Then after submit I'm getting "Error: 413"

![IMG_20230507_160755](https://user-images.githubusercontent.com/112317009/236679574-214e4e0d-bc7c-4756-8d97-d14989a214ee.jpg)
![IMG_20230507_160811](https://user-images.githubusercontent.com/112317009/236679576-5d274011-209e-4f76-93d8-33c780690f0d.jpg)

**Comment by anasty17** [comment]
> > I have tried and no issues. Explain exactly how to produce the error
> 
> First sir I reply with `/qm s` the torrent link Secondly I Select in sequently order 1-6 Then after submit I'm getting `"Error: 413"`
> 
> ![IMG_20230507_160755](https://user-images.githubusercontent.com/112317009/236679574-214e4e0d-bc7c-4756-8d97-d14989a214ee.jpg) ![IMG_20230507_160811](https://user-images.githubusercontent.com/112317009/236679576-5d274011-209e-4f76-93d8-33c780690f0d.jpg)

![20230507_180741](https://user-images.githubusercontent.com/77075674/236685776-8b750b41-cdc0-44fb-9bec-3ccadc200beb.jpg)

As u see the selection done look at the size and number selected files

**Comment by anasty17** [comment]
I guess u r not using vps and the platform have request limit

**Comment by Namlee123** [comment]
This problem is on the vps server side, it suffers from some server side limitations.
I try on Amazon VPS and it works fine, but with google cloud platform vps the maximum data sent is limited.
I managed to fix it on the vps side.
