### ISSUE TITLE
Multi Drive List Inactive

### ISSUE THREAD

**Issue by Namlee123** [anasty17/mirror-leech-telegram-bot#1456]
Hello
The BOT does not offer any folder selection buttons.
When start using command "/m /qm" the task runs. And there is no Mutil Drive choice.
Please check this function again.

**Comment by anasty17** [comment]
Bro this future not available yet in the official repo. Its in moded repo only but i will add soon in different way

**Comment by nirobmon74666** [comment]
Is the issue fixed? I can't use it even now. does it requires addition conf variables or addition command in the TG bot?

**Comment by anasty17** [comment]
> Is the issue fixed? I can't use it even now. does it requires addition conf variables or addition command in the TG bot?

u was using moded repo!

**Comment by nirobmon74666** [comment]
> > Is the issue fixed? I can't use it even now. does it requires addition conf variables or addition command in the TG bot?
> 
> u was using moded repo! 

No, i used your template and add drive_list.txt file at the root folder. But i didn't get any folder selection option yet. Btw gdrive root folder was also inserted at config file.

**Comment by anasty17** [comment]
> > > Is the issue fixed? I can't use it even now. does it requires addition conf variables or addition command in the TG bot?
> > 
> > 
> > u was using moded repo!
> 
> No, i used your template and add drive_list.txt file at the root folder. But i didn't get any folder selection option yet. Btw gdrive root folder was also inserted at config file.

Drive list only for search! Now u can read the usage. U can choose upload destination by other way. Hit /m and read
