### ISSUE TITLE
`/yl opt: fragment_retries:^inf` Not Working?  ValueError: invalid literal for int() with base 10: 'inf'

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1458]
**Describe the bug**
Bot gives error when executing `/yl opt: fragment_retries:^inf`
Bot won't start downloading ytdlp supported link?

**To Reproduce**
1. Used this Command /yl opt: fragment_retries:^inf
2. Check logs
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11445842/log.txt)

**Expected behavior**
Bot downloads ytdlp link. when executing `/yl opt: fragment_retries:^inf`

**Comment by anasty17** [comment]
I forget this. I will fix it soon🤦‍♂️

**Comment by erickyun** [comment]
Thank you

**Comment by erickyun** [comment]
> I forget this. I will fix it soon🤦‍♂️

I'm still getting `ValueError: invalid literal for int() with base 10: 'inf'`
[log (1).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11453087/log.1.txt)

**Comment by anasty17** [comment]
Ohh the value have ^

**Comment by erickyun** [comment]
> It should be fine now Thanks

👍🙂
