### ISSUE TITLE
Uploading error

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#147]
Heruko showing/watch1 (Memory quota exceeded) error
and mirror stuck at 100% download
mirrors are not uploading
YouTube videos not uploading
it's says download has been stopped by the user after downloading

**Comment by anasty17** [comment]
@rajput-hemant Join this group https://t.me/mltbBugsReport and try theink

**Comment by rajput-hemant** [comment]
> @rajput-hemant Join this group https://t.me/mltbBugsReport and try theink

its works fine after a restart
but its showing this error very frequently -*Memory quota exceeded*- , maybe its because of qbmirror

**Comment by jusidama18** [comment]
@rajput-hemant update to latest repo
