### ISSUE TITLE
Error while using rclone for Google Drive remotes transfer

### ISSUE THREAD

**Issue by Kittyxox** [anasty17/mirror-leech-telegram-bot#1470]
Hi, I have set up the rclone configuration file, which contains both encrypted and unencrypted Google Drive remotes. When I type "/m megalink up: rcl", I select the owner configuration file and the remote drive, but it shows an error in the log:

"2023-05-28 05:47:32,060 - bot.helper.mirror_utils.rclone_utils.transfer ERROR: [transfer:191]"
and in telegram chat it is just showing like this
@mytelegramusername
Elapsed: 14s
Upload: Rclone

I am certain that I have properly set up all the configurations in rclone.

**Comment by anasty17** [comment]
My repo ?

**Comment by Kittyxox** [comment]
yes sir

**Comment by anasty17** [comment]
> yes sir

Not juned repo ?

**Comment by Kittyxox** [comment]
no sir, im using your repo only

**Comment by anasty17** [comment]
Ok send log text in group please

**Comment by ogkimra** [comment]
I'm facing the same, and I'm using your repo

Log :- https://pastebin.com/P4n6qLBp

Context :- Im using Onedrive as remote and rclone for mirroring.

**Comment by anasty17** [comment]
> I'm facing the same, and I'm using your repo
> 
> Log :- https://pastebin.com/P4n6qLBp
> 
> Context :- Im using Onedrive as remote and rclone for mirroring.

/shell cat rlog.txt

**Comment by kaiser62** [comment]
facing the same issue 
bot.helper.mirror_utils.rclone_utils.transfer
after download is completed.
It seems nothing is getting uploaded via rclone. 
Using your repo on docker.

**Comment by kaiser62** [comment]
`Command move needs 2 arguments maximum: you provided 21 non flag arguments: ["/usr/src/app/downloads/228/shell_output.txt" "bertho:" " " "-" "-" "r" "e" "t" "r" "i" "e" "s" "-" "s" "l" "e" "e" "p" " " "3" "s"]</code>`

rclone output shows these on every move command.

**Comment by anasty17** [comment]
> `Command move needs 2 arguments maximum: you provided 21 non flag arguments: ["/usr/src/app/downloads/228/shell_output.txt" "bertho:" " " "-" "-" "r" "e" "t" "r" "i" "e" "s" "-" "s" "l" "e" "e" "p" " " "3" "s"]</code>`
> 
> rclone output shows these on every move command.

What is this? Open new issue and explain when this happens and send logs please
