### ISSUE TITLE
Download more than one file from a tg link

### ISSUE THREAD

**Issue by thomassch8861** [anasty17/mirror-leech-telegram-bot#1478]
When user reply to the tg link with a command ask the user to enter the number of files to download.
Eg:
Assume this is the first episode link of a tv series with 16 episodes.
https://t.me/c/1820463923/261154
when user reply to the above link ask the user to enter the number of files to needed to be downloaded,So when user enter 16 the episodes will be started to download.
This repo has the above feature under commands /leechbatch and /leechmirror 
https://github.com/Sam-Max/rcmltb

**Comment by anasty17** [comment]
U already can add b:start:end and u have multi feature which u can add number of links/file.
/m b:4:30 reply to bulk links file or text message have link seperated by new line
Or 
/m 16 replt to first link/file

**Comment by anasty17** [comment]
Why u don't read the usage before asking?
