### ISSUE TITLE
[Bug] zip `yl -z` is not working?

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1482]
**Describe the bug**
Hi,
Firstly, When I try `/yl -z` reply to zip video, bot cancels download on its own? Furthermore, it sends this message `USERNAME Download: Download Stopped by User!`

Secondly, when I execute this cmd `/yl -z -n [oppai.stream] Rin x Sen + Ran -> Sem Cross Mix: Haru Urara Uragiri to Zetsubou no Kisetsu-hen - 02 (1080p AAC WEBM) -opt http_headers: {'Referer': 'https://oppai.stream/'}` bot stops working?

I would appreciate your help sir? 🙏🙂

[log1 For Second Error](https://github.com/anasty17/mirror-leech-telegram-bot/files/11686289/log1.txt)

[log2 For Second Error](https://github.com/anasty17/mirror-leech-telegram-bot/files/11686404/log2.txt)

**Comment by anasty17** [comment]
Fixed

**Comment by erickyun** [comment]
> Fixed

Thank you
But -opt ytdlpoptions seems not to work?
When I try 
`/yl -z -n [oppai.stream] Rin x Sen + Ran -> Sem Cross Mix: Haru Urara Uragiri to Zetsubou no Kisetsu-hen - 02 (1080p AAC WEBM) -opt http_headers: {'Referer': 'https://oppai.stream/'}`
Bot wont download? Bot sends reply message instead? Note: tested download link is [here](https://github.com/anasty17/mirror-leech-telegram-bot/files/11686404/log2.txt)

Secondly, just to report to you /yl reply message is not up to date here 
`Note: You can't add -m arg for some links only, do it for all links or use multi without bulk!
link pswd: pass(zip/unzip) opt: ytdlpoptions up: remote2:path2
Reply to this example by this cmd for example /cmd b(bulk) m:folder_name(same dir)
You can set start and end of the links from the bulk with b:start:end or only end by b::end or only start by b:start. The default start is from zero(first link) to inf.`

**Comment by anasty17** [comment]
I will fix it soon thanks for reporting but next time open another issue please

**Comment by anasty17** [comment]
Done

**Comment by erickyun** [comment]
> Done

I appreciate your work. Thank you.
