### ISSUE TITLE
ability to zip upload

### ISSUE THREAD

**Issue by hitesh920** [anasty17/mirror-leech-telegram-bot#1483]
does this repo have this feature to put files in one folder using -m then zip that folder using -z?
for eg
/m link -m folder_name -z
/m https://speed.hetzner.de/100MB.bin -m bin-files -z
/m -i 10 -m bin-files -z

this will download and put those files in folder named "bin-files" then it will zip it then upload.

**Comment by anasty17** [comment]
Yes also usimg bulk but u should add -m folder_name for all links along with the links

**Comment by hitesh920** [comment]
> Yes also usimg bulk but u should add -m folder name for all links along with the links. Now u can add space to folder name also. But small issue i will fix it today. If -m folder -name this will raise error because it will recognise -name as arg.

i tried 
/m https://speed.hetzner.de/100MB.bin -m bin-files -z
didnt worked
i wanted bot to zip that link in a folder name "bin-files"
i think bot dont accept -m and -z both simultaneously

**Comment by anasty17** [comment]
It should accept but this feature (-m) maded for more than 1 link to make them in same folder. Maybe i didn't make it workable to one link but if not i will make today also. I didn't think about this before, why someone want to create folder for the file before zip. But if not working i will make it.

**Comment by anasty17** [comment]
> > Yes also usimg bulk but u should add -m folder name for all links along with the links. Now u can add space to folder name also. But small issue i will fix it today. If -m folder -name this will raise error because it will recognise -name as arg.
> 
> i tried /m https://speed.hetzner.de/100MB.bin -m bin-files -z didnt worked i wanted bot to zip that link in a folder name "bin-files" and uplaod bin-files.zip i think bot dont accept -m and -z both simultaneously

Bruh report in group i just notice ur name now!

**Comment by anasty17** [comment]
Done

**Comment by hitesh920** [comment]
> > > Yes also usimg bulk but u should add -m folder name for all links along with the links. Now u can add space to folder name also. But small issue i will fix it today. If -m folder -name this will raise error because it will recognise -name as arg.
> > 
> > 
> > i tried /m https://speed.hetzner.de/100MB.bin -m bin-files -z didnt worked i wanted bot to zip that link in a folder name "bin-files" and uplaod bin-files.zip i think bot dont accept -m and -z both simultaneously
> 
> Bruh report in group i just notice ur name now!

ah i dont use telegram that much this days, thats why reported here xD

**Comment by hitesh920** [comment]
> Done

nicee
