### ISSUE TITLE
mega module not found

### ISSUE THREAD

**Issue by Sl-Sanda-Ru** [anasty17/mirror-leech-telegram-bot#1484]
Traceback (most recent call last):                                                        File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,                                            File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)                                                               File "/home/ubuntu/mirror-leech-telegram-bot/bot/__main__.py", line 22, in <module>
    from .modules import authorize, clone, gd_count, gd_delete, gd_list, cancel_mirror, mirror_leech, status, torrent_search, torrent_select, ytdlp, rss, shell, eval, users_settings, bot_settings                                                                       File "/home/ubuntu/mirror-leech-telegram-bot/bot/modules/mirror_leech.py", line 16, in <module>                                                                                   from bot.helper.mirror_utils.download_utils.mega_download import add_mega_download
  File "/home/ubuntu/mirror-leech-telegram-bot/bot/helper/mirror_utils/download_utils/mega_download.py", line 6, in <module>
    from mega import (MegaApi, MegaListener, MegaRequest, MegaTransfer, MegaError)      ModuleNotFoundError: No module named 'mega'

**Comment by anasty17** [comment]
Use my docker

**Comment by PBhadoo** [comment]
> Use my docker

I can't use docker due to shared server, is it possible to know the Mega package used.?

**Comment by anasty17** [comment]
> > Use my docker
> 
> I can't use docker due to shared server, is it possible to know the Mega package used.?

Hi mate
I'm not using mega sdk anymore
Jdownloader can download from mega
