### ISSUE TITLE
Is that anyway to mirror multi Links ?

### ISSUE THREAD

**Issue by sennoncap** [anasty17/mirror-leech-telegram-bot#1486]
Is that anyway to mirror multi Links ? sir
like /mirror Links 1 && /mirror Link2 && /mirror Link3

**Comment by anasty17** [comment]
This added since 2021
Check multi -i in cmd usage

**Comment by sennoncap** [comment]
sorry for this .. can you show me an eg for Link1 and link2 sir...
please ...

**Comment by anasty17** [comment]
Ask in group for example
