### ISSUE TITLE
Feature request :- Autodetect 

### ISSUE THREAD

**Issue by azaryan7** [anasty17/mirror-leech-telegram-bot#149]
Can you enable autodetect for magnet links and torrent files for qbittorrent??

**Comment by TheReporters** [comment]
> Can you enable autodetect for magnet links and torrent files for qbittorrent??

+1 , **_it would a totally dope feature to have.._**

**Comment by anasty17** [comment]
> Can you enable autodetect for magnet links and torrent files for qbittorrent??

What u mean??
