### ISSUE TITLE
AttributeError when trying to add channel as sudo user?

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1495]
**Describe the bug**
Hello,

When I try to add TG Channel as sudo user in SuperGroup I get AttributeError.

**To Reproduce**
1. in SuperGroup, I reply to Channel message with `/addsudo` cmd.
2. When I check log, I see AttributeError?

I would appreciate if you could please fix this.

[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11886810/log.txt)

**Comment by anasty17** [comment]
Not supported
