### ISSUE TITLE
[Feature request] Add jmdkh-mltb's Multi Category ID

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1496]
Hello,

I would appreciate if you could implement [jmdkh-mltb#multi-category-ids](https://github.com/junedkh/jmdkh-mltb#multi-category-ids) to use upload in categorywise Gdrive TD/folder but for /rss menu for every specific rss feed torrent.

EX. `Title link -up -gd categoryName`
Also for mirror cmd please EX. `/m link -gd categoryName`

I count on your kind consideration of my request?

**Comment by anasty17** [comment]
Check todo list in my channel. Pinned message
