### ISSUE TITLE
Torrent options like `-d` `-s` `-up rcl` don't work together when replying to torrent link?

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1497]
**Describe the bug**
Hi,

When I try to reply torrent link with 
`/qm -s -d 1.0:50 -up rcl` bot won't start downloading? 
Bot sends reply message instead? 

When I execute cmd with replying torrent link options separately `/qm -s` `/qm -d 1.0:50` `/qm -up rcl` it works bot will download torrent 
but executing options together won't work bot send message instead?
Also not replying but including torrent link in cmd `/qm Link -s -d 1.0:50 -up rcl` works but like I said with reply it doesn't work?

I would appreciate if you could please fix this?

Nothing to see in Logs.txt

**Comment by anasty17** [comment]
Got it

**Comment by LoveThisWorld002** [comment]
> Got it
 
Thanks🙂👍
same error with /y /yl cmds btw

**Comment by anasty17** [comment]
Test now

**Comment by LoveThisWorld002** [comment]
> Test now

fixed it works thank you🙂👍👍👍
