### ISSUE TITLE
ytdlp referer opt is not working when link is in cmd but referer is working fine when replying to link?

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1498]
**Describe the bug**
Hello,

When I try to use `-opt http_headers: {'Referer': 'https://randomsite.stream/'}` with **link in cmd** like this
```
/yl LİNK -s -z -opt http_headers: {'Referer': 'https://randomsite.stream/'}
``` 
bot won't use Referer and gives `Error 404` but when I try to **reply link** like this
```
/yl -s -z -opt http_headers: {'Referer': 'https://randomsite.stream/'}
``` 
bot will download and use Referer.

I would appreciate if you could please fix this sir?

[Used Links in log](https://github.com/anasty17/mirror-leech-telegram-bot/files/11903722/log.1.txt)

**Comment by anasty17** [comment]
Fixed
Thanks for reporting
