### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Jack11705** [anasty17/mirror-leech-telegram-bot#150]
Sir can you add Instagram photo download Feature bot only downloads videos If I want to download photos then error showing

**Comment by Jack11705** [comment]
and not all videos get downloaded. some videos get error show please fix this issue to

**Comment by jusidama18** [comment]
@Jack11705 Send error and make sure u already add Instagram credentials in .netrc

**Comment by Jack11705** [comment]
![IMG_20211210_180218](https://user-images.githubusercontent.com/95500336/145574721-55d43fba-e46e-44e1-a035-d56f54929771.jpg)
![IMG_20211210_180158](https://user-images.githubusercontent.com/95500336/145574730-7bd2fda0-729e-4b72-8746-2ec5e2d05a3f.jpg)
if I am downloaded photo this type of error comes

**Comment by Jack11705** [comment]
![IMG_20211210_180233](https://user-images.githubusercontent.com/95500336/145574845-0b6b1d23-c682-4ed0-a136-2b8b9baf7378.jpg)
.netrc is fine some video I am downloaded

**Comment by anasty17** [comment]
@Jack11705 U can't spam insta with downloads ... 2nd u can't download photos

**Comment by Jack11705** [comment]
Yes Sir I know, That's why I have sent a feature request message, Can you add photo download feature?

**Comment by anasty17** [comment]
@Jack11705 No i can't we r using yt-dlp to download from Instagram

**Comment by Jack11705** [comment]
Ok sir, no problem. Thank you for answering me

**Comment by anasty17** [comment]
@Jack11705 U wlc
