### ISSUE TITLE
AttributeError with Multi links cmd?

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1500]
**Describe the bug**
Hello,

I did try to use multi link cmd `reply` `link` `/qm -up drop-crypt:Movies&TvShows/TvShows/The.Witch/ -i 5` but after bot arrived to `-i 3` İt stopped sending message? When I checked log I did see `AttributeError`

I kindly would appreciate if you could please fix this sir?

[log (2).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11923353/log.2.txt)

**Comment by anasty17** [comment]
Try again

**Comment by LoveThisWorld002** [comment]
> Try again

I did just try it but sadly I get same error again

[log (4).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11923946/log.4.txt)

**Comment by anasty17** [comment]
I will check it on Wednesday

**Comment by anasty17** [comment]
bro i can't produce this issue! can u send all links u was trying to mirror i want the next link which error raised on maybe issue related to link

**Comment by LoveThisWorld002** [comment]
> bro i can't produce this issue! can u send all links u was trying to mirror i want the next link which error raised on maybe issue related to link

All magnet links are in log sir [here](https://github.com/anasty17/mirror-leech-telegram-bot/files/11923353/log.2.txt) 

I did download in chronological order 
S03E01
S03E02
S03E03
S03E04
S03E05

So once bot adds S03E03 magnet link AttributeError is produced. Bot never sends auto cmd -i 2 for S03E04 and -i 1 for S03E05, instead bot gives AttributeError once -i 3 for S03E03 is added.

![IMG_20230704_085349_079](https://github.com/anasty17/mirror-leech-telegram-bot/assets/112317009/9807d323-bf3a-44fa-afaa-0b0118e5bde2)

**Comment by anasty17** [comment]
i can't produce the issue please report in group

**Comment by LoveThisWorld002** [comment]
> bro i can't produce this issue! can u send all links u was trying to mirror i want the next link which error raised on maybe issue related to link

Hello,
@anasty17

I did find out that the error is produced when 
Telegram Media/Video files are downloaded with MultiLink cmd!
When I execute `/l -z -i 2 -m folder` to a telegram video file bot gives AttributeError in logs.
but it works fine for telegram .txt text files! but not for telegram video files?

[log (3).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/12013519/log.3.txt)

**Comment by anasty17** [comment]
> > bro i can't produce this issue! can u send all links u was trying to mirror i want the next link which error raised on maybe issue related to link
> 
> Hello, @anasty17
> 
> I did find out that the error is produced when Telegram Media/Video files are downloaded with MultiLink cmd! When I execute `/l -z -i 2 -m folder` to a telegram video file bot gives AttributeError in logs. but it works fine for telegram .txt text files! but not for telegram video files?
> 
> [log (3).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/12013519/log.3.txt)

promote the bot!

**Comment by LoveThisWorld002** [comment]
> > > bro i can't produce this issue! can u send all links u was trying to mirror i want the next link which error raised on maybe issue related to link
> > 
> > 
> > Hello, @anasty17
> > I did find out that the error is produced when Telegram Media/Video files are downloaded with MultiLink cmd! When I execute `/l -z -i 2 -m folder` to a telegram video file bot gives AttributeError in logs. but it works fine for telegram .txt text files! but not for telegram video files?
> > [log (3).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/12013519/log.3.txt)
> 
> promote the bot! issue from ur side please report in group so i can understand well! i have tried what u said and everything is fine. Reach me on group

Hi @anasty17 

I found that if the **telegram file** is telegram `MEDİA` and **.mkv** bot gives AttributeError?
if .mkv telegram file is `document` bot gives no Error everything works fine! This error only happens on **.mkv file types**? Every other file types works fine.

İf you still think issue is from my side I will contact you on TG Group. Thanks for your great work and sorry for my late response.

**Comment by anasty17** [comment]
> > > > bro i can't produce this issue! can u send all links u was trying to mirror i want the next link which error raised on maybe issue related to link
> > > 
> > > 
> > > Hello, @anasty17
> > > I did find out that the error is produced when Telegram Media/Video files are downloaded with MultiLink cmd! When I execute `/l -z -i 2 -m folder` to a telegram video file bot gives AttributeError in logs. but it works fine for telegram .txt text files! but not for telegram video files?
> > > [log (3).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/12013519/log.3.txt)
> > 
> > 
> > promote the bot! issue from ur side please report in group so i can understand well! i have tried what u said and everything is fine. Reach me on group
> 
> Hi @anasty17
> 
> I found that if the **telegram file** is telegram `MEDİA` and **.mkv** bot gives AttributeError? if .mkv telegram file is `document` bot gives no Error everything works fine! This error only happens on **.mkv file types**? Every other file types works fine.
> 
> İf you still can't produce the error I will contact you on TG Group. Thanks for your great work and sorry for my late response.

Please contact me. I have tried to leech tg mkv media file and no error but the result is document. This change happened from tg. Andbi said in group i will remove the mkv exception for renaming
