### ISSUE TITLE
/clone rcl -up rcl ERROR No section: 'mrcc'

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1503]
**Describe the bug**
Hello,

When I execute `/clone rcl -up rcl` cmd select `My Config` I get `No section: 'mrcc'` Error!
When I select `Owner Config` there is no problem bot clone file successfully.

Another Error I found when I execute `/clone rcl -up rcl -rcf ServerSideAcrossConfigs:true` cmd I get 
`bot.helper.mirror_utils.rclone_utils.transfer - ERROR - ` 

Nothing to see in 
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11948969/log.7.1.txt)

I would appreciate if you could please fix this issue?

**Comment by anasty17** [comment]
While cloning don't add serverside option since already added for all.
And u should add -- before any option. I wrote some of examples.

mrcc only for rclone.conf that have been uploaded by usetting

**Comment by erickyun** [comment]
> While cloning don't add serverside option since already added for all. And u should add -- before any option. I wrote some of examples.
> 
> mrcc only for rclone.conf that have been uploaded by usetting

So for the first error I mentioned rclone.conf is already uploaded with usetting I select the remote drives but when copy start I get ERROR No section: 'mrcc' from rclone?

For the second issue I mentioned the cmd should be `/clone rcl -up rcl -rcf --server-side-across-configs` right sir? this also gives same error?

**Comment by anasty17** [comment]
sorry i didn't add server side as default but i have tried what u had, but no issues.
2nd issue fixed

**Comment by erickyun** [comment]
> sorry i didn't add server side as default but i have tried what u had, but no issues. 2nd issue fixed

Thanks but right now when I try to /clone bot gets stuck on status? Cloud Link or Rclone Link won't be send when I check log.txt message says clone done but no link is send?
[log (11).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/11951910/log.11.txt)

![IMG_20230704_220602](https://github.com/anasty17/mirror-leech-telegram-bot/assets/71968711/b390ca1f-ad47-4f6b-8f98-ad410b3155a4)
![IMG_20230704_220526](https://github.com/anasty17/mirror-leech-telegram-bot/assets/71968711/883c253a-28dd-44fb-9874-618ab739b5eb)

I appreciate it if you could also please fix this?

Also sir, this cmd work for you `/clone rcl -up rcl -rcf --server-side-across-configs` right?

**Comment by erickyun** [comment]
> 

2023/07/04 19:24:00 INFO  : Starting transaction limiter: max 3 transactions/s with burst 1
2023/07/04 19:24:00 DEBUG : rclone: Version "v1.62.2" starting with parameters ["rclone" "copy" "--fast-list" "--config" "rclone/111111111.conf" "-P" "evierx4:AZ ABC bypass/IMG_20230704_094530.jpg" "evierx4:" "--exclude" "*.{aria2,!qB}" "--ignore-case" "--low-level-retries" "1" "-M" "--log-file" "rlog.txt" "--log-level" "DEBUG" "--tpslimit" "3" "--transfers" "3"]
2023/07/04 19:24:00 DEBUG : Creating backend with remote "evierx4:AZ ABC bypass/IMG_20230704_094530.jpg"
2023/07/04 19:24:00 DEBUG : Using config file from "/usr/src/app/rclone/111111111.conf"
2023/07/04 19:24:01 DEBUG : Google drive root 'AZ ABC bypass/IMG_20230704_094530.jpg': 'root_folder_id = xxxxxxxx' - save this in the config to speed up startup
2023/07/04 19:24:02 DEBUG : fs cache: adding new entry for parent of "evierx4:AZ ABC bypass/IMG_20230704_094530.jpg", "evierx4:AZ ABC bypass"
2023/07/04 19:24:02 DEBUG : Creating backend with remote "evierx4:"
2023/07/04 19:24:02 DEBUG : Google drive root '': 'root_folder_id = xxxxxxxx' - save this in the config to speed up startup
2023/07/04 19:24:03 DEBUG : IMG_20230704_094530.jpg: Need to transfer - File not found at Destination
2023/07/04 19:24:05 DEBUG : IMG_20230704_094530.jpg: md5 = a03500ff68541a8b112639 OK
2023/07/04 19:24:05 INFO  : IMG_20230704_094530.jpg: Copied (server-side copy)
2023/07/04 19:24:05 INFO  : 
Transferred:      559.113 KiB / 559.113 KiB, 100%, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         4.6s

2023/07/04 19:24:05 DEBUG : 8 go routines active

**Comment by anasty17** [comment]
> 

![20230704_231441](https://github.com/anasty17/mirror-leech-telegram-bot/assets/77075674/c7fdf045-bfef-4eca-b60d-8d8512ab1fd4)

**Comment by anasty17** [comment]
How rclone/111111111.conf ??

**Comment by anasty17** [comment]
*Stdout*
2023/07/04 20:17:44 DEBUG : rclone: Version "v1.62.2" starting with parameters ["rclone" "copy" "--fast-list" "--config" "rclone.conf" "-P" "test1:InDesign.2023" "test2:InDesign.2023" "--exclude" "*.{aria2,!qB,exe,nfo,txt,jpg}" "--ignore-case" "--low-level-retries" "1" "-M" "--log-file" "rlog.txt" "--log-level" "DEBUG" "--server-side-across-configs"]
2023/07/04 20:17:44 DEBUG : Creating backend with remote "test1:InDesign.2023"
2023/07/04 20:17:44 DEBUG : Using config file from "/usr/src/app/rclone.conf"
2023/07/04 20:17:44 DEBUG : Creating backend with remote "test2:InDesign.2023"
2023/07/04 20:17:45 DEBUG : m0nkrus.nfo: Excluded from sync (and deletion)
2023/07/04 20:17:45 DEBUG : Google drive root 'InDesign.2023': Waiting for checks to finish
2023/07/04 20:17:45 DEBUG : Google drive root 'InDesign.2023': Waiting for transfers to finish
2023/07/04 20:17:48 DEBUG : Adobe.InDesign.2023.u2.Multilingual.md5: md5 = 6804047fc69664556bd284998d435b40 OK
2023/07/04 20:17:48 INFO  : Adobe.InDesign.2023.u2.Multilingual.md5: Copied (server-side copy)
2023/07/04 20:17:48 DEBUG : Adobe.InDesign.2023.u2.Multilingual.iso: md5 = 8ed7c335ff513c6f479c2e91650ab5d7 OK
2023/07/04 20:17:48 INFO  : Adobe.InDesign.2023.u2.Multilingual.iso: Copied (server-side copy)
2023/07/04 20:17:49 DEBUG : Adobe.InDesign.2023.u2.Multilingual.sha: md5 = aff838cd2b7e8d94cc636ff650a843d0 OK
2023/07/04 20:17:49 INFO  : Adobe.InDesign.2023.u2.Multilingual.sha: Copied (server-side copy)
2023/07/04 20:17:49 DEBUG : Adobe.InDesign.2023.u2.Multilingual.sfv: md5 = 44ba71f83e33bb28efd425b0aca6a62b OK
2023/07/04 20:17:49 INFO  : Adobe.InDesign.2023.u2.Multilingual.sfv: Copied (server-side copy)
2023/07/04 20:17:49 INFO  : 
Transferred:        1.213 GiB / 1.213 GiB, 100%, 310.514 MiB/s, ETA 0s
Transferred:            4 / 4, 100%
Elapsed time:         5.3s

2023/07/04 20:17:49 DEBUG : 15 go routines active

**Comment by erickyun** [comment]
> How rclone/111111111.conf ??

I did hide my telegram İD sir. I just wrote randomly sorry for not being clear enough.

**Comment by erickyun** [comment]
Were you able to produce error?
Try gdrive to gdrive copy within same remote `rclone copy test1x:folder1/file.jpg test1:`
Bot gets stucks 0% until I cancel?

Shall I open new issue for this

**Comment by anasty17** [comment]
> Were you able to produce error? `/clone rcl -up rcl -rcf --retries:999|--low-level-retries:999` Try gdrive to gdrive copy within same remote `rclone copy test1x:folder1/file.jpg test1:` Bot gets stucks 0% until I cancel?
> 
> Shall I open new issue for this

I have already tried. U can't clone from different config file btw. U should tell me exactly how to produce the error.
