### ISSUE TITLE
Same Directory Download and Zip for bulk links in a text file

### ISSUE THREAD

**Issue by thomassch8861** [anasty17/mirror-leech-telegram-bot#1507]
When I replied to a txt file containing filepress links with the command /m -b -z -m folder.name the files gets downloaded and starts to upload one by one to the onedrive (I am using rclone). What I need is first to download all the files to the folder named folder.name zip the folder and upload the zip file to the onedrive.

**Comment by anasty17** [comment]
U can't add options along with cmd when using bulk. All options must be written along with the link. U can read the examples and the notes in usage help by /m without any arg!!
