### ISSUE TITLE
Leech as media not works when leeching telegram document files

### ISSUE THREAD

**Issue by manimaran-1** [anasty17/mirror-leech-telegram-bot#1509]
When leeching telegram media files, bot leeches as media, but if leeching telegram document files, it leech as document type not as media.

I have checked config variables, the value as follows 
as_document=false 

and also checked in user setting

it keeps leech as document type when leeching telegram document type files

**Comment by anasty17** [comment]
This will get fixed soon. There is a chnage done by tg for mkv files
