### ISSUE TITLE
Local Mirror

### ISSUE THREAD

**Issue by m-kaissi** [anasty17/mirror-leech-telegram-bot#1512]
I would like support for local mirroring , I use a vps , and I have mounted a drive using rclone mount and I want to use it with your bot using docker volumes , so that the file will be directly downloaded to the mounted drive using rclone , and no need for uploading it , because it will be downloaded directly to the drive.
Thank you for your hard work.

**Comment by darkmaster420** [comment]
You can do that through rclone. Just add an alias and point your downloads to it

**Comment by m-kaissi** [comment]
It's the same bro , I tried it the bot gonna download the files and then instead of uploading the files , it's just gonna move them , which it's the same speed as uploading using rclone , so there's no point of it.

**Comment by anasty17** [comment]
> It's the same bro , I tried it the bot gonna download the files and then instead of uploading the files , it's just gonna move them , which it's the same speed as uploading using rclone , so there's no point of it.

He meant use the rclone directly in vps and he is right! Use ssh!

**Comment by anasty17** [comment]
> I would like support for local mirroring , I use a vps , and I have mounted a drive using rclone mount and I want to use it with your bot using docker volumes , so that the file will be directly downloaded to the mounted drive using rclone , and no need for uploading it , because it will be downloaded directly to the drive. Thank you for your hard work.

Bro i think u can do this now. This local drive have a remote ?

**Comment by m-kaissi** [comment]
> > I would like support for local mirroring , I use a vps , and I have mounted a drive using rclone mount and I want to use it with your bot using docker volumes , so that the file will be directly downloaded to the mounted drive using rclone , and no need for uploading it , because it will be downloaded directly to the drive. Thank you for your hard work.
> 
> Bro i think u can do this now. This local drive have a remote ?

I guess you didn't understand what I meant.

I have Mounted gdrive as a local drive , so my gdrive is mounted on /home/ubuntu/gdrive , and I can download files directly to that without needing uploading them again , i need just to download them directly to it, so no need for upload , so what I'm suggesting is adding a feature to just let the bot download the files and keep them without uploading them , then I can use docker volumes, so that I can bind where I mounted my gdrive with rclone mount (/home/ubuntu/gdrive) with the download folder in the docker container , so that the files will be downloaded to where I mounted the gdrive rclone.

**Comment by m-kaissi** [comment]
so the docker-compose should be like that

version: "3.3"

services:
  app:
    build: .
    command: bash start.sh
    volumes:
      - /home/ubuntu/gdrive:/usr/src/app/downloads # optional
    ports:
      - "80:80" # qbittorrent selection webserver
      - "8080:8080" # rclone serve index webserver
    restart: on-failure

**Comment by m-kaissi** [comment]
as you see here when I go to that directory inside the vps where I mounted the gdrive using rclone , I can see my gdrive files.
![Capture](https://github.com/anasty17/mirror-leech-telegram-bot/assets/62901183/9576d271-6325-4483-a368-00f485b108be)

**Comment by m-kaissi** [comment]
see , I downloaded this file directly to my gdrive using aria2c. no need for downloading then uploading.
![Capture](https://github.com/anasty17/mirror-leech-telegram-bot/assets/62901183/30869d31-ec93-45e3-b38e-0cc8b98c1a05)

**Comment by darkmaster420** [comment]
You know it still uploads after you move it to gdrive. The same as using rclone idk why you're making it more difficult for yourself

**Comment by m-kaissi** [comment]
Bro it's not uploading, it's a directly getting downloaded to that directory where I mounted the gdrive

**Comment by anasty17** [comment]
How rclone related to this?! I still didn't understand! The bot can allow u to download different types of links.

**Comment by m-kaissi** [comment]
I've been using your bot for more than a year , thank you for your hard work and time.
It's not related to rclone , the feature that I'm asking for is local mirror , the bot just download files using qbit and aria2 and doesn't upload them just keep them in the vps, that's what I'm requesting. Like you can add another option to the default_upload variable so that it can be gd and rc and local.

**Comment by m-kaissi** [comment]
It's available on  [This repo](https://github.com/Sam-Max/rcmltb) , but I guess it got removed.
