### ISSUE TITLE
Add nzb support

### ISSUE THREAD

**Issue by darkmaster420** [anasty17/mirror-leech-telegram-bot#1514]
Can you add nzb support?

**Comment by aicynide** [comment]
Hey dev, you can add it in just a hour😉
https://github.com/sanjit-sinha/Tg-UsenetBot

**Comment by darkmaster420** [comment]
> Hey dev, you can add it in just a hour😉 https://github.com/sanjit-sinha/Tg-UsenetBot

Only tracks progress doesn't download any nzb content

**Comment by aicynide** [comment]
> > Hey dev, you can add it in just a hour😉 https://github.com/sanjit-sinha/Tg-UsenetBot
> 
> Only tracks progress doesn't download any nzb content

Nice IQ, Rajesh

**Comment by anasty17** [comment]
very soon mate
