### ISSUE TITLE
Over storage

### ISSUE THREAD

**Issue by BotTutorials** [anasty17/mirror-leech-telegram-bot#1519]
Please add below feature
**- put task in the queue when there is not enough storage space**
**- cancel task when file size is greather than storage space**

**Comment by anasty17** [comment]
dropped!
this will never get stable because of aria2 and qbittorrent allocation files ... and .. selecting files from jdownloader and torrents and and also problem might be from using storage from outside docker can cause 1 queued download from total tasks which is 1 also
