### ISSUE TITLE
Error R14 (Memory quota exceeded)

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#152]
Showing Error R14 (Memory quota exceeded) even after forking latest repo 
![image](https://user-images.githubusercontent.com/68769346/145664135-7c82af4c-1a7f-42b5-a956-fb9c7344f629.png)

**Comment by jusidama18** [comment]
@rajput-hemant already refork?

**Comment by anasty17** [comment]
@rajput-hemant Full log

**Comment by anasty17** [comment]
@rajput-hemant I was talking about ram exceeded while downloading direct link not mega

**Comment by rajput-hemant** [comment]
> @rajput-hemant I was talking about ram exceeded while downloading direct link not mega

no i didn't Mirror mega
problem is with Torrent mirroring
or maybe its specific yo qbmirror only

**Comment by anasty17** [comment]
Decrease asyncio threads from 8 to 4
