### ISSUE TITLE
Auto map all tg files/links from first tg link until reach specific range

### ISSUE THREAD

**Issue by kkhanyaseen** [anasty17/mirror-leech-telegram-bot#1529]
Create a option to download from tg links when user send the number of files.
Example:
The first episode file of a tv series has this tglink https://t.me/c/1820463923/147141. Assume the Telegram channel is private and content restricted. The whole tv show has 16 episodes. So when user reply to the https://t.me/c/1820463923/147141 link with a command ask the user to enter the number of files need to be downloaded. So the files will start to get download. Only need to increment the last number in the link.
If first episode link is https://t.me/c/1820463923/147141 then the second episode link should be https://t.me/c/1820463923/147142 Make this work for every command like zipping in to a folder and uploading

**Comment by anasty17** [comment]
Is it hard to copy all files links ?

**Comment by kkhanyaseen** [comment]
More than 100 link can't copy one by one bruh, too much time waste. I hope u will add🙏

**Comment by anasty17** [comment]
I will think about better solution for this.

**Comment by anasty17** [comment]
> Create a option to download from tg links when user send the number of files. Example: The first episode file of a tv series has this tglink https://t.me/c/1820463923/147141. Assume the Telegram channel is private and content restricted. The whole tv show has 16 episodes. So when user reply to the https://t.me/c/1820463923/147141 link with a command ask the user to enter the number of files need to be downloaded. So the files will start to get download. Only need to increment the last number in the link. If first episode link is https://t.me/c/1820463923/147141 then the second episode link should be https://t.me/c/1820463923/147142 Make this work for every command like zipping in to a folder and uploading

This will would be used like multi feature. Alsobwe can add tg links for link message not only document files
