### ISSUE TITLE
[feature request] Select files before downloading using aria2

### ISSUE THREAD

**Issue by ckn4** [anasty17/mirror-leech-telegram-bot#153]
Could you please add the feature  taht selecting files from Torrent before downloading using aria2? Just like [this](https://github.com/gaowanliang/DownloadBot/blob/main/img/3.jpg).

I tried to use the same funcation using qbittorrent, but failed. I used the command "/qbmirror s", it just downloads without asking which files to select. And finally it says "`HttpError 403 when requesting https://www.googleapis.com/drive/v3/files/***/permissions?supportsTeamDrives=true&alt=json returned "The user does not have sufficient permissions for this file.". Details: "[{'domain': 'global', 'reason': 'insufficientFilePermissions', 'message': 'The user does not have sufficient permissions for this file.'}]"`" I am sure I have the permissions to upload to my gdrive, because I have upload successfully several times before.

Thanks.

**Comment by anasty17** [comment]
Qbittorrent only for torrents
