### ISSUE TITLE
[Bug] Error with `/yl` got an unexpected keyword argument 'n'"

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1535]
**Describe the bug**
Hi,
when I reply execute to https://youtu.be/ssvu5MMR67s
```
/yl -opt fragment_retries:^inf|final_ext:mkv|writesubtitles:True|allsubtitles:true|subtitleslangs: ['all', '-live_chat']|postprocessors: [{'key': 'FFmpegVideoRemuxer', 'preferedformat': 'mkv'}, {'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': False}, {'api': 'https://sponsor.ajay.app', 'categories': {'chapter', 'filler', 'interaction', 'intro', 'music_offtopic', 'outro', 'poi_highlight', 'preview', 'selfpromo', 'sponsor'}, 'key': 'SponsorBlock', 'when': 'after_filter'}, {'force_keyframes': False, 'key': 'ModifyChapters', 'remove_chapters_patterns': [], 'remove_ranges': [], 'remove_sponsor_segments': set(), 'sponsorblock_chapter_title': '[SponsorBlock]: ' '%(category_names)l'}, {'add_chapters': True, 'add_infojson': 'if_exists', 'add_metadata': True, 'key': 'FFmpegMetadata'}]
```

I get `got an unexpected keyword argument 'n'"` Error? Bot won't upload file and gets stuck on download progress? cancel wont work once this error is produced Only after I restrart the bot it will return to normal.

I would appreciate if you could please fix this error sir.

[log (6).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/12386574/log.6.txt)

**Comment by anasty17** [comment]
Lib bug

**Comment by anasty17** [comment]
not lib issue. but i forget the retry sleep functions
will fix in minutes

**Comment by erickyun** [comment]
> not lib issue. but i forget the retry sleep functions will fix in minutes

Thank you sir
