### ISSUE TITLE
Telegram is very slow

### ISSUE THREAD

**Issue by kuesttman** [anasty17/mirror-leech-telegram-bot#1541]
Hello everything is fine?

Once again, I would like to thank you and say that I really like your work with this project.

One question, I would like to clarify.
I'm hosting Mirror Bot on a VPS, so I can stay online and have a good internet connection.
However, downloading/uploading Telegram is very slow. Speeds between 900KBps ~ 4MBps... Since when I download/upload from Google Drive/Mega.Nz/Torrent... they go with speeds between 15MBps to 50MBps...
Is it if it was the update of the telegram bot, or is it some limitation of Telegram itself?

Thank you very much in advance.

**Comment by anasty17** [comment]
it depend on vps location and bot or user dc location. not issue related to code

**Comment by kuesttman** [comment]
How do I check my user's dc? It's possible?

**Comment by anasty17** [comment]
Sure google it bro! U can see it if u r using plus messenger beta version
