### ISSUE TITLE
Mediainfo Implementation

### ISSUE THREAD

**Issue by Antidaze** [anasty17/mirror-leech-telegram-bot#1543]
I guess mediainfo already in docker so it would be great if u implement mediainfo generation from like torrents, ddls and telegram files.This would be useful for many users.
Thank you for this awesome repo

**Comment by anasty17** [comment]
Why media info is important?

**Comment by Antidaze** [comment]
Not really bro but it's good to have with.for few it might be important.some modified repos have it but but ur version would be better so please consider it.

**Comment by xd003** [comment]
@anasty17 

```
import requests
import subprocess

url = "your_url_here"
response = requests.get(url, headers={'Range': 'bytes=0-1000000'}, stream=True)

with open("partial.mp4", "wb") as f:
    for chunk in response.iter_content(chunk_size=1024):
        if chunk:
            f.write(chunk)

subprocess.run(["mediainfo", "partial.mp4"])
```

Can use this for mediainfo, it will download a very small chunk of the file very quickly & generate a mediainfo accordingly

**Comment by anasty17** [comment]
> @anasty17
> 
> ```
> import requests
> import subprocess
> 
> url = "your_url_here"
> response = requests.get(url, headers={'Range': 'bytes=0-1000000'}, stream=True)
> 
> with open("partial.mp4", "wb") as f:
>     for chunk in response.iter_content(chunk_size=1024):
>         if chunk:
>             f.write(chunk)
> 
> subprocess.run(["mediainfo", "partial.mp4"])
> ```
> 
> Can use this for mediainfo, it will download a very small chunk of the file very quickly & generate a mediainfo accordingly

yeah bro it's easy when u r using one download package (tool)! 
i should add to all or nothing. what if folder ?
u only gave example for ddl

**Comment by anasty17** [comment]
this will not work for all links 
so
dropped!
