### ISSUE TITLE
Path Saver

### ISSUE THREAD

**Issue by darkmaster420** [anasty17/mirror-leech-telegram-bot#1545]
Can you add a saved path selector like say you use 2 paths a lot so instead of typing the whole path all over or selecting it with rclone every time you can add something that keeps track of some paths like 
1. drive1:path/path/path/path1
2. drive1:path/path/path/path2
3. drive2:path/path/path/path
So when you say you want a torrent downloaded to say path 2 it could be
/qm -path 2 -other -stuff

**Comment by anasty17** [comment]
Add title upon ur request for specific rclone-path/gdrive-id/tg-chat

**Comment by anasty17** [comment]
Note:
add in usetting option to save default upload destination rclone-path/gdrive-id/tg-chat
title1= -10066566546475 - tg
title2= rclone:path - rclone
title3= gdrive_id

**Comment by anasty17** [comment]
added
