### ISSUE TITLE
Upload file sorter by matching name

### ISSUE THREAD

**Issue by undeadmecha0** [anasty17/mirror-leech-telegram-bot#1546]
**Is your feature request related to a problem? Please describe.**
I'm using RSS for TV shows and has 25 titles subbed.
It will upload to its specific folder for each show because i added -up gdl/rcl in the command however sometimes it will hit rate limit and causes error (resource not found) meaning the ip is on a cooldown for rate limit.

**Describe the solution you'd like**
My current RSS format is 
tvshow1 link -c /m -up gdl -inf tvshow1
tvshow25 link -c /m -up gdl -inf tvshow25
Is it possible to have an upload sorter? If it matches the specific filename it will upload to a chosen folder like

Fitgirl|Dodi|Repack -up id/remote:games
Season|Episode -up id/remote:tv shows
BDRip|Remux|WEB-DL -up id/remote:movies
.mp3|flac -up id/remote:music

A configurable one like how you subscribe rss
So that i can only sub to a single RSS instead of 25 and not hit rate limit.
Is this possible?

**Describe alternatives you've considered**
I already tried to change the RSS delay to 1-2 hour and still hit it. 
Tried to divide the RSS tasks in 2 bots and still hits it but sometimes it works lol.

**Comment by anasty17** [comment]
Why using gdl/rcl use specific upload destination. And sure i can't know if is the file is game or movie or any other thing. And sure u will hit the limit and rss delay no related. This because u have added the same rss feed more than once and u sending more requests to the same rss feed at the execute time

**Comment by undeadmecha0** [comment]
Well i was using gdl/rcl for every feed so that the "TVSHOW1" in the RSS will directly upload to "TVSHOW1" folder not in the cluttered default upload folder.
It sorts "automatically" which is far better than having more buttons for destination uploads or sorting manually
Which kinda defeats the purpose of having RSS if it still need more hands on manual sorting
Uh that's how i envisioned it to be turns out to be a poor idea
Its working _fine_ now I just reduced the amount of sub

Anyways thanks for the response i found this script for qbitrclone it has a name parser incase you will be interested
https://github.com/Abu3safeer/qbittorrent_rclone
