### ISSUE TITLE
Direct link error while QUEUE DOWNLOAD

### ISSUE THREAD

**Issue by ShadowHunterV** [anasty17/mirror-leech-telegram-bot#1548]
Some direct links (created from direct link generator) are valid for limited time.  but if I added queue download bot create link from direct link generator then added to queue. but some time queue took long time so created link is expired. 
So create link after queue end.
Sorry for bad English <:)

**Comment by anasty17** [comment]
No i will add option force start option

**Comment by anasty17** [comment]
Note:
add arg -f to force start

**Comment by ketela7** [comment]
its this work ?
how to use ?

**Comment by anasty17** [comment]
Not added yet. Still in issues!
