### ISSUE TITLE
Auto add incomplete tasks after restart

### ISSUE THREAD

**Issue by Miss-Milli** [anasty17/mirror-leech-telegram-bot#1550]
- Auto add incomplete tasks if bot restarts unexpectedly.
- If bot restart by /restart cmd then it will ask if owner wants to add those tasks back or not.

**Comment by TheFlashSpeedster** [comment]
Yeah, its really helpful.
There should be option to either **add or cancel** incomplete tasks whether its restarted unexpectedly or manually (via /restart)

Owner: Option to add all incomplete tasks
User: Option to add their own incomplete tasks

**Comment by anasty17** [comment]
> Yeah, its really helpful. There should be option to either **add or cancel** incomplete tasks whether its restarted unexpectedly or manually (via /restart)
> 
> Owner: Option to add **all or their own** incomplete tasks User: Option to add their own incomplete tasks

No it's only for owner

**Comment by anasty17** [comment]
Note:
Save message text (link/args), message id, cmd, user_id, chat_id, (isQbit=False, isLeech=False or check cmd if qb or leech)

**Comment by anasty17** [comment]
https://github.com/anasty17/mirror-leech-telegram-bot/issues/1656
