### ISSUE TITLE
Support m3u8 links

### ISSUE THREAD

**Issue by 1715819** [anasty17/mirror-leech-telegram-bot#1552]
Can support download m3u8 link?

Related projects:https://github.com/globocom/m3u8

This item is for reference only.

**Comment by anasty17** [comment]
> Can support download m3u8 link?
> 
> Related projects:https://github.com/globocom/m3u8
> 
> This item is for reference only.

if there is an issue in yt-dlp or something missing let me know please

**Comment by anasty17** [comment]
> > Can support download m3u8 link?
> > Related projects:https://github.com/globocom/m3u8
> > This item is for reference only.
> 
> if there is an issue in downloading m3u8 with yt-dlp or something missing let me know please
