### ISSUE TITLE
[Bug] Error with /usetting YT-DLP Options

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1562]
**Describe the bug**
Hi,
Firstly, I did find a bug with /yl cmd
when, I reply link with /yl I get an **incompleted uploaded video** when I [use this as](https://github.com/anasty17/mirror-leech-telegram-bot/files/12590229/usetting.YT-DLP.Option.txt) /usetting YT-DLP Option. The video file gets incompleted uploaded like frag.16.part and incompleted.youtube.video.mkv I get in total two different files uploaded to Telegram!

Secondly, when I reply link `/yl -s` I select 240p but bot won't download 240p but still uses YT-DLP Option format:bv*[height<=1080][ext=mp4]+ba[ext=m4a]/bv* and I get 1080p video instead.

I would appreciate if you could please fix this issues.

[log (9).txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/12589962/log.9.txt)

**Comment by anasty17** [comment]
1st problem mostly from yt-dlp or from ur options. Is there any difference in result while trying default options from bsetting? I guess no
2nd there was an issue only while using default audio format option. I have tried selection while default download format is audio

**Comment by erickyun** [comment]
> 1st problem mostly from yt-dlp or from ur options. Is there any difference in result while trying default options from bsetting? I guess no 2nd there was an issue only while using default audio format option. I have tried selection while default download format is audio

Actually for a long time problem the 1st problem also sometime occurs with playlist but now it also happens with youtube video links only? When I try multiple times /yl I get complete video after some tries? but this problem still persists?

2nd problem still occurs for me if I use this or this one as YT-DLP Option! Bot won't download selected example 360p quality but 1080p instead?

```
format:bv*[height<=1080][ext=mp4]+ba[ext=m4a]
```

```
format:bv*[height<=1080][ext=mp4]+ba[ext=m4a]/bv*|fragment_retries:^inf|final_ext:mkv|writesubtitles:True|subtitleslangs:['tur.*', 'en.*', '.*-orig']|writeautomaticsub:True|postprocessors:[{'key': 'FFmpegVideoRemuxer', 'preferedformat': 'mkv'}, {'format': 'ass', 'key': 'FFmpegSubtitlesConvertor', 'when': 'before_dl'}, {'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': False}, {'api': 'https://sponsor.ajay.app', 'categories': {'chapter', 'filler', 'interaction', 'intro', 'music_offtopic', 'outro', 'poi_highlight', 'preview', 'selfpromo', 'sponsor'}, 'key': 'SponsorBlock', 'when': 'after_filter'}, {'force_keyframes': False, 'key': 'ModifyChapters', 'remove_chapters_patterns': [], 'remove_ranges': [], 'remove_sponsor_segments': set(), 'sponsorblock_chapter_title': '[SponsorBlock]: ' '%(category_names)l'}, {'add_chapters': True, 'add_infojson': 'if_exists', 'add_metadata': True, 'key': 'FFmpegMetadata'}]
```

**Comment by anasty17** [comment]
Add default format:ba/b-mp3-320
And try select if something wrong in my code then it will download mp3. Otherwise the issue from yt-dlp. And try to remove the default quality.

**Comment by anasty17** [comment]
> Add default format:ba/b-mp3-320 And try select if something wrong in my code then it will download mp3. Otherwise the issue from yt-dlp. And try to remove the default quality.

This incomplete download only happens with u. How to produce this issue?

**Comment by erickyun** [comment]
> Add default format:ba/b-mp3-320 And try select if something wrong in my code then it will download mp3. Otherwise the issue from yt-dlp. And try to remove the default quality.
> 
> This incomplete download only happens with u. How to produce this issue?

This incomplete download error happens most times with long 1080p youtube videos at leats 10min.
So I have two VPS both are from Buyvm RYZEN KVM 1GB but one VPS does have extra Block Storage Slab - 256GB mounted and this error always occurs with the mounted Storage vps? I don't know why? Your help is appreciate sir?

**Comment by anasty17** [comment]
> > Add default format:ba/b-mp3-320 And try select if something wrong in my code then it will download mp3. Otherwise the issue from yt-dlp. And try to remove the default quality.
> > This incomplete download only happens with u. How to produce this issue?
> 
> This incomplete download error happens most times with long 1080p youtube videos at leats 10min. So I have two VPS both are from Buyvm RYZEN KVM 1GB but one VPS does have extra Block Storage Slab - 256GB mounted and this error always occurs with the mounted Storage vps? I don't know why? Your help is appreciate sir?

Mostly connection speed or low ram and cpu.
Try to download 1 task

**Comment by erickyun** [comment]
> > > Add default format:ba/b-mp3-320 And try select if something wrong in my code then it will download mp3. Otherwise the issue from yt-dlp. And try to remove the default quality.
> > > This incomplete download only happens with u. How to produce this issue?
> > 
> > 
> > This incomplete download error happens most times with long 1080p youtube videos at leats 10min. So I have two VPS both are from Buyvm RYZEN KVM 1GB but one VPS does have extra Block Storage Slab - 256GB mounted and this error always occurs with the mounted Storage vps? I don't know why? Your help is appreciate sir?
> 
> Mostly connection speed or low ram and cpu. Try to download 1 task

I will try to ask yt-dlp about this because it is happening now with all kind of YTUBE videos?

**Comment by erickyun** [comment]
**Verbose:** [Log.txt](https://github.com/yt-dlp/yt-dlp/files/12736894/log.13.txt)

**Comment by anasty17** [comment]
I have added exception gor this folder name. This shouldn't be the file/folder name. I will check soon.
Thanks for reporting. Next time please open new issue

**Comment by erickyun** [comment]
> I have added exception gor this folder name. This shouldn't be the file/folder name. I will check soon. Thanks for reporting. Next time please open new issue

**Verbose:** [Log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/12743104/log.1.txt)

**Comment by anasty17** [comment]
mate this happened because the video not downloaded idk why! why u the only one who facing those problems.
meet me on telegram for conv.
