### ISSUE TITLE
how can we deploy bot on huggingface space using docker, this side provide docker and cpu and ram, please look into it

### ISSUE THREAD

**Issue by imner0** [anasty17/mirror-leech-telegram-bot#1566]
how can we deploy bot on hugging face space ?
hugging face provide docker with RAM and CPU free
please sir look into it please

**Comment by anasty17** [comment]
storage? just upload files using git and access token and run !

**Comment by imner0** [comment]
Huggingface don't have any storage issue, maybe it's unlimited.
I don't know bro how to deploy on huggingface face I don't have this much knowledge about programming i just follow your steps.
In Huggingface space  you can only run using dockerfile, and their dockerfile have specific port we only use that port.

**Comment by anasty17** [comment]
How no storage limit! I will check soon

**Comment by imner0** [comment]
> How no storage limit! I will check soon

Sir, did you find solution on this?

**Comment by anasty17** [comment]
It's not about finding solution! As i told u. But u should know how much storage u can get!!

**Comment by imner0** [comment]
50gb Persistent. this much storage is fine for small files

**Comment by anasty17** [comment]
> 50gb Persistent. this much storage is fine for small files ?

yes
