### ISSUE TITLE
/usr/bin/python3: No module named bot

### ISSUE THREAD

**Issue by heypious** [anasty17/mirror-leech-telegram-bot#1568]
I have build the docker image on 4 different machines and tried to deploy it (Raspberry pi 3b, i3 pc, old hp 32bit laptop and google cloud shell).
When trying to deploy (execute the docker run command)
error would come "/usr/bin/python3: No module named bot"
![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/59928150/0ead65c5-dd6d-49cd-9961-32f4440d0c0b)
i am executing all commands in the mirrorbot directory where bot directory is there (made by git clone)
![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/59928150/6d987a4f-bcf2-47e5-bd14-2bc25f12c1b1)

Note: I have ran "pip3 install -r requirements-cli.txt" in all machines before building and deploying

**Comment by anasty17** [comment]
some thing wrong in build!
