### ISSUE TITLE
qBittorrent settings?

### ISSUE THREAD

**Issue by Anon0511** [anasty17/mirror-leech-telegram-bot#157]
Hey,

thank you for your work!

I have it setup on my dedicated server. For qBittorent, isn't there supposed to be an UI?

```
<h1>See mirror-leech-telegram-bot <a href='https://www.github.com/anasty17/mirror-leech-telegram-bot'>@GitHub</a> By <a href='https://github.com/anasty17'>Anas</a></h1>
```

**Comment by junedkh** [comment]
@Anon0511 Which server you have ?

**Comment by Anon0511** [comment]
Sorry, I don't understand what you mean specifically. It's a dedicated Hetzner server and the Bot is running in Docker.

**Comment by jusidama18** [comment]
@Anon0511 It's mirror bot, UI not really necessary besides for qbit select

**Comment by Anon0511** [comment]
Probably for it's supposed reason, yes.

But I only have private trackers and Ratio is very important to me. I was looking forward for being able to create new torrents and up them to benefit from the speed of G. 
Also I want to use `QB_SEED = "True"` and keep `MaxRatio -1` and `GlobalMaxSeedingMinutes -1` and manage that manually.

I checked within the container and with curl, seems like the port from qBittorrent.conf is the one being used, I expected it to end up being the `SERVER_PORT`. So Web access works now for me.

```
tcp6       0      0 :::8090                 :::*                    LISTEN      13/qbittorrent-nox
```

Although, that opens up another question, what is `SERVER_PORT` actually used for?

**Comment by anasty17** [comment]
@Anon0511 For web selection

**Comment by Anon0511** [comment]
Thanks
