### ISSUE TITLE
Failed to Download youtube videos when selecting some resolution

### ISSUE THREAD

**Issue by NekoMio** [anasty17/mirror-leech-telegram-bot#1576]
**Describe the bug**
Failed to Download youtube videos when selecting some resolution

**To Reproduce**
1. /y https://www.youtube.com/watch?v=r7c3IqbeW8A
2. select 2160p
3. Download Error

**Expected behavior**

**Screenshots**
![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/28840791/5f1d57f4-1cf6-45b0-b74a-0dedc09e130a)

**Additional context**
Download use format "bv*[format_id=313]+ba/b[height=?2160]" but fail

**Comment by NekoMio** [comment]
> 1. https://www.youtube.com/watch?v=r7c3IqbeW8A

**Comment by anasty17** [comment]
fixed thanks for reporting
