### ISSUE TITLE
Add RSS category and size, 

### ISSUE THREAD

**Issue by nonefor** [anasty17/mirror-leech-telegram-bot#1577]
Kindly add categories and size information in rss feed post, it will show about that link category and size. Additionally, be mindful that some RSS sites provide URL paths/pages instead of complete URL, that should be fixed.

**Comment by anasty17** [comment]
send rss that provide category and size

**Comment by nonefor** [comment]
This one - https://www.limetorrents.to/rss/

And this one uses path only - https://www.torrentdownloads.pro/rss

**Comment by anasty17** [comment]
each one is different!
