### ISSUE TITLE
Stop Duplicate tg files

### ISSUE THREAD

**Issue by anasty17** [anasty17/mirror-leech-telegram-bot#1583]
checking file after download 
size and name is enough
incase we have incompleted downloads
u will get the file forwared and old file will be deleted. 
so instead of uploading same file we will simpl forwared it replying to the new task

**Comment by junedkh** [comment]
bot cannot delete if message older then two days.

**Comment by anasty17** [comment]
> bot cannot delete if message older then two days.

bot even can't search bro... this need user session

**Comment by junedkh** [comment]
> > bot cannot delete if message older then two days.
> 
> bot even can't search bro... this need user session

Oh yes..
