### ISSUE TITLE
yt-dlp not work with audio only links

### ISSUE THREAD

**Issue by TgSeed** [anasty17/mirror-leech-telegram-bot#1585]
**Describe the bug**
Titles says, yt-dlp doesn't work with audio only links, e.g soundcloud

**To Reproduce**
1. `/yl https://soundcloud.com/small-kidd/dumb-star`

**Additional context**
This is stupid bug with a clear solution.

**Comment by anasty17** [comment]
Why the fuck u r talking like bitches ?if u wanna help just stay polite or don't! Next impolite behaviour i will block u!

**Comment by BotTutorials** [comment]
> **Describe the bug** Titles says, yt-dlp doesn't work with audio only links, e.g soundcloud
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. `/yl https://soundcloud.com/small-kidd/dumb-star`
> 
> **Additional context** This is stupid bug with a clear solution.

So why you don't solve yourself 😂😂

**Comment by TgSeed** [comment]
> Why the fuck u r talking like bitches ?if u wanna help just stay polite or don't! Next impolite behaviour i will block u!

I started fine with creating simple issues and PRs to help you, but you started bitching on merging and accepting thrm, so here we are! deal with it

**Comment by TgSeed** [comment]
> > **Describe the bug** Titles says, yt-dlp doesn't work with audio only links, e.g soundcloud
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. `/yl https://soundcloud.com/small-kidd/dumb-star`
> > 
> > **Additional context** This is stupid bug with a clear solution.
> 
> So why you don't solve yourself 😂😂

Who says i didnt?
https://github.com/TgSeed/mirror-leech-telegram-bot/commit/bc7880ce57ad8a8d2bcc6913d82fb4dda8cf6dad
I fixed that before creating this issue, just didnt made a PR as the repo. owner doesnt deserve.
😂😂

**Comment by ClayArsenio26** [comment]
sir, can you help me ? can I setting the yt-dlp if start leeching to telegram is there nothing clicked choose the video quality, will return to leech best video default ? not return to Timed Out. Task has been cancelled!

**Comment by anasty17** [comment]
> sir, can you help me ? can I setting the yt-dlp if start leeching to telegram is there nothing clicked choose the video quality, will return to leech best video default ? not return to Timed Out. Task has been cancelled!

Sure first ask in group or open new issue.
Use -opt format:bv*+ba/b along with the cmd or set default yt-dlp quality and write format:bv*+ba/b
This format for best quality. Read more from yt-dlp readme
