### ISSUE TITLE
Can't generate token.pickle file after google new policies

### ISSUE THREAD

**Issue by crastex** [anasty17/mirror-leech-telegram-bot#1586]
**Describe the bug**
Can't generate token.pickle from [generate_drive_token.py](https://github.com/anasty17/mirror-leech-telegram-bot/blob/master/generate_drive_token.py) anymore as google patched it

**To Reproduce**
1. You can check generating the token.pickle for yourself it wont work

**Expected behavior**
It should be generated :-|

**Screenshots**
![Screenshot (176)](https://github.com/anasty17/mirror-leech-telegram-bot/assets/140511728/7f2711ba-2657-46d5-84b2-a68965efc4e2)

**Additional context**
Its something like google did it with rclone authorize setup for what gdtot came with a solution of pasting localhost error which they using now since months and working so better. Can we have something like that login method if we cant fix this (https://new10.gdtot.cfd/login2) reference (https://www.youtube.com/shorts/T_S7fSMfjfo)

**Comment by crastex** [comment]
@anasty17

**Comment by anasty17** [comment]
U have exe generate_drive_token.py on the same device of the this browser?
