### ISSUE TITLE
Yt-dlp Time out (if time out not choose quality return default quality is best video)

### ISSUE THREAD

**Issue by ClayArsenio26** [anasty17/mirror-leech-telegram-bot#1589]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when use ytdl command not choose quality within the specified time will time out, taks not execution.

**Describe the solution you'd like**
does anyone know how to set yt-dlp with the command ytdlleech or ytdl when timeout does not select quality restore default quality is best video. so if I upload the hls file and don't click on quality it will still run and work fine with the default best video quality.

please guided me tutorial to setting yt-dlp.
thank u very much :)

**Comment by anasty17** [comment]
Use yt-dlp default options
format:bv*+ba/b
