### ISSUE TITLE
Choose favorite folders to mirror

### ISSUE THREAD

**Issue by kuesttman** [anasty17/mirror-leech-telegram-bot#1590]
It would be very interesting to be able to add several Drive folders and choose which folder to use for Uploading, as if they were FAVORITE FOLDERS:
Folder 1: IDxxxxxxx
Folder 2: IDxxxxxxxx
Folder 3: IDxxxxxxxx
Folder 4: IDxxxxxxx

And when you execute the command "/clone link" or "/mirror link" the bot will show a button for each folder and UP to the respective folder.

The same could be applied to LEECH, add 3 or 4 Telegram Group or Channel IDs or even the Channel topic ID to send LEECH...
Channel 1: ID -0xxxxxxx
Channel 2: ID -0xxxxxxx
Group 1: ID -0xxxxxxx
Topic 1: ID -0xxxxxxx

And when doing LEECH, show the button for each channel or group that is added to favorites, and do LEECH for it.

The option to choose which folder to clone to the drive is very good, making it easier to organize the cloned contents.
You could create a new command like "/folders" to add the IDs of the Drive folders, or add a configuration in "/bsetting" or /usetting" to be able to add several IDs, perhaps with some limitation on the number of Drive Folders and Telegram Channels/Groups.

**Comment by anasty17** [comment]
duplicated
