### ISSUE TITLE
Unable to Download playlists! Incomplete Data Received & [Errno 2]

### ISSUE THREAD

**Issue by GollumArain** [anasty17/mirror-leech-telegram-bot#1591]
Downloading a single video works effortlessly but I'm unable to download playlists. It fetches incomplete data as can be seen below, retries and after 3 tries it simply gives Error related to directory of file, which is not correct, because downloading single files, to the same directory works fine. There's no problem with the YT-DLP, because it works directly (without the bot).

NOOB ALERT

app_1 | 2023-10-10 07:51:15,680 - bot - INFO - Downloading with YT-DLP: https://www.youtube.com/playlist?list=PLBsP89CPrMePNK7yIxcyRdiIFentQVHra
app_1 | 2023-10-10 07:51:16,282 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (1/3)...
app_1 | 2023-10-10 07:51:19,327 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (2/3)...
app_1 | 2023-10-10 07:51:22,377 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (3/3)...
app_1 | 2023-10-10 07:51:25,427 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Giving up after 3 retries
app_1 | 2023-10-10 07:51:37,167 - bot - INFO - Checking File/Folder if already in Drive: MKBHD Interviews!
app_1 | 2023-10-10 07:51:37,169 - bot.helper.mirror_utils.gdrive_utlis.helper - INFO - Authorizing with 15.json service account
app_1 | 2023-10-10 07:51:37,556 - bot.helper.mirror_utils.download_utils.yt_dlp_download - INFO - Download with YT_DLP: MKBHD Interviews!
app_1 | 2023-10-10 07:51:38,004 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (1/3)...
app_1 | 2023-10-10 07:51:41,049 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (2/3)...
app_1 | 2023-10-10 07:51:44,100 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Retrying (3/3)...
app_1 | 2023-10-10 07:51:47,148 - bot.helper.mirror_utils.download_utils.yt_dlp_download - WARNING - [youtube:tab] Incomplete data received. Giving up after 3 retries
app_1 | 2023-10-10 07:51:47,166 - bot.helper.mirror_utils.download_utils.yt_dlp_download - ERROR - ERROR: [Errno 2] No such file or directory: '/root/media/34/MKBHD Interviews!/MKBHD Interviews!.jpg'

**Comment by GollumArain** [comment]
> I will testbbro but mostly its connection or yt-dlp issue

Any update?

**Comment by CevreMuhendisi** [comment]
up 
![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/59526034/940e2924-9749-4fac-abbf-97cced74a11c)
