### ISSUE TITLE
Feature: Adding contributors section to the readme.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [anasty17/mirror-leech-telegram-bot#1593]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
Any contributions make are greatly appreciated, for that we need to add new section for contributors and adding to the readme file!
![contributors](https://github.com/anasty17/mirror-leech-telegram-bot/assets/147402107/9d1280dd-1f6d-4229-aff6-5b71eff6f297)

**Comment by Kalyanimhala** [comment]
@junedkh  kindly assign me this #1593 this issue I want to work on it.

**Comment by anasty17** [comment]
done
