### ISSUE TITLE
Generate or Get Index Link by Gdrive Link

### ISSUE THREAD

**Issue by JOHN748** [anasty17/mirror-leech-telegram-bot#1601]

**Comment by ferdousahammed** [comment]
Regarding this matter, I have pulled request {#1602}.

**Comment by JOHN748** [comment]
> Regarding this matter, I have pulled request {#1602}.

My requirement is to get index link of a file by its google drive link.

**Comment by anasty17** [comment]
not worth really
just add file id in link
