### ISSUE TITLE
Bot not letting me choose folder in rclone remote

### ISSUE THREAD

**Issue by jackthenewbie** [anasty17/mirror-leech-telegram-bot#1603]
**Describe the bug**
According to docker logs it seems like rclone.conf is not exist, even though the bot response list all remote
**To Reproduce**
1. Rclone config at ``mirror-leech-telegram-bot/rclone.conf``
2. config.env as follow

- Let skip the required vars. 
- AUTHORIZED_CHATS = SUDO_USERS = "id1 id2"
- DEFAULT_UPLOAD="rcl"
- RCLONE_SERVE_PORT = "90"
- BASE_URL_PORT = "90"

3. Run command ``/m [magnet link] -up rcl``. Bot responsed with 
![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/55600733/394f9807-3d56-414c-8b1b-60c2efcd5476)

4. Click on 1 remote, nothing happen. 
5. Check logs in docker and [this](https://logpaste.com/OWPFeNIl)
 
**Expected behavior**
Bot will show what remote folders are? I'm moving from another similar repo to this repo, so I'm expected a similar behavor. First time using this rclone thingy in this repo.

**Screenshots**
See above

**Comment by anasty17** [comment]
Send full log
Seems there are many errors

**Comment by jackthenewbie** [comment]
https://logpaste.com/f0HHggzM
This log i can get with docker log command

**Comment by anasty17** [comment]
Bro something missing in ur config.env 
Read first line
