### ISSUE TITLE
need developer

### ISSUE THREAD

**Issue by horasjey** [anasty17/mirror-leech-telegram-bot#1604]
Hallo
I want hire someone for create stream proxsy video from channel private
i mean like this
![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/45363813/b2c13561-043b-4743-9dde-8efb1d3dbce3)

**Comment by anasty17** [comment]
Contact me on telegram 
tg://user?id=314489490
I didn't understood what exactly do u want 
And don't explain here please.
