### ISSUE TITLE
Bug Rclone

### ISSUE THREAD

**Issue by Yyg-Masamba** [anasty17/mirror-leech-telegram-bot#1608]
Bro, when we rclone files and the download percent unit usually reaches more than 100% (125%) and is still in the process of downloading, this bug is if we rclone files of 100GB or more. 

It also often happens that the rclone process stops itself when uploading or stops in the middle of the rclone download process. Again, usually files that are 100GB-300gb in size.

I think this is an rclone bug in your repo. Please fix it.

**Comment by Clone-CMT** [comment]
same too me....plz fix

**Comment by anasty17** [comment]
> Bro, when we rclone files and the download percent unit usually reaches more than 100% (125%) and is still in the process of downloading, this bug is if we rclone files of 100GB or more.
> 
> It also often happens that the rclone process stops itself when uploading or stops in the middle of the rclone download process. Again, usually files that are 100GB-300gb in size.
> 
> I think this is an rclone bug in your repo. Please fix it.

U will rwply to my request or should i close this issue ?

**Comment by Yyg-Masamba** [comment]
> > Bro, when we rclone files and the download percent unit usually reaches more than 100% (125%) and is still in the process of downloading, this bug is if we rclone files of 100GB or more.
> > It also often happens that the rclone process stops itself when uploading or stops in the middle of the rclone download process. Again, usually files that are 100GB-300gb in size.
> > I think this is an rclone bug in your repo. Please fix it.
> 
> U will rwply to my request or should i close this issue ?

it's good bro admin, please close. thanks for responding.
