### ISSUE TITLE
Add mirror in topic

### ISSUE THREAD

**Issue by pranendraa** [anasty17/mirror-leech-telegram-bot#1610]
Please add this

**Comment by anasty17** [comment]
Hmmm i want to do this but after stable release of telethon v2

**Comment by pranendraa** [comment]
okey :D

**Comment by anasty17** [comment]
give ideas please

**Comment by rooted-cyber** [comment]
upload in sourceforge.net

**Comment by anasty17** [comment]
> 1.Videotools like metadata attachment watermark stream remover adder Subtitle adder remover remux 2.seedr.cc configuration 3.web scraping fetch links from the websites

We r talking about telegram topica
Gives ideas related to it

**Comment by MeDeVILe** [comment]
Support Pyload like jdownloader

**Comment by anasty17** [comment]
> Will you please add login.py for logging directly in telegram without session string .

Open new issue
