### ISSUE TITLE
send the absolute path of files

### ISSUE THREAD

**Issue by wangzhehan84** [anasty17/mirror-leech-telegram-bot#1616]
**Is your feature request related to a problem? Please describe.**
The message for each file uploaded by the bot only includes the file name. In some cases, the file name may not accurately reflect the file's content, for example, 1.rar...10.rar. This makes it difficult to know the file content on Telegram and also hinders searchability. 
**Describe the solution you'd like**
 Can an option be added to include the absolute path information of the file in the message?

**Comment by anasty17** [comment]
I didn't understood what do u mean! Explain exactly in which part you are talking

**Comment by wangzhehan84** [comment]
when i use  /l rcl to upload files in many folders to telegram,it will send a text message,but it only send file name.  and the folder name is very useful to distinguish the file.
　　for example:the file vol1.rar is in comic book 1 floder. 
send a text message with"/comic book 1/vol1.rar" without send "vol1.rar".

**Comment by anasty17** [comment]
> **Is your feature request related to a problem? Please describe.** The message for each file uploaded by the bot only includes the file name. In some cases, the file name may not accurately reflect the file's content, for example, 1.rar...10.rar. This makes it difficult to know the file content on Telegram and also hinders searchability. **Describe the solution you'd like** Can an option be added to include the absolute path information of the file in the message?

that's why rename feature is exists! Some paths are too long!
