### ISSUE TITLE
add 1337x on qbit search

### ISSUE THREAD

**Issue by Taki-Tachiibana** [anasty17/mirror-leech-telegram-bot#162]
please add 1337x on qbit search.

**Comment by anasty17** [comment]
@Taki-Tachiibana U can add or remove whatever u want check var readme

**Comment by Taki-Tachiibana** [comment]
@anasty17  but "https://raw.githubusercontent.com/v1k45/1337x-qBittorrent-search-plugin/master/leetx.py"
This plugin not working.
So how do I add it?

**Comment by anasty17** [comment]
@Taki-Tachiibana Search online maybe u will find someone has updated the plugin idk

**Comment by kamileecher** [comment]
https://github.com/hemantapkh/1337x
Add this work

13 Ara 2021 Pzt 19:22 tarihinde Anas ***@***.***> şunu yazdı:
