### ISSUE TITLE
yt-dl error

### ISSUE THREAD

**Issue by deniganda** [anasty17/mirror-leech-telegram-bot#1622]
`('Received response with content-encoding: br, but failed to decode it.', error('BrotliDecoderDecompressStream failed while processing the stream'))`

when i use `/y` or `/yl`, my bot always reply my comand with that error text above

**Comment by FabriSC** [comment]
same error

**Comment by anasty17** [comment]
I will check if this issue is from my side

**Comment by FabriSC** [comment]
probably an rss package has been updated, which is what causes the conflict with yt

**Comment by anasty17** [comment]
> probably an rss package has been updated, which is what causes the conflict with yt

feedparser? No new updates

**Comment by FabriSC** [comment]
You can check it, I tried starting the bot in a new container, because it keeps giving me errors on several servers

**Comment by FabriSC** [comment]
app_1  | [20-Nov-23 12:44:23 PM] [INFO] - Running job "RSS (trigger: interval[0:15:00], next run at: 2023-11-20 07:29:23 UTC)" (scheduled at 2023-11-20 07:14:23.994089+00:00)
app_1  | [20-Nov-23 12:44:23 PM] [WARNING] - RSS_CHAT not added! Shutting down rss scheduler...
app_1  | [20-Nov-23 12:44:24 PM] [INFO] - Job "RSS (trigger: interval[0:15:00], next run at: 2023-11-20 07:29:23 UTC)" executed successfully
app_1  | [20-Nov-23 12:44:24 PM] [INFO] - Scheduler has been shut down
app_1  | [20-Nov-23 12:44:31 PM] [INFO] - Running Task Manager ...
app_1  | [youtube] Extracting URL: https://youtu.be/BzmsnAjdEEY?si=bEsL3k6S5dEf8FaI
app_1  | [youtube] BzmsnAjdEEY: Downloading webpage
app_1  | [20-Nov-23 12:45:17 PM] [INFO] - Running Task Manager ...
app_1  | [20-Nov-23 12:45:17 PM] [INFO] - https://youtu.be/I6I2oAifl38?si=IKKfgejOnGNsv2KL
app_1  | [20-Nov-23 12:45:18 PM] [INFO] - ERROR: Use ytdl cmds for Youtube links
app_1  | [20-Nov-23 12:45:24 PM] [INFO] - Running Task Manager ...
app_1  | [youtube] Extracting URL: https://youtu.be/I6I2oAifl38?si=IKKfgejOnGNsv2KL
app_1  | [youtube] I6I2oAifl38: Downloading webpage
app_1  | [20-Nov-23 12:45:34 PM] [INFO] - Running Task Manager ...
app_1  | [youtube] Extracting URL: https://youtu.be/I6I2oAifl38?si=IKKfgejOnGNsv2KL
app_1  | [youtube] I6I2oAifl38: Downloading webpage
app_1  | [youtube] I6I2oAifl38: Downloading ios player API JSON
app_1  | [youtube] I6I2oAifl38: Downloading android player API JSON
app_1  | [youtube] I6I2oAifl38: Downloading m3u8 information
