### ISSUE TITLE
`app_1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5bf5a48e80>: Failed to establish a new connection: [Errno 111] Connection refused'))`

### ISSUE THREAD

**Issue by LoveThisWorld002** [anasty17/mirror-leech-telegram-bot#1625]
**Describe the bug**
After repo update bot won't start for me anymore?

<details>
<summary>log.txt?</summary>

```
root@localhost:~/MLTB# sudo docker-compose up --build

Successfully tagged mltb_app:latest
Recreating mltb_app_1 ... done
Attaching to mltb_app_1
app_1  | 2023-11-23 09:29:41,172 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
app_1  | 2023-11-23 09:29:44,576 - root - WARNING - MEGA Credentials not provided!
app_1  | [2023-11-23 09:29:44 +0000] [42] [INFO] Starting gunicorn 21.2.0
app_1  | [2023-11-23 09:29:44 +0000] [42] [INFO] Listening at: http://0.0.0.0:80 (42)
app_1  | [2023-11-23 09:29:44 +0000] [42] [INFO] Using worker: gevent
app_1  | [2023-11-23 09:29:44 +0000] [66] [INFO] Booting worker with pid: 66
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 203, in _new_conn
app_1  |     sock = connection.create_connection(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
app_1  |     raise err
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
app_1  |     sock.connect(sa)
app_1  | ConnectionRefusedError: [Errno 111] Connection refused
app_1  |
app_1  | The above exception was the direct cause of the following exception:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
app_1  |     response = self._make_request(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
app_1  |     conn.request(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 395, in request
app_1  |     self.endheaders()
app_1  |   File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
app_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
app_1  |   File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
app_1  |     self.send(msg)
app_1  |   File "/usr/lib/python3.10/http/client.py", line 975, in send
app_1  |     self.connect()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 243, in connect
app_1  |     self.sock = self._new_conn()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 218, in _new_conn
app_1  |     raise NewConnectionError(
app_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5bf5a48e80>: Failed to establish a new connection: [Errno 111] Connection refused
app_1  |
app_1  | The above exception was the direct cause of the following exception:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
app_1  |     resp = conn.urlopen(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
app_1  |     retries = retries.increment(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 515, in increment
app_1  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
app_1  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5bf5a48e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
app_1  |
app_1  | During handling of the above exception, another exception occurred:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
app_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
app_1  |   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
app_1  |     return _get_module_details(pkg_main_name, error)
app_1  |   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
app_1  |     __import__(pkg_name)
app_1  |   File "/usr/src/app/bot/__init__.py", line 481, in <module>
app_1  |     aria2_options = aria2.client.get_global_option()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 1342, in get_global_option
app_1  |     return self.call(self.GET_GLOBAL_OPTION)  # type: ignore
app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 265, in call
app_1  |     return self.res_or_raise(self.post(payload))
app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 361, in post
app_1  |     return requests.post(self.server, data=payload, timeout=self.timeout).json()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 115, in post
app_1  |     return request("post", url, data=data, json=json, **kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
app_1  |     return session.request(method=method, url=url, **kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
app_1  |     resp = self.send(prep, **send_kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
app_1  |     r = adapter.send(request, **kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
app_1  |     raise ConnectionError(e, request=request)
app_1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5bf5a48e80>: Failed to establish a new connection: [Errno 111] Connection refused'))
root@localhost:~/MLTB# sudo docker-compose stop
Stopping mltb_app_1 ... done
root@localhost:~/MLTB# sudo docker-compose down
Removing mltb_app_1 ... done
Removing network mltb_default
root@localhost:~/MLTB#
```

</details>

**Comment by anasty17** [comment]
Which vps ?

**Comment by anasty17** [comment]
I guess it's fixed now

**Comment by LoveThisWorld002** [comment]
> Which vps ?

BuyVM/frantech

**Comment by LoveThisWorld002** [comment]
> I guess it's fixed now

I'm still facing this issue?

**Comment by LoveThisWorld002** [comment]
> I guess it's fixed now

Same thing does happen even if I change my port to 6801


<details>
<summary>log.txt?</summary>

```
web/wserver.py:11:aria2 = ariaAPI(ariaClient(host="http://localhost", port=6801, secret=""))
bot/__init__.py:457:aria2 = ariaAPI(ariaClient(host="http://localhost", port=6801, secret=""))
root@localhost:~/MLTB# sudo docker-compose up
Creating network "mltb_default" with the default driver
Creating mltb_app_1 ... done
Attaching to mltb_app_1
app_1  | 2023-11-24 15:37:45,872 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
app_1  | 2023-11-24 15:37:49,325 - root - WARNING - MEGA Credentials not provided!
app_1  | [2023-11-24 15:37:49 +0000] [42] [INFO] Starting gunicorn 21.2.0
app_1  | [2023-11-24 15:37:49 +0000] [42] [INFO] Listening at: http://0.0.0.0:80 (42)
app_1  | [2023-11-24 15:37:49 +0000] [42] [INFO] Using worker: gevent
app_1  | [2023-11-24 15:37:49 +0000] [66] [INFO] Booting worker with pid: 66
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 203, in _new_conn
app_1  |     sock = connection.create_connection(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
app_1  |     raise err
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
app_1  |     sock.connect(sa)
app_1  | ConnectionRefusedError: [Errno 111] Connection refused
app_1  |
app_1  | The above exception was the direct cause of the following exception:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
app_1  |     response = self._make_request(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
app_1  |     conn.request(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 395, in request
app_1  |     self.endheaders()
app_1  |   File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
app_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
app_1  |   File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
app_1  |     self.send(msg)
app_1  |   File "/usr/lib/python3.10/http/client.py", line 976, in send
app_1  |     self.connect()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 243, in connect
app_1  |     self.sock = self._new_conn()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 218, in _new_conn
app_1  |     raise NewConnectionError(
app_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4cb043f130>: Failed to establish a new connection: [Errno 111] Connection refused
app_1  |
app_1  | The above exception was the direct cause of the following exception:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
app_1  |     resp = conn.urlopen(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
app_1  |     retries = retries.increment(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 515, in increment
app_1  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
app_1  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6801): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4cb043f130>: Failed to establish a new connection: [Errno 111] Connection refused'))
app_1  |
app_1  | During handling of the above exception, another exception occurred:
app_1  |
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
app_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
app_1  |   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
app_1  |     return _get_module_details(pkg_main_name, error)
app_1  |   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
app_1  |     __import__(pkg_name)
app_1  |   File "/usr/src/app/bot/__init__.py", line 481, in <module>
app_1  |     aria2_options = aria2.client.get_global_option()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 1342, in get_global_option
app_1  |     return self.call(self.GET_GLOBAL_OPTION)  # type: ignore
app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 265, in call
app_1  |     return self.res_or_raise(self.post(payload))
app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 361, in post
app_1  |     return requests.post(self.server, data=payload, timeout=self.timeout).json()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 115, in post
app_1  |     return request("post", url, data=data, json=json, **kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
app_1  |     return session.request(method=method, url=url, **kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
app_1  |     resp = self.send(prep, **send_kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
app_1  |     r = adapter.send(request, **kwargs)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
app_1  |     raise ConnectionError(e, request=request)
app_1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6801): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4cb043f130>: Failed to establish a new connection: [Errno 111] Connection refused'))
root@localhost:~/MLTB#
```

</details>

**Comment by anasty17** [comment]
> > I guess it's fixed now
> 
> Same thing does happen even if I change my port to 6801
> 
> log.txt?
> ```
> web/wserver.py:11:aria2 = ariaAPI(ariaClient(host="http://localhost", port=6801, secret=""))
> bot/__init__.py:457:aria2 = ariaAPI(ariaClient(host="http://localhost", port=6801, secret=""))
> root@localhost:~/MLTB# sudo docker-compose up
> Creating network "mltb_default" with the default driver
> Creating mltb_app_1 ... done
> Attaching to mltb_app_1
> app_1  | 2023-11-24 15:37:45,872 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
> app_1  | 2023-11-24 15:37:49,325 - root - WARNING - MEGA Credentials not provided!
> app_1  | [2023-11-24 15:37:49 +0000] [42] [INFO] Starting gunicorn 21.2.0
> app_1  | [2023-11-24 15:37:49 +0000] [42] [INFO] Listening at: http://0.0.0.0:80 (42)
> app_1  | [2023-11-24 15:37:49 +0000] [42] [INFO] Using worker: gevent
> app_1  | [2023-11-24 15:37:49 +0000] [66] [INFO] Booting worker with pid: 66
> app_1  | Traceback (most recent call last):
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 203, in _new_conn
> app_1  |     sock = connection.create_connection(
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
> app_1  |     raise err
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
> app_1  |     sock.connect(sa)
> app_1  | ConnectionRefusedError: [Errno 111] Connection refused
> app_1  |
> app_1  | The above exception was the direct cause of the following exception:
> app_1  |
> app_1  | Traceback (most recent call last):
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
> app_1  |     response = self._make_request(
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
> app_1  |     conn.request(
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 395, in request
> app_1  |     self.endheaders()
> app_1  |   File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
> app_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
> app_1  |   File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
> app_1  |     self.send(msg)
> app_1  |   File "/usr/lib/python3.10/http/client.py", line 976, in send
> app_1  |     self.connect()
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 243, in connect
> app_1  |     self.sock = self._new_conn()
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 218, in _new_conn
> app_1  |     raise NewConnectionError(
> app_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4cb043f130>: Failed to establish a new connection: [Errno 111] Connection refused
> app_1  |
> app_1  | The above exception was the direct cause of the following exception:
> app_1  |
> app_1  | Traceback (most recent call last):
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
> app_1  |     resp = conn.urlopen(
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
> app_1  |     retries = retries.increment(
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 515, in increment
> app_1  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
> app_1  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6801): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4cb043f130>: Failed to establish a new connection: [Errno 111] Connection refused'))
> app_1  |
> app_1  | During handling of the above exception, another exception occurred:
> app_1  |
> app_1  | Traceback (most recent call last):
> app_1  |   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
> app_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> app_1  |   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
> app_1  |     return _get_module_details(pkg_main_name, error)
> app_1  |   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
> app_1  |     __import__(pkg_name)
> app_1  |   File "/usr/src/app/bot/__init__.py", line 481, in <module>
> app_1  |     aria2_options = aria2.client.get_global_option()
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 1342, in get_global_option
> app_1  |     return self.call(self.GET_GLOBAL_OPTION)  # type: ignore
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 265, in call
> app_1  |     return self.res_or_raise(self.post(payload))
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 361, in post
> app_1  |     return requests.post(self.server, data=payload, timeout=self.timeout).json()
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 115, in post
> app_1  |     return request("post", url, data=data, json=json, **kwargs)
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
> app_1  |     return session.request(method=method, url=url, **kwargs)
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
> app_1  |     resp = self.send(prep, **send_kwargs)
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
> app_1  |     r = adapter.send(request, **kwargs)
> app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
> app_1  |     raise ConnectionError(e, request=request)
> app_1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6801): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4cb043f130>: Failed to establish a new connection: [Errno 111] Connection refused'))
> root@localhost:~/MLTB#
> ```

Not related to port i will check

**Comment by LoveThisWorld002** [comment]
> > > I guess it's fixed now
> > 
> > 
> > Same thing does happen even if I change my port to 6801
> > log.txt?
> > ```
> > web/wserver.py:11:aria2 = ariaAPI(ariaClient(host="http://localhost", port=6801, secret=""))
> > bot/__init__.py:457:aria2 = ariaAPI(ariaClient(host="http://localhost", port=6801, secret=""))
> > root@localhost:~/MLTB# sudo docker-compose up
> > Creating network "mltb_default" with the default driver
> > Creating mltb_app_1 ... done
> > Attaching to mltb_app_1
> > app_1  | 2023-11-24 15:37:45,872 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
> > app_1  | 2023-11-24 15:37:49,325 - root - WARNING - MEGA Credentials not provided!
> > app_1  | [2023-11-24 15:37:49 +0000] [42] [INFO] Starting gunicorn 21.2.0
> > app_1  | [2023-11-24 15:37:49 +0000] [42] [INFO] Listening at: http://0.0.0.0:80 (42)
> > app_1  | [2023-11-24 15:37:49 +0000] [42] [INFO] Using worker: gevent
> > app_1  | [2023-11-24 15:37:49 +0000] [66] [INFO] Booting worker with pid: 66
> > app_1  | Traceback (most recent call last):
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 203, in _new_conn
> > app_1  |     sock = connection.create_connection(
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 85, in create_connection
> > app_1  |     raise err
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 73, in create_connection
> > app_1  |     sock.connect(sa)
> > app_1  | ConnectionRefusedError: [Errno 111] Connection refused
> > app_1  |
> > app_1  | The above exception was the direct cause of the following exception:
> > app_1  |
> > app_1  | Traceback (most recent call last):
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 790, in urlopen
> > app_1  |     response = self._make_request(
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 496, in _make_request
> > app_1  |     conn.request(
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 395, in request
> > app_1  |     self.endheaders()
> > app_1  |   File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
> > app_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
> > app_1  |   File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
> > app_1  |     self.send(msg)
> > app_1  |   File "/usr/lib/python3.10/http/client.py", line 976, in send
> > app_1  |     self.connect()
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 243, in connect
> > app_1  |     self.sock = self._new_conn()
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 218, in _new_conn
> > app_1  |     raise NewConnectionError(
> > app_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4cb043f130>: Failed to establish a new connection: [Errno 111] Connection refused
> > app_1  |
> > app_1  | The above exception was the direct cause of the following exception:
> > app_1  |
> > app_1  | Traceback (most recent call last):
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
> > app_1  |     resp = conn.urlopen(
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 844, in urlopen
> > app_1  |     retries = retries.increment(
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/urllib3/util/retry.py", line 515, in increment
> > app_1  |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
> > app_1  | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=6801): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4cb043f130>: Failed to establish a new connection: [Errno 111] Connection refused'))
> > app_1  |
> > app_1  | During handling of the above exception, another exception occurred:
> > app_1  |
> > app_1  | Traceback (most recent call last):
> > app_1  |   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
> > app_1  |     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
> > app_1  |   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
> > app_1  |     return _get_module_details(pkg_main_name, error)
> > app_1  |   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
> > app_1  |     __import__(pkg_name)
> > app_1  |   File "/usr/src/app/bot/__init__.py", line 481, in <module>
> > app_1  |     aria2_options = aria2.client.get_global_option()
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 1342, in get_global_option
> > app_1  |     return self.call(self.GET_GLOBAL_OPTION)  # type: ignore
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 265, in call
> > app_1  |     return self.res_or_raise(self.post(payload))
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/aria2p/client.py", line 361, in post
> > app_1  |     return requests.post(self.server, data=payload, timeout=self.timeout).json()
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 115, in post
> > app_1  |     return request("post", url, data=data, json=json, **kwargs)
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
> > app_1  |     return session.request(method=method, url=url, **kwargs)
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
> > app_1  |     resp = self.send(prep, **send_kwargs)
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
> > app_1  |     r = adapter.send(request, **kwargs)
> > app_1  |   File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 519, in send
> > app_1  |     raise ConnectionError(e, request=request)
> > app_1  | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6801): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4cb043f130>: Failed to establish a new connection: [Errno 111] Connection refused'))
> > root@localhost:~/MLTB#
> > ```
> 
> Not related to port i will check

Did you find any fix for me sir?

**Comment by anasty17** [comment]
I will try to produce it now

**Comment by anasty17** [comment]
got it ! bad vps specifications i will handle this

**Comment by LoveThisWorld002** [comment]
> got it ! bad vps specifications i will handle this

Thank you very much that solved my problem.

**Comment by ponez** [comment]
I still have this problem, 

```bash
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97461b93f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by anasty17** [comment]
senf full logs

**Comment by anasty17** [comment]
> I still have this problem,
> 
> ```shell
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=6800): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97461b93f0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```

send full log
