### ISSUE TITLE
Cant build using docker-compose

### ISSUE THREAD

**Issue by JohnCale47** [anasty17/mirror-leech-telegram-bot#1627]
![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/37181988/66b44074-98e3-4ed2-9f2d-5d200d0f9c84)

getting this error.. used docker-compose up --build
tried clearing docker images and restarting my instance

**Comment by anasty17** [comment]
Why cropping the log that i will understand the issue from it

**Comment by JohnCale47** [comment]
> Why cropping the log that i will understand the issue from it

thers is nothing more.. i do docker-compose up --build and this happens ..thats it no log

**Comment by anasty17** [comment]
> > Why cropping the log that i will understand the issue from it
> 
> thers is nothing more.. i do docker-compose up --build and this happens ..thats it no log

I want to see when this error come 
Just send full log or close the issue please

**Comment by JohnCale47** [comment]
Tried again today, changed nothing, its working now and successfully building, no idea what happened.
