### ISSUE TITLE
youtube mp3 download

### ISSUE THREAD

**Issue by ZakariaRasoli** [anasty17/mirror-leech-telegram-bot#1629]
please check youtube mp3 download 

bot send video not mp3

**Comment by anasty17** [comment]
Ok i will check

**Comment by ZakariaRasoli** [comment]
sending me a video with a YouTube cover.

**Comment by ZakariaRasoli** [comment]
![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/17747457/6bade4eb-db46-415d-93c4-0c7203fa2f23)

**Comment by anasty17** [comment]
fixed
