### ISSUE TITLE
Watch command problem

### ISSUE THREAD

**Issue by majnurangeela** [anasty17/mirror-leech-telegram-bot#163]
Hello there ! After latest update. problem is /watch command downloads whole playlist instead of single video when a video link is copied from any playlist.
You can try on your own,
Playlist link: https://www.youtube.com/playlist?list=PLu0W_9lII9ahIappRPN0MCAgtOu3lQjQi
Video link from the same Playlist: https://www.youtube.com/watch?v=5_5oE5lgrhw&list=PLu0W_9lII9ahIappRPN0MCAgtOu3lQjQi

PS: I had selected 720 quality.

![photo_2021-12-13_17-22-29](https://user-images.githubusercontent.com/84721324/145807609-58684102-e9ac-4aa2-8f86-514cd66af535.jpg)
![photo_2021-12-13_17-22-38](https://user-images.githubusercontent.com/84721324/145807619-3c227e84-5936-481e-804f-e008edd4360c.jpg)

**Comment by snehitap** [comment]
@majnurangeela This is the video link https://youtu.be/5_5oE5lgrhw

**Comment by jusidama18** [comment]
@majnurangeela If from playlist don't add from &list=......

**Comment by majnurangeela** [comment]
Ok Thanks !
