### ISSUE TITLE
Add custom split for mirror

### ISSUE THREAD

**Issue by skynight137** [anasty17/mirror-leech-telegram-bot#1631]
cmd like: /qm https... -split 10gb
like gdrive free sa max 15gb of filesize. This always fails to upload.because ratelimit exceded

**Comment by ketela7** [comment]
> Already added!!!

you only add on leech, not mirror??

**Comment by anasty17** [comment]
This only for leech! I will not add this for mirror

**Comment by ketela7** [comment]
This should also work for mirrors, because you named it mirror-leech ..
