### ISSUE TITLE
[Bug] RcloneDownload JsonLoad: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1632]
**Describe the bug**
Hi,

When I try to execute `/l rcl` to download from gdrive. I get `RcloneDownload JsonLoad: Expecting value: line 1 column 1 (char 0)` error from tg message. 

btw upload `-up rcl` works fine.

Log.txt and rlog.txt nothing to see. 

I would appreciate if you could please fix this?

**Comment by erickyun** [comment]
I found out that if path contains `&` this error is reproduced. 

Example this
`gdrivex4:AZ ABC bypass/TvShow&Movies/Movies/file.mkv` 
Gives error.
but 
`gdrivex4:AZ ABC bypass/file.mkv` 
works fine.

**Comment by anasty17** [comment]
I will fix it soon 
Thanks for reporting

**Comment by erickyun** [comment]
> I will fix it soon Thanks for reporting

This issue still pursues for me.

**Comment by anasty17** [comment]
in command line also ?
i will test this

**Comment by erickyun** [comment]
> in command line also ? i will test this

command line works fine tested with:

```
/shell rclone --config=rclone/random.conf copy "gdrivex4:AZ ABC bypass/TvShow&Movies/img.jpg" dropbox-user-encrypt: -Pv
