### ISSUE TITLE
yt-dlp error phantomjs

### ISSUE THREAD

**Issue by ketela7** [anasty17/mirror-leech-telegram-bot#1639]
i'm trying to dl with yt-dlp from ph.
and got error like this:
@anon ERROR: [PornHub] 656f4b569c247: PhantomJS not found, Please download it from https://phantomjs.org/download.html

when i try using shell comand, like /shell yt-dlp link, this work and video is saved to server.
whats wrong?

**Comment by anasty17** [comment]
Yes i know. I have asked dev for alternative because phantomjs dead. He told me its only for ph and some p* sites so i have ignored
Phantomjs not available for Ubuntu 22.04
