### ISSUE TITLE
config.env

### ISSUE THREAD

**Issue by crazy-racer** [anasty17/mirror-leech-telegram-bot#164]
your repo config.env file to fill all options please create video bro it is getting difficult to fill some options please try to make video bro

                 @anasty17 help me

**Comment by crazy-racer** [comment]
> @crazy-racer Check readme

I do not understand readme to understand in detail, otherwise please make a video

**Comment by gudmeong** [comment]
@crazy-racer 😂😂

**Comment by anasty17** [comment]
@crazy-racer Tell me which var u don't understand
