### ISSUE TITLE
Quick commands for RSS "get filtered items"

### ISSUE THREAD

**Issue by StarMadeThis** [anasty17/mirror-leech-telegram-bot#1640]
This is for /rss. 
Instead of do command and then pressing buttons, my idea would be to add it with arguments like this:

`/rss -get name 10`

i hope this is useful. 
thank you anas!

**Comment by anasty17** [comment]
i remember u said: i want to get filtered items from get

**Comment by anasty17** [comment]
this not worth rss is not mirror cmd and used too much to add 
like no one will add 50 rss per day
