### ISSUE TITLE
Archives Image Previews. 

### ISSUE THREAD

**Issue by StarMadeThis** [anasty17/mirror-leech-telegram-bot#1641]
You know what is annoying? Not knowing what images are inside a .rar or .zip

If you want to know what images are inside you have to
-e the WHOLE archive 

Idea. 
an argument to only upload 4 photos of a .rar, .zip, etc as an album. 
This way we can have a preview or whats inside. 

maybe
`/l -eii `
This will extract and send **Only** the previews of the images inside.

`/l -ei `
This will extract and send the previews **with** the rar of the images inside.

**Comment by anasty17** [comment]
why u r downloading something u don't know what in it

**Comment by anasty17** [comment]
No important
