### ISSUE TITLE
[Error] With `/qm` if file name has `

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1643]
**Describe the bug**
Hi,

I having `'NoneType' object has no attribute 'id'` when I execute ``/qm -d 1.0:550 -up mrcc:dropbox-encrypt:PLEX/ -i 3`` the `-i` is not working for me When torrent file has ` in its name.

<details>
<summary>log.txt</summary>

```

app_1  | 2023-12-26 08:32:20,447 - bot - ERROR - 'NoneType' object has no attribute 'id'
app_1  | 2023-12-26 08:32:20,448 - asyncio - ERROR - Task exception was never retrieved
app_1  | future: <Task finished name='Task-1280' coro=<TaskConfig.run_multi() done, defined at /usr/src/app/bot/helper/common.py:309> exception=AttributeError("'str' object has no attribute 'id'")>
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/src/app/bot/helper/common.py", line 344, in run_multi
app_1  |     chat_id=self.message.chat.id, message_ids=nextmsg.id
app_1  | AttributeError: 'str' object has no attribute 'id'
app_1  | 2023-12-26 08:32:42,110 - apscheduler.executors.default - INFO - Job "RSS (trigger: interval[0:15:00], next run at: 2023-12-26 08:47:18 UTC)" executed successfully

```
</details>

Also getting /bin/sh: 1: t: not found` when I execute /qm -up mrcc:dropbox-encrypt:PLEX/ is not working for me if torrent folder name has ` in it. I get `/bin/sh: 1: t: not found`?

I would appreciate your help please?

I updated qbittorrent-nox btw 

```
/shell qbittorrent-nox --version
*Stdout*
qBittorrent v4.6.2
```

Downloading works fine but gives error on the start for uploading.

**Comment by anasty17** [comment]
Not my docker!

**Comment by anasty17** [comment]
Send the torrent

**Comment by erickyun** [comment]
> Send the torrent

https://pastebin.com/raw/Rtfqy6pS

**Comment by anasty17** [comment]
Alpine?

**Comment by erickyun** [comment]
> Alpine?

OS: buyvm Luxem Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-135-generic x86_64)

**Comment by anasty17** [comment]
Static package?

**Comment by erickyun** [comment]
> Static package?

This [Link](https://my.frantech.ca/cart.php?a=confproduct&i=0) with LU Block Storage Slab - 256GB is my os.

I did remove everything and reinstall from docker.

**Comment by anasty17** [comment]
Bro i meant the docker! In my docker this is not the qbitorrent version

**Comment by anasty17** [comment]
fixed wait for push but i didn't understood hich docker u r using maybe i will same as u.

**Comment by erickyun** [comment]
> fixed wait for push but i didn't understood hich docker u r using maybe i will use same as u.

I did use your docker, but I installed new version of qBittorrent [Link](https://github.com/userdocs/qbittorrent-nox-static/releases/download/release-4.6.2_v2.0.9/x86_64-qbittorrent-nox) manually.
But I did reinstall everything from zero and this error is also produced with your docker.

**Comment by anasty17** [comment]
> Static package?

already asked u. Fixed

**Comment by erickyun** [comment]
> > Static package?
> 
> already asked u. Fixed wait for push

Thanks for the fix it works! but the only problem now that is bot gives `ERROR while getting link. Path`

<details>
<summary>log.txt</summary>

```
bot.helper.mirror_utils.rclone_utils.transfer - ERROR - while getting link. Path: dropbox-encrypt:PLEX/[example] Ijiranaide, Nagatoro-san (Don`t Toy with Me, Miss Nagatoro) (Seasons 1-2) [1080p][HEVC x265 10bit][Dual-Audio][Multi-Subs] | Stderr: /bin/sh: 1: Syntax error: EOF in backquote substitution
```
</details>

**Comment by anasty17** [comment]
Maybe i forget to edit this one. U won't tell me how u got latest qbittorrent?

**Comment by anasty17** [comment]
fixed
