### ISSUE TITLE
[Bug] Rclone upload Syntax error if -up path has `'`

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1652]
**Describe the bug**
Hi,

I 'm getting `/bin/sh: 1: Syntax error: Unterminated quoted string` Error with rclone upload destination if -up has `'` name in it! Download works but with upload Bot won't start upload gives syntax error immediately! Example:

İf I execute 
`/m -up mrcc:gdrive:Test/folder's/` bot gives Syntax error because of `'`
But
`/m -up mrcc:gdrive:Test/folders/` works! Because there is no `'`

<details>
<summary>log.txt</summary>

```
2024-01-02 05:34:24,499 - bot.helper.mirror_utils.rclone_utils.transfer - ERROR - /bin/sh: 1: Syntax error: Unterminated quoted string
```
</details>

Note: I want emphasize that this time the error is NOT WİTH ` but WİTH ' sir incase I was not clear enough? I sincerely would appreciate if you could please fix this sir.

**Comment by anasty17** [comment]
ok i will handle this soon, after i got my laptop again from maintenance

**Comment by erickyun** [comment]
> ok i will handle this soon, after i got my laptop again from maintenance

@anasty17 I found also bug with /clone since it is related with rclone I will not open new issue 

When I execute
`/clone mrcc:evierx4:Z Temp/LibDrive.7z -up mrcc:megaevierx4:` I get No section: 'egaevierx4' Error?

but if I execute `/m mrcc:evierx4:Z Temp/LibDrive.7z -up mrcc:megaevierx4:` it gets succesfully uploaded!

I would appreciate if you could please fix this issue to.


<details>
<summary>log.txt</summary>

```
2024-01-03 14:50:56,409 - bot - INFO - mrcc:evierx4:Z Temp/LibDrive.7z
2024-01-03 14:51:00,135 - bot - INFO - Clone Started: Name: LibDrive.7z - Source: evierx4:Z Temp/LibDrive.7z - Destination: egaevierx4:
2024-01-03 14:51:02,217 - apscheduler.executors.default - INFO - Running job "RSS (trigger: interval[0:15:00], next run at: 2024-01-03 15:06:01 UTC)" (scheduled at 2024-01-03 14:51:01.963969+00:00)
2024-01-03 14:51:14,020 - apscheduler.executors.default - INFO - Job "RSS (trigger: interval[0:15:00], next run at: 2024-01-03 15:06:01 UTC)" executed successfully
2024-01-03 14:51:17,272 - bot - INFO - mrcc:evierx4:Z Temp/LibDrive.7z
2024-01-03 14:51:20,327 - bot - INFO - Download with rclone: Z Temp/LibDrive.7z
2024-01-03 14:51:26,483 - bot - INFO - Download completed: LibDrive.7z
2024-01-03 14:51:26,492 - bot - INFO - Rclone Upload Name: LibDrive.7z
2024-01-03 14:51:43,791 - bot.helper.mirror_utils.rclone_utils.transfer - INFO - Upload Done. Path: megaevierx4:LibDrive.7z
2024-01-03 14:51:43,806 - bot - INFO - Task Done: LibDrive.7z
2024-01-03 14:51:44,004 - bot - INFO - Cleaning Download: /usr/src/app/downloads/62274
```
</details>

**Comment by anasty17** [comment]
Okay

**Comment by anasty17** [comment]
2024-01-03 14:51:00,135 - bot - INFO - Clone Started: Name: LibDrive.7z - Source: evierx4:Z Temp/LibDrive.7z - Destination: egaevierx4:

r u sure from this ?!! because this impossible mostly from ur edits!

**Comment by erickyun** [comment]
> 2024-01-03 14:51:00,135 - bot - INFO - Clone Started: Name: LibDrive.7z - Source: evierx4:Z Temp/LibDrive.7z - Destination: egaevierx4:
> 
> DEstination missing 'm'
> 
> r u sure from this ?!! because this impossible mostly from ur edits!

yes sir I'm sure!
I just tried `/clone mrcc:megaevierx4:Screenshot_2024-01-03-23-01-10-362_com.mixplorer.jpg -up mrcc:evierx4:` and I did get 
`
Error: While getting rclone stat. Path: egaevierx4:Screenshot_2024-01-03-23-01-10-362_com.mixplorer.jpg. Stderr: 2024/01/04 18:12:41 Failed to create file system for "egaevierx4:Screenshot_2024-01-03-23-01-10-362_com.mixplorer.jpg": didn't find section in config file
`

but
`/m mrcc:megaevierx4:Screenshot_2024-01-03-23-01-10-362_com.mixplorer.jpg -up mrcc:evierx4:` works fine! 

Mirror from from works! But Clone from mega doesn't work?

**Comment by erickyun** [comment]
> > 2024-01-03 14:51:00,135 - bot - INFO - Clone Started: Name: LibDrive.7z - Source: evierx4:Z Temp/LibDrive.7z - Destination: egaevierx4:
> > DEstination missing 'm'
> > r u sure from this ?!! because this impossible mostly from ur edits!
> 
> yes sir I'm sure! I just tried `/clone mrcc:megaevierx4:Screenshot_2024-01-03-23-01-10-362_com.mixplorer.jpg -up mrcc:evierx4:` and I did get `Error: While getting rclone stat. Path: egaevierx4:Screenshot_2024-01-03-23-01-10-362_com.mixplorer.jpg. Stderr: 2024/01/04 18:12:41 Failed to create file system for "egaevierx4:Screenshot_2024-01-03-23-01-10-362_com.mixplorer.jpg": didn't find section in config file`
> 
> but `/m mrcc:megaevierx4:Screenshot_2024-01-03-23-01-10-362_com.mixplorer.jpg -up mrcc:evierx4:` works fine!

Edit: I can the the remote exist in my config when I execute `/shell rclone --config=rclone/userid.conf lsf megaevierx4:` so the problem is with /clone cmd I think!

**Comment by anasty17** [comment]
test now please

**Comment by erickyun** [comment]
> test now please

Hi anas,

I just tried latest commit I got same error again sadly. I found out that if config starts with m I get this error `No section` BUT if there is no `m` in remote name if it works!!

e.g. `/clone mrcc:evierx4:Z Temp/LibDrive.7z -up mrcc:mtest:` gives error!

but `/clone mrcc:evierx4:Z Temp/LibDrive.7z -up mrcc:test:` WORKS! 

İf remote name has `m` lettter it works?

**Comment by anasty17** [comment]
Ok i will debug it

**Comment by anasty17** [comment]
test please and close the issue if everything working well
thanks for reporting

**Comment by erickyun** [comment]
> test please and close the issue if everything working well thanks for reporting

Thank you it works. 🙂🙏👍
