### ISSUE TITLE
Add zst decompression

### ISSUE THREAD

**Issue by spike0en** [anasty17/mirror-leech-telegram-bot#1653]
Suggesting a shift from 7zip to PeaZip to add support for formats like Zstandard (.zst) and others currently not supported.

Consider the sample links below:
Link1: https://example.com/release/split.zip.001.zst
Link2: https://example.com/release/split.zip.002.zst
Link3: https://example.com/release/split.zip.003.zst
Link4: https://example.com/release/split.zip.004.zst

A notable enhancement would be the bot's capability to intelligently detect and extract the final zip file from the dual stages of extraction (zst > splitted zips > final "split.zip" in this case) in the provided multi-links. Leveraging PeaZip's .zst extraction and split archive merging features will significantly elevate the bot's adaptability and user interaction.

**Comment by anasty17** [comment]
peazip is not enough using cli everything based on gui
but i will try to add suport for this type

**Comment by anasty17** [comment]
> Suggesting a shift from 7zip to PeaZip to add support for formats like Zstandard (.zst) and others currently not supported.
> 
> Consider the sample links below: Link1: https://example.com/release/split.zip.001.zst Link2: https://example.com/release/split.zip.002.zst Link3: https://example.com/release/split.zip.003.zst Link4: https://example.com/release/split.zip.004.zst
> 
> A notable enhancement would be the bot's capability to intelligently detect and extract the final zip file from the dual stages of extraction (zst > splitted zips > final "split.zip" in this case) in the provided multi-links. Leveraging PeaZip's .zst extraction and split archive merging features will significantly elevate the bot's adaptability and user interaction.

Send link to test

**Comment by anasty17** [comment]
> Suggesting a shift from 7zip to PeaZip to add support for formats like Zstandard (.zst) and others currently not supported.
> 
> Consider the sample links below: Link1: https://example.com/release/split.zip.001.zst Link2: https://example.com/release/split.zip.002.zst Link3: https://example.com/release/split.zip.003.zst Link4: https://example.com/release/split.zip.004.zst
> 
> A notable enhancement would be the bot's capability to intelligently detect and extract the final zip file from the dual stages of extraction (zst > splitted zips > final "split.zip" in this case) in the provided multi-links. Leveraging PeaZip's .zst extraction and split archive merging features will significantly elevate the bot's adaptability and user interaction.

mate you will send links to test or should i close this issue ?

**Comment by spike0en** [comment]
> > Suggesting a shift from 7zip to PeaZip to add support for formats like Zstandard (.zst) and others currently not supported.
> > Consider the sample links below: Link1: https://example.com/release/split.zip.001.zst Link2: https://example.com/release/split.zip.002.zst Link3: https://example.com/release/split.zip.003.zst Link4: https://example.com/release/split.zip.004.zst
> > A notable enhancement would be the bot's capability to intelligently detect and extract the final zip file from the dual stages of extraction (zst > splitted zips > final "split.zip" in this case) in the provided multi-links. Leveraging PeaZip's .zst extraction and split archive merging features will significantly elevate the bot's adaptability and user interaction.
> 
> mate you will send links to test or should i close this issue ?

Hello you can try these links: 
https://github.com/zlewchan/nothing_archive/releases/download/_drd/fastboot--image-split.zip.001.zst
https://github.com/zlewchan/nothing_archive/releases/download/_drd/fastboot--image-split.zip.002.zst
https://github.com/zlewchan/nothing_archive/releases/download/_drd/fastboot--image-split.zip.003.zst
