### ISSUE TITLE
Search Command Filtering Option

### ISSUE THREAD

**Issue by JOHN748** [anasty17/mirror-leech-telegram-bot#1655]
**Feature Request in Search Command:**

In search results it's frustrating to look for active and good seeded torrents by looking through telegraph pages, 

So it'll be helpful if there's an option to filter a search results by torrent seeders count  by descending order, so that it's quicker to get active torrents rather than looking for an active torrents in 10s and 100s of pages.

**Example:** 

` /search {query} -arg`

**Arguments:**

```
-sd (seeders_descending) 
-ld (leechers_descendung) [Unwanted I think]
-fsd (filesize_descending) 
```

**Comment by anasty17** [comment]
sorry i don't have time for this
