### ISSUE TITLE
[Bug] Join splitted files not working `/jl -b -j -m folder`

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1658]
**Describe the bug**
Hi

When I execute `/jl -b -j -m folder` splitted files won't join? 
I would appreciate if you could fix this issue please.

[Links](http://tinyurl.com/3e448xn3)

**Comment by anasty17** [comment]
how those files splitted ? this join only join files spliteed by split package or similar package but not ffmpeg or archive

**Comment by anasty17** [comment]
> > how those files splitted ? this join only join files spliteed by split package or similar package but not ffmpeg or archive
> 
> I was able to join them before sir. I believe the files are splitted with py7zip.

U can unzip and zip again -m folder -e -z

**Comment by anasty17** [comment]
> > how those files splitted ? this join only join files spliteed by split package or similar package but not ffmpeg or archive
> 
> I was able to join them before sir. I believe the files are splitted with py7zip.

What logs say ?

**Comment by erickyun** [comment]
> > > how those files splitted ? this join only join files spliteed by split package or similar package but not ffmpeg or archive
> > 
> > 
> > I was able to join them before sir. I believe the files are splitted with py7zip.
> 
> What logs say ?

[Log.txt](http://tinyurl.com/kdp26nfc)

**Comment by erickyun** [comment]
On this commit https://github.com/anasty17/mirror-leech-telegram-bot/commit/4c4598311b57886d1cd5e64d01faefcdb2e70dd9 everything worked fine for me?

**Comment by erickyun** [comment]
> > > how those files splitted ? this join only join files spliteed by split package or similar package but not ffmpeg or archive
> > 
> > 
> > I was able to join them before sir. I believe the files are splitted with py7zip.
> 
> What logs say ?

[Log.txt](http://tinyurl.com/ydxeewc7)

**Comment by anasty17** [comment]
i have tested the links
/l -b -j -m test      ..... with this cmd
join success
mkv video with size 1781.2 mb and duration 23:55
u wrote /jl 
is this issue only happens while using /jl only ?

**Comment by erickyun** [comment]
> i have tested the links /l -b -j -m test ..... with this cmd join success mkv video with size 1781.2 mb and duration 23:55 u wrote /jl is this issue only happens while using /jl only ?

Yes I just test myself `/l -b -j -m test` works!
But `/jl -b -j -m test` doesn't work?

**Comment by anasty17** [comment]
Mostly this happens because jdownloader create folder   u can changes this in packagizer rule or any other settings. Once u want to use jdownloader then u should learn its options

**Comment by erickyun** [comment]
> Mostly this happens because jdownloader create folder u can changes this in packagizer rule or any other settings. Once u want to use jdownloader then u should learn its options

Oke then issue can be closed thank you for your answer sir.
Could you please tell me what option I need to change please?

**Comment by anasty17** [comment]
I forget exactly which option. Jdownloader confusing me.
And u can with packagizer also need to search on how u can edit it

**Comment by anasty17** [comment]
well i was thinking in case join arg added then combine packages into one package in jdownloader
