### ISSUE TITLE
[Bug] gofile rar file gets uploaded twice with `/jm -e -up mrcc:gdrive:Folder/`

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1661]
**Describe the bug**
Hi,
When I execute `/jm -e -up mrcc:gdrive:Folder/` to extract rar file the context in rar file gets uploaded twice. 
[Link](https://pastebin.com/raw/wqs7XWHb)

Nothing to see in logs?

**Comment by anasty17** [comment]
U disabled the auto extract from jdownloader?

**Comment by anasty17** [comment]
![Screenshot from 2024-01-18 01-51-45](https://github.com/anasty17/mirror-leech-telegram-bot/assets/77075674/70cb53dc-6e2f-47cb-b168-b8608f6df09d)

**Comment by erickyun** [comment]
> U disabled the auto extract from jdownloader?

Thanks, you're right sir. My sincerely apologize, I'm bad.🙏🙏
