### ISSUE TITLE
Leech

### ISSUE THREAD

**Issue by Ardogandano** [anasty17/mirror-leech-telegram-bot#1662]
Why if I leech the results in document form, not in video form. While I use other bots (repos) besides MLTB, the result is a video not a document, even though I have set it in bsetting AS_DOCUMENT = False. Please fix it.

Other repo (not MLTB)
![1](https://github.com/anasty17/mirror-leech-telegram-bot/assets/93655280/773d3409-dfd6-4f51-936e-5cb1e34b8d3c)

Repo MLTB
![2](https://github.com/anasty17/mirror-leech-telegram-bot/assets/93655280/455f9684-7cf4-4ca8-813e-4d166f52fa2c)

![3](https://github.com/anasty17/mirror-leech-telegram-bot/assets/93655280/a2d06d2c-6a3e-4c73-bde0-07016a09cea6)

**Comment by anasty17** [comment]
Send the file in tg

**Comment by anasty17** [comment]
which repo ?

**Comment by Ardogandano** [comment]
your repo, problem leech
