### ISSUE TITLE
Pyrofork

### ISSUE THREAD

**Issue by djsaikrishna** [anasty17/mirror-leech-telegram-bot#1663]
does MLTB support pyrofork..? if not support any plan to bring it future..?

**Comment by anasty17** [comment]
why ?

**Comment by djsaikrishna** [comment]
Pyrofork upload is fast compare to program, and Pyrofork upload speed is constant also

**Comment by anasty17** [comment]
> Pyrofork upload is fast compare to program, and Pyrofork upload speed is constant also

this not true! i have tested it
