### ISSUE TITLE
Doesnt show total file size while selecting torrents

### ISSUE THREAD

**Issue by askfriends** [anasty17/mirror-leech-telegram-bot#167]
Hi bro..
There is something little but very usef info missing and that is when we select files it doesnt show selected file size, so can u add that?
It should show total size on first screen of /qbmirror s and then it should adjust according to selected files only.

**Comment by anasty17** [comment]
@askfriends Make pr

**Comment by askfriends** [comment]
> @askfriends Make pr

pr? sorry i dont know that

**Comment by okAxL** [comment]
@askfriends pull request

**Comment by askfriends** [comment]
> @askfriends pull request

can u do that? bcoz i dont know how to do that, sorry

**Comment by anasty17** [comment]
@askfriends Me 2

**Comment by anasty17** [comment]
Done

**Comment by askfriends** [comment]
> Done

thanks bro
