### ISSUE TITLE
Filter contents based on words.

### ISSUE THREAD

**Issue by noobietele** [anasty17/mirror-leech-telegram-bot#1670]
is it possible to filter content with certain words while uploading to drive or leeching ,,like extension filter ??
Like a Torrent has 10 files ,5 files with name **abc** and 5 files with name **xyz** ,so i can like add filter for xyz so files that are named xyz or contain xyz in their title will not upload/leech

**Comment by anasty17** [comment]
Why u don't select files before download start ?

**Comment by noobietele** [comment]
Can't as using rss for auto-download torrents. 

Also it can be useful when leeching drive folder links,as selecting only works for torrent.

**Comment by anasty17** [comment]
> Can't as using rss for auto-download torrents.
> 
> Also it can be useful when leeching drive folder links,as selecting only works for torrent.

And jdownloader. And i will add selection for rclone
