### ISSUE TITLE
Multiple Logs Support in bot via topics.

### ISSUE THREAD

**Issue by noobietele** [anasty17/mirror-leech-telegram-bot#1671]
Like for mirror we have support to upload to different destination using -c ,with categories.txt, it it possible to implement in leech too?

As because of topics now we dont need to create multiple groups for different content,all content can be placed in one group only.
but for that we have to continously change log id to upload different content to different topics or deploy multiple bot for each category/topic of content.

can it be done using one bot only ,like categories.txt we can also upload different log id's or pass it as argument in the command it self like -c or -id, somthing like /leech -logid/lid  topicsid

**Comment by anasty17** [comment]
This will be added after adding topic support 
Bsetting will be for each chat regarding upload and other settings maybe and maybe all idk

**Comment by noobietele** [comment]
Thanks,I’ll be waiting for it

**Comment by anasty17** [comment]
this done also https://github.com/anasty17/mirror-leech-telegram-bot/commit/d933dc9ea7f794488038868c58e3032cc3b8e352
