### ISSUE TITLE
error while ytdl bro

### ISSUE THREAD

**Issue by rahulmanjhu2** [anasty17/mirror-leech-telegram-bot#1674]
<img width="1358" alt="Screenshot 2024-01-30 at 2 27 46 PM" src="https://github.com/anasty17/mirror-leech-telegram-bot/assets/88344968/2a2f5e71-b9de-4ce8-aa5a-4f55d2da72cd">
I don't know coding but I'm face this error while using ytdl cmd bot in tg says No Upload Destination!

**Comment by rahulmanjhu2** [comment]
<img width="384" alt="Screenshot 2024-01-30 at 2 46 07 PM" src="https://github.com/anasty17/mirror-leech-telegram-bot/assets/88344968/6c9fcafb-5b48-4784-ba3d-6aa6e609f284">

**Comment by rahulmanjhu2** [comment]
<img width="1363" alt="Screenshot 2024-01-30 at 2 59 20 PM" src="https://github.com/anasty17/mirror-leech-telegram-bot/assets/88344968/80cfc25d-bd78-46ae-9e96-0141b2f6534e">

**Comment by chailana** [comment]
How to fix this problem. Anyone can help i am having the same issue
