### ISSUE TITLE
Rclone sync using Service Account support

### ISSUE THREAD

**Issue by ketela7** [anasty17/mirror-leech-telegram-bot#1675]
Hi,  anasty17
this my rlog.txt end .

```
Transferred:   	          0 B / 33.476 GiB, 0%, 0 B/s, ETA -
Errors:                 4 (fatal error encountered)
Checks:                 7 / 7, 100%
Transferred:            0 / 17, 0%
Elapsed time:         8.9s

2024/02/02 00:18:12 DEBUG : 24 go routines active
2024/02/02 00:18:12 Failed to sync with 4 errors: last error was: googleapi: Error 403: The user's Drive storage quota has been exceeded., storageQuotaExceeded

```

I like the leech or mirror feature using rclone with Services Accounts.  It's petrifying once.  I hope this is in the clone.py module instead of solving "googleapi: Error 403: The user's Drive storage quota has been exceeded., storageQuotaExceeded"
thanks

**Comment by anasty17** [comment]
It was complicated that's why i didn't add it

**Comment by anasty17** [comment]
> check this, this can help you .. https://gist.githubusercontent.com/ketela7/571afb4def61154492be6709ed2eb443/raw/gistfile1.txt

Complicated in mltb

**Comment by anasty17** [comment]
> Hi, anasty17 this my rlog.txt end .
> 
> ```
> Transferred:   	          0 B / 33.476 GiB, 0%, 0 B/s, ETA -
> Errors:                 4 (fatal error encountered)
> Checks:                 7 / 7, 100%
> Transferred:            0 / 17, 0%
> Elapsed time:         8.9s
> 
> 2024/02/02 00:18:12 DEBUG : 24 go routines active
> 2024/02/02 00:18:12 Failed to sync with 4 errors: last error was: googleapi: Error 403: The user's Drive storage quota has been exceeded., storageQuotaExceeded
> ```
> 
> I like the leech or mirror feature using rclone with Services Accounts. It's petrifying once. I hope this is in the clone.py module instead of solving "googleapi: Error 403: The user's Drive storage quota has been exceeded., storageQuotaExceeded" thanks

how this related to service accounts ? it's drive storage quota means ur storage is full
