### ISSUE TITLE
Transferring files from local directory to Telegram via a bot

### ISSUE THREAD

**Issue by CevreMuhendisi** [anasty17/mirror-leech-telegram-bot#1676]
I have a folder with mkv files in the system where the bot is installed. How can I upload these files (as media files) to Telegram using the bot? I would appreciate your assistance.

**Comment by erickyun** [comment]
> I have a folder with mkv files in the system where the bot is installed. How can I upload these files (as media files) to Telegram using the bot? I would appreciate your assistance.

Hi,

I haven't test this myself but I think if you
Use rclone and setup rclone.conf like

```
[LocalUpload]
type = local
```

And you should probably mount Path where the mkv files are located in docker-compose.

e.g.
```
volumes:
      - /root/folder/path/example:/media
```

and then 
/l -up LocalUpload:media or /l rcl

Hope this works for you🙏🙂

**Comment by anasty17** [comment]
Not from bot goals. Why adding files directly to vps!

**Comment by anasty17** [comment]
Copy all paths and use them like links and use multi link
