### ISSUE TITLE
Change device name of myjdownloader

### ISSUE THREAD

**Issue by hackmonker** [anasty17/mirror-leech-telegram-bot#1677]
Right now the bot assigns a random number as device name in myjdownloader. An environment variable to define our own device name will be much better in my opinion, that way we can also add to jdownloader via api from other scripts. Also, if there are multiple jdownloader devices, it would be very easier to know which is the one from mltb mirror bot.
Something like MYJDOWNLOADER_DEVICE_NAME can be given as it was implemented here https://github.com/jlesage/docker-jdownloader-2.

**Comment by xd003** [comment]
+1 this should be very easy to add & would be extremely useful

**Comment by anasty17** [comment]
No need for all this to add specific name but u should at least know that i have added random number for purpose until i fix all issues in it then i will try to find fix the issue i have faced in case using fixed name
