### ISSUE TITLE
[Bug] Starting JDownloader... httpx.ReadTimeout

### ISSUE THREAD

**Issue by CevreMuhendisi** [anasty17/mirror-leech-telegram-bot#1680]
Hi,

Starting JDownloader, bot won't start now! im using docker image

[_mirrorbot_logs.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/14225950/_mirrorbot_logs.txt)

**Comment by anasty17** [comment]
This issue from telegraph site
