### ISSUE TITLE
Request To Add A New Feature : Ability to change the drive folder id in telegram

### ISSUE THREAD

**Issue by lastonpheonix** [anasty17/mirror-leech-telegram-bot#169]
bro, is it possible to add a feature which allows you to change the folder/drive where the bot will clone/mirror  directly from  telegram instead of changing it in config.env then restarting the bot.

**Comment by anasty17** [comment]
By what ? Folder id or name ?

**Comment by lastonpheonix** [comment]
Like have this variable in config.env rgt (GDRIVE_FOLDER_ID = "") being able to change this directly form telegram without needing to restart the bot, like lets say i am downloading a move then i can just do a command like "/id 1u4bdu5ji5b6i6j938" and then download and  ithe bot will upload to the folder with  id = "1u4bdu5ji5b6i6j938" which will be my movies folder and if i am downloading a show i can change the id to the id of my tv shows folder and bot will upload to the tv shows folder

**Comment by snehitap** [comment]
@lastonpheonix Why bother all TDs & unlimited edu gonna purge in July 2022

**Comment by kreuber** [comment]
> 

No, Edu gets limited to 100TB. But since when get "all Shared Drives purged"? There are enough people with Enterprise Accounts, like myself.

**Comment by lastonpheonix** [comment]
> @lastonpheonix Why bother all TDs & unlimited edu gonna purge in July 2022

Not enterprise ones, i use those, plus being able to change the folder where bot mirrors to from telegram itself would be pretty neat
