### ISSUE TITLE
/usr/bin/python3: No module named mltb

### ISSUE THREAD

**Issue by rogoe2** [anasty17/mirror-leech-telegram-bot#1690]
I've followed instructions on my azure vps windows 10.
Installed python, docker.
Cloned the repo. git clone https://github.com/anasty17/mirror-leech-telegram-bot mirrorbot/ && cd mirrorbot
Installed requirements. pip3 install -r requirements-cli.txt
Configured the config.env
docker build . -t mltb
docker run -p 80:80 -p 8080:8080 mltb

And "/usr/bin/python3: No module named mltb" is the response get. What have I done wrong?

**Comment by junedkh** [comment]
Change file type to LF "start.sh and aria.sh"

**Comment by junedkh** [comment]
@rogoe2 check this [answer](https://stackoverflow.com/a/54245311)
