### ISSUE TITLE
Backend in rclone there is no support for teldrive in mirror bot

### ISSUE THREAD

**Issue by EmporioBreak** [anasty17/mirror-leech-telegram-bot#1698]
The bot cannot work with modified versions of rclone in which custom backends have been added.

For example, together with the teldrive project.
Which makes your telegram channel into an analog of google drive
https://github.com/divyam234/teldrive

This project also supports rclone, but the creator of the project added his own type of backend to it.
https://github.com/divyam234/rclone

I think it would be a cool idea to add backend support for this project's rclone to the bot.

I think it would be a cool idea and will look forward to this addition if you are interested😍

This is my rlog.txt
`*Stdout*
2024/03/21 15:25:16 DEBUG : rclone: Version "v1.66.0" starting with parameters ["rclone" "move" "--fast-list" "--config" "rclone.conf" "-P" "/root/mirror-downloads/36/Proxyman_5_1_1_Mac_Patched.dmg" "tg:" "--exclude" "*.{aria2,!qB}" "--retries-sleep" "3s" "--ignore-case" "--low-level-retries" "1" "-M" "--log-file" "rlog.txt" "--log-level" "DEBUG"]
2024/03/21 15:25:16 DEBUG : Creating backend with remote "/root/mirror-downloads/36/Proxyman_5_1_1_Mac_Patched.dmg"
2024/03/21 15:25:16 DEBUG : Using config file from "/usr/src/app/rclone.conf"
2024/03/21 15:25:16 DEBUG : fs cache: adding new entry for parent of "/root/mirror-downloads/36/Proxyman_5_1_1_Mac_Patched.dmg", "/root/mirror-downloads/36"
2024/03/21 15:25:16 DEBUG : Creating backend with remote "tg:"
2024/03/21 15:25:16 Failed to create file system for "tg:": didn't find backend called "teldrive"`

**Comment by anasty17** [comment]
Nice
It will work also with rclone serve ?

**Comment by EmporioBreak** [comment]
Yup

**Comment by anasty17** [comment]
Nice

**Comment by EmporioBreak** [comment]
Looking forward to you adding this backend) How long is it?

**Comment by anasty17** [comment]
No eta

**Comment by anasty17** [comment]
mate this can't read current uploaded data and if someone lost the database then all files gone
