### ISSUE TITLE
Add domain

### ISSUE THREAD

**Issue by KedaiTubeMsb** [anasty17/mirror-leech-telegram-bot#1702]
Bro Anas, can you add the domain vidhide.com

Link: https://vidhidevip.com/download/k0oxm6vzi1qo

**Comment by junedkh** [comment]
@KedaiTubeMsb where is the main domain ?

**Comment by KedaiTubeMsb** [comment]
vidhide.com

**Comment by junedkh** [comment]
@KedaiTubeMsb they contain captcha and api is paid for directlink endpoint.
