### ISSUE TITLE
support for multi delete for leeched file 

### ISSUE THREAD

**Issue by hitesh920** [anasty17/mirror-leech-telegram-bot#1708]
it would be nice to add multi delete option for leeched files..
just like juned did previously..in his repo..

**/leechdel or /ld**
/cmd <telegram file/msg link>

bot should delete files replied to one another and so on..
for eg
if file-3 is replied to file-2 and file-2 is replied to file-1...
when we do
/cmd <telegram file/msg link of the file-1>
theb bot should delete file-1,2,3 cuz all are linked with each other by replies..

i think leech_dump is must for this..

**Comment by anasty17** [comment]
use telegram plus and press on vire replies then press on first and last message then press on corret mark to select all btw

**Comment by junedkh** [comment]
> use telegram plus and press on vire replies then press on first and last message then press on corret mark to select all btw

Thanks mf 😂🤣
