### ISSUE TITLE
handel this error

### ISSUE THREAD

**Issue by hitesh920** [anasty17/mirror-leech-telegram-bot#1711]
i belive in clean error free logs..
if you have free time then please handel this error

![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/71580009/5425e2f2-f67e-451d-9c47-546e46e1bda7)
while adding new path using /usetting
required format is: name space id
i just did: name

**Comment by anasty17** [comment]
okay

**Comment by anasty17** [comment]
Done
