### ISSUE TITLE
improvements needed in qbit selection page

### ISSUE THREAD

**Issue by hitesh920** [anasty17/mirror-leech-telegram-bot#1729]
![image](https://github.com/anasty17/mirror-leech-telegram-bot/assets/71580009/6bbd5518-1dfe-4b3c-a23d-c5cc7a53a8ce)
here you see the header says all files are selected by default, but it shows all files are unticked

my recommendations are
it should shows all files are tickked... according to the header
and add select all and unselect all options

**Comment by hitesh920** [comment]
and also after i hit subbmit..
it should says in a popup "submitted sucessfully"

**Comment by junedkh** [comment]
Okay I'll check soon.

**Comment by rinrinx** [comment]
and also, for example, when you try not to pull a 10gb section from a 300gb torrent file, it will pull the entire 300gb. Therefore, if your server is 200gb, then there is no point in pulling a certain part from a 300gb file. In short, the cutting does not work correctly, even when the bot cuts a part of the torrent file. it pulls the status and the entire size of the server server as well, causing the server space to fill up

**Comment by anasty17** [comment]
done
