### ISSUE TITLE
[Feature Request] RSS Feed Auto Mirror

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#173]
If possible, can you add a feature to mirror torrents from RSS feeds and then forward mirrored status messages to a channel?

also, can you suggest something to forward mirrored status messages to a channel? I've deployed an RSS feed telegram bot from [magneto261290's](https://github.com/magneto261290) repo, but it is flooding and mirroring files in the mirror group.

**Comment by junedkh** [comment]
@rajput-hemant Already working on it.

**Comment by rajput-hemant** [comment]
> @rajput-hemant Already working on it.

okay, 
also, can you suggest something to forward 
![image](https://user-images.githubusercontent.com/68769346/146214488-26d80bfd-4a06-497c-9921-02226d4a9fc8.png)
these messages only to a desired channel?

**Comment by junedkh** [comment]
@rajput-hemant Just wait and watch 🙂

**Comment by dishapatel010** [comment]
> > @rajput-hemant Already working on it.
> 
> okay, also, can you suggest something to forward ![image](https://user-images.githubusercontent.com/68769346/146214488-26d80bfd-4a06-497c-9921-02226d4a9fc8.png) these messages only to a desired channel?

[Dump mirror things to desire chat](https://github.com/dishapatel010/mirror-leech-telegram-bot-1/commit/739ad06915a1941c6fb0963471d90aad7d1171bc)

**Comment by rajput-hemant** [comment]
> > > @rajput-hemant Already working on it.
> > 
> > 
> > okay, also, can you suggest something to forward these messages only to a desired channel?
> 
> [Dump mirror things to desire chat](https://github.com/dishapatel010/mirror-leech-telegram-bot-1/commit/739ad06915a1941c6fb0963471d90aad7d1171bc)

thank you very much🥺

**Comment by rajput-hemant** [comment]
> > > @rajput-hemant Already working on it.
> > 
> > 
> > okay, also, can you suggest something to forward these messages only to a desired channel?
> 
> [Dump mirror things to desire chat](https://github.com/dishapatel010/mirror-leech-telegram-bot-1/commit/739ad06915a1941c6fb0963471d90aad7d1171bc)

it will forward mirrors upload message right? Is it possible to forward leeched videos also?

**Comment by rajput-hemant** [comment]
@dishapatel010 
Hey can you help me out with auto-forwarding leeched videos/files to another channel,  Need to forward videos/files only but not the upload message like this one
![image](https://user-images.githubusercontent.com/68769346/146564274-a9a0c1f4-664f-4ef8-a0d8-bef9e5bd7703.png)

**Comment by anasty17** [comment]
@rajput-hemant Wait for group branch !

**Comment by dishapatel010** [comment]
> @dishapatel010 Hey can you help me out with auto-forwarding leeched videos/files to another channel, Need to forward videos/files only but not the upload message like this one ![image](https://user-images.githubusercontent.com/68769346/146564274-a9a0c1f4-664f-4ef8-a0d8-bef9e5bd7703.png)

Here you go >>> [Dump leech to channel/group](https://github.com/dishapatel010/mirror-leech-telegram-bot-1/commit/40864042985c84000634ce4635cc4377b1245523)

**Comment by erickyun** [comment]
> If possible, can you add a feature to mirror torrents from RSS feeds and then forward mirrored status messages to a channel?
> 
> also, can you suggest something to forward mirrored status messages to a channel? I've deployed an RSS feed telegram bot from [magneto261290's](https://github.com/magneto261290) repo, but it is flooding and mirroring files in the mirror group.

How do you auto qbmirror rss could you please tell me?
Could you write here or dm in reddit u/ForFun002

**Comment by anasty17** [comment]
@erickyun Written in readme... so i already explained... then reading readme finish setup and deploy... then try cmds ... there an explanation for each cmd ... but cmds will not work without reading readme
