### ISSUE TITLE
Add option to choose from where to sync the config.env

### ISSUE THREAD

**Issue by Lucif3rHun1** [anasty17/mirror-leech-telegram-bot#1740]
**Is your feature request related to a problem? Please describe.**
The feature which sync the offline config.env with mongo db sometimes does not correctly syncs.

**Describe the solution you'd like**
I would like to have an option like usemongo true which will then only use mongo db, and will read mongodb url and usemongo var only from config.env and if false read config.env offline file and sync with online mongo.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anasty17** [comment]
like u mean if u have changed something in config.env so it will take the new values from config.env ?

**Comment by Lucif3rHun1** [comment]
No, if it has mongo enabled and says usemongo true then it will only use mongodb everytime instead of looking for config.env other values. but if  usemongo false it will just use the file.

**Comment by anasty17** [comment]
> No, if it has mongo enabled and says usemongo true then it will only use mongodb everytime instead of looking for config.env other values. but if usemongo false it will just use the file.

Ok but can u tell me why ?
