### ISSUE TITLE
Download/Upload at the same time.

### ISSUE THREAD

**Issue by kuesttman** [anasty17/mirror-leech-telegram-bot#1743]
Would it be possible to configure the bot for the batch mirror function, so that it uploads the downloaded files while downloading the rest? This would be useful for those who don't have much HD storage and have many links to mirror or leech.
It is also interesting to be able to leech the files that have already been downloaded while downloading the rest, instead of waiting for all the files to download and only then uploading them.
Example: for a list with 20 file links, I use the command /m -b responding to the message with the file. It can upload as it downloads the files or leech as the files are completed downloading.
It is also possible to mirror and leech the same file at the same time so that it does not have to be downloaded twice.

**Comment by anasty17** [comment]
this is very hard to manage each download tool require different treat
