### ISSUE TITLE
RSS tag causing errors

### ISSUE THREAD

**Issue by undeadmecha0** [anasty17/mirror-leech-telegram-bot#1747]
**Describe the bug**
RSS tag: ID/NAME causes "too many values to unpack"

**To Reproduce**

1. Rss sends /qm magnet
2. bot no response
3. check logs
4. log says 
  coro=<Mirror.newEvent() done, defined at /usr/src/app/bot/modules/mirror_leech.py:80> exception=ValueError('too many values to unpack (expected 2)')>
Traceback (most recent call last):
  File "/usr/src/app/bot/modules/mirror_leech.py", line 193, in newEvent
    await self.getTag(text)
  File "/usr/src/app/bot/helper/common.py", line 348, in getTag
    self.tag, id_ = text[1].split("Tag: ")[1].split()
    ^^^^^^^^^^^^^

**Comment by anasty17** [comment]
https://github.com/anasty17/mirror-leech-telegram-bot/blob/ae4b66a82aa6d897b551c7939832d58dc367295c/bot/helper/common.py#L359


U r not up to date
