### ISSUE TITLE
Add feature to include/exclude site for Yt-Dlp Options

### ISSUE THREAD

**Issue by Lucif3rHun1** [anasty17/mirror-leech-telegram-bot#1748]
**Is your feature request related to a problem? Please describe.**
Right now, if I put the yt-dlp options, it applied on all sites but I require that to happen for 1 site or should happen to all, excluding 1.

**Describe the solution you'd like**
I would like to have a variable to either include/exclude where the yt args will be applied or not. Or if we can have a map something like for youtube.com: format: bv*ext=mp4]+baext=m4a]/bext=mp4]/b, for other site different options, if none mentioned it will use the default settings.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anasty17** [comment]
Use args for this excluded site
