### ISSUE TITLE
[Feature Request] Queue in qbmirror

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#175]
If possible can you please add a feature to limit the number of downloads/tasks and add pending downloads/tasks to the queue

**Comment by snehitap** [comment]
@rajput-hemant Already there

https://github.com/anasty17/mirror-leech-telegram-bot/blob/master/aria.sh

Set max-concurrent-downloads to your desired value

**Comment by anasty17** [comment]
Check qbittorrent config
