### ISSUE TITLE
CAPTION & SUFFIX

### ISSUE THREAD

**Issue by rizz-electrical-engg** [anasty17/mirror-leech-telegram-bot#1755]
Will u add #customcaption , #suffix and #attachment file also[means which can upload my vids witn water mark] in it .please.................

 Thankyou

**Comment by anasty17** [comment]
Custom caption ok
But what do u mean by attachment file! And why so many dots !

**Comment by white-wolf-mia** [comment]
> Custom caption ok
> But what do u mean by attachment file! And why so many dots !
=>
Already explained it's like an water mark in video like we apply our thumbnail in video 

And dots are nothing just sarcasm 🥲

**Comment by anasty17** [comment]
> > Custom caption ok
> > But what do u mean by attachment file! And why so many dots !
> > =>
> > Already explained it's like an water mark in video like we apply our thumbnail in video
> 
> And dots are nothing just sarcasm 🥲

Already u can add custom thumb for each task

**Comment by white-wolf-mia** [comment]
But whats about leech caption??
