### ISSUE TITLE
Yt-dlp download range 

### ISSUE THREAD

**Issue by MeDeVILe** [anasty17/mirror-leech-telegram-bot#1767]
**Is your feature request related to a problem? Please describe.**
I was trying to download range of video adding yt-dlp options like 

`/yl https://youtu.be/AOl4dsKcEVw -opt verbose:True | download_ranges: download_range_func(None, [(3, 10)]) | force_keyframes_at_cuts:True`

As a response I get 

`'str' object is not callable`

**Describe the solution you'd like**

Am I doing something wrong or maby `download_range_func` needs to be imported like in this example:

`import yt_dlp
from yt_dlp.utils import download_range_func

start_time = 2  # accepts decimal value like 2.3
end_time = 7  

yt_opts = {
    'verbose': True,
    'download_ranges': download_range_func(None, [(start_time, end_time)]),
    'force_keyframes_at_cuts': True,
}

with yt_dlp.YoutubeDL(yt_opts) as ydl:
    ydl.download("https://www.youtube.com/watch?v=BxUS1K7xu30")`

? 

**Describe alternatives you've considered**
It would be nice feature to have `-c` option as cut something to use like `/cmd link -c 00:12-01:11` to download only this range of video.

Thanks for your code!

**Comment by anasty17** [comment]
I will fix it
But i will not add arg to cut 
To cut yt-dlp have many options i can't add alt arg for each yt-dlp options

**Comment by anasty17** [comment]
mate you must use 

[
        {
            'start_time': 0,
            'end_time': 60,
            'title': 'First Minute',
            'index': 1,
        },
        {
            'start_time': 120,
            'end_time': 180,
            'title': 'Second Minute',
            'index': 2,
        },
    ]
    
    list of dicts i will push update for this but not like how you did it

**Comment by anasty17** [comment]
> **Is your feature request related to a problem? Please describe.** I was trying to download range of video adding yt-dlp options like
> 
> `/yl https://youtu.be/AOl4dsKcEVw -opt verbose:True | download_ranges: download_range_func(None, [(3, 10)]) | force_keyframes_at_cuts:True`
> 
> As a response I get
> 
> `'str' object is not callable`
> 
> **Describe the solution you'd like**
> 
> Am I doing something wrong or maby `download_range_func` needs to be imported like in this example:
> 
> `import yt_dlp from yt_dlp.utils import download_range_func
> 
> start_time = 2 # accepts decimal value like 2.3 end_time = 7
> 
> yt_opts = { 'verbose': True, 'download_ranges': download_range_func(None, [(start_time, end_time)]), 'force_keyframes_at_cuts': True, }
> 
> with yt_dlp.YoutubeDL(yt_opts) as ydl: ydl.download("[https://www.youtube.com/watch?v=BxUS1K7xu30")`](https://www.youtube.com/watch?v=BxUS1K7xu30%22)%60)
> 
> ?
> 
> **Describe alternatives you've considered** It would be nice feature to have `-c` option as cut something to use like `/cmd link -c 00:12-01:11` to download only this range of video.
> 
> Thanks for your code!

after the fix, there is something missing. This incase u added more than 1 range we must add output template for it im asking dev about how to done this to create different parts names

**Comment by anasty17** [comment]
fixed now you can add multiple ranges
