### ISSUE TITLE
Error: 'Sign in to confirm you’re not a bot' while trying to download from YouTube

### ISSUE THREAD

**Issue by NskTorrent** [anasty17/mirror-leech-telegram-bot#1771]
Hello! Thank you for your bot!
What needs to be done to enable downloading from YouTube?
Currently, the following error appears:
ERROR: [youtube] UIXqgUKMSrQ: Sign in to confirm you’re not a bot. This helps protect our community. Learn more.

**Comment by anasty17** [comment]
report to yt-dlp
