### ISSUE TITLE
Support for Direct Download Links for Telegram Files.

### ISSUE THREAD

**Issue by mayurv123** [anasty17/mirror-leech-telegram-bot#1772]
Hi,

Thank you for the great work on this project! I’d like to suggest adding a feature to generate direct download links for files hosted on Telegram.

https://github.com/EverythingSuckz/TG-FileStreamBot/tree/python
This repository does the same thing.
Thank you

**Comment by anasty17** [comment]
Already in issues mate
But i don't have enough free time
