### ISSUE TITLE
Torrent Selection Range

### ISSUE THREAD

**Issue by undeadmecha0** [anasty17/mirror-leech-telegram-bot#1773]
**Is your feature request related to a problem? Please describe.**
Torrent selection on torrents with hundreds of files is a tedious task to select/unselect one by one

**Describe the solution you'd like**
A range selector for the first file you want and the last file you want
And it automatically selects all the files in between

**Describe alternatives you've considered**
Selecting them one by one painfully

**Comment by anasty17** [comment]
You asking for feature here 😂
Should I say no, this will bloat the bot

**Comment by ITMEDIAVISION** [comment]
Hey Anasty!
what about adding a temp web page where you can select the files?
Just thinking out loud 😂😂

**Comment by junedkh** [comment]
@undeadmecha0 we have redesign our webpage please check it out.

**Comment by vcbat** [comment]
how to add leech caption ?

**Comment by anasty17** [comment]
> **Is your feature request related to a problem? Please describe.** Torrent selection on torrents with hundreds of files is a tedious task to select/unselect one by one
> 
> **Describe the solution you'd like** A range selector for the first file you want and the last file you want And it automatically selects all the files in between
> 
> **Describe alternatives you've considered** Selecting them one by one painfully

is the new torrent selection ui from juned is enough ?
