### ISSUE TITLE
MLTB lite?

### ISSUE THREAD

**Issue by undeadmecha0** [anasty17/mirror-leech-telegram-bot#1774]
**Is your feature request related to a problem? Please describe.**
MLTB has gone so much bloated over the years i miss the old anas where he only focus on being a stable bot not an all around bot with a billion features

**Describe the solution you'd like**
Docker/Repo where aria/qbit+rss and rclone are the only ones installed?
No group features or any indian ffmpeg leech rename mediainfo nzb/jdownloader shenanigans and group features
Just the core of MLTB
The original anas

**Describe alternatives you've considered**
Too much bloat to for you to fix everytime and maintain when you are busy in life
المجد لفلسطين

**Comment by anasty17** [comment]
Hi
The bot is stable
And all features is useful 
Usetting for some friends 
Rename is useful 
Substitute is useful too
Jdownloader is a good tool
Nzb for who want, it's a good features
I didn't add mediainfo things
All good and yet more is comming 
Users like you shouldn't notice any issue 
Even if i made lite version u will not notice any difference just missing features
