### ISSUE TITLE
The torrent name doesn't display during upload and remains missing after completion.

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#1777]
**Describe the bug**
Hi @anas17

The torrent name doesn't appear on status message when the upload starts, and the issue persists after the torrent completes.

**To Reproduce**

1. `/qm -d 1.0:50 -up -up mrcc:remotennmae:folder/name/`
2. after/while Upload ..
3. Check logs: Nothing To See.

**Expected behavior**
The torrent name should appear when the upload starts and remain visible after completion.

**Comment by anasty17** [comment]
-up -up ?!

**Comment by erickyun** [comment]
> -up -up ?! Give me link to test ?! I always use qbitorrent. This happened in all cases or just while using rclone ?

> -up -up 

I thought I made a typo, but now I see that all my RSS subscriptions have changed to '-up -up,' and I don't know why.

But even without my -up -up, this issue persists when using qBittorrent with rclone.

**Comment by anasty17** [comment]
Got it this from / in folder name
