### ISSUE TITLE
Add Direct link

### ISSUE THREAD

**Issue by mariamariasilva1933** [anasty17/mirror-leech-telegram-bot#1779]
please add more supported direct link
many thanks to all!
cheers to all!

mega.nz
katfile.com
rapidgator.net
filecat.net
nitroflare.com

**Comment by anasty17** [comment]
use jdownloader
cheers

**Comment by mariamariasilva1933** [comment]
jdownloader only work for mega.nz

thanks

**Comment by anasty17** [comment]
> jdownloader only work for mega.nz
> 
> thanks

works for many sites im not sure for all of the sites u have provided but rapidgator.net works also

check supported on google
