### ISSUE TITLE
[FEATURE REQUEST] Selective download 

### ISSUE THREAD

**Issue by yadianluffy** [anasty17/mirror-leech-telegram-bot#178]
hello it would be more comfortable if the selective download works automatically every time a qb command is executed
And if you don't like the idea, could you tell me how to do it in the code to use it in mine?

**Comment by SpeedyIndeedy** [comment]
@yadianluffy Not everyone want to select when downloading

**Comment by anasty17** [comment]
@yadianluffy Learn by ur self, imagine each one want specific thing in this repo and i should reply to each one !

**Comment by yadianluffy** [comment]
Precisely what would it cost to those who do not want to select to touch the done button and voila, they would start their download without selecting anything

**Comment by anasty17** [comment]
> Precisely what would it cost to those who do not want to select to touch the done button and voila, they would start their download without selecting anything

What would it cost u if u add s after cmd, and what about rss users?!

**Comment by yadianluffy** [comment]
Thanks for answering my suggestion so quickly, it's true, it doesn't cost me anything, using the s command, it was just an idea that came to mind
