### ISSUE TITLE
Qbittorrent update

### ISSUE THREAD

**Issue by kuesttman** [anasty17/mirror-leech-telegram-bot#1789]
Would it be possible to update qbittorrent to the latest available version (5.0.1 or 5.0.2) as flaws were discovered in previous versions used by MLTB. I am unable to download from some trackers.

**Comment by anasty17** [comment]
How version related to trackers ?!

**Comment by kuesttman** [comment]
Any version prior to 5.0.1 is being blocked by the tracker.
So, it would be a good idea to update the qBittorrent version to the latest version 5.0.1

**Comment by kuesttman** [comment]
The version installed on MLTB is:
# qbittorrent-nox --version
qBittorrent v4.6.7

Would it be possible to update the image to match qbittorrent version 5.0.1?
