### ISSUE TITLE
LEECH_FILENAME_CAPTION: Add custom caption to leeched file. Str

### ISSUE THREAD

**Issue by vcbat** [anasty17/mirror-leech-telegram-bot#1791]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anasty17** [comment]
What if folder have multiple files ?

**Comment by 5hojib** [comment]
> What if folder have multiple files ?

Maybe he asking for per files, with placeholder like, {filename}, {size}, {duration} etc.

**Comment by anasty17** [comment]
> > What if folder have multiple files ?
> 
> Maybe he asking for per files, with placeholder like, {filename}, {size}, {duration} etc.

No i don't think
He want to add it manually like new name

**Comment by vcbat** [comment]
![photo_2024-12-14_09-08-48](https://github.com/user-attachments/assets/976067e4-c7b1-40de-ba0a-ae3359837fdf)
![photo_2024-12-14_09-08-46](https://github.com/user-attachments/assets/5f75a4cf-7f4b-47c8-b2e8-b5941d809f33)
![photo_2024-12-14_09-08-43](https://github.com/user-attachments/assets/3cec0496-e318-4243-87f3-e0a777d23cf4)




like this i can't add caption like this

**Comment by 5hojib** [comment]
Some data collected through ffprobe here

**Comment by vcbat** [comment]
what ?

**Comment by anasty17** [comment]
> Some data collected through ffprobe here

No it's same as he settled 

And no i will not add this stupid thing
