### ISSUE TITLE
Update qBittorrent version in MLTB image.

### ISSUE THREAD

**Issue by kuesttman** [anasty17/mirror-leech-telegram-bot#1792]
The version installed on MLTB is:
```
# qbittorrent-nox --version
qBittorrent v4.6.7
```

Would it be possible to update the image to match qbittorrent version 5.0.1?
I'm having trouble with some trackers blocking qBittorrent versions older than 5.0.1

_Originally posted by @kuesttman in https://github.com/anasty17/mirror-leech-telegram-bot/issues/1789#issuecomment-2543325346_

**Comment by anasty17** [comment]
if u found a way to install sabnzbd on alpine, please let me know. But don't mention sabnzbd docker

**Comment by anasty17** [comment]
i will try ubuntu 24.10

**Comment by anasty17** [comment]
ok it's working but i will install par2 turbo using pip
i will push update for this

**Comment by anasty17** [comment]
building image ...

**Comment by 5hojib** [comment]
> building image ...

With alpine?

**Comment by anasty17** [comment]
> > building image ...
> 
> With alpine?

No 
Sabnzbd is a headache on it
Ubuntu 24.10

**Comment by kuesttman** [comment]
I updated the image here, and it now comes with Ubuntu version 24.10 and qbittorrent version 5.0.2.
And torrent downloads from some private trackers that had stopped working are now working again.

We would like to thank you in advance for all your support in resolving these issues.
