### ISSUE TITLE
Upload Progress Bugging

### ISSUE THREAD

**Issue by mine-nandha** [anasty17/mirror-leech-telegram-bot#183]
https://user-images.githubusercontent.com/86552361/146587523-40854759-9b63-4d65-a9aa-cdfca0a3d0f6.mp4

While mirroring files using qbmirror, upload Progress gettin freezed lyk this. ☝️after some time it does finish uploading tho (btw ofc it has 700+ files but downloading progress bar worked fine. So I thought I could raise an issue)

**Comment by anasty17** [comment]
@mine-nandha U got upload finish msg?

**Comment by anasty17** [comment]
@mine-nandha Send log to report group

**Comment by junedkh** [comment]
@mine-nandha If it has many folders it will take time please wait.

**Comment by mine-nandha** [comment]
> @mine-nandha U got upload finish msg?

Yes, just now.

**Comment by mine-nandha** [comment]
> @mine-nandha If it has many folders it will take time please wait.

Yes ik bruh. Just wanted to say that uploading progress isn't working on that particular matter.

**Comment by junedkh** [comment]
@mine-nandha Okay bro. Thanks sharing that 😊
