### ISSUE TITLE
[Feature Request] Mirror/Leech  Link Directly to Users 

### ISSUE THREAD

**Issue by MissLoki** [anasty17/mirror-leech-telegram-bot#185]
Suppose a user mirror/leech a link, After Completion the links should be send directly to him ,like he has to start the bot, all links will be forwarded to the chat i.e between user and bot.

It will be very useful in leech, as in leech the group gets populated with files ,also can't identify which file belong to whom.

**Comment by MissLoki** [comment]
I have seen some groups doing this with mirror don't know if possible with leech

**Comment by SpeedyIndeedy** [comment]
@MissLoki It will be done when a separate branch for group is created

**Comment by MissLoki** [comment]
OK ,Thanks

**Comment by MNDL-27** [comment]
> @MissLoki It will be done when a separate branch for group is created

any guide how to do that?

**Comment by anasty17** [comment]
I will add this to settings.. every user will choose channel or group to keep all his file there and sure they muat add the bot to that channel or group .. maybe not with dm .. depending if on each restart they want to text the bot or not like rss with string session
