### ISSUE TITLE
Feature Request] BYPASS MEGA  5GB LIMIT ?

### ISSUE THREAD

**Issue by MissLoki** [anasty17/mirror-leech-telegram-bot#188]
Is it possible to bypass mega 5gb limit ??

**Comment by snehitap** [comment]
@MissLoki Yes, buy the pro/business plan.. this is the only way.. 
Now close this issue and don't escalate plz...

**Comment by jusidama18** [comment]
> Is it possible to bypass mega 5gb limit ??

ofc with premium account u can bypass them
