### ISSUE TITLE
[Feature Request]  Bypass Ads Links Like Linkvertise

### ISSUE THREAD

**Issue by talha-exe** [anasty17/mirror-leech-telegram-bot#189]
Hi Anas,

I just saw that in one particular group, there is a mirror bot to which you provide a ads link and it bypasses it and provides you direct link. I was hoping if you can integrate that feature in your bot, that would be amazing. I am attaching source.

![Screenshot 2021-12-21 121833](https://user-images.githubusercontent.com/94534752/146887884-a9a5555d-4a3b-4248-8039-ed2333993e6a.png)

**Comment by anasty17** [comment]
@talha-exe Hi, search on bot to bypass... I'm working on mirror bot

**Comment by jusidama18** [comment]
@talha-exe it's mirror bot not bypass bot

**Comment by anasty17** [comment]
@talha-exe How i could add bypass for linkvertise and we already provide this Shortener for who want to add ads!! ... imagine u mirror a file in public group and linkvertise Shortener add for download links ... and in same bot there is a cmd for bypass it wtf

**Comment by talha-exe** [comment]
Understood @anasty17
