### ISSUE TITLE
[Question/Feature Request] RSS Keyword Filter

### ISSUE THREAD

**Issue by DarremMolko** [anasty17/mirror-leech-telegram-bot#191]
I was wondering how feasible is it to add a filter for RSS like in this repo: https://github.com/ayrat555/el_monitorro
User sets a filter, for example "Batman" and the bot monitors the subscribed feed and only sends to channel the posts with the matching keyword (in this case Batman).

**Comment by ZekXtreme** [comment]
@DarremMolko Doesn't make sense

**Comment by DarremMolko** [comment]
The usecase is, if you want an specific movie like for example The Matrix: Resurrection, you can set a filter for that. Or if you want an specific TV Show like The Expanse, you set a filter to get only episodes from that show and so on.

**Comment by dishapatel010** [comment]
> The usecase is, if you want an specific movie like for example The Matrix: Resurrection, you can set a filter for that. Or if you want an specific TV Show like The Expanse, you set a filter to get only episodes from that show and so on.

Use filters from Rss it self. Ex. nyaa
