### ISSUE TITLE
Add feature of showing magnet link in telegraph 

### ISSUE THREAD

**Issue by Harshakorikanti** [anasty17/mirror-leech-telegram-bot#192]
If you can do it please add feature to see magnet link after searching in telegraph page without using sharing to telegram button 
And add feature to show 
![Screenshot_2021-12-21-20-04-37-832_ir ilmili telegraph](https://user-images.githubusercontent.com/91387760/146947217-8286095d-2659-4675-9e83-b64edada8c0a.jpg)
time taken to search file in GDrive and from torrent links
![Screenshot_2021-12-21-20-06-20-954_ir ilmili telegraph](https://user-images.githubusercontent.com/91387760/146947455-709ada62-1420-4d09-a176-c68ed0562965.jpg)

**Comment by jusidama18** [comment]
@Harshakorikanti 1. For what u need to see long magnet when in the end u will send those magnet to telegram, and it's reduce telegraph page with sending button

2. Not really necessarily
