### ISSUE TITLE
Feature Request for Seeding using files from Gdrive

### ISSUE THREAD

**Issue by KillingParadise** [anasty17/mirror-leech-telegram-bot#194]
Is it possible to add a feature for bot to get torrent's files from Gdrive + the magnet link and start seeding it ?

1) Would help in seeding dead torrents via bot.
2) Helps in seeding private tracker torrents for longer than 24 hours when using Heroku.

Thank You.

**Comment by anasty17** [comment]
Yeah it's not seed project!!!

**Comment by KillingParadise** [comment]
Alright got it, thanks for the reply.
