### ISSUE TITLE
Request - Ability to filter Rss feed 

### ISSUE THREAD

**Issue by mb807635** [anasty17/mirror-leech-telegram-bot#198]
By default bot is mirroring all the content that is being published in a rss feed. Hope you can make it filter through ,so that only content user wanted gets mirrored.

Rss feed generator- https://github.com/Jackett/Jackett
Rss feed reader and being filtered currently - https://github.com/iamLiquidX/rss-feed-telegram-bot
I hope this suffice.

**Comment by ZekXtreme** [comment]
Everyone has different needs so making a bot specifically for someone doesn't make sense ..you should edit according to your need
