### ISSUE TITLE
Unable to get GDToT cookies with the javascript. 

### ISSUE THREAD

**Issue by spiderbyV** [anasty17/mirror-leech-telegram-bot#200]
Hey, 

When trying to get GDToT cookies using the javascript, my browser does no prompt, it triggers neither the if nor else statement. Disabled uBO, still the same. 
Any ideas on how to proceed further? Thank you.

**Comment by anasty17** [comment]
@spiderbyV Which browser? Phone or pc ?

**Comment by spiderbyV** [comment]
FF in Win10. 

I ended up using [Lennon Hill's addon](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/)

**Comment by spiderbyV** [comment]
@anasty17 I used the input from the above mentioned addon, via editing config vars. 
Still I get the "ERROR: PHPSESSID and CRYPT variables not provided".
Could that be because of using the addon to get these values?

**Comment by anasty17** [comment]
Readme

**Comment by spiderbyV** [comment]
My query wasn't how to use the cookie data, rather, would obtaining cookies data from another method would have an effect on it's compatibility with this repo since the javascript option wasn't returning anything in FireFox (and Edge). 
But thanks for your time, I'll figure this out somehow.

**Comment by spiderbyV** [comment]
In case someone faces this issue in the future, you can use that addon to get the PHPSESSID and CRYPT. It makes no difference which method is used.
