### ISSUE TITLE
Add title of releases from RSS on log channel

### ISSUE THREAD

**Issue by l3v11** [anasty17/mirror-leech-telegram-bot#206]
Currently the log channel shows Feed link only.. But can't be sure what the torrent name is.. So adding Name along with Feed link would be awesome...

Here's an example if you'd like to see

![IMG_20211224_085724](https://user-images.githubusercontent.com/57452819/147311025-f25f9168-3037-4df7-8823-bb9888532508.jpg)

**Comment by anasty17** [comment]
@l3v11 First this not rss bot ... i added rss to directly download...2nd update ur repo and try i added this to stop this spam

**Comment by l3v11** [comment]
@anasty17 Ohh thanks
