### ISSUE TITLE
Some sites Rss feed not working

### ISSUE THREAD

**Issue by aashath031** [anasty17/mirror-leech-telegram-bot#208]
![rss](https://user-images.githubusercontent.com/92869296/147318567-56c227c6-3188-44e5-9c8c-cd186b6d3d36.PNG)

Please fix this error Link : https://fitgirl-repacks.site/feed/

**Comment by anasty17** [comment]
This link not opening

**Comment by jusidama18** [comment]
@aashath031 It has ddos protection that's why
