### ISSUE TITLE
Direct link support

### ISSUE THREAD

**Issue by Killerxy** [anasty17/mirror-leech-telegram-bot#211]
Need direct support link for 
"Stream.bunkr.is, vidmx.xyz"

**Comment by ix1702** [comment]
and "fshare.vn"
https://www.fshare.vn/

**Comment by jusidama18** [comment]
@Killerxy Provide example link

**Comment by Killerxy** [comment]
> @Killerxy Provide example link

http://cdn12.vidmx.xyz/h7todicramlbu3tf6rvtlnxlyxi7nmq2hrdgr7d5y2224sefe26ju5gnwgha/TamilYogi.vip_-_Annaatthe_(2021)_Tamil_TRUE_WEB_DL_1080p_AVC_UNTOUCHED_(DD+5_1_640Kbps_&_AAC_2_0)_3_3GB_ESub_HD_720p.mp4

**Comment by jusidama18** [comment]
@Killerxy Original link, that's direct link 🙄

**Comment by Killerxy** [comment]
@jusidama18  http://vidmx.xyz

**Comment by Killerxy** [comment]
https://stream.bunkr.is

**Comment by jusidama18** [comment]
@Killerxy "example link" not site link or direct link

**Comment by ix1702** [comment]
> @Killerxy "example link" not site link or direct link

https://www.fshare.vn/file/U1DGUPNU3MKPLJO
This one is the same as mega. Reply this if you need vip account to test.

**Comment by Killerxy** [comment]
> @Killerxy "example link" not site link or direct link

I can't get it
I got this link from tamilyogi.cool
