### ISSUE TITLE
[Feature Request] Support for skipping checked feeds

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#213]
If possible can you please add a feature to skip feeds that have been already sent to the bot for mirroring?
It is sending the same link multiple times from the same torrent site's RSS, the bot fails to process so many requests and freezes.
It automatically restarts or I have to reboot it manually. Even then the same cycle repeats.

**Comment by anasty17** [comment]
@rajput-hemant Already skipping sent links!!

**Comment by anasty17** [comment]
@rajput-hemant Unless u edit in code, send rss link in report group and send full log

**Comment by rajput-hemant** [comment]
![image](https://user-images.githubusercontent.com/68769346/147436362-19f77487-663b-409e-be91-dafa63b9da8c.png)
here's the RSS channel link: https://t.me/+3A4iLSHzLfwyZDE9
here's the log: [log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/7778424/log.txt

**Comment by anasty17** [comment]
@rajput-hemant Send in group

**Comment by rajput-hemant** [comment]
I'd have send it if i could, i'm banned in the group

**Comment by rajput-hemant** [comment]
@anasty17 
So is it really skipping checked feeds or its not?
and how can I fix it?
Also, I haven't edited anything in the code but bot commands, qbit & some message strings.

**Comment by anasty17** [comment]
@rajput-hemant Not really I'm kidding
