### ISSUE TITLE
Change in CUSTOM_FILENAME

### ISSUE THREAD

**Issue by aphabeta** [anasty17/mirror-leech-telegram-bot#214]
@anas_tayyar requesting you for a small change in CUSTOM_FILENAME. The bot leaves a space between Custom filename and filename. Please remove the space as it looks unnecessary. Requesting for it since I dont want to fill upstream repo with edited repo to get automatic updates. https://telegra.ph/file/2eb2a8d2a93b1b9b5e364.jpg

**Comment by anasty17** [comment]
@aphabeta Yes there is a space

**Comment by aphabeta** [comment]
Can you remove it please ?

**Comment by anasty17** [comment]
@aphabeta No
