### ISSUE TITLE
[Feature Request] Add a message string before file/folder starts cloning

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#215]
If possible, please add a Processing message before it starts cloning as it does with the GDTot links.
If a drive folder has too many files in it, it takes time before it starts cloning, it'll be better if there is a message so that the user doesn't send that link again thinking that it's not added yet.

**Comment by nekoru-kun** [comment]
@rajput-hemant Update to lastest commit

**Comment by rajput-hemant** [comment]
@nekoru-kun I'm on the latest commit

**Comment by mine-nandha** [comment]
@rajput-hemant https://github.com/anasty17/mirror-leech-telegram-bot/pull/159#issue-1077751379

👆🏻

**Comment by nekoru-kun** [comment]
@rajput-hemant Try redeploy your bot, cause gdtot processing status message should have been in the last update

**Comment by rajput-hemant** [comment]
@nekoru-kun @mine-nandha you didn't get it, I'm asking to implement the same for drive clone also, as it does with gdtot links.
I'm saying that it shows nothing if a drive folder has too many files in it, so it would be better if it shows processing messing while it checks for the file size of the drive folder and then delete that processing message when it starts cloning.

**Comment by nekoru-kun** [comment]
@rajput-hemant my bad
sorry I didn't read your issue carefully
