### ISSUE TITLE
[Feature Request] Detect Duplicate files and skip them while Cloning

### ISSUE THREAD

**Issue by MissLoki** [anasty17/mirror-leech-telegram-bot#216]
In case bot crashes or clone is interrupted we have to manually delete folder from teamdrive, as it checks for duplicate files  in td ,it will be nice if it can check all files that are in the folder and skip already copied files and resume cloning ,
Like Clonebot from msguitechat

**Comment by ZekXtreme** [comment]
@MissLoki 😒it skips duplicate files bother to check config

**Comment by MissLoki** [comment]
It check folder any name ,and stop cloning ,even if the folder is empty
