### ISSUE TITLE
Idling in bot

### ISSUE THREAD

**Issue by puspmeena** [anasty17/mirror-leech-telegram-bot#218]
even after adding base_url_of_bot, idling isn't stopped.

**Comment by dinesh-0602** [comment]
@puspmeena Add in config file. Not heroku

**Comment by puspmeena** [comment]
@dinesh-0602 i did add it in config.env as instructed in readme

**Comment by dinesh-0602** [comment]
@puspmeena Come to bugs report grp

**Comment by puspmeena** [comment]
@dinesh-0602 sad im banned 😅😅
