### ISSUE TITLE
ERROR - Inline keyboard button url is invalid

### ISSUE THREAD

**Issue by Warior5378** [anasty17/mirror-leech-telegram-bot#219]
ERROR - Inline keyboard button url is invalid
how to fix this ????

**Comment by jusidama18** [comment]
@Warior5378 Add https:// before ur link

**Comment by Warior5378** [comment]
> 
bro which link

**Comment by jusidama18** [comment]
@Warior5378 U add additional button in config.env?

**Comment by Warior5378** [comment]
> @Warior5378 U add additional button in config.env?

oh yaa i forgot their thanks

**Comment by Warior5378** [comment]
how to use torrent select feature

**Comment by VarnaX-279** [comment]
@Warior5378 Thank God, You're not asked this in Group

**Comment by jusidama18** [comment]
@Warior5378 read what mirror command give u

**Comment by Warior5378** [comment]
> @Warior5378 read what mirror command give u

thanks a lot found it

**Comment by Warior5378** [comment]
> @Warior5378 Thank God, You're not asked this in Group

ja na be rotadu

**Comment by l3v11** [comment]
@Warior5378 Where there is readme, there is the way
