### ISSUE TITLE
qbmirror is unable to extract link from jackett

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#221]
![image](https://user-images.githubusercontent.com/68769346/147554270-b7f589b7-9566-44b1-8c0e-5429fa36c4bc.png)
qbmirror is unable to extract link from jackett
If I use the mirror command with the same link, it works fine

**Comment by anasty17** [comment]
Send link

**Comment by anasty17** [comment]
I have added check for link if it's torrent or not to avoid bot crash when add direct link like video with qbcommands, so i will add this head also
