### ISSUE TITLE
Feature Request: Total Traffic from time to time

### ISSUE THREAD

**Issue by nguyenphuc241** [anasty17/mirror-leech-telegram-bot#222]
Great job when developing this repo! 
I'm here requesting for the feature that can measures our traffic like: Total Upload - Download - Transfers - etc. We can connect to Postgresql, then we can save the data there? The data will be written every time bot restarts.

When we need to know about how much traffic have been transferred in a specific amount of days, we can query to the database? 
Sorry I'm not familiar with this kind of programming o(*￣︶￣*)o

Anyways, thanks for this wholesome repo, I'm really grateful (✿◡‿◡)

**Comment by anasty17** [comment]
Not important
