### ISSUE TITLE
[REQUEST] Torrent Reseed

### ISSUE THREAD

**Issue by dailyentertainment** [anasty17/mirror-leech-telegram-bot#229]
Maybe this request won't make sense for lots of users. 
First I want to thank you because of QB Seed option. Heroku-hosted bots automatically restart once a day and files get deleted. But these files are stored in gdrive. Is it possible to add an option (like /storemirror or something like that) where files will be stored? Then we can use /qbmirror {metadata}. Because these files are already stored qbittorrent will check them and start reseeding. 

I don't know if it is a valid request. I will wait for a reply. Thanks again for your great work.

**Comment by anasty17** [comment]
Not valid ... heroku delete everything

**Comment by Box-boi** [comment]
@dailyentertainment Possible with rclone, although painful to setup

**Comment by dailyentertainment** [comment]
When we use QBSeed, Heroku doesn't delete those files.

**Comment by anasty17** [comment]
Do u want block on github?
