### ISSUE TITLE
[feature request] add kickass button in torrent api search options

### ISSUE THREAD

**Issue by yadianluffy** [anasty17/mirror-leech-telegram-bot#230]
https://github.com/Ryuk-me/Torrents-Api

hi ryuk-me just updated your repository and added kickass torrent site i updated my fork and tried to search but i don't get the kickass option to search could you please add it. 

thanks great job with the repo

**Comment by jusidama18** [comment]
@yadianluffy Soon

**Comment by yadianluffy** [comment]
and bitsearch which was recently added as well

**Comment by anasty17** [comment]
@yadianluffy 👍
