### ISSUE TITLE
Issue with RSS Auto Mirror

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#232]
The flooding issue still exists, Bot still sends the same links even after setting the RSS interval to 900. Maybe after every restart, it sends the already sent feeds links from the DB that have been already mirrored. It works okay if STOP DUPLICATE is true or if the torrent is already in the list as it just cancels the mirror, but sometimes it sends too many links at once and bots stop responding, forcing it to restart again due to memory exceeded error or due to disk space.
In the case of leech, it gets worse. 
Please fix it if possible.

And I don't know if it's just with me or other users also have the same problem.
I'M ON THE LATEST COMMIT but even then if it's just with me, please ignore this issue.

**Comment by anasty17** [comment]
Logs

**Comment by rajput-hemant** [comment]
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/7796652/log.txt)
