### ISSUE TITLE
[Feature Request] Upload to a specific folder in Google Drive

### ISSUE THREAD

**Issue by 0ibaba** [anasty17/mirror-leech-telegram-bot#234]
Is it possible to upload to specific folders in Google Drive using their Folder ID?
Something more convenient would be, to be able to set specific names and Folder IDs in config.env , that way we can specify the name instead of the Folder ID.

Something like  `/mirror <magnet-link> ~ <folder id/name set in config>`

I'm not sure if this was asked before, so I'm sorry if it was.

**Comment by anasty17** [comment]
Not important... manage ur files from drive app
