### ISSUE TITLE
Really a big issue 

### ISSUE THREAD

**Issue by XahidEx** [anasty17/mirror-leech-telegram-bot#235]
Please increase the auto-restart time. It's so annoying if I clone a large drive. It goes half and gets canceled for the auto restart option.

**Comment by VarnaX-279** [comment]
@XahidEx Do you know about heroku?

**Comment by snehitap** [comment]
@XahidEx Wtf Auto restart.. 😂 U using heroku?

**Comment by XahidEx** [comment]
Yes, And Bot gets auto restarted after 24 hours. 😪

**Comment by XahidEx** [comment]
So It's an issue with Heroku, right?

**Comment by snehitap** [comment]
@XahidEx Not a issue, heroku app restarts after every 24 hrs thats how heroku works in free tier..

**Comment by XahidEx** [comment]
What do you prefer to use? I don't have VPS. Any other solution? Railway also not working you know.

**Comment by VarnaX-279** [comment]
Use Heroku Paid dyno or buy a vps,
This is not our problem or bug.

**Comment by dp014755** [comment]
That is porblem because on other repo Like harsh the bot is not restart or shutdown

**Comment by dinesh-0602** [comment]
@dp014755 LMAOO. Nice promotion

**Comment by VarnaX-279** [comment]
@dp014755 Every bot hosted in heroku free dyno must restart every 24 hours
