### ISSUE TITLE
/cancellall doesnt cancel seeding torrents

### ISSUE THREAD

**Issue by askfriends** [anasty17/mirror-leech-telegram-bot#242]
bro i just noticed /cancelall doesn't cancel currently seeding torrents while it should cancel both ongoing download task plus seeding torrents.

**Comment by anasty17** [comment]
Cancelall only cancel downloading tasks or in queue u can edit in code to make it cancel other tasks

**Comment by askfriends** [comment]
> Cancelall only cancel downloading tasks or in queue u can edit in code to make it cancel other tasks

yes it does the exact as u said but it should also cancel seeding tasks as well, dont u think so?

**Comment by anasty17** [comment]
@askfriends Open poll in group
