### ISSUE TITLE
Request for .dlc file support.

### ISSUE THREAD

**Issue by aphabeta** [anasty17/mirror-leech-telegram-bot#253]
#FeatureRequest Is it possible to add .dlc file mirroring support ? Like these files open in jdownloader and mirror all links from from different hosts.

**Comment by anasty17** [comment]
No

**Comment by aphabeta** [comment]
> No... possible but i will not think about it

Oh Please consider it 🥺🥺. Anytime you can, when you are free. It will be very helpful.
