### ISSUE TITLE
Not deleting original gdtot file after cloning.

### ISSUE THREAD

**Issue by ronin08** [anasty17/mirror-leech-telegram-bot#258]
After cloning with gdtot link, the bot is not deleting the original file from main drive.

please check on your side. I can confirm this and I have updated the bot with latest repo release.

**Comment by anasty17** [comment]
@ronin08 Service accounts have access to ur drive root ?

**Comment by ronin08** [comment]
yup! 
I had tried with adding the sa to main drive by giving the highest permission -- editor to my service accounts

but still doesn't work . and log says insufficient permission!

**Comment by anasty17** [comment]
@ronin08 Add token.pickle in repo!

**Comment by ronin08** [comment]
thanks! I have some issues in token_pickle_url.
this will probably fix my issue:)

well I have a suggestion ..can i share
