### ISSUE TITLE
No 1337x Search Found

### ISSUE THREAD

**Issue by FilmBee** [anasty17/mirror-leech-telegram-bot#261]
I deployed the torrent mirror bot from official repo but there is no 1337x search I also checked config file there is no python file for 1337x...  can you give me the updated config file link please... my bot is hosted in heroku... I really need the 1337x search... please sir help me🙏

I used Config from https://raw.githubusercontent.com/anasty17/mirror-leech-telegram-bot/master/config_sample.env

**Comment by anasty17** [comment]
Readme
