### ISSUE TITLE
Type error while cloning (after the last commit)

### ISSUE THREAD

**Issue by mine-nandha** [anasty17/mirror-leech-telegram-bot#264]
![IMG_20220110_100000](https://user-images.githubusercontent.com/86552361/148719008-e5a6c822-6004-437e-929f-1b447b74068d.jpg)

Here's a link 
https://drive.google.com/file/d/1JuvcfBZc37amU0iymi6t843ve9WqbOKu/view?usp=sharing

**Comment by anasty17** [comment]
Thanks
