### ISSUE TITLE
Need little help about latest commit 

### ISSUE THREAD

**Issue by Ajayveer9911github** [anasty17/mirror-leech-telegram-bot#271]
Do I have to edit updated code **one by one (file by file)** , before redeploying the app?
If not, please can you elaborate how to redeploy for this new commit dated on 10-01-2022.

**Comment by anasty17** [comment]
@Ajayveer9911github Google search to update ur fork

**Comment by Ajayveer9911github** [comment]
Sir, I had cloned using template upstream repo while creating bot. Now, I don't see any option to fetch upstream repo. As there is no upstream repo. What should I do?

**Comment by prono69** [comment]
@Ajayveer9911github Lemme help you . You have android right ? Then download Mgit app from Play Store . It's a git GUI so it's very easy to do such things .
