### ISSUE TITLE
[FEATURE REQUEST] Idea

### ISSUE THREAD

**Issue by yadianluffy** [anasty17/mirror-leech-telegram-bot#272]
hello could you create a command or a separate menu for the seed of torrents because when you are sharing several files that you use the command /status to see a download in progress you will see there the files you are sharing and the download in progress in several pages later because the recommended limit per page is 4 at a time I hope you like this idea this idea is not bad

example 
/status shows the downloads in progress
/seeding shows the files that you are sharing

**Comment by anasty17** [comment]
@yadianluffy Not worth

**Comment by anasty17** [comment]
@yadianluffy I don't want to add something hurt the memory and will cause tg flooding

**Comment by yadianluffy** [comment]
ok thank you very much for your answer
