### ISSUE TITLE
Can't Seed Private Tracker/Freeleech Torrent

### ISSUE THREAD

**Issue by vivekdarji00** [anasty17/mirror-leech-telegram-bot#275]
Bot can't seed any private tracker & freeleech torrent
Is it possible to seed a private tracker/freeleech torrent?
![IMG_20220111_194221](https://user-images.githubusercontent.com/70027857/148958769-93366b15-971d-4cc6-920f-be70ae701f34.jpg)

**Comment by mine-nandha** [comment]
Yes, bot can't seed any single torrent unless it has atleast a leecher. 😑
Now please close this issue before the owner does😂
