### ISSUE TITLE
How can I disable the drive link button?

### ISSUE THREAD

**Issue by davidalvaz21** [anasty17/mirror-leech-telegram-bot#278]
hello.
How can I disable the drive link button?
I just want to show only the index link to the users.
thank you so much.

**Comment by anasty17** [comment]
No direct option u need to edit in code

**Comment by davidalvaz21** [comment]
Thanks for answering.
I removed this line :
`buttons.buildbutton("☁️ Drive Link", link)`
from the following paths :
bot/modules/mirror.py
bot/helper/mirror_utils/upload_utils/gdriveTools.py

and i re-deploy it but nothing changed.
Unfortunately I am a beginner, which file should I edit?
Thanks again

**Comment by anasty17** [comment]
Learn by ur self don't ask how to edit

**Comment by davidalvaz21** [comment]
I was just looking for a simple answer , false pride is not good sir ...
