### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Ajayveer9911github** [anasty17/mirror-leech-telegram-bot#279]
How to fix this 

![Screenshot_20220111-210505_Chrome](https://user-images.githubusercontent.com/96938395/148972915-e153a506-5136-45d8-9f43-90dbaeb51020.jpg)
[fourbitmirror2-logs-1641915142556.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/7847805/fourbitmirror2-logs-1641915142556.txt)

**Comment by anasty17** [comment]
@Ajayveer9911github If u can send log file to group will be better

**Comment by Ajayveer9911github** [comment]
Thank you sir, you fixed this.

**Comment by Ajayveer9911github** [comment]
The error is fixed . RSS feed is being fetched🔃 (shown in logs) , but it's not uploading on telegram⚠️.

**Comment by anasty17** [comment]
Plz don't report without logs

**Comment by anasty17** [comment]
Send log file in group ... report in group not here
