### ISSUE TITLE
Request To Add Support For This Type Of Link
 https://appdrive.in/file/38e1ea3dc37d9fe0dc69 
https://appdrive.in/file/9adbd4f3b62b829668f4

### ISSUE THREAD

**Issue by neilchetty** [anasty17/mirror-leech-telegram-bot#281]

**Comment by anasty17** [comment]
@neilchetty This doesn't need for generator u can get the link

**Comment by missemily2022** [comment]
@anasty17 Would it be possible if the Bot automatically fetches Link and clones instead of manually doing by us?

**Comment by snehitap** [comment]
@missemily2022 How much lazy can u be 😂😂

**Comment by missemily2022** [comment]
@snehitap Bro I am not lazy

I was asking if it's ever possible
