### ISSUE TITLE
error in the mirror after the last upgrade

### ISSUE THREAD

**Issue by yadianluffy** [anasty17/mirror-leech-telegram-bot#287]
[decidefristoneytrewq-logs-1642089721524.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/7864142/decidefristoneytrewq-logs-1642089721524.txt)

**Comment by missemily2022** [comment]
@yadianluffy It's a problem on your side

You have not uploaded the Service Accounts folder


Or you forgot to rename the service accounts to numerical order before uploading them for Mirror Bot use


Kindly Read the Readme.md again

**Comment by anasty17** [comment]
@yadianluffy Yeah im fixing it 5 mins

**Comment by yadianluffy** [comment]
@anasty17 thank you

**Comment by anasty17** [comment]
@yadianluffy Done restart dyno

**Comment by yadianluffy** [comment]
@anasty17 now it works correctly thank you very much

**Comment by anasty17** [comment]
@yadianluffy There is one more issue

**Comment by yadianluffy** [comment]
@anasty17 ????
