### ISSUE TITLE
Leeching issue

### ISSUE THREAD

**Issue by rubandurai27** [anasty17/mirror-leech-telegram-bot#289]
Drive links not leeching after update ( I mean drive links not leech in latest commits) .
Plz resolve this issue

**Comment by anasty17** [comment]
Test in group test bot

**Comment by anasty17** [comment]
Check group

**Comment by rubandurai27** [comment]
![Screenshot_2022-01-14-18-03-46-211_org telegram plus](https://user-images.githubusercontent.com/77948100/149516582-eee8de4a-ff29-48a2-ad99-1dafae260c55.jpg)

![Screenshot_2022-01-14-18-08-00-398_com android chrome](https://user-images.githubusercontent.com/77948100/149516840-1a1cc0da-4c2c-4fc1-9fa9-69fe077f1834.jpg)

Plz check my bot  @tnmiirorbot on telegram . I am auth you ..
