### ISSUE TITLE
Search API Bug

### ISSUE THREAD

**Issue by braindedboi** [anasty17/mirror-leech-telegram-bot#290]
EZTV returns 50 results even if there is no match.
![IMG_20220115_003137](https://user-images.githubusercontent.com/85474068/149570830-ce5d6096-e389-4534-884a-16422ccd6c49.jpg)

Also, TPB returns "No results returned", which is unnecessary.
![IMG_20220115_003608](https://user-images.githubusercontent.com/85474068/149571228-a7ad5a41-6e53-4b2c-9154-62af21ab11d3.jpg)

**Comment by anasty17** [comment]
@braindedboi What TPB?

**Comment by braindedboi** [comment]
> @braindedboi What TPB?

The Pirate Bay

**Comment by anasty17** [comment]
@braindedboi Plugin issue report to plugin dev

**Comment by anasty17** [comment]
@braindedboi Or use api

**Comment by braindedboi** [comment]
> @braindedboi Or use api

Api also same. It may be a problem with EZTV site...

**Comment by anasty17** [comment]
@braindedboi Problem from host not from code ... deploy ur api on vps .It's working well

**Comment by braindedboi** [comment]
> @braindedboi Problem from host not from code ... deploy ur api on vps .It's working well

Ohh. Ok. I will try tomorrow. Thanks
