### ISSUE TITLE
[FEATURE REQUEST] Deleting Messages After Some Time ?

### ISSUE THREAD

**Issue by MissLoki** [anasty17/mirror-leech-telegram-bot#294]
Is it possible to add a feature so that the bots deletes their own messages after some time (6 hours or 12 hours) ,time can be set by users  at the time of bot creation .(It will help in avoiding Grp Bans )

Also is it possible to add feature in LEECH so that the bots sends the files to each user in pm, condition is that they must start the bot in pm, it will avoid confusion when multiple users are leeching.

**Comment by anasty17** [comment]
@MissLoki First u can set auto delete msg for group ... i will not add this ... 2nd don't ask for group features

**Comment by MissLoki** [comment]
Auto Delete is 24 hrs wanted less than that ,anyway No Worries !

**Comment by anasty17** [comment]
@MissLoki Soon will create branch for groups ... all this is heavy on me .. can't do everything alone .. so need more time ... master branch should be stable before creating any other branch
