### ISSUE TITLE
Heroku is unable to sign in to the bot because of this issue

### ISSUE THREAD

**Issue by Lostvale0** [anasty17/mirror-leech-telegram-bot#300]
Is the issue from your side or telegram's side?
![image](https://user-images.githubusercontent.com/94958746/149678393-994a96b0-cdca-4200-abcf-e4d0cdb06e6b.png)

**Comment by anasty17** [comment]
Ur issue read the error

**Comment by Lostvale0** [comment]
> Ur issue read the error
I don't think so.

**Comment by anasty17** [comment]
When u got this error while bot start or what ?

**Comment by anasty17** [comment]
Send full log

**Comment by Lostvale0** [comment]
Thanks the issue is fixed!
