### ISSUE TITLE
Error: Error: Command failed: heroku container:login

### ISSUE THREAD

**Issue by Andrio-Codes** [anasty17/mirror-leech-telegram-bot#314]
![image](https://user-images.githubusercontent.com/21367218/150323803-3faf75d3-ab79-4ca7-ab5c-0ef79de194e8.png)

Getting this error while running the Workflow.

**Comment by Andrio-Codes** [comment]
> ![image](https://user-images.githubusercontent.com/21367218/150323803-3faf75d3-ab79-4ca7-ab5c-0ef79de194e8.png)
> 
> Getting this error while running the Workflow.
> 

Why is it closed?

**Comment by RafeeDaBoy** [comment]
Did you fix this?

**Comment by anasty17** [comment]
@RafeeDaBoy I will next year

**Comment by Andrio-Codes** [comment]
> Did you fix this?

Yes. It was happening because of service accounts. I removed it.

**Comment by anasty17** [comment]
@Andrio-Codes Wtf

**Comment by RafeeDaBoy** [comment]
@Andrio-Codes I just re-typed my info into the secrets and it worked. Probably made an error somewhere

> @RafeeDaBoy I will next year
I should've phrased it better, I asked @Andrio-Codes if he found a solution

**Comment by anasty17** [comment]
> @Andrio-Codes I just re-typed my info into the secrets and it worked. Probably made an error somewhere
> 
> > @RafeeDaBoy I will next year
> 
> I should've phrased it better, I asked @Andrio-Codes if he found a solution

When i close the issue directly u should know ... u r the issue
