### ISSUE TITLE
Rss

### ISSUE THREAD

**Issue by mangopissemand1** [anasty17/mirror-leech-telegram-bot#315]
Rss doesnt work at all recently after the code got changed. I have filled out my userstring, delay, rss chat id and command, but doesnt do anything now. It is a valid link.

**Comment by mangopissemand1** [comment]
I dont use database, should i do that?

**Comment by mangopissemand1** [comment]
The bot wont respond. Tried redeploying with no luck.

**Comment by minekavi** [comment]
> I dont use database, should i do that?

Open your eyes and check readme first.
RSS NOTE: DATABASE_URL and RSS_CHAT_ID is required, otherwise all rss commands will not work.
