### ISSUE TITLE
Clone Is Taking Long Time - Not cloning

### ISSUE THREAD

**Issue by amjiddader** [anasty17/mirror-leech-telegram-bot#317]
Hi, 

I deployed this awesome tool on my dedicated server.
Bot is up and running - 
Downloading is fast & works like a charm.

### I am unable to use clone feature 
When i enter google drive url its keeps checking file size. 
and doesn't respond even after 24 Hours. 

1. My server uplink is 10Gbps
2.  Using 500 service account
3. Downloading to my Shared drive 
4. Downloading from shared drive 
5. Folder size is about 1.2TB 

### expected solution 

I think a workaround for this is to disable file_size check if in upload.utils - 
Problem is when drive link is sent to bot.
First it checks link and give us folder_id , name, size.

I know size is important to determine lot of stuff..
But it is useful to clone larger stuff ...

While in download progress it will not show how much storage is used will show i.e ∞ 

-------
Final note: i tried to edit upload.util but i couldn't figure how can i only disable file size check function

--- 

Please someone or @anasty17  if you will send me modified file or atleast ..
Create a variable in config. env to choose
CLONE_SIZE_CHECK = False -/

Thanks

**Comment by anasty17** [comment]
@amjiddader Will not send anything.. this not clone bot ... minimal features for personal use ... deploy clone bot or use Autorclone
