### ISSUE TITLE
[Feature Request] Add ability to cancel metadata downloaded torrent after a specific time.

### ISSUE THREAD

**Issue by Hyperflaw5** [anasty17/mirror-leech-telegram-bot#327]
Hello sir , Firstly Thanks to you for making this repo.
Well i am using rss feature of the bot precisely . But if there are a lot of feed update .and since it is automatically mirroring . Task count goes more and more and since it is hosted on heroku . It is crashing due to load.
i tried to limit the active task to 8 in qBittorent config. But Some of the torrent stuck on 0B. Since it downloads metadata already . so It does not cancel automatically .And on the other hand feeds are updating in every update. and adding new tasks.So it makes the bot to be crashed. 

if this feature available in bot please tell me how to do . Thanks :)

**Comment by anasty17** [comment]
I have added readme feature ... use it

**Comment by Hyperflaw5** [comment]
Sir, I can't find anything in readme about it .

**Comment by anasty17** [comment]
@Hyperflaw5 Take ur time

**Comment by Hyperflaw5** [comment]
well sir i go through every line of the readme . cant figure out 😥😥😥😥😥
Can you please atleast give me a hint or smthing

**Comment by anasty17** [comment]
@Hyperflaw5 Variables description

**Comment by anasty17** [comment]
@Hyperflaw5 Maybe i will add var for it soon

**Comment by snehitap** [comment]
@Hyperflaw5 Edit in here...

https://github.com/snehitap/mirror-leech-telegram-bot-1/blob/2100d4dcc6d83ae5c6576ad444645aee2def1ea4/bot/helper/mirror_utils/download_utils/qbit_downloader.py#L181

https://github.com/snehitap/mirror-leech-telegram-bot-1/blob/2100d4dcc6d83ae5c6576ad444645aee2def1ea4/bot/helper/mirror_utils/download_utils/qbit_downloader.py#L131

**Comment by Hyperflaw5** [comment]
@snehitap Thanks Sir 

@anasty17 Don't Mind . But this thing is not written in Readme. I have Checked(With taking time) whole readme about 4 times xD.
Btw Thanks For the help :)

**Comment by anasty17** [comment]
> @snehitap Thanks Sir
> 
> @anasty17 Don't Mind . But this thing is not written in Readme. I have Checked(With taking time) whole readme about 4 times xD. Btw Thanks For the help :)

![Uploading Screenshot_20220125-103306_Chrome.jpg…]()

**Comment by anasty17** [comment]
> @snehitap Thanks Sir
> 
> @anasty17 Don't Mind . But this thing is not written in Readme. I have Checked(With taking time) whole readme about 4 times xD. Btw Thanks For the help :)

![Screenshot_20220125-103306_Chrome](https://user-images.githubusercontent.com/77075674/150940840-f445500c-a295-4f0d-b64e-0ab00b240cd2.jpg)

**Comment by anasty17** [comment]
> @snehitap Thanks Sir
> 
> @anasty17 Don't Mind . But this thing is not written in Readme. I have Checked(With taking time) whole readme about 4 times xD. Btw Thanks For the help :)

Next time i must block u directly to stop annoying us
