### ISSUE TITLE
New python api

### ISSUE THREAD

**Issue by rohan1211** [anasty17/mirror-leech-telegram-bot#364]
Plz update to new python api....

**Comment by rohan1211** [comment]
Sir i contact him he had exam he almost finished only need to addrest of sites he will do it soon.... He fixed all bugs

**Comment by jusidama18** [comment]
@rohan1211 just wait peacefully let people enjoy life

**Comment by anasty17** [comment]
Yeah goodluck for him, i will wait the rest
