### ISSUE TITLE
Bot Restarts randomly Everyday

### ISSUE THREAD

**Issue by BlackFoxy616** [anasty17/mirror-leech-telegram-bot#369]
Bot Working just fine but it restarts everyday randomly and one of my friend deployed same bot and he say his bot doesn't restart like this, it's not a big issue as bot works fine apart from restarting...but it could great if someone help me r tell me y it happens 
Thank you

**Comment by snehitap** [comment]
@BlackFoxy616 Join group then ask u will get ur answer 😅

**Comment by sidkap20** [comment]
Sending logs when?
