### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghostmirrorlab** [anasty17/mirror-leech-telegram-bot#372]
https://github.com/anasty17/mirror-leech-telegram-bot/blob/284bc6d3d86f1a1013d383d2630e1b16c5f162d6/bot/helper/ext_utils/bot_utils.py#L128

bot giving error sometimes

[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/8008326/log.txt)

this log has been taken before the latest commit

"Geo bypass not working anymore"

**Comment by anasty17** [comment]
@ghostmirrorlab Update ur repo ... already fixed

**Comment by ghostmirrorlab** [comment]
okay thx
