### ISSUE TITLE
Add support for tarmirror, tarwatch, qbit tar, etc

### ISSUE THREAD

**Issue by Strangelet07** [anasty17/mirror-leech-telegram-bot#378]
Zip is slow and uses a lot of resources and so provide an alternative like tar to mirror fastly pls

On HDD Extracting Time

.tar - 7zip 01:10sec Winrar 01:51sec
.zip - 7zip 02:02sec Winrar 02:08sec

On SDD Extracting Time

.tar - 7zip 11sec Winrar 11sec
.zip - 7zip 17sec Winrar 20sec

so .tar is really fast

Dark Desire (2022) S02 720p 10bit WEBRip HEVC [NF Hindi AAC 2.0 128Kbps] ~ (strange) PSA 2.55 GB (2,74,45,24,800 bytes)

**Comment by missemily2022** [comment]
Earlier Tar was there
But a lot of people wanted Zip as people were more acquainted to use it

So Tar was replaced with Zip

**Comment by missemily2022** [comment]
@Strangelet07 Yes it's possible to add both

**Comment by anasty17** [comment]
> Zip is slow and uses a lot of resources and so provide an alternative like tar to mirror fastly pls
> 
> On HDD Extracting Time
> 
> .tar - 7zip 01:10sec Winrar 01:51sec .zip - 7zip 02:02sec Winrar 02:08sec
> 
> On SDD Extracting Time
> 
> .tar - 7zip 11sec Winrar 11sec .zip - 7zip 17sec Winrar 20sec
> 
> so .tar is really fast
> 
> Dark Desire (2022) S02 720p 10bit WEBRip HEVC [NF Hindi AAC 2.0 128Kbps] ~ (strange) PSA 2.55 GB (2,74,45,24,800 bytes)

Compress rate is zero!
