### ISSUE TITLE
Automatically Bot was stopped

### ISSUE THREAD

**Issue by Selfie-bd** [anasty17/mirror-leech-telegram-bot#385]
I fork this repo . I didn't change anything in this repo. I didn't add upstream Repo. Bot running successfully. But suddenly Stop Working....

`Pleaze Fix This `   
            Or
 `say what happen`

**Comment by Selfie-bd** [comment]
`Run akhileshns/heroku-deploy@v3.12.12
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Successfully logged into heroku
Added git remote heroku
Setting CONFIG_FILE_URL and restarting ***... done, v11
received unexpected HTTP status: 500 Internal Server Error
 ▸    Error: docker push exited with Error: 1

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: heroku container:push web --app *** 
received unexpected HTTP status: 500 Internal Server Error
 ▸    Error: docker push exited with Error: 1

        
received unexpected HTTP status: 500 Internal Server Error
 ▸    Error: docker push exited with Error: 1
Error: Error: Command failed: heroku container:push web --app *** 
received unexpected HTTP status: 500 Internal Server Error
 ▸    Error: docker push exited with Error: 1`

**Comment by anasty17** [comment]
Before deploying u need to fetch and merge... and don't rerun old workflow

**Comment by Selfie-bd** [comment]
I fork your repo today only

They are no fetch and merge

**Comment by Selfie-bd** [comment]
Same problem

**Comment by anasty17** [comment]
Readme is the solution

**Comment by Selfie-bd** [comment]
Ok

**Comment by Selfie-bd** [comment]
> Readme is the solution

Where?
