### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Selfie-bd** [anasty17/mirror-leech-telegram-bot#390]
![Screenshot_2022-02-10-12-14-35-324_org telegram messenger](https://user-images.githubusercontent.com/83945969/153352324-82ec16c2-52a5-4182-9108-5b8dc12ed045.jpg)

![Screenshot_2022-02-10-12-14-26-224_com opera browser](https://user-images.githubusercontent.com/83945969/153352350-1970fd21-8dbc-4f06-9110-d7b432cefc05.jpg)

### **Deploy Manually Complete 👍 but bot not Work**

**Comment by anasty17** [comment]
Readme

**Comment by Selfie-bd** [comment]
> Bro, really looking at github Repos first time!?

Bro I know. he say repeatedly `see readme` i deleted entire repo and fork new and I didn't change anything or i didn't give upstream Repo. I deploy Manually. 1st time deploy done. But stopped.🤧

**Comment by anasty17** [comment]
> > Bro, really looking at github Repos first time!?
> 
> Bro I know. he say repeatedly `see readme` i deleted entire repo and fork new and I didn't change anything or i didn't give upstream Repo. I deploy Manually. 1st time deploy done. But stopped.🤧

What about heroku guide ? I must write the notes that i already wrote them in readme for everyone ?

**Comment by anasty17** [comment]
Next time will block u from github:)

**Comment by Selfie-bd** [comment]
> Next time will block u from github:)

**What**
