### ISSUE TITLE
facing issue while unzipping files

### ISSUE THREAD

**Issue by geraltnooob** [anasty17/mirror-leech-telegram-bot#412]
<img width="1001" alt="Screenshot 2022-02-28 at 6 41 22 PM" src="https://user-images.githubusercontent.com/88482834/155989083-19fbe584-e044-4780-847e-b952d5cda683.png">

i am not able to extract zip files

**Comment by anasty17** [comment]
Try now

**Comment by anasty17** [comment]
Useless logs btw ... when u want to send log ... send full log

**Comment by geraltnooob** [comment]
[vamshixxx-logs-1646104562280.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/8158515/vamshixxx-logs-1646104562280.txt)

Sorry about that , I am getting this kind of error , I unzipped another file it worked but it didn't work for this

**Comment by anasty17** [comment]
@geraltnooob Update ur repo !
If u didn't add UPSTREAM_REPO and u r using heroku branch ... then restart dyno ... if added UPSTREAM_REPO then update ur UPSTREAM_REPO to last commit
