### ISSUE TITLE
[FEATURE REQUEST] Download files from direct link like gdrive and then make the bot seed it as torrent.

### ISSUE THREAD

**Issue by pikkemanden** [anasty17/mirror-leech-telegram-bot#413]
So basically, a new feature where you can let the bot download the files from gdrive to the harddrive of the bot instead of deleting it, and then when you do /qbmirror {magnet link} it will then start seeding instead of download again. This would be very helpful for private trackers

**Comment by anasty17** [comment]
@pikkemanden Not a seed bot

**Comment by pikkemanden** [comment]
> @pikkemanden Not a seed bot

But it could be possible to do?

**Comment by anasty17** [comment]
@pikkemanden Yes possible but this mirror bot .. not seed bot .. minimal feature to seed downloaded torrent only .. to avoid ratio problem if u r downloading from private trackers

**Comment by pikkemanden** [comment]
If it is minimal feature why dont you add it? Alot of people here could really need it.

**Comment by anasty17** [comment]
Already added what i said minimal features!!!
