### ISSUE TITLE
Error: Command failed: heroku container:push web --app *** 

### ISSUE THREAD

**Issue by gdsday** [anasty17/mirror-leech-telegram-bot#42]
![image](https://user-images.githubusercontent.com/94415630/142970046-77a37e18-d18d-45c7-b191-f5ef52377922.png)
I'm too bad with this. Fork-> Ran with heroku workflow-> this error. Any advice?

**Comment by anasty17** [comment]
@gdsday Wtf

**Comment by anasty17** [comment]
@anasty17

**Comment by anasty17** [comment]
![20211123_061338](https://user-images.githubusercontent.com/77075674/142970316-4bb2a832-068c-4f33-ba45-5363427e49d0.jpg)
This cmd not in my docker please wake up

**Comment by gdsday** [comment]
ohshet mybad sorry, just redo the bot the sixth in the day

**Comment by anasty17** [comment]
Refork and try

**Comment by anasty17** [comment]
Done ? Something was wrong and already fixed just delete ur fork and fork again

**Comment by gdsday** [comment]
yes, will updated after few minutes, thank you:)

**Comment by gdsday** [comment]
yes, the error is gone. Thanks for the fix:)

**Comment by anasty17** [comment]
@gdsday Thank u
