### ISSUE TITLE
Google's OAuth 2.0: Error 400: invalid_request

### ISSUE THREAD

**Issue by se7h0220** [anasty17/mirror-leech-telegram-bot#422]
I already created 2 mirror bot last day ago with no problem, but now I can't create anymore. The error always pops up like this.

```
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
Request Details
The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
If you’re the app developer, make sure that these request details comply with Google policies.
redirect_uri: urn:ietf:wg:oauth:2.0:oob
```

Every time I run the command "python3 generate_drive_token.py" to get authentication, the error always pops up.

**Comment by anasty17** [comment]
Not code issue idk what u done

**Comment by param1903** [comment]
Yes, I am also facing the same, don't know what's the issue

**Comment by anasty17** [comment]
@param1903 Ok already fixed but didn't push yet

**Comment by param1903** [comment]
> @param1903 Ok already fixed but didn't push yet

Thank you for the prompt fix

**Comment by Manssizz** [comment]
error found on `add_to_team_drive.py` too
![image](https://user-images.githubusercontent.com/23637327/170827578-9611f876-4018-4e7d-b6e1-b6fdb846a392.png)
