### ISSUE TITLE
How to auto leech rss? RSS_COMMAND = "/qbleech" does do nothing?

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#425]
Hi,

İn `RSS_COMMAND` field I tried `/qbleech` or `qbleech` tried /qbmirror too
but it didn't work?
it does send the command successfully like this
`/qbleech https://nyaa.si/download/1498676.torrent`
 but the problem is that the bot doesn't start auto downloading the bot does nothing?

**Comment by anasty17** [comment]
Cz u don't read well

**Comment by erickyun** [comment]
> Cz u don't read well

Could please tell me 
if it is possible to auto leech or mirror rss?
And if yes, could you tell me how?

**Comment by anasty17** [comment]
Already said in readme u want me to copy paste from readme?

**Comment by erickyun** [comment]
> Already said in readme u want me to copy paste from readme?

☹️
I did read it
did add RSS_COMMAND RSS_CHAT_ID USER_STRING_SESSION but it isn't working? I'm noob and my english isn't sufficient I think maybe I dont understand everything or I'm missing something I would really appreciate it if you could show me what I'm missing?

**Comment by erickyun** [comment]
> Already said in readme u want me to copy paste from readme?

yes please

I did read it
did add RSS_COMMAND RSS_CHAT_ID USER_STRING_SESSION but it isn't working? Do I need cronjob or something I don't understand my english isn't sufficient I think maybe I'm missing something or doing something wrong I would really appreciate it if you could tell me what I'm missing?
