### ISSUE TITLE
it doesnt work anymore

### ISSUE THREAD

**Issue by martindilller** [anasty17/mirror-leech-telegram-bot#427]
HttpError 403 when requesting https://www.googleapis.com/upload/drive/v3/files?supportsTeamDrives=true&alt=json&uploadType=resumable returned "Insufficient permissions for the specified parent.". Details: "[{'domain': 'global', 'reason': 'insufficientParentPermissions', 'message': 'Insufficient permissions for the specified parent.'}]"

**Comment by jm1002dev** [comment]
it's working fine for us. check your team drive cause either it's deleted or your account doesn't have access to team drive
