### ISSUE TITLE
Uploading failed - File not found

### ISSUE THREAD

**Issue by soheilkhanalipur** [anasty17/mirror-leech-telegram-bot#433]
HttpError 404 when requesting None returned "File not found: 0AFQSmLEVjAspUk9PVA.". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: 0AFQSmLEVjAspUk9PVA.', 'locationType': 'parameter', 'location': 'fileId'}]"

**Comment by soheilkhanalipur** [comment]
@anasty17 ???????

**Comment by Coolboyrajat** [comment]
Please read the description (The owner makes a huge effort to put every single detail possible in words and video), If you are not a coder please not try the stuff. This is not the issue you are not following the Steps Properly Watch again you know where you have gone wrong.

Rest the error is simple ... but the reason not to tell the solution is you are not a coder

**Comment by Coolboyrajat** [comment]
> HttpError 404 when requesting None returned "File not found: 0AFQSmLEVjAspUk9PVA.". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: 0AFQSmLEVjAspUk9PVA.', 'locationType': 'parameter', 'location': 'fileId'}]"

Please read the description (The owner makes a huge effort to put every single detail possible in words and video), If you are not a coder please not try the stuff. This is not the issue you are not following the Steps Properly Watch again you know where you have gone wrong.

Rest the error is simple ... but the reason not to tell the solution is you are not a coder
