### ISSUE TITLE
Requesting a new feature 

### ISSUE THREAD

**Issue by DevilStyle** [anasty17/mirror-leech-telegram-bot#446]
Hello, finally I managed to make the bot work, I wanted to ask you if it is possible to add the upload on 1fichier for premium users, I find a very fast and stable host, then I wanted to ask you another thing about 1fichier.com, when you download something with the bot, unfortunately if you want to download another file from 1fichier.com it is not possible because there is the limit,  is there a way to bypass this thing? Thank you very much for your work

**Comment by anasty17** [comment]
No
