### ISSUE TITLE
Feature request: queue system for telegram files

### ISSUE THREAD

**Issue by sunilroyy007** [anasty17/mirror-leech-telegram-bot#45]
When we mirror Telegram files it should download certain limit of videos until those are finished others should be in queue. Just like how we keep limit on aria2 concurrent download

Example: if we mirror 10 Telegram files 5 should download simultaneously and remaining will be in queue

**Comment by lokomartin** [comment]
When using qBittorrent command like /qbleech or /qbmirror dont have queue system yet.

**Comment by anasty17** [comment]
@lokomartin Check qbittorrent folder in repo and enable it in qbittorrent config

**Comment by lokomartin** [comment]
@anasty17 Thank you.

**Comment by anasty17** [comment]
> When we mirror Telegram files it should download certain limit of videos until those are finished others should be in queue. Just like how we keep limit on aria2 concurrent download
> 
> Example: if we mirror 10 Telegram files 5 should download simultaneously and remaining will be in queue

Download 5 by 5 easier for me

**Comment by sunilroyy007** [comment]
> > When we mirror Telegram files it should download certain limit of videos until those are finished others should be in queue. Just like how we keep limit on aria2 concurrent download
> > Example: if we mirror 10 Telegram files 5 should download simultaneously and remaining will be in queue
> 
> Download 5 by 5 easier for me

I was trying to mirror lot of files from a channel using userbot by forwarding them to mirrorbot.  I turned on bot at night and came at morning and It handled 400 files without restarting but it gave error to almost all files only 50 files got mirroed. So i thought it would be good to keep a queue system to avoid this type of problem.

Ps: I cant find those drive or index links anywhere so mirroring tg files. Some of the links are expired and some are non existent

**Comment by anasty17** [comment]
@sunilroyy007 How to ignore this guy ?

**Comment by sunilroyy007** [comment]
> @sunilroyy007 How to ignore this guy ?

What?

**Comment by okAxL** [comment]
@sunilroyy007 bruh, your request is in queue

**Comment by sunilroyy007** [comment]
> @sunilroyy007 bruh, your request is in queue

How can i know that? I was just replying to his comment
