### ISSUE TITLE
Instead of Delete as Command can it be a button 

### ISSUE THREAD

**Issue by Coolboyrajat** [anasty17/mirror-leech-telegram-bot#454]
Instead of copying link and pasting after the `/del` command can we have a additional button just like "`VIEW_LINK`" in the gist used only by Sudo user.

**Comment by anasty17** [comment]
Wrong press will delete some files or folders by wrong

**Comment by Coolboyrajat** [comment]
> Wrong press will delete some files or folders

OK ... but we can restore it from `TRASH` if it happen by mistake.

So let do this way keep the `/del` cmd and add a new var just like `VIEW_LINK` , `DELETE_LINK` = `BOOLEAN`
💡
