### ISSUE TITLE
Requesting new feature

### ISSUE THREAD

**Issue by tania010** [anasty17/mirror-leech-telegram-bot#461]
Would it be possible to add support for Open Directories?
I know it's possible to download with direct links but a show with multiple seasons can have hundreds of episodes/direct links, a link scrapper can be used to get all the direct links first but then the folder structure would be lost.

example link: http://167.114.174.132:9092/series/Flash/ 
ideally, the bot would create the top folder as "Flash" and add all the subfolders (seasons) under/inside that folder

**Comment by anasty17** [comment]
Rarely to use, i will not work on this thing. U r the first one asked for this

**Comment by Zylern** [comment]
Yeah it will be useful feature i donot think any other leech repo have this feature :)
Please work on it bro
