### ISSUE TITLE
How can I open rss?

### ISSUE THREAD

**Issue by ShZDr** [anasty17/mirror-leech-telegram-bot#464]
I opened rss in the bot, but it does not respond to rss commands.

Config:
# REQUIRED CONFIG
BOT_TOKEN = "Private"
GDRIVE_FOLDER_ID = "Private"
OWNER_ID = 5231863820
DOWNLOAD_DIR = "/usr/src/app/downloads"
DOWNLOAD_STATUS_UPDATE_INTERVAL = 10
AUTO_DELETE_MESSAGE_DURATION = 20
IS_TEAM_DRIVE = "True"
TELEGRAM_API = Private
TELEGRAM_HASH = "Private"
# OPTIONAL CONFIG
DATABASE_URL = ""
AUTHORIZED_CHATS = "Private"
SUDO_USERS = "Private"
IGNORE_PENDING_REQUESTS = ""
USE_SERVICE_ACCOUNTS = "True"
INDEX_URL = ""
STATUS_LIMIT = "4"
STOP_DUPLICATE = "True"
CMD_INDEX = ""
UPTOBOX_TOKEN = ""
# Update
UPSTREAM_REPO = "https://github.com/anasty17/mirror-leech-telegram-bot"
UPSTREAM_BRANCH = ""
# Leech
TG_SPLIT_SIZE = ""
AS_DOCUMENT = ""
EQUAL_SPLITS = ""
CUSTOM_FILENAME = ""
# qBittorrent
BASE_URL_OF_BOT = "Private"
SERVER_PORT = ""
WEB_PINCODE = ""
QB_SEED = "True"
QB_TIMEOUT = ""
# Rss
RSS_DELAY = ""
RSS_COMMAND = "/rssget"
RSS_CHAT_ID = "-799058430"
USER_STRING_SESSION = ""
# Pivate Files
ACCOUNTS_ZIP_URL = ""
TOKEN_PICKLE_URL = ""
MULTI_SEARCH_URL = ""
YT_COOKIES_URL = ""
NETRC_URL = ""
# Mega
MEGA_API_KEY = ""
MEGA_EMAIL_ID = ""
MEGA_PASSWORD = ""
BLOCK_MEGA_FOLDER = ""
BLOCK_MEGA_LINKS = ""
# Shortener
SHORTENER = ""
SHORTENER_API = ""
# GDTOT COOKIE
CRYPT = ""
# Size Limits
TORRENT_DIRECT_LIMIT = ""
ZIP_UNZIP_LIMIT = ""
CLONE_LIMIT = ""
MEGA_LIMIT = ""
STORAGE_THRESHOLD = ""
# Buttons
VIEW_LINK = "True"
BUTTON_FOUR_NAME = ""
BUTTON_FOUR_URL = ""
BUTTON_FIVE_NAME = ""
BUTTON_FIVE_URL = ""
BUTTON_SIX_NAME = ""
BUTTON_SIX_URL = ""
# Torrent Search
SEARCH_API_LINK = ""
SEARCH_PLUGINS = '["https://raw.githubusercontent.com/qbittorrent/search-plugins/master/nova3/engines/rarbg.py",
                   "https://raw.githubusercontent.com/qbittorrent/search-plugins/master/nova3/engines/piratebay.py",
                   "https://raw.githubusercontent.com/qbittorrent/search-plugins/master/nova3/engines/legittorrents.py",
                   "https://raw.githubusercontent.com/qbittorrent/search-plugins/master/nova3/engines/limetorrents.py",
                   "https://raw.githubusercontent.com/qbittorrent/search-plugins/master/nova3/engines/torrentscsv.py",
                   "https://raw.githubusercontent.com/qbittorrent/search-plugins/master/nova3/engines/zooqle.py",
                   "https://raw.githubusercontent.com/qbittorrent/search-plugins/master/nova3/engines/eztv.py",
                   "https://raw.githubusercontent.com/MaurizioRicci/qBittorrent_search_engines/master/kickass_torrent.py",
                   "https://raw.githubusercontent.com/MaurizioRicci/qBittorrent_search_engines/master/yts_am.py",
                   "https://raw.githubusercontent.com/MadeOfMagicAndWires/qBit-plugins/master/engines/linuxtracker.py",
                   "https://raw.githubusercontent.com/MadeOfMagicAndWires/qBit-plugins/master/engines/nyaasi.py",
                   "https://raw.githubusercontent.com/LightDestory/qBittorrent-Search-Plugins/master/src/engines/ettv.py",
                   "https://raw.githubusercontent.com/LightDestory/qBittorrent-Search-Plugins/master/src/engines/glotorrents.py",
                   "https://raw.githubusercontent.com/LightDestory/qBittorrent-Search-Plugins/master/src/engines/thepiratebay.py",
                   "https://raw.githubusercontent.com/nindogo/qbtSearchScripts/master/magnetdl.py",
                   "https://raw.githubusercontent.com/khensolomon/leyts/master/yts.py"]'

**Comment by anasty17** [comment]
1. Wrong rss cmd 
2.  U need to user string session or add bot to a channel then adding channel to group as written in readme rss notes under rss variables description
