### ISSUE TITLE
/rsslist "ERROR - Message is too long" and rss feed notifying issue?

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#470]
Hi,

I have two problems the first problem I am having is
 

### 1-

I'm getting no response when I try /rsslist

log says `2022-04-03 20:18:01,809 - bot - ERROR - Message is too long`

### 2-

The other problem I'm facing with rss is,
when new torrent is added to the subscribed rss feed I follow.
 The bot will send me not only message from the new added torrent but it also sends/notifies me from the previous added torrent.

Example I follow torrent.site/xxxChannel 
When xxxChannel uploads 1 new torrent 
The bot does not only notify me the new added torrent but it also sends me the previous added torrent! 
until I make the bot stop working (removing with rssunsub) otherwise it wont stop notifying!

**Comment by anasty17** [comment]
Hi
Regarding first problem tell me how much rss links u have subscribed 
2nd i hope u r up to date ... cz this problem will be faced with all users not only u ... can u please send this rss link .. which is sending the Torrent twice

**Comment by erickyun** [comment]
I'm subscribed to 57 rss.

I'm up to date also it isn't happening for only a specific rss link twice it happens on every rss link.

[subscribed rss link](https://bin.disroot.org/?bf8bf5bab0b0ab98#3y53hfkvsnFVVUPxf5CFWWWVZbj6mjGVhZsFv8XgSX3q)

I noticed that this problem only happens
When I have 53-53 subscribed rss! when I have 53 subs I am not facing both problems there is no issue but 57 subs there is?

**Comment by erickyun** [comment]
I did try to deploy again and there seems to be no problem right now? weird? 
Sorry for the disturbance and thank you for your response I'm closing this issue I hope I won't face the same problem again.

**Comment by anasty17** [comment]
Maybe bcz some rss have common links .. like 2 rss from nyaa regarding 1st problem.. this bcz too much rss in ome msg .. i didn't expect that someone will add this number of rss

**Comment by erickyun** [comment]
> Maybe bcz some rss have common links .. like 2 rss from nyaa regarding 1st problem.. this bcz too much rss in ome msg .. i didn't expect that someone will add this number of rss

So could we say there is a limit which we shouldn't exceed? cuz one less rss there wasn't any problem

**Comment by anasty17** [comment]
Depending on much bytes in message ... each letter is 1 byte ... limit is 4096 byte

**Comment by erickyun** [comment]
> Depending on how much bytes in message ... each letter is 1 byte ... limit is 4096 byte for 1 message

Could you not make the bot split the message in two (a separate message) before it exceeds the limit 4096 byte for 1 message?

Because it seems like a bug the will work normal if it not exceeds the limit?( if I won't exceed the byte limit the bot won't give me the issues I did talk about above it work normal)

**Comment by erickyun** [comment]
> Depending on how much bytes in message ... each letter is 1 byte ... limit is 4096 byte for 1 message

@anasty17 

Could you not make the bot split the message in two (a separate message) before it exceeds the limit 4096 byte for 1 message?

Because it seems like a bug the bot will work normal if it not exceeds the limit?( if I won't exceed the byte limit the bot won't give me the issues I did talk about above! it works normal!)

**Comment by anasty17** [comment]
> > Depending on how much bytes in message ... each letter is 1 byte ... limit is 4096 byte for 1 message
> 
> @anasty17
> 
> Could you not make the bot split the message in two (a separate message) before it exceeds the limit 4096 byte for 1 message?
> 
> Because it seems like a bug the bot will work normal if it not exceeds the limit?( if I won't exceed the byte limit the bot won't give me the issues I did talk about above! it works normal!)

It's not a bug ... but u have added too much rss links.. i will do nothing for this issue
