### ISSUE TITLE
Error: Error: Command failed: heroku create *** --region us --stack container

### ISSUE THREAD

**Issue by SuperRem25** [anasty17/mirror-leech-telegram-bot#480]
![error](https://user-images.githubusercontent.com/80263758/162560910-7d2fb954-a678-499f-b123-4d04a63515d6.png)

help....

**Comment by OAJJAIN** [comment]
Deploy on heroku. Okteto speed is slow, shortage low and bot sleeps after 24hrs

**Comment by SuperRem25** [comment]
> Deploy on heroku. Okteto speed is slow, shortage low and bot sleeps after 24hrs

Yeah was trying to, i was manually deploying it and this happened. (while watching the tutorial recommended by the devs) OR do you mean by deploying it by connecting my github account then choosing my local repo of the bot and then deploying it directly in heroku's website, then yeah already did that but the bot didn't start.

**Comment by anasty17** [comment]
> > Deploy on heroku. Okteto speed is slow, shortage low and bot sleeps after 24hrs
> 
> Yeah was trying to, i was manually deploying it (in github, action section) and this happened. (while watching the tutorial recommended by the devs) OR do you mean by deploying it by connecting my github account then choosing my local repo of the bot and then deploying it directly in heroku's website, then yeah already did that but the bot didn't start.

Already mentioned in readme! Don't deploy from browser or from hmanager

**Comment by anasty17** [comment]
> ![error](https://user-images.githubusercontent.com/80263758/162560910-7d2fb954-a678-499f-b123-4d04a63515d6.png)
> 
> help....

Read the error! Fix ur vars
