### ISSUE TITLE
Bot unresponsive after CLI deployment

### ISSUE THREAD

**Issue by SuperRem25** [anasty17/mirror-leech-telegram-bot#483]
![err](https://user-images.githubusercontent.com/80263758/162595423-0651c655-1ff1-40c2-8f26-6ce7a5c197aa.png)

**Comment by anasty17** [comment]
How i can know what u have done !

**Comment by SuperRem25** [comment]
> How i can know what u have done !

What should I show you?

**Comment by anasty17** [comment]
I need to know if u read readme well or not

**Comment by SuperRem25** [comment]
> I need to know if u read readme well or not

Yep. The reason I didn't know it must be deployed thru CLI and not in hmanager or in any browser is because i follwed the deployment video very very closely. (in the vid, they deployed it through github workflow in a browser). Should I just 'redo' all of this instead?

**Comment by anasty17** [comment]
Omg u can with workflow or cli ... i meant from browser that auth github with heroku and importing the repo to build from heroku site ... u can with workflow but u didn't read well

**Comment by SuperRem25** [comment]
> Omg u can with workflow or cli ... i meant from browser that auth github with heroku and importing the repo to build from heroku site ... u can with workflow but u didn't read well 

The workflow didn't properly worked (already read the readme and did the necessary stuff) so I tried the cli and it did work. Nevermind then, I'll redo it.
