### ISSUE TITLE
Index link Missing in telegraph

### ISSUE THREAD

**Issue by akashsinghyadav** [anasty17/mirror-leech-telegram-bot#502]
![Screenshot_20220420-183924](https://user-images.githubusercontent.com/11516692/164237818-a55947d7-d01b-46b4-b73e-792145ea6642.jpg)
In telegraph (after using list cmd and if in case file already exist) the index link is missing. Only drive link is being provided

**Comment by anasty17** [comment]
Fill correct index link. Check readme
