### ISSUE TITLE
[Feature Request] Add folder id for each RSS subscribed feed

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#505]
Hi,

I have request if you like the idea ofcourse.

Could you add extra feature to specify folder id for each `rss subscribed feed` to upload all the mirrors to specified folder id.

Example: /rsssub rssfeed Folderİd

Or maybe a feature where we can specify which `folder id` we want to upload with /qbmirror

Example: /qbmirror magnettorrent folderid

Which feature would be easy for you to implement I don't know but I would really appreciate it if you could add the first one please to make everything automatically.

**Comment by anasty17** [comment]
Not planning to add this, I'm planning to add feature which each user can choose the upload destination, if u r using channel then u can set folder id for channel
