### ISSUE TITLE
The megarest is not found

### ISSUE THREAD

**Issue by Biditmangal** [anasty17/mirror-leech-telegram-bot#509]
![image](https://user-images.githubusercontent.com/39191019/165042449-27a18fdd-e33e-4e81-aab1-b612ef2e3840.png)

**Comment by berry8838** [comment]
Hello, friend, after I retart, I also encountered such a problem, then I run "pip install megasdkrestclient", but I still report the error  "from megasdkrestclient import MegaSdkRestClient, errors as mega_err
ModuleNotFoundError: No module named 'megasdkrestclient'",
How do you solve it? Is it convenient to reply?
