### ISSUE TITLE
youtube problem

### ISSUE THREAD

**Issue by yadianluffy** [anasty17/mirror-leech-telegram-bot#52]
Suppose I want to download a YouTube playlist that list contains 25 videos of which 3 are private and 2 are infringing YouTube's terms, what I want is for the bot instead of canceling the complete download, exclude those 5 bad videos and download the 20 others that are public is just an idea thanks

error 1 example 
@Taku_but_tactical your download has been stopped due to: ERROR: [youtube] ipQX6Sas3h4: Video unavailable. This video is no longer available due to a copyright claim by TOEI ANIMATION CO.,LTD.

error 2 example
@Taku_but_tactical your download has been stopped due to: ERROR: [youtube] TC--PUel42s: Video unavailable. This video contains content from Marvelous Inc., who has blocked it on copyright grounds.

_Originally posted by @yadianluffy in https://github.com/anasty17/mirror-leech-telegram-bot/discussions/51_

**Comment by anasty17** [comment]
@yadianluffy Send links

**Comment by anasty17** [comment]
![20211123_225353](https://user-images.githubusercontent.com/77075674/143116699-1f8fd3b6-fc15-49c7-a2ec-63066e386997.jpg)
I have already added skip for 10 errors

**Comment by anasty17** [comment]
skip_playlist_after_errors: Number of allowed failures until the rest of  the playlist is skipped

**Comment by yadianluffy** [comment]
increase that value from 10 to 50 but you still have the same problem
I send you the log of the bot?

**Comment by yadianluffy** [comment]
> @yadianluffy Send links

https://www.youtube.com/playlist?list=PL9iXyZ7BC0plLlV-FQdpkUv0KaLyRwgmh

https://www.youtube.com/playlist?list=PLtqlNG1m9756OZKFOoaKHO7Ifn_Copjv2

https://www.youtube.com/playlist?list=PL490CD25236E0824B

**Comment by anasty17** [comment]
> > @anasty17 Send links
> 
> https://www.youtube.com/playlist?list=PL9iXyZ7BC0plLlV-FQdpkUv0KaLyRwgmh
> 
> https://www.youtube.com/playlist?list=PLtqlNG1m9756OZKFOoaKHO7Ifn_Copjv2
> 
> https://www.youtube.com/playlist?list=PL490CD25236E0824B

Done
