### ISSUE TITLE
ERROR - One important variable is missing. The README.md file of heroku branch

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#520]
Hi,

I'm getting this error bot crashes?
Could you help me please?

```
2022-04-27T01:24:06.095284+00:00 app[web.1]: 2022-04-27 01:24:06,095 - root - ERROR - One important variable is missing. The README.md file of heroku branch there to be read! Exiting now!
2022-04-27T01:24:06.133275+00:00 app[web.1]: /usr/bin/python3: No module named bot
2022-04-27T01:24:06.266933+00:00 heroku[web.1]: Process exited with status 1
2022-04-27T01:24:06.358382+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by anasty17** [comment]
The error written! Follow the error msg

**Comment by erickyun** [comment]
> The error written! Follow the error msg

But every variable is set ?
CONFIG_FILE_URL
HEROKU_EMAIL
HEROKU_API_KEY
HEROKU_APP_NAME

The worked fine until I just decided to update the bot?

**Comment by anasty17** [comment]
What error say ? Heroku branch readme! Check it

**Comment by erickyun** [comment]
Thank you for your reply @anasty17 but
I did follow heroku branch correctly but still got the error! I did try it like 3 times already but still error persist.

What worked for was that I did have a fork of your repo from yesterday I did try to deploy with that repo and it worked!

But todays updated repo doesn't work?

**Comment by anasty17** [comment]
U didn't read the notes in heroku branch readme... u r skiping the important notes then u say i follow the readme... no u r not without the notes

**Comment by NskTorrent** [comment]
I also can't figure out how to fix it. Please give detailed instructions. Redeploy has been executed. "UPSTREAM_REPO" also tried to register, but without success.

**Comment by erickyun** [comment]
> I also can't figure out how to fix it. Please give detailed instructions. Redeploy has been executed. "UPSTREAM_REPO" also tried to register, but without success.

Delete your repo, fork again add UPSTREAM_REPO and deploy.

**Comment by NskTorrent** [comment]
> > I also can't figure out how to fix it. Please give detailed instructions. Redeploy has been executed. "UPSTREAM_REPO" also tried to register, but without success.
> 
> Delete your repo, fork again add UPSTREAM_REPO and deploy.

Thank you for your feedback! I'm completely new to this topic. Do I understand correctly that I need to delete all the contents of two branches - master and heroku? But then what about personal files ? Do they need to be temporarily saved and then returned? What value should the UPSTREAM_REPO variable have ? Thank you in advance for the detailed answer. If possible, please describe the procedure as for the child)))

**Comment by NskTorrent** [comment]
> > I also can't figure out how to fix it. Please give detailed instructions. Redeploy has been executed. "UPSTREAM_REPO" also tried to register, but without success.
> 
> Delete your repo, fork again add UPSTREAM_REPO and deploy.

Thank you very much! I went all the way from the beginning and realized where I was wrong )
