### ISSUE TITLE
rss feature completely broken

### ISSUE THREAD

**Issue by fortniteballs1** [anasty17/mirror-leech-telegram-bot#529]
its broken

**Comment by fortniteballs1** [comment]
2022-04-27 10:26:09,491 - bot - ERROR - Client has not been started yet: This is what it says in logs and just spam it

**Comment by erickyun** [comment]
> 2022-04-27 10:26:09,491 - bot - ERROR - Client has not been started yet: This is what it says in logs and just spam it

I'm also facing same problem.
`bot - ERROR - Client has not been started yet`

**Comment by anasty17** [comment]
Create new string session

**Comment by anasty17** [comment]
Will try as soon as possible if the issue from pyrogram version difference

**Comment by anasty17** [comment]
Pyrogram v2 required to generate user string session... script for generate has been updated

**Comment by erickyun** [comment]
I did just try and I'm getting this error?

````
line 5, in <module>
    with Client(api_id=API_KEY, api_hash=API_HASH, in_memory=True) as app:
TypeError: Client.__init__() got an unexpected keyword argument 'in_memory'
```

**Comment by erickyun** [comment]
I did just try it and I'm receiving this error?

```
line 5, in <module>
    with Client(api_id=API_KEY, api_hash=API_HASH, in_memory=True) as app:
TypeError: Client.__init__() missing 1 required positional argument: 'name'
