### ISSUE TITLE
#help

### ISSUE THREAD

**Issue by yadianluffy** [anasty17/mirror-leech-telegram-bot#53]
I have already tried in many ways and I could not make SEARCH_API_LINK work for me
a little help would not hurt if it is not a nuisance

https://searcherluffy.herokuapp.com/
![Captura de pantalla (3)](https://user-images.githubusercontent.com/88897873/143155576-6b3a0f3d-facc-47c5-9610-396a23f3ef0d.png)

**Comment by anasty17** [comment]
Read var description in readme

**Comment by anasty17** [comment]
Or donate your eyes
