### ISSUE TITLE
generate_string_session.py missing 1 required positional argument: 'name'

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#531]
@anasty17 

I did just try generate_string_session.py and I'm receiving this error? After entering API HASH.

```
line 5, in <module>
    with Client(api_id=API_KEY, api_hash=API_HASH, in_memory=True) as app:
TypeError: Client.__init__() missing 1 required positional argument: 'name'

**Comment by fortniteballs1** [comment]
![image](https://user-images.githubusercontent.com/104302437/165602221-fc7610d4-726b-4c78-83da-b63c3641df9c.png)
i got the same issue

**Comment by anasty17** [comment]
Ohh ok

**Comment by anasty17** [comment]
Fixed
