### ISSUE TITLE
Help me with all types of Link i tried

### ISSUE THREAD

**Issue by world-inside-the-pc** [anasty17/mirror-leech-telegram-bot#539]
HttpError 404 when requesting None returned "File not found: 0ABsclVb6UpDFUk9PVA.". Details: "[{'domain': 'global', 'reason': 'notFound', 'message': 'File not found: 0ABsclVb6UpDFUk9PVA.', 'locationType': 'parameter', 'location': 'fileId'}]"
I even tried restarting the bot it did not work

**Comment by anasty17** [comment]
U r td gone
