### ISSUE TITLE
[Action Required] Migrate your OAuth out-of-band flow to an alternative method before Oct. 3, 2022

### ISSUE THREAD

**Issue by nodirhajiev** [anasty17/mirror-leech-telegram-bot#549]
![Screenshot_2022-05-04-13-08-28-960_com.google.android.gm.jpg](https://user-images.githubusercontent.com/38133441/166646731-d979c730-9f1e-413c-bbc2-270624102f49.jpg)

Hi. Sorry for out of topic. Did someone get mail like this? After 6 months, google will block developer project?

**Comment by anasty17** [comment]
We already change the token.pickle generation method from 5 march i guess. Ignore.

**Comment by akshzyx** [comment]
How do I chnage it tho, how do I use new token.pickle generation method, I don't know much about it.
