### ISSUE TITLE
Add cutt.ly Shortener support 

### ISSUE THREAD

**Issue by Monster-ZeroX** [anasty17/mirror-leech-telegram-bot#553]
Please add https://cutt.ly/ URL Shortener, They give unlimited shorts, so it will be really helpful for anyone.

**Comment by anasty17** [comment]
@junedkh

**Comment by missemily2022** [comment]
![image](https://user-images.githubusercontent.com/97376138/166885933-e12b73fc-0f05-439b-b733-704effaaff3e.png)
@anasty17 @junedkh I think this should help in adding the Shortener

**Comment by dickymuliafiqri** [comment]
https://cleanuri.com/docs

Simple and clean, and ofc free to use.
no need account, just api.

**Comment by nodirhajiev** [comment]
Hi. Have a question ⁉️ How to make a direct link with cutt.ly after mirroring automatically. For example: View link, Drive link, Direct links are generated with shorts

**Comment by dickymuliafiqri** [comment]
> 

Hi, i have made a module to shorten a given link.
Source: https://github.com/dickymuliafiqri/shylook-mltb/blob/master/bot/modules/shorten.py
PR: https://github.com/anasty17/mirror-leech-telegram-bot/pull/564

But it seems Anas was expect something else, anyway you can read my code as reference to achieve your needs.
