### ISSUE TITLE
PM bot and leech-mirror log support

### ISSUE THREAD

**Issue by weebmedico01** [anasty17/mirror-leech-telegram-bot#557]
add PM bot and leech-mirror log support

just like in this repo https://github.com/arshsisodiya/helios-mirror

**Comment by anasty17** [comment]
Simply use that repo!

**Comment by weebmedico01** [comment]
> Simply use that repo!

maa chuda bsdsk chote mote update hi deta rhiyo tu repo m tere bska h bhi ni add krna pm aur leech log isme slammirror ka hi utha rkha repo tune
