### ISSUE TITLE
accounts gets suspended.

### ISSUE THREAD

**Issue by rex6942** [anasty17/mirror-leech-telegram-bot#558]
heroku account that i had been using for 3-4 weeks got suspended today, made another one to deploy bot to, deployed, but after a few minutes of usage that got suspended too, any way around this?

**Comment by nodirhajiev** [comment]
Same as your situation, bro. How to fix it?

**Comment by rex6942** [comment]
hey, why'd you close this? and for refrence, this was the email i got
![Capture](https://user-images.githubusercontent.com/104386228/167241669-0f466414-90fc-4228-a7aa-9f81b45e40fc.PNG)
