### ISSUE TITLE
All Bots get Banned and Suspended on Heroku 😢

### ISSUE THREAD

**Issue by feronot** [anasty17/mirror-leech-telegram-bot#559]
Hi, All Bots get Banned and Suspended on Heroku 
and when you deploy a new bot, it will be banned too
please help

**Comment by tania010** [comment]
heroku account just got banned too.

**Comment by AshishSharma2006** [comment]
My 6 Accounts Banned Please Help 😔🙏

**Comment by nodirhajiev** [comment]
> My 6 Accounts Banned Please Help 😔🙏

Did u add cc to verify heroku account?

**Comment by AshishSharma2006** [comment]
> > My 6 Accounts Banned Please Help 😔🙏
> 
> Did u add cc to verify heroku account?

no
