### ISSUE TITLE
Error mirroring files from mega.nz and google drive

### ISSUE THREAD

**Issue by nodirhajiev** [anasty17/mirror-leech-telegram-bot#568]
![image](https://user-images.githubusercontent.com/38133441/167416639-88299d18-f7f2-45cf-b6e0-6c16a60f2bfe.png)
 Files uploading correctly. But when uploading is finishes, there is no success message

**Comment by anasty17** [comment]
If u enabled extra buttons then check if u didn't anything wrong 
If no then this error from filename

**Comment by nodirhajiev** [comment]
Found the error. It was cutt.ly api. It's not working. Other short apis are working

**Comment by junedkh** [comment]
@nodirhajiev dm me in telegram
