### ISSUE TITLE
Gdrive upload not working

### ISSUE THREAD

**Issue by WhiteWalker02** [anasty17/mirror-leech-telegram-bot#57]
Deployed your repo tried both CLI and git workflow but couldn't get gdrive upload working. Tried uploading token.pickle file to cloud to get link which was then added to token.pickle field in config.env, also tried uploding same to git and the deploying it using git workflow but still no good. Need help to get gdrive upload working, Its throwing error and I am unable to determine what's the problem here.

**Comment by anasty17** [comment]
@WhiteWalker02 Maybe ur token.pickle Corrupted

**Comment by WhiteWalker02** [comment]
Does it work if we upload it to git (credentials.json and token.pickle) and run the workflow? Also, why it does not work if I import your repo?

**Comment by anasty17** [comment]
@WhiteWalker02 Look i made this heroku branch before 2 hours from making the repo public didn't test all case at first ... now if you r up to date ... yeah it will work without adding token.pickle or account.zip url in config.env and by adding them to repository directly but u shouldn't delete .gitignore file this the only thing will keep ur private data restart
