### ISSUE TITLE
Deployment without Docker 

### ISSUE THREAD

**Issue by pr13260** [anasty17/mirror-leech-telegram-bot#573]
I wanted to Ask if there is a way to do it without docker 
Yeah it would be lengthy but it would work 

Thanks in advance:D

**Comment by junedkh** [comment]
What issue with docker?

**Comment by missemily2022** [comment]
@junedkh I think he is worried about Suspension on Heroku

**Comment by pr13260** [comment]
> What issue with docker?

Why not try without docker ?

**Comment by pr13260** [comment]
> @junedkh I think he is worried about Suspension on Heroku
> 

Na i just wanna try without docker

**Comment by anasty17** [comment]
Follow docker and google
