### ISSUE TITLE
vps deploy error

### ISSUE THREAD

**Issue by AJ-dev9921** [anasty17/mirror-leech-telegram-bot#586]
app_1  | 2022-05-16 03:02:09,195 - root - INFO - Successfully updated with latest commit from UPSTREAM_REPO
app_1  | [2022-05-16 03:02:10 +0000] [29] [INFO] Starting gunicorn 20.1.0
app_1  | [2022-05-16 03:02:10 +0000] [29] [INFO] Listening at: http://0.0.0.0:80 (29)
app_1  | [2022-05-16 03:02:10 +0000] [29] [INFO] Using worker: sync
app_1  | [2022-05-16 03:02:10 +0000] [51] [INFO] Booting worker with pid: 51
app_1  | 2022-05-16 03:02:12,678 - bot - INFO - Generating BOT_STRING_SESSION
app_1  | 2022-05-16 03:02:12,679 - root - INFO - Initializing Aria2c
app_1  | 2022-05-16 03:02:18,306 - bot - INFO - Creating TELEGRAPH Account using  'pteNhIzJ' name
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
app_1  |     return _run_code(code, main_globals, None,
app_1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
app_1  |     exec(code, run_globals)
app_1  |   File "/usr/src/app/bot/__main__.py", line 21, in <module>
app_1  |     from .modules import authorize, list, cancel_mirror, mirror_status, mirror, clone, watch, shell, eval, delete, count, leech_settings, search, rss
app_1  |   File "/usr/src/app/bot/modules/mirror.py", line 24, in <module>
app_1  |     from bot.helper.mirror_utils.download_utils.mega_downloader import add_mega_download
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/mega_downloader.py", line 5, in <module>
app_1  |     from mega import (MegaApi, MegaListener, MegaRequest, MegaTransfer, MegaError)
app_1  | ModuleNotFoundError: No module named 'mega'

**Comment by anasty17** [comment]
Update ur repo
