### ISSUE TITLE
Exec format error: 'qbittorrent-nox'

### ISSUE THREAD

**Issue by Ajayveer9911github** [anasty17/mirror-leech-telegram-bot#597]
#10 145.9 __import__(pkg_name)
#10 145.9 File "/maruf/mirror-leech-telegram-bot/bot/__init__.py", line 58, in <module>
#10 145.9 srun(["qbittorrent-nox", "-d", "--profile=."])
#10 145.9 File "/usr/lib/python3.8/subprocess.py", line 493, in run
#10 145.9 with Popen(*popenargs, **kwargs) as process:
#10 145.9 File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
#10 145.9 self._execute_child(args, executable, preexec_fn, close_fds,
#10 145.9 File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
#10 145.9 raise child_exception_type(errno_num, err_msg, err_filename)
#10 145.9 OSError: [Errno 8] Exec format error: 'qbittorrent-nox'------x Error b

**Comment by anasty17** [comment]
Fix will pushed in 15 min

**Comment by Ajayveer9911github** [comment]
> Fixed deploy again

Fixed..!
