### ISSUE TITLE
asyncio - WARNING - socket.send() raised exception

### ISSUE THREAD

**Issue by mohitjoshi155** [anasty17/mirror-leech-telegram-bot#598]
this error coming even on latest repo after this commit
https://github.com/anasty17/mirror-leech-telegram-bot/commit/589e8133d049e7ceaa5039b4079a324099d1c586

**Comment by Sunilthevan** [comment]
> this error coming even on latest repo after this commit [589e813](https://github.com/anasty17/mirror-leech-telegram-bot/commit/589e8133d049e7ceaa5039b4079a324099d1c586)

**Comment by Sunilthevan** [comment]
How to solve
