### ISSUE TITLE
No module named 'bencoding'

### ISSUE THREAD

**Issue by AJ-dev9921** [anasty17/mirror-leech-telegram-bot#604]
app_1  | [2022-05-21 01:50:01 +0000] [416] [INFO] Shutting down: Master
app_1  | warning: no common commits
app_1  | 2022-05-21 01:50:02,067 - root - INFO - Successfully updated with lates                                                                                        t commit from UPSTREAM_REPO
app_1  | [2022-05-21 01:50:03 +0000] [521] [INFO] Starting gunicorn 20.1.0
app_1  | [2022-05-21 01:50:03 +0000] [521] [INFO] Listening at: http://0.0.0.0:8                                                                                        0 (521)
app_1  | [2022-05-21 01:50:03 +0000] [521] [INFO] Using worker: sync
app_1  | [2022-05-21 01:50:03 +0000] [545] [INFO] Booting worker with pid: 545
app_1  | 2022-05-21 01:50:05,083 - bot - INFO - Generating BOT_STRING_SESSION
app_1  | 2022-05-21 01:50:05,085 - root - INFO - Initializing Aria2c
app_1  | 2022-05-21 01:50:10,331 - bot - INFO - Creating TELEGRAPH Account using                                                                                          'VcjJuEiS' name
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
app_1  |     return _run_code(code, main_globals, None,
app_1  |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
app_1  |     exec(code, run_globals)
app_1  |   File "/usr/src/app/bot/__main__.py", line 21, in <module>
app_1  |     from .modules import authorize, list, cancel_mirror, mirror_status,                                                                                         mirror, clone, watch, shell, eval, delete, count, leech_settings, search, rss
app_1  |   File "/usr/src/app/bot/modules/mirror.py", line 23, in <module>
app_1  |     from bot.helper.mirror_utils.download_utils.qbit_downloader import                                                                                         QbDownloader
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/qbit_downlo                                                                                        ader.py", line 3, in <module>
app_1  |     from bencoding import bencode, bdecode
app_1  | ModuleNotFoundError: No module named 'bencoding'
how to fix

**Comment by anasty17** [comment]
What do u know about UPSTREAM_REPO repo ?

**Comment by AJ-dev9921** [comment]
UPSTREAM_REPO = ""
this section is empty
