### ISSUE TITLE
How should I fix it?

### ISSUE THREAD

**Issue by alexAung099** [anasty17/mirror-leech-telegram-bot#607]
ERROR: [vk] -185511667_456239260: Failed to parse JSON  (caused by JSONDecodeError('Expecting value: line 1 column 1 (char 0)')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by anasty17** [comment]
Report to yt-dlp
