### ISSUE TITLE
status is showing the same file.

### ISSUE THREAD

**Issue by carolynsteeves1** [anasty17/mirror-leech-telegram-bot#609]
Hi anas, when downloading multiple files, the bot is showing the same torrent in status, when its diffrent torrents. I think this might be a issue to qbit old version. Im on latest repo

**Comment by anasty17** [comment]
Update ur code!

**Comment by carolynsteeves1** [comment]
> Update ur code!

I just redeployed again using newest repo, and i still have the same problem. I'm torreting from an private tracker, and it didn't happen before when it was on 4.4.2. Right now my torrents are just stuck, and qbittorrent adressed this issue themseleves, so ig its better to update
