### ISSUE TITLE
status is showing the same file.

### ISSUE THREAD

**Issue by carolynsteeves1** [anasty17/mirror-leech-telegram-bot#612]
Hi anas, when downloading multiple files, the bot is showing the same torrent in status, when its diffrent torrents. I think this might be a issue to qbit old version. Im on latest repo and commit, so my code is updated. I just redeployed again using newest repo, and i still have the same problem. I'm torreting from an private tracker, and it didn't happen before when it was on 4.4.2. Right now my torrents are just stuck on metadata, which it didn't do before this repo updated to 4.3.9, and qbittorrent adressed this issue themseleves, so ig its better to update 4.4.2 again

**Comment by anasty17** [comment]
Delete old image first then deploy again
