### ISSUE TITLE
(Docker) Changing download path + path used for getting space left on drive

### ISSUE THREAD

**Issue by anteac** [anasty17/mirror-leech-telegram-bot#619]
Hey,

i spotted a line of code that calculates the space left on drive, but when using docker-compose there is no easy way to map a different drive or mountpoint to download to and check disk space since the latter is hardcoded. 

actually isnt a problem at all since its a template, but I cant find out where I have to edit things for  it to work. Would be appreciated if someone could explain.

**Comment by anasty17** [comment]
The storage capacity in code for download directory
