### ISSUE TITLE
Leech settings and thumbnails not persistent

### ISSUE THREAD

**Issue by 4r3t** [anasty17/mirror-leech-telegram-bot#62]
Upon dyno restart or even restarting the bot on private server, causes the the thumbs and leech settings to be removed.
DATABASE_URL given and working fine because I'm already using qbit selection.
I don't think I have made any errors on my end, thus issuing this issue.

**Comment by anasty17** [comment]
Database now only for sudo .. soon will add rss and will  add all leech settings to database ... soon

**Comment by 4r3t** [comment]
> Database now only for sudo .. soon will add rss and will add all leech settings to database ... soon

Alright. Thanks for such a fast response.
Is there a support group or a discuss chat currently for this repository, or everything is solely managed here on github?

**Comment by anasty17** [comment]
@4r3t Github is enough.. no support needed everything written in readme for who want to read ... else there is many mirror groups 🤷‍♂

**Comment by 4r3t** [comment]
> @4r3t Github is enough.. no support needed everything written in readme for who want to read ... else there is many mirror groups 🤷‍♂

Respect your decision. Kudos to what you have done for the community :D
