### ISSUE TITLE
Can you make this repo available for Scalingo, it'll be better than as now Heroku is gone.

### ISSUE THREAD

**Issue by akshzyx** [anasty17/mirror-leech-telegram-bot#626]
and not everyone can buy vps. Scalingo will be a big help.

**Comment by inferouss** [comment]
Yeah, scalingo will be good, not everyone can buy vps. Scalingo can solve the problem.

**Comment by anasty17** [comment]
Heroku not gone

**Comment by akshzyx** [comment]
Like for now we can't use this repo on Heroku so.
