### ISSUE TITLE
Add gdtot support for heroku branch

### ISSUE THREAD

**Issue by majnurangeela** [anasty17/mirror-leech-telegram-bot#63]
I tried to deploy master branch using heroku cli method bot says one or more vars are missing and crashes immediately even if I've filled all required vars and some optional vars correctly. So I'm trying to say do you have plans for adding gdtot support for heroku branch ?

**Comment by SpeedyIndeedy** [comment]
@majnurangeela attach your config file and just replace your values with 'filled', so that i can see if any mandatory var wasn't filled

**Comment by majnurangeela** [comment]
@SpeedyIndeedy
[config.env.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/7607300/config.env.txt)
Here is the config file

**Comment by anasty17** [comment]
@majnurangeela Hi, u don't need to deploy master branch on heroku ... there is a branch for it ... or u can deploy master branch two times with same app name for new app... if u filled upstream repo var with official repo so ur bot will get all files from it .. so first u shouldn't delete .gitignore file 2nd u must use git add . -f to add ignored files .. those ignored files will stay in ur heroku app other files will updated on each restart

**Comment by majnurangeela** [comment]
Okay, Thanks for fast replies. I got it problem was i was deleting .gitignore file and git folder and initializing my own git using git init that was the fault. Thank You once again !
