### ISSUE TITLE
Bot Commands are not changing

### ISSUE THREAD

**Issue by majnurangeela** [anasty17/mirror-leech-telegram-bot#64]
Sorry to interrupt you once again but I came to know that I changed bot commands from bot_commands.py file and redeployed the app but still old commands are working and new commands are not replaced.

**Comment by anasty17** [comment]
@majnurangeela Cli or workflow?

**Comment by majnurangeela** [comment]
@anasty17 CLI

**Comment by anasty17** [comment]
@majnurangeela Ok if heroku branch and u want to edit anything in repo so u need to add upstream repo url variable private or public check that variable for more information about to add private repo .. then edit what u want in that repo ... and u can update and edit in thing in repo from github repo that u added by restart cmd

**Comment by anasty17** [comment]
@majnurangeela If not heroku branch so u added upstream repo to repo which bot cmds is default

**Comment by majnurangeela** [comment]
@anasty17 Yeah, you were right I just left UPSTREAM_REPO var empty afterwards new commands are working perfectly. Thanks for your attention.
