### ISSUE TITLE
No mudole named bot

### ISSUE THREAD

**Issue by esmail-mkh** [anasty17/mirror-leech-telegram-bot#646]
Heroku says: no module named bot and its crashing

**Comment by Only-Iron-Man** [comment]
+1

**Comment by feronot** [comment]
+1

**Comment by Devansh1511** [comment]
Same here

**Comment by Vrmaniac** [comment]
Hey guyzzz set the upstream repo and upstream Branch as master

**Comment by AkashWasim** [comment]
> Hey guyzzz set the upstream repo and upstream Branch as master

upstream repo is anas's repo link right?

**Comment by AshishSharma2006** [comment]
> Hey guyzzz set the upstream repo and upstream Branch as master

not working
