### ISSUE TITLE
Upload not working through SA's

### ISSUE THREAD

**Issue by lemoonnn** [anasty17/mirror-leech-telegram-bot#65]
Hi..
I deployed bot via github workflow and added both token.pickle accounts.zip url in config.env & set use service account to "True" also added Google group (with same sa) to td with manger permission but upload won't happening. Btw upload works fine if I'm not using sa's. And my sa are fine (not banned or anything) so what I'm doing wrong here... please slove this
This is what log file shows:
2021-11-26 05:49:22,382 - bot - INFO - Generating USER_SESSION_STRING
2021-11-26 05:49:22,383 - root - WARNING - MEGA API KEY not provided!
2021-11-26 05:49:22,383 - root - WARNING - MEGA Credentials not provided!
2021-11-26 05:49:22,383 - root - WARNING - UPTOBOX_TOKEN not provided!
2021-11-26 05:49:26,743 - bot - INFO - Creating TELEGRAPH Account using  'duEFmSXa' name
2021-11-26 05:49:34,438 - apscheduler.scheduler - INFO - Scheduler started
2021-11-26 05:49:34,622 - bot - INFO - Bot Started!
2021-11-26 05:52:51,237 - bot - INFO - https://github.com/endeavouros-team/ISO/releases/download/1-EndeavourOS-ISO-releases-archive/endeavouros-2021.08.27-x86_64.iso
2021-11-26 05:52:51,328 - bot - INFO - Started: 05eb832921ab9b60 DIR:/usr/src/app/downloads/2448 
2021-11-26 05:53:28,626 - bot - INFO - Download completed: endeavouros-2021.08.27-x86_64.iso
2021-11-26 05:53:28,635 - bot - INFO - Upload Name: endeavouros-2021.08.27-x86_64.iso
2021-11-26 05:53:28,636 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 97.json service account

**Comment by anasty17** [comment]
@lemoonnn Try list cmd

**Comment by lemoonnn** [comment]
@anasty17 I didn't got result back, it's just stopped
Here's the log
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/7608849/log.txt)

**Comment by jusidama18** [comment]
> @anasty17 I didn't got result back, it's just stopped Here's the log [log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/7608849/log.txt)

make sure only service accounts json files in accounts folder not email.txt or anything else

**Comment by lemoonnn** [comment]
> > @anasty17 I didn't got result back, it's just stopped Here's the log [log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/7608849/log.txt)
> 
> make sure only service accounts json files in accounts folder not email.txt or anything else

Nope only 100 json files like 0.json to 99.json
Also i generated my sa's using Credentials.json on Autorclone so both token.pickle & accounts.zip are from same account, so idk what's the problem

**Comment by anasty17** [comment]
@lemoonnn Do /shell ls accounts

**Comment by snehitap** [comment]
Make sure u zipped the accounts folder not only jsons.. means if u open the zip file u should see the accounts folder not jsons..

**Comment by anasty17** [comment]
@snehitap Mostly the accounts name is wrong cz bot will not start if accounts folder is empty

**Comment by lemoonnn** [comment]
> @lemoonnn Do /shell ls accounts

Got this:
Stdout
 0.json
 10.json
 11.json
 12.json
 13.json
 14.json
 15.json
 16.json
 17.json
 18.json
 19.json
 1.json
 20.json
 21.json
 22.json
 23.json
 24.json
 25.json
 26.json
 27.json
 28.json
 29.json
 2.json
 30.json
 31.json
 32.json
 33.json
 34.json
 35.json
 36.json
 37.json
 38.json
 39.json
 3.json
 40.json
 41.json
 42.json
 43.json
 44.json
 45.json
 46.json
 47.json
 48.json
 49.json
 4.json
 50.json
 51.json
 52.json
 53.json
 54.json
 55.json
 56.json
 57.json
 58.json
 59.json
 5.json
 60.json
 61.json
 62.json
 63.json
 64.json
 65.json
 66.json
 67.json
 68.json
 69.json
 6.json
 70.json
 71.json
 72.json
 73.json
 74.json
 75.json
 76.json
 77.json
 78.json
 79.json
 7.json
 80.json
 81.json
 82.json
 83.json
 84.json
 85.json
 86.json
 87.json
 88.json
 89.json
 8.json
 90.json
 91.json
 92.json
 93.json
 94.json
 95.json
 96.json
 97.json
 98.json
 99.json
 9.json

**Comment by anasty17** [comment]
Idk restart the bot

**Comment by lemoonnn** [comment]
> Idk restart the bot

Nope still same after restart. But normally it should work right, i mean even if we deploy via work flow sa upload should work fine right?? Cuz this is the first time I'm deploying from work flow

**Comment by anasty17** [comment]
@lemoonnn Same with workflow ... pm me https://t.me/anas_tayyar and give access to bot

**Comment by lemoonnn** [comment]
> @lemoonnn Same with workflow ... pm me https://t.me/anas_tayyar and give access to bot

Ok will do, thanks

**Comment by anasty17** [comment]
Anything?!
