### ISSUE TITLE
QBMIRROR command is not working

### ISSUE THREAD

**Issue by nodirhajiev** [anasty17/mirror-leech-telegram-bot#651]
`Failed to connect to qBittorrent. 
Unknown Error: ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='localhost', port=8090): Read timed out. (read timeout=15.1)"))`

How to fix it? Or need any changes in configs?

**Comment by majnurangeela** [comment]
Read readme.md file properly I just deployed the bot and it is working fine... Perhaps you haven't filled BASE_URL_OF_BOT env variable

**Comment by nodirhajiev** [comment]
> Read readme.md file properly I just deployed the bot and it is working fine... Perhaps you haven't filled BASE_URL_OF_BOT env variable

I've filled url of bot in config. It's not helping

**Comment by AkashWasim** [comment]
> Read readme.md file properly I just deployed the bot and it is working fine... Perhaps you haven't filled BASE_URL_OF_BOT env variable

there is no base url in the required section but theres one under #qbit section.. do you mean that or i have to add another base url under the required section?

**Comment by nodirhajiev** [comment]
I think after changing server_port=8080, it's working properly

**Comment by AkashWasim** [comment]
> I think after changing server_port=8080, it's working properly

its working for you? can you please show your config.env you can hide or blur your details

**Comment by nodirhajiev** [comment]
> > I think after changing server_port=8080, it's working properly
> 
> its working for you? can you please show your config.env you can hide or blur your details 

Just change SERVER_PORT="8080"
