### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by thanioruvangkls** [anasty17/mirror-leech-telegram-bot#654]
please add geobypass country IN for MXplayer link in youtubedl helper file bro please
Otherwise it shows 
ERROR: 8b343551cdde8f4e4e5b3a9207e58f45: An extractor error has occurred. (caused by KeyError('profile')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

If geobypass country is set to IN then it will be perfectly working so please add that in youtubedl download helper for MXplayer links

**Comment by anasty17** [comment]
Send to me example link

**Comment by thanioruvangkls** [comment]
MXplayer series episode link
Example : https://www.mxplayer.in/show/watch-critical-tamil-dubbed/season-1/episode-1-online-ccedb8988294004d18451021fce01695

**Comment by anasty17** [comment]
Ok is there any other domain than .in ?
And for now u can use yt-dlp args
I will add this soon

**Comment by dsdonseenu119** [comment]
is this working on Heroku sir ?

**Comment by thanioruvangkls** [comment]
> Ok is there any other domain than .in ? And for now u can use yt-dlp args I will add this soon

No bro,  .in is the only domain for this site

**Comment by sherlockia2** [comment]
> Ok is there any other domain than .in ? And for now u can use yt-dlp args I will add this soon

Can you plz show the command on how to give the args to download this link.
Because this one is not working...
/leechwatch https://www.mxplayer.in/show/watch-critical-tamil-dubbed/season-1/episode-1-online-ccedb8988294004d18451021fce01695 args:geo_bypass_country:IN
