### ISSUE TITLE
Encrypt  files before uploading To GDrive

### ISSUE THREAD

**Issue by Frozen12** [anasty17/mirror-leech-telegram-bot#675]
Uploading Files without encryption to Google Team Drive sometimes results-in Google Account Ban when reported by someone. uploading files without encryption is a privacy concerns too.

Encryption can be implemented like this 

> Files can be encrypted using `rclone` crypt remote

> we can view and download encrypted files using rclone based index site like [RCLONE-SERVE-INDEX](https://github.com/developeranaz/RCLONE-SERVE-INDEX) 

I know to enable encryption before upload whole bot code layout might need to changed. But please give it a  thought.

reference : 
[Rclone crypt](https://rclone.org/crypt/)

**Comment by anasty17** [comment]
Don't share ur files.. delete ur group
