### ISSUE TITLE
This Torrent already added or not a torrent. If something wrong please report.

### ISSUE THREAD

**Issue by HerokuLover** [anasty17/mirror-leech-telegram-bot#686]
"This Torrent already added or not a torrent. If something wrong please report."

Getting this error with 95% of the torrents ( while using RSS with Jackett Links )

**Comment by HerokuLover** [comment]
These (type of ) links specially from jackett

http://jackett4all.tk/dl/1337x/?jackett_apikey=7zf0bf1d8sufqnp7xqel34240ch1kk5k&path=Q2ZESjhKUENsbnRUbjB0RHZTbi1PYk5HOWNaV0ZLcU91LTlVQmw4YjA3OXFkekItWGV1THgwdGowVmg0cDRuSjhSSy03WmhfQjN4UUZMYno2TUlPY3F0MjVnUTVzd0VZMkcwX1dRQS1kMXFSOGx4a3c5SmtFSEE0QXlXeVd4TGd0WXBtSktlMmg0eEtFVk5tZUdxOVQyLVdLemQ0YXU4M1d3TzZwUENyblpwb2VraEV6NW9rZmNCYWVqczdYTGR0aThDeWxiQTVZVXppMXZxYzQ5U0p1Z3p1T2V4UUNOZmJ3eHBlSGNzcXUyLUtVWlZSMUMzTzRmdXlvTVlNMnBGN1lrbFkwcXZ2SjdMX3B5eko1ZnJpQUEtTUxiZlJTQkJjQWdBY3hnUWJaQnEtMkRDUw&file=The+Legend+of+Hei+2019+1080p+BluRay+x265+HEVC+10bit+EAC3+5.1+English+Chinese+SAMPA+QxR


http://jackett4all.tk/dl/1337x/?jackett_apikey=7zf0bf1d8sufqnp7xqel34240ch1kk5k&path=Q2ZESjhNQ0c5OXc2a3VCRXFsUk9nUjNXcGJEN0kyaU83OUVYNlJmeHc2MnZJYVRkY3J0N0YwYWNWRnlobWZKQ2JLUlE0R1pxUmVoVWo3VHZxQVRCemRQQ2R3cXAxVi1DWm5oMTFtM3MwdnBzLVRnOTE2SWx1dnJHZ3E0dGhFS2pENF9rMzdMR2ZtYkdnTXB4MHYwdkRUQnkwT3VtU2hpS1RTdGRLbWZMTFEzRm1KTWd6WTZXLU1LSkx2RWxLRzlZNS1JTmdxeG1lYWJ2REdJVlcyS3FMWERUbW1tOXlmRkFlRThsUzNpUS13c1lKc0cyb2N2QVhWYTREVnYxaDFzS29DUHp1cnoxNWVrX0xJTlNQdHUtN3NVaExVOA&file=The+Shack+2017+Extras+1080p+BluRay+x265+HEVC+10bit+EAC3+5.1+SAMPA+QxR


http://jackett4all.tk/dl/1337x/?jackett_apikey=7zf0bf1d8sufqnp7xqel34240ch1kk5k&path=Q2ZESjhNQ0c5OXc2a3VCRXFsUk9nUjNXcGJDUUNXbWI2RVZkandvcWU1OFRwVnlrOFY0MnpyQk1SRUFraWxDd2xYSEdoV3QtczNwc0JTdXVFSVR1TzEzWjRIWUhoVkNzckVjcU8yclBZaUttc3p0V2RqQ29lVUliZWQ2OVhzamdWalpHNGhKSkRFZl8tSTJOOWtGVmxUUWwyWk8zNFBRQzdjci1DWF9FeXljNjZkZ1RUeU56VVEzZ1hDaUprNEhWSmxVVWRKT1Z1N1JDODhycHozaUVKRW9VUkJ0SXpPQjFkdXhvMDhzdmlDSTZIbk5CczBVOEx4ekwxSm1RUjE4ajF3TjJ5TC1OaE1OcFZIWWpxUV9Lb0ViN2xvRnJ0NTB4RGtFTmdLbnVIczZOelAtWA&file=REPACK+Counterpart+2017+Season+1+2+S01+S02+1080p+Mixed+x265+HEVC+10bit+EAC3+5.1+Ghost+QxR

http://jackett4all.tk/dl/1337x/?jackett_apikey=7zf0bf1d8sufqnp7xqel34240ch1kk5k&path=Q2ZESjhNQ0c5OXc2a3VCRXFsUk9nUjNXcGJBR19vbm5FZUhGYVBaT3lMUnJ2Tk4tWmZBWEk1R2hFWWhFNlZzMXk1NnF6d0tMWjNNeFIzdjl0WC1QTW52eUNjb282elc2ZGFSTXpDY2RlZVlUSlpkQmMtam5tYTJkNnJ3R3ZMMWJ2OHNVcjBkUl84SDh1YzY4Y0VuNHYwSDBuNzZDTldpRjE3RUFOSHpIZ0lTVUVFb2szSmFrWjAxUHpFRVFwVGtWQjJVSUpjdTduYWJWbHBpTzl3U080bVFpaU1NajlDNnh4UjhuUlM5NGtUXzcwM3pTZ0M5aGFpbjNjVnpTRmpqd1FlUnNJYzA1d202bHRjY01maEZuN3RqYktxMnc3d3Z2d2pLdTMtQi1QYy05cXdLTg&file=REPACK+Counterpart+2017+Season+1+2+S01+S02+1080p+Mixed+x265+HEVC+10bit+EAC3+5.1+Ghost+QxR

**Comment by anasty17** [comment]
Those not magnet links nor ddl for torrent file... i solved this problem in master branch with old qbittorrent. I was using requests to download torrent files but those link have magnet. When u try to open it it direct u to torrent app.

**Comment by anasty17** [comment]
Working btw first link not valid

**Comment by anasty17** [comment]
![Uploading Screenshot_20220611-005500_Plus.jpg…]()

**Comment by HerokuLover** [comment]
These (type of ) links specially from jackett

http://jackett4all.tk/dl/1337x/?jackett_apikey=7zf0bf1d8sufqnp7xqel34240ch1kk5k&path=Q2ZESjhKUENsbnRUbjB0RHZTbi1PYk5HOWNaV0ZLcU91LTlVQmw4YjA3OXFkekItWGV1THgwdGowVmg0cDRuSjhSSy03WmhfQjN4UUZMYno2TUlPY3F0MjVnUTVzd0VZMkcwX1dRQS1kMXFSOGx4a3c5SmtFSEE0QXlXeVd4TGd0WXBtSktlMmg0eEtFVk5tZUdxOVQyLVdLemQ0YXU4M1d3TzZwUENyblpwb2VraEV6NW9rZmNCYWVqczdYTGR0aThDeWxiQTVZVXppMXZxYzQ5U0p1Z3p1T2V4UUNOZmJ3eHBlSGNzcXUyLUtVWlZSMUMzTzRmdXlvTVlNMnBGN1lrbFkwcXZ2SjdMX3B5eko1ZnJpQUEtTUxiZlJTQkJjQWdBY3hnUWJaQnEtMkRDUw&file=The+Legend+of+Hei+2019+1080p+BluRay+x265+HEVC+10bit+EAC3+5.1+English+Chinese+SAMPA+QxR

http://jackett4all.tk/dl/1337x/?jackett_apikey=7zf0bf1d8sufqnp7xqel34240ch1kk5k&path=Q2ZESjhNQ0c5OXc2a3VCRXFsUk9nUjNXcGJEN0kyaU83OUVYNlJmeHc2MnZJYVRkY3J0N0YwYWNWRnlobWZKQ2JLUlE0R1pxUmVoVWo3VHZxQVRCemRQQ2R3cXAxVi1DWm5oMTFtM3MwdnBzLVRnOTE2SWx1dnJHZ3E0dGhFS2pENF9rMzdMR2ZtYkdnTXB4MHYwdkRUQnkwT3VtU2hpS1RTdGRLbWZMTFEzRm1KTWd6WTZXLU1LSkx2RWxLRzlZNS1JTmdxeG1lYWJ2REdJVlcyS3FMWERUbW1tOXlmRkFlRThsUzNpUS13c1lKc0cyb2N2QVhWYTREVnYxaDFzS29DUHp1cnoxNWVrX0xJTlNQdHUtN3NVaExVOA&file=The+Shack+2017+Extras+1080p+BluRay+x265+HEVC+10bit+EAC3+5.1+SAMPA+QxR

http://jackett4all.tk/dl/1337x/?jackett_apikey=7zf0bf1d8sufqnp7xqel34240ch1kk5k&path=Q2ZESjhNQ0c5OXc2a3VCRXFsUk9nUjNXcGJDUUNXbWI2RVZkandvcWU1OFRwVnlrOFY0MnpyQk1SRUFraWxDd2xYSEdoV3QtczNwc0JTdXVFSVR1TzEzWjRIWUhoVkNzckVjcU8yclBZaUttc3p0V2RqQ29lVUliZWQ2OVhzamdWalpHNGhKSkRFZl8tSTJOOWtGVmxUUWwyWk8zNFBRQzdjci1DWF9FeXljNjZkZ1RUeU56VVEzZ1hDaUprNEhWSmxVVWRKT1Z1N1JDODhycHozaUVKRW9VUkJ0SXpPQjFkdXhvMDhzdmlDSTZIbk5CczBVOEx4ekwxSm1RUjE4ajF3TjJ5TC1OaE1OcFZIWWpxUV9Lb0ViN2xvRnJ0NTB4RGtFTmdLbnVIczZOelAtWA&file=REPACK+Counterpart+2017+Season+1+2+S01+S02+1080p+Mixed+x265+HEVC+10bit+EAC3+5.1+Ghost+QxR

http://jackett4all.tk/dl/1337x/?jackett_apikey=7zf0bf1d8sufqnp7xqel34240ch1kk5k&path=Q2ZESjhNQ0c5OXc2a3VCRXFsUk9nUjNXcGJBR19vbm5FZUhGYVBaT3lMUnJ2Tk4tWmZBWEk1R2hFWWhFNlZzMXk1NnF6d0tMWjNNeFIzdjl0WC1QTW52eUNjb282elc2ZGFSTXpDY2RlZVlUSlpkQmMtam5tYTJkNnJ3R3ZMMWJ2OHNVcjBkUl84SDh1YzY4Y0VuNHYwSDBuNzZDTldpRjE3RUFOSHpIZ0lTVUVFb2szSmFrWjAxUHpFRVFwVGtWQjJVSUpjdTduYWJWbHBpTzl3U080bVFpaU1NajlDNnh4UjhuUlM5NGtUXzcwM3pTZ0M5aGFpbjNjVnpTRmpqd1FlUnNJYzA1d202bHRjY01maEZuN3RqYktxMnc3d3Z2d2pLdTMtQi1QYy05cXdLTg&file=REPACK+Counterpart+2017+Season+1+2+S01+S02+1080p+Mixed+x265+HEVC+10bit+EAC3+5.1+Ghost+QxR

Sent from ProtonMail mobile

-------- Original Message --------
