### ISSUE TITLE
rss filters do not work properly

### ISSUE THREAD

**Issue by Nobody370** [anasty17/mirror-leech-telegram-bot#688]
url of rss https://www.limetorrents.lol/searchrss/psa/

![photo4983380455843801932](https://user-images.githubusercontent.com/88897873/173202699-de96e169-0b55-4ec8-b896-94a97784a9fe.jpg)

**Comment by anasty17** [comment]
This name not related to filter ... this is the last record just keep on this filter and u will not get 1080p
