### ISSUE TITLE
I'm new to this , pls help

### ISSUE THREAD

**Issue by geraltsmirror** [anasty17/mirror-leech-telegram-bot#689]
<img width="1258" alt="Screenshot 2022-06-12 at 9 16 53 AM" src="https://user-images.githubusercontent.com/107182915/173213512-2d2340b0-ed76-4c2f-a05f-a9703be9d062.png">
<img width="992" alt="Screenshot 2022-06-12 at 9 16 31 AM" src="https://user-images.githubusercontent.com/107182915/173213520-9b85df61-b046-46a8-a7cb-0bcab216bb7b.png">

**Comment by geraltsmirror** [comment]
saw the readme sorry

**Comment by anasty17** [comment]
Ur repo private ?
