### ISSUE TITLE
error on /qb cmd

### ISSUE THREAD

**Issue by Nobody370** [anasty17/mirror-leech-telegram-bot#693]
https://itorrents.org/torrent/DF441F93E83C69AA067F7205BC1F05575741EBE4.torrent?title=[LimeTorrents.lol]Suits.S06E11.WEB-DL.x264-FUM%5Bettv%5D

hello these direct links to torrents that the api search gives you on the limetorrent site are not working with the QB commands

**Comment by anasty17** [comment]
It's working. U didn't show me the error btw .. on my vps site blocked... on heroku working
