### ISSUE TITLE
request

### ISSUE THREAD

**Issue by narutouzumaki271** [anasty17/mirror-leech-telegram-bot#700]
Add support to clone 
APPDRIVE, DRIVEAPP, DRIVEBIT, DRIVELINKS, DRIVESHARER, DRIVEACE, HUBDRIVE, GDTOT, KATDRIVE , KOLOP ,  DRIVEHUB, DRIVEFIRE

**Comment by anasty17** [comment]
This endless thing and i dc for it and i don't know scraping and even if the code is ready i will not waste my time on it so u can pull request

**Comment by AshishSharma2006** [comment]
> Add support to clone APPDRIVE, DRIVEAPP, DRIVEBIT, DRIVELINKS, DRIVESHARER, DRIVEACE, HUBDRIVE, GDTOT, KATDRIVE , KOLOP , DRIVEHUB, DRIVEFIRE

kahi @ashish_leech_group se tho nhi ayena bhai 😂
