### ISSUE TITLE
Issue with Mega.nz transfer

### ISSUE THREAD

**Issue by priyaarm** [anasty17/mirror-leech-telegram-bot#702]
Hello there, I am a student from India and I have some important courses in a mega account and I need them urgently in g drive, I have seen many groups use mega premium for free and I don't know how cause they don't tell that, I really need that because I want to transfer some college courses. If you can help me with that then I will be very thankful , please help me.

**Comment by rahulkhatri137** [comment]
You know why issues tab is there on GitHub?

**Comment by priyaarm** [comment]
> You know why issues tab is there on GitHub?

Sorry I am new on github
