### ISSUE TITLE
Mirroring is Not Working Even Everything is perfect

### ISSUE THREAD

**Issue by dvrajput** [anasty17/mirror-leech-telegram-bot#71]
it says "your download has been stopped due to: Internal error occurred"
&
Gdtot Also Not Working

**Comment by dvrajput** [comment]
if its not an error then message me in telegram @imnoob123

**Comment by anasty17** [comment]
@dvrajput U r the error

**Comment by anasty17** [comment]
@dvrajput Internal error occurred so i can't do anything for u ... if mirroring tg files .. so this happens idk exactly why ... gdtot works fine but no one want to read readme
