### ISSUE TITLE
CAN YOU MAKE THIS REPO TO BE DEPLOYABLE ON "CLEVER CLOUD"

### ISSUE THREAD

**Issue by Rebaxa007** [anasty17/mirror-leech-telegram-bot#718]
**Is your feature request related to a problem? Please describe.**
NO
**Describe the solution you'd like**
I WOULD LIKE TO HAVE IT DEPLOYABLE ON "CLEVER CLOUD"
**Describe alternatives you've considered**

**Additional context**
CLEVER CLOUD DOES PROVIDE 24/7 RUNNING PROVITION AND DON'T RESTART THE BOT AS HEROKU.
SO IT'S BATTER FOR RUNNING BOT.

**Comment by anasty17** [comment]
Does it support docker?

**Comment by anasty17** [comment]
Try by ur self, what is the problem?
