### ISSUE TITLE
GDTot User rate limit exceeded

### ISSUE THREAD

**Issue by rajput-hemant** [anasty17/mirror-leech-telegram-bot#72]
ERROR:  Error: 403 User rate limit exceeded

It's showing this error, on every gdtot link

**Comment by anasty17** [comment]
U have clone limit ! Per day check readme read about service accounts

**Comment by rajput-hemant** [comment]
no sir, im already using service accounts, drive clone is working fine.
GDTot Clone is stuck with this issue
also if i manually download through gdtot links, then also it gives the same error

**Comment by anasty17** [comment]
@rajput-hemant Ur main account limit is over for today

**Comment by rajput-hemant** [comment]
but i cloned only 14gb from GDTot clone, how much is the limit.
So GDTot Clone don't use service accounts, right?

**Comment by snehitap** [comment]
The file u r trying to clone from gdtot, limit of that file must be reached..

**Comment by anasty17** [comment]
@snehitap Maybe file owner limit and maybe his limit .. its not error

**Comment by rajput-hemant** [comment]
> The file u r trying to clone from gdtot, limit of that file must be reached..

i tried with different GDTot links
its not quota exceeded error
its ERROR: Error: 403 User rate limit exceeded
with different acc i was able to get drive link, but was unable with the account used for bot uploads
@snehitap @anasty17

**Comment by dinesh-0602** [comment]
@rajput-hemant Both are same lol. User Quota exceeded and user rate limit exceeded

**Comment by rajput-hemant** [comment]
@dinesh-0602 but sir i literally tried with more than 10 GDTot links, i tried with the telly's newest encode, but still the issue persist.

**Comment by dinesh-0602** [comment]
@rajput-hemant If user limit exceeded means, you can't even do one 1 transfer and doesn't matter how many links you tried., it wil bs the same. You should try after 24hours

**Comment by rajput-hemant** [comment]
> @rajput-hemant If user limit exceeded means, you can't even do one 1 transfer and doesn't matter how many links you tried., it wil bs the same. You should try after 24hours

okay sir, thanks

**Comment by anasty17** [comment]
@rajput-hemant It's from ur account

**Comment by anasty17** [comment]
@askfriends User Service Accounts and token.pickle at same time ... so gdtot clone will be from token.pickle and other normal uploads and clone will be from service accounts

**Comment by askfriends** [comment]
> @askfriends User Service Accounts and token.pickle at same time ... so gdtot clone will be from token.pickle and other normal uploads and clone will be from service accounts

Thanks bro for clarifying, so it means i have to use same google account with whom token.pickle belongs, right?

**Comment by anasty17** [comment]
@askfriends Sure

**Comment by askfriends** [comment]
> @askfriends Sure

ok bro got it.
Thanks

**Comment by anasty17** [comment]
@askfriends U wlc

**Comment by askfriends** [comment]
> @askfriends U wlc

Bro i am able to clone gdtot links while im using gdtot crypt and phssid from another gmail account, it works.

**Comment by anasty17** [comment]
@askfriends Yes bro u can simce the google drive link is public but bot is not able to delete the first cloned file
