### ISSUE TITLE
Doodstream

### ISSUE THREAD

**Issue by Killerxy** [anasty17/mirror-leech-telegram-bot#727]
**Describe the bug**
Doodstream Error

**To Reproduce**
1. Used this Command with this link https://dood.pm/e/myoowakcuv37bc62w3tmhp6rpk75apj
2. It says " ERROR: Unsupported URL: https://dood.pm/e/myoowakcuv37bc62w3tmhp6rpk75apj"
3. But Yt-dlp supports doodstream
4.  Using latest commit 

**Screenshots**
[Log](https://telegra.ph/file/f7cb10f0c559d6026c2a8.jpg)

**Comment by anasty17** [comment]
Report to yt-dlp
