### ISSUE TITLE
qbmirror s command issue

### ISSUE THREAD

**Issue by RealNoobieDrive** [anasty17/mirror-leech-telegram-bot#728]
when we use qbmirror s for downloading large torrent file ,after downloading 1 part of file when we try to mirror second file ,it gives file/folder already in drive as stop-duplicate in on, so due to this we cant mirror remaining parts .. Is it possible to make stop-duplicate not work when using qbmirror s or any other way to resolve this issue .

**Comment by anasty17** [comment]
I already did this!
