### ISSUE TITLE
Heroku Accounts Suspended 

### ISSUE THREAD

**Issue by noob-af-bd** [anasty17/mirror-leech-telegram-bot#73]
I deployed via Github action  but still account suspended after 7 hour of deploy  

Any way to prevent suspension??

I tried redeploy method with same name but still no luck...

**Comment by anasty17** [comment]
How many branches in repo ?

**Comment by anasty17** [comment]
> I deployed via Github action but still account suspended after 7 hour of deploy
> 
> Any way to prevent suspension??
> 
> I tried redeploy method with same name but still no luck...

Deploying with same app name working 100% ... u did something wrong ... since people don't get this small trick i made branch for heroku check it... working 100% also ... just follow readme

**Comment by noob-af-bd** [comment]
> How many branches in repo ?

2 repo just Forked yesterday...

**Comment by anasty17** [comment]
So deploy heroku branch and plz gorget everything u know and follow readme

**Comment by noob-af-bd** [comment]
Ok...sir.... Thanks for the reply..... 😘

Have a good day 🥰
