### ISSUE TITLE
Rename file for Qb

### ISSUE THREAD

**Issue by pradeishc** [anasty17/mirror-leech-telegram-bot#745]
**Could you make rename file for qbmirror, qbleech, qbzipleech and all qb's.**

**Comment by anasty17** [comment]
We can only rename after download complete

**Comment by pradeishc** [comment]
How to do in qb ?

**Comment by anasty17** [comment]
U can't from qbitorrent u need to change it manually with python

**Comment by pradeishc** [comment]
Maybe we can download the file and rename before uploading to telegram.

**Comment by anasty17** [comment]
Yes we can do this, i thought u r asking for this incase u r using stop duplicate

**Comment by anasty17** [comment]
> Maybe we can download the file and rename before uploading to telegram.

Not maybe, I already told u this! https://github.com/anasty17/mirror-leech-telegram-bot/issues/745#issuecomment-1185693117
