### ISSUE TITLE
support for seeding private trackers more than 24h

### ISSUE THREAD

**Issue by Helpless69** [anasty17/mirror-leech-telegram-bot#751]
**Is your feature request related to a problem? Please describe.**
Private trackers needs to be seed for atleast 72h but Heroku app restarts every 24h.

**Describe the solution you'd like**
Maybe add a feature to save the magnet link to database, download file again using index link after app restarts and seed again.

**Describe alternatives you've considered**
https://github.com/sanjit-sinha/Bhadoo-Index-Scraper

**Comment by anasty17** [comment]
Not a seed bot
