### ISSUE TITLE
Zip/Extract multiple files or splits from tg

### ISSUE THREAD

**Issue by orlandokc** [anasty17/mirror-leech-telegram-bot#759]
anyway to zipmirror batch files from tg

**Comment by anasty17** [comment]
Not yet

**Comment by SRvasoya31** [comment]
File Joiner 

File Joiner allows you to easily join .001/002/003 files. File Joiner is a free application, available in both 64bit and 32bit versions.
Features
Faster joining with option to append all files to first file
Loading files from folder and recursive loading from sub-folders
Auto sorting (numerical [.001, .002] or full path sorting)
Auto loading consecutive parts when you open or drag&drop file with extension .001
Auto output file path generator (file "c:\test.avi.001" will generate output file path "c:\test.avi")
Tests for missing parts and parts with wrong file size (e. g. bad download)
MD5 and CRC32 hash calculation for output file
Option to associate extension .001 in windows explorer, allows you to load files by double clicking the .001 file (not portable)
Progress bar to monitor the hash operation (with progress bar in taskbar)
File Joiner 64bit (x64) and 32bit (x86) versions available
Multilanguage support
UNICODE support
High DPI Awareness
