### ISSUE TITLE
/bin/sh: 1: Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by mine-nandha** [anasty17/mirror-leech-telegram-bot#76]
![IMG_20211128_034431](https://user-images.githubusercontent.com/86552361/143722121-4fa217d5-9147-4131-9afc-4938eb1bface.jpg)
It was working fine for 2 days and now it's keeps crashing. (Workflow method)

**Comment by anasty17** [comment]
U did mistake in config.env

**Comment by anasty17** [comment]
Just fill what u know .. and leave the rest as it is

**Comment by anasty17** [comment]
Just fill what u know .. and leave the rest as it is

**Comment by mine-nandha** [comment]
Thanks. Actually I did mistake in Config.env. The last time I was updating upstream_repo I forgot to add a " (double quote).
