### ISSUE TITLE
Error on leeching files i  gdrive 

### ISSUE THREAD

**Issue by Killerxy** [anasty17/mirror-leech-telegram-bot#769]
**Describe the bug**
Bot says "Files Corrupted. Check logs", while leeching files in gdrive

**To Reproduce**
1. Used this /leech Command with this [link](https://drive.google.com/file/d/1AZafT1jU4xFIlm6DGaB2o700du4kxDzh/view?usp=drivesdk)
2. after downloading ..
3.  [logs](https://katb.in/idiwaqumuyi.txt)
4. Even used different gdrive & index links
5. Using latest commit

**Comment by anasty17** [comment]
Read Read

**Comment by Killerxy** [comment]
Getting same error again [log](https://telegra.ph/file/a8ff194ef5b804de6c00e.jpg)
