### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by I-Am-HappyBoy** [anasty17/mirror-leech-telegram-bot#771]
1) Auto Detect Feature or 

Put One Command And Select Commands Manually By Pressing Inline Button.

Needed This Feature For VPS In Master Or A New Branch.

2) MediaInfo Feature Needed For Telegram Files.

3) Add Free Uptobox Token Support As Whisky Said His New Tutorial Video (https://www.youtube.com/watch?v=IUmq1paCiHI).
Also Please Update His New Tutorial Video.

**Comment by anasty17** [comment]
Hi, 
1. I Don't like this idea
2. It's not mediainfo bot, @mediainforobot use this.
3. It takes time and this not cz we can use only 4 workers at the same time.
