### ISSUE TITLE
Requests Feature

### ISSUE THREAD

**Issue by Zusyaku** [anasty17/mirror-leech-telegram-bot#774]
Plz re add shortlink feature again in bot for to support creator and make help to buy mega premium and can you add new feature to rename file after downloaded
*example /mirror https://github.com/anasty17/file.zip rename: sourcecode.zip

and some bug plz fix

**Comment by anasty17** [comment]
No features for super groups

**Comment by anasty17** [comment]
U can rename all links except torrents and mega(heroku branch)
