### ISSUE TITLE
Zippyshare 

### ISSUE THREAD

**Issue by NasiGorengRebus** [anasty17/mirror-leech-telegram-bot#775]
Please fix zippyshare link

**Comment by anasty17** [comment]
Issue in lk21 lib, will try to fix it

**Comment by anasty17** [comment]
Send zippyshare links to test

**Comment by anasty17** [comment]
Fixed i guess

**Comment by gasptx** [comment]
On some link still error

Try this
https://www29.zippyshare.com/v/GnIgDWTD/file.html

**Comment by anasty17** [comment]
Aha send more links not working

**Comment by NasiGorengRebus** [comment]
All not working now

**Comment by anasty17** [comment]
> All not working now

Ok seems everyday it will change, i will use js lib

**Comment by anasty17** [comment]
They will always change it, and I'm not good in scraping.
This scrap can done easily but they will change again and again nothing fixed or known i will not follow the chnages everytime

**Comment by NasiGorengRebus** [comment]
Ok, i fix it by myself

**Comment by anasty17** [comment]
> Ok, I already fix it

Good for u
