### ISSUE TITLE
ERROR - 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by Killerxy** [anasty17/mirror-leech-telegram-bot#777]
Error only occurs while leeching 
Bot says "Files Corrupted. Check logs"
Using string session, tg premium user.

 [Log](https://telegra.ph/file/a8ff194ef5b804de6c00e.jpg)

There was no error without using string

[Full log](https://katb.in/afiquwigabe.txt)

**Comment by anasty17** [comment]
Read readme

**Comment by anasty17** [comment]
What u have read regarding user session string var send screenshot

**Comment by Killerxy** [comment]
Error only occurs on newly created group

Tried with old group leeched

I this its a bug

**Comment by Killerxy** [comment]
While using string session bot upload only in supergroup.
But without it bot upload in group & supergroup

**Comment by Killerxy** [comment]
> It's not a bug but u noob. U should understand bots before using github codes. When i say group this means supergroup cz no difference btw group and pm both can't read id same as user account unless it's in supergroup. Where all admins and bots will see same message id.

👍
