### ISSUE TITLE
invalid load key, '<'.

### ISSUE THREAD

**Issue by drtfx7** [anasty17/mirror-leech-telegram-bot#78]
Deployed on Heroku. Everything works except cloning.
![image](https://user-images.githubusercontent.com/94729366/143730216-2bec77f7-2014-4b98-9cec-4b8e74add175.png)

**Comment by dinesh-0602** [comment]
@drtfx7 Do you have token.pickle in your repo? check with /shell ls

**Comment by anasty17** [comment]
Send full logs ...

**Comment by drtfx7** [comment]
> Send full logs ...

i am a noob, could you tell me how to do that?

**Comment by anasty17** [comment]
@drtfx7 Hit /log in ur bot ... file from bot received... send it to t.me/anas_tayyar

**Comment by drtfx7** [comment]
> @drtfx7 Do you have token.pickle in your repo? check with /shell ls

i uploaded my token.pickle to zippyshare and put the url in TOKEN_PICKLE_URL of config.env
is that wrong?

**Comment by drtfx7** [comment]
> @drtfx7 Hit /log in ur bot ... file from bot received... send it to t.me/anas_tayyar

sent

**Comment by drtfx7** [comment]
resolved the issue by uploading token.pickle file to dropbox/index.
