### ISSUE TITLE
Account not Connecting

### ISSUE THREAD

**Issue by DextiNxD** [anasty17/mirror-leech-telegram-bot#780]
my premium telegram account not connecting please help me for solve

![image](https://user-images.githubusercontent.com/95567528/180061960-c3692782-a772-4765-8aa4-fa659a37eff3.png)

**Comment by anasty17** [comment]
Read the error! U r using old session string format... generate string session with pyrogram v2 or above

**Comment by DextiNxD** [comment]
still same error

**Comment by DextiNxD** [comment]
can you please make string generator

**Comment by anasty17** [comment]
> can you please make string generator
Already in repo!
