### ISSUE TITLE
premium error

### ISSUE THREAD

**Issue by alonelove7** [anasty17/mirror-leech-telegram-bot#781]
Hi dear
i tried in supergroup (https://t.me/ted5d5dd)
this error
 What is it about?
pyrogram ?
it's last version

app_1  | pyrogram.errors.exceptions.bad_request_400.ChannelInvalid: Telegram says: [400 CHANNEL_INVALID] - The channel parameter is invalid (caused by "channels.GetChannels")

[full error](https://drive.google.com/file/d/1lwLFauSLNjtoZf9QoxVNfC3vXYXiJtQB/view?usp=sharing)

**Comment by anasty17** [comment]
Channel!!!!

**Comment by alonelove7** [comment]
😂
i closed it
The error was not related to the channel
account had a problem.

**Comment by alonelove7** [comment]
why so serious :)
