### ISSUE TITLE
Selction done automatic 

### ISSUE THREAD

**Issue by codewithweeb** [anasty17/mirror-leech-telegram-bot#785]
**Is your feature request related to a problem? Please describe.**
Sometime when authorised user use the qb selection and forgot to select the file due to large mirroring then in background the torrent was paused and use the bot resources 

**Describe the solution you'd like**
solution is 
1. make auto select means auto start the remaining torrent after a specific time if user didn't select anything 

**Describe alternatives you've considered**
no

**Additional context**
no

**Comment by anasty17** [comment]
Ha! U forget! Then it's ur problem

**Comment by anasty17** [comment]
If u meant this for groups, don't open issue here again! No features for supergroups!
