### ISSUE TITLE
MediaFire Folder Download Support

### ISSUE THREAD

**Issue by I-Am-HappyBoy** [anasty17/mirror-leech-telegram-bot#786]
There Is Bunch Of Courses Stuff.. Want To Download Them In Drive.

Is It Possible To Support MediaFire Folder Download?

https://www.mediafire.com/folder/j1y7497pycb0s/(Amit+Mishra)-+Master+Blogging+Program+@CourseOnCloud

**Comment by anasty17** [comment]
No, this scraping thing is endless! I will not involve my self in it. Other people will ask for other sites and so on. So i will not add any scrap script, maybe i can fix the already added. But no more scraping.
