### ISSUE TITLE
The Docker Hub image does not seem legit

### ISSUE THREAD

**Issue by avbentem** [anasty17/mirror-leech-telegram-bot#787]
https://hub.docker.com/r/anasty17/mltb shows a build step that ~~copies some 27 MB folder into subfolders of the image's root, and another step~~ involves _executing_ some secret. ~~Both make~~ That makes it hard to see what's really included in the image. 

Like [today's `latest` for linux/amd64 shows](https://hub.docker.com/layers/mltb/anasty17/mltb/latest/images/sha256-bcd0c8430fb4b28fac8e3615789bf8eb94d2f17d7766d11982e5ebdeaccc7a9e?context=explore):

```
ADD file:00dae10e79b05c4e1a3db053a1f85a4f38a39fe85cbbd88d74201a01a7dd59b5 in / 
CMD ["bash"]
ARG DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
RUN |1 DEBIAN_FRONTEND=noninteractive /bin/sh -c bash /run/secrets/secretxt # buildkit
```

[The Dockerfile in this very repository](https://github.com/anasty17/mirror-leech-telegram-bot/blob/master/Dockerfile) seems to refer to that image, so presumably the Hub account is yours.

So: is the Docker Hub account still under your control, and is that image legit?

**To Reproduce**

Click a tag or digest on https://hub.docker.com/r/anasty17/mltb/tags
 
**Expected behavior**

Some way to tell the image is legit.

**Screenshots**

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/1497002/180302992-3c920e3e-a25d-4e4d-b578-722ae192332d.png">

**Comment by anasty17** [comment]
Yes this is my dockerhub account. I didn't get what do you want ?

**Comment by avbentem** [comment]
That was quick! And good to know it's still in your control. But regardless, it feels a bit shady to _execute_ the contents of a secret to change the image's contents. What script is in that secret? 

Surely the [old pre-May 15th Dockerfile](https://github.com/anasty17/mirror-leech-telegram-bot/commit/02630e16cdcf4212cc4afd424a684b69297c5261) was much easier to validate!

(Aside, I was wrong about the first step being a bit weird too. The hashed file names is just how Hub shows files or folders being copied into an image.)

**Comment by anasty17** [comment]
I put it in secret for some reasons! I named it as secret so people can understand! It's only for public use! So you asking me to show you what I'm hiding just because you asked for it ?!

**Comment by avbentem** [comment]
> So you asking me to show you what I'm hiding just because you asked for it ?!

If you're referring to my "What script is in that secret?", why can't you explain what it does?

> It's only for public use!

Or for _private_ use, maybe? That would explain all, of course. Though people are finding the image on Hub, [and some are confused and don't trust it](https://forums.docker.com/t/explore-docker-image-hidden-file/126885).

(Aside, I am not using the image nor your code. Just wanted to make sure you still controlled the Docker account. You're welcome.)

**Comment by anasty17** [comment]
Just ignore this little kid
