### ISSUE TITLE
zip split

### ISSUE THREAD

**Issue by MMD2V1** [anasty17/mirror-leech-telegram-bot#788]
**Describe the solution you'd like**
The ability to split the zip file into parts and upload it to GDrive.
ex. split into 2 equal parts or split into 4GB per part.

**Describe alternatives you've considered**
/leech can split the files but the maximum split part is 2GB and 4GB for premium TG users. not all have premium TG.

**Comment by anasty17** [comment]
Splitting only for leech, no need to split for google drive. I will not add this
