### ISSUE TITLE
Please Add Best Video+Best Audio Feature In /watch Command

### ISSUE THREAD

**Issue by vivekdarji00** [anasty17/mirror-leech-telegram-bot#789]
Please Add Best Video+Best Audio Feature In /watch Command
Sometimes video is perfect but audio bitrate is low 128kbps/64kbps .
Best video gives only 128kbps audio

**If possible add this feature**

![IMG_20220722_103834](https://user-images.githubusercontent.com/70027857/180367150-5dbdc139-ff8c-4be9-9df2-dad17f81af6d.jpg)

**Comment by anasty17** [comment]
Best video means best video and best audio
