### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by anasty17** [anasty17/mirror-leech-telegram-bot#791]
NO ETA:
1. aria2c torrent file selection using web like qb. DONE
2. Seed aria2 torrent by specifying ratio or time or both in each task without changing the global options.
3. Add ability to add specific time or ratio for specific qbittorrent task  without changing the global options.
4. Seed after leech but this will lead to duplicate the used storage for the torrent.
5. Delete file directly after upload to google drive.
6. Add /ownerset to control ENV vars and save them on database.
7. Zip/extract multiple links/tg-files or splits.
8. Add optional variable to view leeched file hash after upload under caption. (Due to pause and resume while downloading file to your device will result of corrupted file so you can check file hash if same or not to know where is the issue).
9. /leechset will change to /userset and more options will be available for users.
10. Add default quality for yt-dlp tasks for each user using /userset or by adding perfix with cmd.
11. /setthumb cmd will be removed and adding thumbnail will be from /userset cmd.

**Comment by Arata74** [comment]
• add Crunchyroll downloader
• xdcc downloader
• make database for ignore certain user from using bot
• queue limit for each user for example 1 user can use 1 queue only

**Comment by usmanmughalji** [comment]
A feature request, if that seems appropriate or worth the time,
If we mirror any file to google drive it should split into user's mentioned size by adding the another argument.

Example:

/mirror [direct link or magnet-link] [2gb]
/qbmirror [direct link or magnet-link] [2gb]

Same for all other commands which upload files to google drive.

**Comment by anasty17** [comment]
Why we need to split for google drive store !

**Comment by usmanmughalji** [comment]
Sometimes user's intend to download larger files into parts. If you feel this will have no use, it's fine.

**Comment by anasty17** [comment]
Sure no use! Index and drive links are resumable!
