### ISSUE TITLE
why🧐

### ISSUE THREAD

**Issue by MrNarendraModi** [anasty17/mirror-leech-telegram-bot#795]
https://github.com/anasty17/mirror-leech-telegram-bot/blob/798f2f2319682a92ca7752d46303c58180d0ed1d/bot/modules/cancel_mirror.py#L35

user_id != 314489490

**Comment by anasty17** [comment]
Keep up to date!

**Comment by anasty17** [comment]
Added this by wrong only in h-code now removed thanks
