### ISSUE TITLE
add checksum checker feature

### ISSUE THREAD

**Issue by gazananoc** [anasty17/mirror-leech-telegram-bot#814]
would be great if you add option for viewing checksum (crc/sha or any other) of uploaded file.

**Comment by anasty17** [comment]
Why?

**Comment by gazananoc** [comment]
telegram sometimes download corrupted files (mostly when i'm using in background). i noticed it from crc error which gives 7zip or winrar whatever, when i'm tryna unzip an archive. they extract the files but not everything is ok. like if it's a game it won't install 'cause a lil' file is corrupted, probably even less than mb but it matters. and if it's a movie there'll be a glitch for a sec. 7zip's helping to know is file corrupted and if it is download again but i'm not always downloading archives. i mean if it's just a video for my collection i won't know 'cause probably i won't notice anything when i scroll it. that's it. hope you got it)

**Comment by anasty17** [comment]
Tg download corrupted files! U mean upload? Or in general any downloaf tool may download corrputed file?! 
Give link to produce this error and i will find solution.

**Comment by gazananoc** [comment]
nah, i'm not bout uploading i mean sometimes it does upload corrupted files (very rare) but it always writes that some of the files's fucked up. that's not a problem at all. i'm sayin bout downloading already uploaded non corrupted file from tg to phone/pc.

**Comment by anasty17** [comment]
Okay
