### ISSUE TITLE
Sent / Forward some files to bot then return them as zipped file

### ISSUE THREAD

**Issue by vishnoe115** [anasty17/mirror-leech-telegram-bot#829]
Request Add Feature :
List of files that sent / forwarded by the user then returns them as zipped file.

I found related repository for it https://github.com/painor/zip_files_bot

Thanks in advance 🙏

**Comment by anasty17** [comment]
U read to do list ?

**Comment by vishnoe115** [comment]
ohh sorry, my bad. thank you so much
