### ISSUE TITLE
Heroku is banning it!!!

### ISSUE THREAD

**Issue by Targaryenation** [anasty17/mirror-leech-telegram-bot#830]
I'm not a coder and i don't know is there any way to fix this but i'm gonna say it. Those heroku motherfuckers are banning apps.  I mean i fucking used 6 different accounts in this month and they all are banned now. Please add some way to bypass that or something like that. I remember using tortoolkit repo a long time without getting ban (torrenting was ever against salesforce's rules btw). Now tortoolkit is fucked, it ain't getting updates and heroku bans it within 3 minutes. Your repo is the only one which i can use more than a day though. And it would be really really fucking great to see it more stable in heroku so Anas please try to do something if it's possible man.

**Comment by anasty17** [comment]
There is no ban
