### ISSUE TITLE
Add seeding settings feature

### ISSUE THREAD

**Issue by thevazgen** [anasty17/mirror-leech-telegram-bot#832]
There are a lot of good private trackers that don't have freeleech - you gotta seed to leech more! I've noticed that bot very very rare is seeding, but not enough, like only 10mbs.  Would be great to see seed settings where you can select how much bot should seed after leeching torrent. Please do this if it's possible.

**Comment by anasty17** [comment]
Already there if u can read readme

**Comment by thevazgen** [comment]
well, i didn't know. but it's working only for mirroring if i get it right. i need it for leeching to telegram though. guess it's not closed)

**Comment by anasty17** [comment]
Check this issue https://github.com/anasty17/mirror-leech-telegram-bot/issues/791

**Comment by champagnegen** [comment]
Gotcha ty
