### ISSUE TITLE
Mega Bug in master Branch

### ISSUE THREAD

**Issue by jbook1** [anasty17/mirror-leech-telegram-bot#843]
Getting below error while mirroring mega  (I am on latest commit)

app_1  | 2022-08-01 12:05:22,435 - bot - INFO - Fetching Root Node.
app_1  | 2022-08-01 12:05:22,435 - bot - INFO - Node Name: Cloud Drive
app_1  | 2022-08-01 12:05:22,671 - bot - INFO - Checking File/Folder if already in Drive
app_1  | 2022-08-01 12:05:22,672 - bot.helper.mirror_utils.upload_utils.gdriveTools - INFO - Authorizing with 40.json service account
app_1  | Exception in thread Thread-3:
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
app_1  |     self.run()
app_1  |   File "/usr/lib/python3.8/threading.py", line 870, in run
app_1  |     self._target(*self._args, **self._kwargs)
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/mega_downloader.py", line 181, in add_mega_download
app_1  |     executor.do(api.startDownload, (node, path, name, None, False, None))
app_1  |   File "/usr/src/app/bot/helper/mirror_utils/download_utils/mega_downloader.py", line 129, in do
app_1  |     function(*args)
app_1  | TypeError: startDownload() takes from 3 to 4 positional arguments but 7 were given

Test Link : https://mega.nz/file/lO8C3RAZ#Fq6HUzNZMaXP1xCszc0P8FuOZrxXKqrX9UnBhO6mkWk

**Comment by anasty17** [comment]
Delete ur old image and deploy again, next time check commit details, i wrote this fix for new docker.

Check readme how to delete current docker image.
