### ISSUE TITLE
Leech Splitting Causing Ban 

### ISSUE THREAD

**Issue by RealNoobieDrive** [anasty17/mirror-leech-telegram-bot#857]
Splitting phase of leech is causing ban in heroku

**Comment by anasty17** [comment]
I know also yt-dlp when converting to mkv or to mp3

**Comment by RealNoobieDrive** [comment]
is it fixable??

**Comment by anasty17** [comment]
Join official channel

**Comment by RealNoobieDrive** [comment]
i guess after 1.9k star, will be waiting then

**Comment by darsaliq00** [comment]
> Join official channel

can u provide link of ur official channel

**Comment by anasty17** [comment]
In repository description!
