### ISSUE TITLE
[Feature request] Make /sleep command available for telegram groups

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#863]
[Feature request] 
Adding bot to channel and then to group Commands like/qbmirror work but `/sleep` doesn't work?
İf you like the idea could you please consider to make /sleep command work for telegram groups?

**Comment by anasty17** [comment]
I didn't understood, elaborate.

**Comment by erickyun** [comment]
> I didn't understood, elaborate.

The Extra `/sleep` command for Heroku Branch that lets the bot idle does not work in Telegram groups? I'm receiving no response when I try to execute /sleep command in telegram groups?

**Comment by anasty17** [comment]
Show logs!

**Comment by anasty17** [comment]
Ohhh sleep cmd works only for owner or sudo users.
Promote the channel!

**Comment by erickyun** [comment]
> Ohhh sleep cmd works only for owner or sudo users. Promote the channel! /addsudo channel id


So I have the following as

Authorized Chats:
OWNER_ID
channel id
group id
Sudo Users:
OWNER_ID
channel id
group id

but /sleep or /log is still not working in telegram group for me?

**Comment by anasty17** [comment]
No need to add owner id! U should add channel id in sudo

**Comment by erickyun** [comment]
> No need to add owner id! U should add channel id in sudo

I tried it didn't work?

When I try to execute from the **channel** (that is linked to group) `/log /sleep /authorize /addsudo` I'm receiving  **no** respond on the group!
but I'm receiving respond from the follow cmds `/qbcmd /leechcmd /mirrorcmd /ping` they work on channel that is linked to group.

also manually executing directly from the **group** `/log /sleep /authorize /addsudo` works! But my only problem here is that these cmd won't work once I execute them on channel?

**Comment by anasty17** [comment]
Check channel id in ur group

**Comment by erickyun** [comment]
> Check channel id in ur group. Not code issue

I thank you for your help.
I don't know why it isn't working for me but I will try to figure it out. 
Have a nice day sir.

**Comment by anasty17** [comment]
> > Check channel id in ur group. Not code issue
> 
> I thank you for your help. I don't know why it isn't working for me but I will try to figure it out. Have a nice day sir.

![20220806_001548](https://user-images.githubusercontent.com/77075674/183198487-ba32dd40-a668-41f6-a18b-3c22aa3c7872.jpg)

It's working

**Comment by erickyun** [comment]
> > > Check channel id in ur group. Not code issue
> > 
> > 
> > I thank you for your help. I don't know why it isn't working for me but I will try to figure it out. Have a nice day sir.
> 
> ![20220806_001548](https://user-images.githubusercontent.com/77075674/183198487-ba32dd40-a668-41f6-a18b-3c22aa3c7872.jpg)
> 
> It's working

Thank you very much :)
This way worked for me👍🙂
