### ISSUE TITLE
Avoid Data Lost on Heroku Restart!

### ISSUE THREAD

**Issue by ami-ayanbhar** [anasty17/mirror-leech-telegram-bot#864]
My english sucks, so if you don't understand my grammar let me know!

**PROBLEM**
We all know that when the Heroku server restarts, our all tasks such as downloading, uploading, downloaded files (saved on the server) etc gets reset and we lost our progress! because of that we are unable to download slow and big torrents though the bot if specially the bot is running on heroku server right?
⠀
⠀
**Avoid Data Lost on Restarts**
There's only one way to avoid this problem that i could think of. If we download and upload the file at the same time and store task info on external database.

**Download and upload at the same time but how and where? what to do after restart?**
If download and upload at the same time doesn't possible then you need to use a buffer (e.g. 10mb buffer) for uploading or in other words you need to maintain a gap between downloaded and uploaded data. how much downloaded and uploaded, a gap or buffer. (more info at the bottom)
All files going to upload in a temp folder in gdrive and after that when the download gets complete all files going to move to the final destination/folder.
All data, how much data and files uploaded to the server, path of the files, names etc will continuously register/save into the database.
after restart the bot will check the database for previous tasks, how much it's done/uploaded to drive. and starts it again from there where it got stopped/pause.
let me put an example otherwise you will get confused with my grammar.

**Example:**
1. I added a task for mirroring a file. (and using buffer size 10mb)
2. The task got registered into the database & continuously updating it's info (how much it uploaded to the drive, path, filename etc...)
3. Starts the download & reach 10mb (10mb downloaded)
4. Then the uploading got starts and tries to maintain 10mb buffer between downloaded data and uploaded data. (All files are uploading to a temp folder in gdrive)
5. Eventually the server restarts!
6. After restart, the server will check the previous tasks and its info (It's Progress/Uploaded Data on Gdrive and other stuffs) from the database.
7. Added the old tasks again!
8.  The task gets completed and all files gets moved temp folder to main/final folder.
⠀
⠀

**Got it right? A short summary**
1. Store Task's data in External Database 
2. Server Continually Checking The Task's Progress and Updating/Storing it to The Database. 
3. File Downloads & Uploads at The Same Time With a Buffer or Gap and Server Tries to Maintain it. 
4. Files Will Upload to a Temp Folder on Gdrive
5. After Restart Server Will Check Previous Tasks and It's Progress and Readd These Tasks.
6. After Completing, Move All Files Temp Folder to Final/Main Folder.
⠀
⠀
⠀
**With This Trick You Can Also Fix The Limited Storage Issue!**
When a file uploaded to gdrive (temp folder), and it doesn't need anymore then server can automatically delete it for saving space/storage!!!

    **If The Server Delete Files For Saving Space Then How to Seed After Download?**
After Download, The Files Will Just Copy Temp Folder to Final/Main Folder. Files on temp folder not going to delete after complete. After the download and copying process finished, files going to download again to the server and seeding starts!
**Also if possible add a way to seed files that i stopped before. i have few files in gdrive and i want to start seeding those files again. add a option for this pls**

I have plenty more ideas but it will be a lot of work so i, not adding these one. there one feature i want but i will request for it later.

**Comment by ami-ayanbhar** [comment]
you need to just store, user id, task name, source, engine that was using, msg id (source), status msg id, seed after download or not, files that uploaded to gdrive (path and name), files that doesn't complete but haf uploaded to gdrive (path and name) etc... you don't need to store how much data/size* of a file uploaded to drive.
after restart just download haf uploaded files and starts the downloading again!

**Comment by anasty17** [comment]
What is this bro! Just tell me what the feature you want without explaining how. Because no sense of what u said. 
And simply i can say buy vps, without understanding what do u want to avoid from loss.
