### ISSUE TITLE
/List is sending html file instead of telegraph link

### ISSUE THREAD

**Issue by darkmaster420** [anasty17/mirror-leech-telegram-bot#871]
I used /list to search for both files and folders.
I got a html file back 
I am using the latest commit from anas repo
![Screenshot_20220809-180958~2](https://user-images.githubusercontent.com/64340223/183788855-68f5e444-357a-4ad7-8f4a-c12999c5778a.png)
Here's a screenshot

**Comment by anasty17** [comment]
This is feature not bug 😂
Bcz telegraph block some regions
And like this is better than pages u can see all results directly

**Comment by pradeishc** [comment]
Instead of using html file, we can use BASE_URL_OF_BOT

**Comment by anasty17** [comment]
> Instead of using html file, we can use BASE_URL_OF_BOT

I know but why not keeping the file ?
This idea is better

**Comment by pradeishc** [comment]
It's just a idea from my side.

**Comment by anasty17** [comment]
We already think about this. This is the best solution.
