### ISSUE TITLE
stopped due to: name 'path' is not defined

### ISSUE THREAD

**Issue by LilHattaf** [anasty17/mirror-leech-telegram-bot#872]
when im trying to /unzipleech my .zip file from my google drive, this error appear "your download has been stopped due to: name 'path' is not defined", but when i try to do the same thing with other link, its working fine

**Comment by LilHattaf** [comment]
> Which branch ? Send full logs
![image_2022-08-10_17-23-20](https://user-images.githubusercontent.com/104055553/183879630-033c891d-e93d-4a48-81b8-a38563b6a456.png)

only this appear .
idk which branch, but i deployed it on heroku branch

**Comment by anasty17** [comment]
Send link to test. I have tried and no issues

**Comment by LilHattaf** [comment]
![image](https://user-images.githubusercontent.com/104055553/183881723-0fdddd39-38de-4a76-adcd-11de499a572e.png)

**Comment by Parvez342** [comment]
Same problem
It can leech from Google drive folder but not if yougive the file link

**Comment by anasty17** [comment]
> ![image](https://user-images.githubusercontent.com/104055553/183881723-0fdddd39-38de-4a76-adcd-11de499a572e.png)
> 
> https://drive.google.com/uc?id=14iUqu2aYzVhcm1QFZl5YwE9mJSBZAJ98&export=download

Ok got it, will fix and push in 10 minutes

**Comment by LilHattaf** [comment]
> > ![image](https://user-images.githubusercontent.com/104055553/183881723-0fdddd39-38de-4a76-adcd-11de499a572e.png)
> > https://drive.google.com/uc?id=14iUqu2aYzVhcm1QFZl5YwE9mJSBZAJ98&export=download
> 
> Ok got it, will fix and push in 10 minutes

alright sir, thanks

**Comment by anasty17** [comment]
> > > ![image](https://user-images.githubusercontent.com/104055553/183881723-0fdddd39-38de-4a76-adcd-11de499a572e.png)
> > > https://drive.google.com/uc?id=14iUqu2aYzVhcm1QFZl5YwE9mJSBZAJ98&export=download
> > 
> > 
> > Ok got it, will fix and push in 10 minutes
> 
> alright sir, thanks

Fixed try now

**Comment by LilHattaf** [comment]
all working fine sir, thanks for the fix 👍
