### ISSUE TITLE
search with api not working after last commit

### ISSUE THREAD

**Issue by Nobody370** [anasty17/mirror-leech-telegram-bot#881]
**Describe the bug**
search with api not working after last commit
**To Reproduce**
1. Used this Command with this link or file.
2. Before/after/while Upload ..
3. Check logs

**Expected behavior**

**Screenshots**

**Additional context**
https://torrents-api-py3.herokuapp.com
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9302039/log.txt)

**Comment by anasty17** [comment]
@Nobody370 ur api is up to date ?
@junedkh bro i didn't check this.

**Comment by junedkh** [comment]
@Nobody370 update your api
Or you can use https://api.jmdkh.eu.org

**Comment by anasty17** [comment]
Use the python api latest version. Old api doesn't support all sites

**Comment by Nobody370** [comment]
Thanks 👌
