### ISSUE TITLE
DockerFile Config is Not Working in Oracle VPS

### ISSUE THREAD

**Issue by rkrurmc2** [anasty17/mirror-leech-telegram-bot#885]
Docker Image Support for Linux amd64, arm64/v8, arm/v7, s390x is not working on Oracle VPS, I already try all of them.

Anasty17/mltb:latest — setting is working though but seeding torrent file is not working.

**Comment by anasty17** [comment]
Now u have reported 2 different things! 
U said docker not working for oracle then how u saying that seeding not working and how u know if seeding working or not
