### ISSUE TITLE
List

### ISSUE THREAD

**Issue by Tysonmovierulz** [anasty17/mirror-leech-telegram-bot#889]
**Is your feature request related to a problem? Please describe.**
A In Your New Update When we list command to search Anything In Drive it sending as html file.users are irritating with that.They need to download that file and open it.Sometimes Browsers sucks,So opening the html file is not possible. 

**Describe alternatives you've considered**
A Instead of Sending html file,bot can create A pop up page like status.

**Additional context**
I am attaching an image for this...

I am Just Asking For a feature like this.If I asked anything wrong then ignore it.
Please try to add like this if you found it will be helpful for all.
[List](https://te.legra.ph/file/b99fb80cc44ec00773543.jpg)

**Comment by anasty17** [comment]
Users ! This not supergroup bot. This possible sure but u need to press next maybe too many time to get what u want, so html file with small scroll can see almost all results in front of u. And u can keep it forever. With bot msg u can't keep them. Telegraph was the best choice btw them but creating account and pages or edit pages can't done anymore in some regions.
