### ISSUE TITLE
Status Paused

### ISSUE THREAD

**Issue by Tysonmovierulz** [anasty17/mirror-leech-telegram-bot#895]
After Downloading the torrent 100% status is paused.Dont Know why .There is no error in logs but Sometimes it happening.please Solve this issue Sir!

**Comment by anasty17** [comment]
Send logs even if nothing in logs! Who told its an issue to say solve it!

**Comment by Tysonmovierulz** [comment]
I will send but I am busy now....I will send as early as possible..
