### ISSUE TITLE
Suggestion for yt-dlp

### ISSUE THREAD

**Issue by Lucif3rHun1** [anasty17/mirror-leech-telegram-bot#908]
**Is your feature request related to a problem? Please describe.**
When I have to leech multiple yt-dlp supported videos, I have to choose quality each time.

**Describe the solution you'd like**
The solution goes as… the buttons would be displayed(if and when I would want in another quality) otherwise after the timeout it will be choose the pre defined quality by the user and download the videos.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anasty17** [comment]
No i will add it to user settings soon, or u can add it by perfix. Already in todo
