### ISSUE TITLE
Issue with /leechwatch…

### ISSUE THREAD

**Issue by Lucif3rHun1** [anasty17/mirror-leech-telegram-bot#909]
**Describe the bug**
I am on the latest commit which was made 8 hours ago. I am not able to use /leechwatch for some reason.

**To Reproduce**
1. /leechwatch https://youtu.be/-EyD2yBqlcQ
2. Just restarted the bot and did it.
3. Log is empty… https://telegra.ph/file/681bafb186f8e2baf6f88.jpg

**Expected behavior**
It should have started leeching.

**Screenshots**
https://telegra.ph/file/041d4a3bdeb68eeb1e9cc.jpg

**Additional context**

**Comment by anasty17** [comment]
Use /help cmds changes
