### ISSUE TITLE
All of my RSS feed gets deleted when /sleep is used

### ISSUE THREAD

**Issue by erickyun** [anasty17/mirror-leech-telegram-bot#913]
**Describe the bug**
Hi,
When I execute `/sleep` command and wake up the bot after sometime. 
My subscribed rss feed gets empty?
When I execute `/rl` to check my subscribed rss feed it says "No subscriptions"

**To Reproduce**
1. Used this Command with this link or file.
`/sleep`
2. Before/after/while Upload ..
after bot is waked up with BASE_URL_OF_BOT from heroku
3. Check logs

**Expected behavior**
"To not lost subscribed rss feed."

**Screenshots**

**Additional context**

**Comment by anasty17** [comment]
/sleep not related to any error. It just stop the ping!
Check ur database and next time send logs before and after

**Comment by erickyun** [comment]
My bad sorry. İt seems when I remove `SEARCH_API_LINK` it worked fine.

[log when sleep used.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9337805/log.when.sleep.used.txt)

[log after wake up.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9337806/log.after.wake.up.txt)

**Comment by anasty17** [comment]
It's not related to search api link

**Comment by anasty17** [comment]
Just update ur search api to latest from source code
