### ISSUE TITLE
Suggestion: Use short& concise about/bio for the project.

### ISSUE THREAD

**Issue by ronin08** [anasty17/mirror-leech-telegram-bot#924]
**Is your feature request related to a problem? Please describe.**
Current bio is too long and makes for a bad impression. There should be short and professional bio. Features and other details are best to be described in readme. 

**Describe the solution you'd like**
Suggestion: ```A Telegram bot to mirror various metalinks to Google Drive. See features for more details.```

**Comment by anasty17** [comment]
Thanks I'm ok with this
