### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by everettheidenreich** [anasty17/mirror-leech-telegram-bot#925]
Mirror leech line 87 : use file_ = reply_to.document or reply_to.video or reply_to.audio or  reply_to.photo

Your are import inlinereplymarkup everywhere just import in Button build and change the last line of build_menu to return inlinereplymarkup(menu) and remove import in other files

**Comment by anasty17** [comment]
How first paragraph related to the 2nd ?
Yeah better pr if u want.

**Comment by nadarsurya** [comment]
No both are different 
In mirror leech 87 you are using for loop 
Just use 
file_ = reply_to.document or reply_to.video or reply_to.audio or reply_to.photo

and 2nd one 
![IMG_20220818_014038](https://user-images.githubusercontent.com/47964646/185233687-25d0b72b-646a-4433-869e-e69b95220557.jpg)

We call build menu with inlinereplymarkup if we import inlinereplymarkup in button_build.py we no need to import everywhere and can just call build_menu() for creating button

**Comment by everettheidenreich** [comment]
No both are different
In mirror leech line 87 you are using for loop 
Just use 
use file_ = reply_to.document or reply_to.video or reply_to.audio or reply_to.photo

![IMG_20220818_014038](https://user-images.githubusercontent.com/111451860/185235490-0533ec90-3487-4267-aac6-f0a133e1f63d.jpg)

We are call build_menu with inlinereplymarkup in everywhere if we import inlinereplymarkup in build_menu.py we can just call build_menu for button build

**Comment by anasty17** [comment]
Thanks, Yeah i got what u meant. But too much things i still optimize the repo one by one. If u would like to pull request, also in tg_downloader_helper.py

**Comment by anasty17** [comment]
But if u want to open pull request u should handle all of them is None or for reply.photo return [] empty list as i remember so need some changes also. I wamt to open pr let me know please

**Comment by everettheidenreich** [comment]
Sorry for late reply anas , i see you are done everything
