### ISSUE TITLE
error on qbittorrent

### ISSUE THREAD

**Issue by Nobody370** [anasty17/mirror-leech-telegram-bot#926]
**Describe the bug**

**To Reproduce**
1. Used this Command with this link or file.
2. Before/after/while Upload ..
3. Check logs

**Expected behavior**

**Screenshots**

**Additional context**
[aqueus-helmet-1324-logs-1660786913026.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9366980/aqueus-helmet-1324-logs-1660786913026.txt)

**Comment by anasty17** [comment]
Just restart the bot and don't abuse. 
This normally happens after u hit restart and after restart everything should be fine
