### ISSUE TITLE
Last-api

### ISSUE THREAD

**Issue by GarouTheDevil** [anasty17/mirror-leech-telegram-bot#929]
FileNotFoundError: [Errno 2] No such file or directory: 'last-api'
2022-08-18T13:23:18.602479+00:00 app[web.1]: 2022-08-18 13:23:18,602 - asyncio - ERROR - Unclosed client session

Error Occuring While Deploying, I Am Heroku User

**Comment by anasty17** [comment]
Update ur code!

**Comment by GarouTheDevil** [comment]
> code 
Heroku Branch Shows It Is Up To Date

**Comment by anasty17** [comment]
> > code
> > Heroku Branch Shows It Is Up To Date

Idk ! Refork again. I can't follow each one sync problem
