### ISSUE TITLE
Leech upload channel?

### ISSUE THREAD

**Issue by svampebobber** [anasty17/mirror-leech-telegram-bot#939]
Sup anas, love your work. Can we get an feature added where bot will upload to an organized channel instead of just in chat? The files get filled up in messages

**Comment by anasty17** [comment]
Ok but no pm and no user settings for this. It will be for personal use only

**Comment by dox-on** [comment]
> Ok but no pm and no user settings for this. It will be for personal use only

Could you add file stream feature ?

**Comment by svampebobber** [comment]
> Ok but no pm and no user settings for this. It will be for personal use only

Yes its for personal use only, i just want to organize everything

**Comment by anasty17** [comment]
> > Ok but no pm and no user settings for this. It will be for personal use only
> 
> Could you add file stream feature ?

U mean tg index?

**Comment by dox-on** [comment]
> 
> U mean tg index?

Idk about that, Streamable link from uploaded file [base repo](https://github.com/EverythingSuckz/TG-FileStreamBot)

**Comment by anasty17** [comment]
Yeah soon, i didn't tey it yet so i didn't add it in to do list

**Comment by svampebobber** [comment]
it has been done in this repo https://github.com/arshsisodiya/helios-mirror but i like yours more, since you are the creator of it all kinda

**Comment by anasty17** [comment]
Don't share any bad stuff here

**Comment by anasty17** [comment]
Done
