### ISSUE TITLE
Problem On File Already Found Search Results

### ISSUE THREAD

**Issue by noobrom** [anasty17/mirror-leech-telegram-bot#941]
![Screenshot_20220819-152748_Telegram](https://user-images.githubusercontent.com/109625726/185589392-04970657-edb7-4c3c-9c25-bf59808c2fd5.png)
**Describe the bug**

**To Reproduce**
1. Used this Command with this link or file.
2. Before/after/while Upload ..
3. Check logs

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by svampebobber** [comment]
it means it is already in your google drive. Read the readme

**Comment by anasty17** [comment]
Telegraph removed. Open this html file to see the results
