### ISSUE TITLE
Mirroring stuck on Upload 

### ISSUE THREAD

**Issue by kyash4** [anasty17/mirror-leech-telegram-bot#943]
When i was doing mirroring, it is stucking while uploading to gdrive

![image](https://user-images.githubusercontent.com/96533520/185604069-08b08155-02b2-4638-8397-d0a1318900bc.png)

Now time is 4:27 PM IST GMT - 5:30+ when i am writing this issue and i also restarted my bot once
I had put unzip mirroring of size of 399.12 MB at 04:18 PM IST GMT - 5:30+ now it's almost 9 mins

**Comment by anasty17** [comment]
Send logs!

**Comment by kyash4** [comment]
[log.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9381656/log.txt)

**Comment by anasty17** [comment]
I guess there are too many small files uploading that's it just wait

**Comment by kyash4** [comment]
but it's now 04:46 PM IST GMT - 5:30+ but file isn't uploaded till yet
