### ISSUE TITLE
Bot not starting

### ISSUE THREAD

**Issue by ronin08** [anasty17/mirror-leech-telegram-bot#947]
**Describe the bug**
Bot is crashing at the start.

**To Reproduce**
Just use the latest commit and start the bot

**Expected behavior**
Bot should start without any problem.

**Screenshots**

**Additional context**
Log file: 
[heroku.txt](https://github.com/anasty17/mirror-leech-telegram-bot/files/9383698/stable08-logs-1660925457525.txt)

**Comment by carolynsteeves1** [comment]
delete repo and refork. Then redeploy

**Comment by anasty17** [comment]
Deploy with the official docker
