### ISSUE TITLE
Search To TG Itself

### ISSUE THREAD

**Issue by OmiduSithul** [anasty17/mirror-leech-telegram-bot#954]
Hi Anas, hope you doing good, I would like to request you to add the search feature to upload to the tg itself without the html cz a lot of guys don't like it because when we tried to open it, a warn comes from tg saying that "The owner of this file can get access to your IP address". Also it is very neat and clean to use this method rather than the html search. You can you this [repo](https://github.com/TheHamkerCat/GdriveSearcherBot) to get an understanding. Hope you would accept my request.

**Comment by anasty17** [comment]
What! Who guys! Which warning!
