### ISSUE TITLE
m3u8

### ISSUE THREAD

**Issue by AndresCrepine** [anasty17/mirror-leech-telegram-bot#960]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Hello, I would like to know if it is possible to add an option to download .m3u8, because when I try to do it, I get the following error: The response status is not successful. status=403
However, with bots that are public, it does.

**Describe alternatives you've considered**
Maybe FFmpeg?

**Additional context**
Already described

**Comment by anasty17** [comment]
Use yt-dlp!

**Comment by AndresCrepine** [comment]
I am not familiar with YT-DLP, but with FFmpeg. I know that to download from a .m3u8 file, you should put `ffmpeg -i "ulr m3u8" -c copy -bsf:a aac_adtstoasc "name.mp4"`, but again, I would like to know if it is possible to be added to this repository.
I have tried too with /ytdl but I get this error:
ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by  HTTPError 403: 'Forbidden' ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by anasty17** [comment]
Then check what 403 http error correspond to

**Comment by AndresCrepine** [comment]
Forget it, I tried `external_downloader` and `hls_prefer_native`, but that didn't work either.
