### ISSUE TITLE
Torrent search plugin doesn't work accurately.

### ISSUE THREAD

**Issue by MinorX** [anasty17/mirror-leech-telegram-bot#961]
![IMG_20220820_201134](https://user-images.githubusercontent.com/90025330/185752063-49af2984-f9d0-4129-9f51-391f633b9013.jpg)

Hey Anas, Hope you're doing fine 😀!
I've attached a screenshot for the torrents searched by the plugins.
When I search for some torrent(s). It always shows something else than asked for. 
Is there any way to make it more accurate so that it only shows me what I want and doesn't show torrents random!!!

Thanks 🙏

**Comment by anasty17** [comment]
I can't control qBit-plugins, try to add/remove plugins as u wish
