### ISSUE TITLE
Question: How to use [ /btsel - select files from torrent ] ?

### ISSUE THREAD

**Issue by nareshroy8520** [anasty17/mirror-leech-telegram-bot#968]
How to use /btsel ?
I tried by adding magnet link next to command like [ /btsel <magnet link> ] but it says [ GID <magnet link> not found. ]

![Screenshot 2022-08-22 113035](https://user-images.githubusercontent.com/96655209/185849825-af78c7fa-1ffe-4d08-8f3e-086a254cc180.jpg)

Plz help me with this. & also is it really used to download only selected files from torrent or its something else ?
Thanks

**Comment by anasty17** [comment]
It's like cancel cmd! U can with gid or by reply
