### ISSUE TITLE
Error in MKV split

### ISSUE THREAD

**Issue by shin-bedo** [anasty17/mirror-leech-telegram-bot#972]
Branch: master
Full logs: https://katb.in/agigaqojepa

Used cmd: /leech
Used link: https://go.savagermz.workers.dev/0:/SuriyaBali%202%20The%20Immortal%20Stone%20of%20Nirvana%20%7B2020%7D%201080p%20WEB-DL%20Hindi%20Chinese%20AAC%202.0%20%5BJOHAL~JATT%5D%20Telly%20Mkv

Deployed few minutes ago after last update.

**Comment by anasty17** [comment]
Mostly issue from the file

**Comment by anasty17** [comment]
Bro seems no extension in name . Use rename and add extension .mkv
