### ISSUE TITLE
ModuleNotFoundError: No module named 'megasdkrestclient'

### ISSUE THREAD

**Issue by AyushIyankan** [anasty17/mirror-leech-telegram-bot#973]
What can be the issue?

![Screenshot 2022-08-23 at 03-08-36 mrxtorrent · Logs Heroku](https://user-images.githubusercontent.com/75990868/186023611-2eafc60a-ed56-4ec3-8494-957874a4a7ba.png)

**Comment by anasty17** [comment]
Deploy heroku branch follow readme

**Comment by AyushIyankan** [comment]
Okay
