### ISSUE TITLE
bug downloading pdf as exe

### ISSUE THREAD

**Issue by rinrinx2** [anasty17/mirror-leech-telegram-bot#975]
unfortunately, pdf files are uploaded to telegram as exe files, despite many attempts, they still load the same way.

![Screenshot_20220823-091945_Telegram](https://user-images.githubusercontent.com/58888200/186084887-b975480c-5e4a-4ad2-a23a-6b09ec51e601.jpg)

**Comment by anasty17** [comment]
I didn't got u

**Comment by rinrinx2** [comment]
https://drive.google.com/file/d/1YAQBpPLjeFkEEuxIGUdCgrk-LvQp1jMQ/view?usp=drivesdk

Brother download the pdf file on this link. Bot is loading the pdf file as a telegrama exe file, this error is only available in pdf files

**Comment by anasty17** [comment]
This file have no extension!

**Comment by anasty17** [comment]
Use rename feature!
