### ISSUE TITLE
Separate use of bot session & user session

### ISSUE THREAD

**Issue by Dale-Jab** [anasty17/mirror-leech-telegram-bot#976]
Hello Sir,

If possibe please add a ability that bot will use __bot session__ if the file size is less than 2GB and it will use __user session__ if the file size is bigger than 2GB.

Reason behind this enhancement request is bot session is very fast in speed (upto 40MBps) and user session is very slow (10MBps or less)

**Comment by anasty17** [comment]
User session is slow! Premium Account and slow then change ur server location! Ur account dc ?

**Comment by anasty17** [comment]
In ur case yeah but it's not good for others.
