### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by I-Am-HappyBoy** [anasty17/mirror-leech-telegram-bot#977]
Sir, Is It Possible To Add https://usersdrive.com/g7oru9abx74h.html This Site On Your Repo..?

Neither, Userdrive DDL Links Or File/Page Url Are Supported For Mirror/Leech.

Sir, If You Can Add This It will Really Helpful To Download Those Stuffs...

**Comment by anasty17** [comment]
I don't think i will add these stuff maybe i can accept pr only. Because it's endless thing there are hundreds of sites like this. If each will will ask for one it will be endless.
