### ISSUE TITLE
Bug in Leech Settings

### ISSUE THREAD

**Issue by adamgilli** [anasty17/mirror-leech-telegram-bot#978]
**Describe the bug**
When Leech Type is set as MEDIA in Leech Settings, .mp3 and .m4b files are sent as video instead of streamable audio files. 
**To Reproduce**
Try to leech any .mp3/.m4b file after setting leech type to media

**Expected behavior**
A stramable audio file needs to be sent instead of video

**Screenshots**
<img width="337" alt="image" src="https://user-images.githubusercontent.com/38134797/186299942-4ba9c599-820b-48e9-a063-0d276d8f8409.png">
Earlier, before few updated

<img width="340" alt="image" src="https://user-images.githubusercontent.com/38134797/186300008-66e9f16c-1d49-4ffd-828e-44497cee7356.png">
Now

**Comment by anasty17** [comment]
Send link

**Comment by anasty17** [comment]
![Screenshot_20220824-072550_Plus](https://user-images.githubusercontent.com/77075674/186328723-1cce6eb6-7cc4-41db-a477-8733d3a340e0.jpg)

**Comment by adamgilli** [comment]
> Send link

.m4b file https://oi-link.herokuapp.com/dl/0/Love%20on%20the%20Brain%20%28The%20Love%20Hypothesis%20%232%29%20%28Unabridged%29.m4b

.mp3 file https://oi-link.herokuapp.com/dl/0/My%20Sister%27s%20Big%20Fat%20Indian%20Wedding.mp3

![image](https://user-images.githubusercontent.com/38134797/186330951-2ccc129d-3843-4718-933a-9e44adc818c3.png)
My output while trying to leech both these files. They are sent as video

**Comment by anasty17** [comment]
Ok i will fix this soon

**Comment by anasty17** [comment]
Fixed

**Comment by anasty17** [comment]
I revert some of that commit ... that m4b file contains motion mjpeg. And it's video not audio only
