### ISSUE TITLE
bot not removing .torrent files from working dir

### ISSUE THREAD

**Issue by hitesh920-1** [anasty17/mirror-leech-telegram-bot#979]
Describe the bug
i have hosted my bot in vps, repo is 100% og with no edit.
when i mirror/leech direct download link of a .torrent file using qb, bot basically download that .torrent file in "/usr/src/app" even though my DOWNLOAD_DIR is "/usr/src/app/downloads" and after mirror/leech complete, bot not removing that .torrent file from working dir "/usr/src/app"

To Reproduce
1. use master branch and try mirror/leech this link https://linuxmint.com/torrents/linuxmint-21-cinnamon-64bit.iso.torrent using qb
2. after file upload, check working dir by /shell ls

Expected behavior
bot should download .torrent files in downloads dir and should remove that file after qb mirror/leech done.

Screenshots
![image](https://user-images.githubusercontent.com/71580009/185926318-3cb3e68f-f852-4182-959e-66c1de276cb2.png)

Additional context

**Comment by anasty17** [comment]
That's right 👍. I will fix this soon

**Comment by anasty17** [comment]
Fixed

**Comment by hitesh920-1** [comment]
> Fixed

thanx
