### ISSUE TITLE
Stop Duplicate for Gdtot

### ISSUE THREAD

**Issue by rahul112kapoor** [anasty17/mirror-leech-telegram-bot#98]
Kindly add Stop duplicate for gdtot content

**Comment by anasty17** [comment]
I guess u didn't test

**Comment by rahul112kapoor** [comment]
> I guess u didn't test

I did but does it stops before using cookies..?
As google gives Only 750gb upload limit for 24 hours

**Comment by anasty17** [comment]
No

**Comment by rahul112kapoor** [comment]
> No

Please implement that ... It will be helpful
