### ISSUE TITLE
ytdl in newer versions is not working correctly

### ISSUE THREAD

**Issue by champagnegen** [anasty17/mirror-leech-telegram-bot#980]
I have couple bots with your repo and not all of em are up to date. I tried to download a youtube playlist with recently deployed one (zipped in 1080p) and it successfully downloaded all the videos but none of them had audio. Tried the same playlist with the same quality with older one and guess what, everything was perfect. What's the problem tho? Are we downgrading or what? lmao

**Comment by anasty17** [comment]
Update ur repo this issue already fixed! U r not up to date!
