### ISSUE TITLE
Rss - Auto downloading not working. [Heroku Branch]

### ISSUE THREAD

**Issue by MinorX** [anasty17/mirror-leech-telegram-bot#981]
Hey Anas ,

I've been trying to set up the rss auto downloading. Basically i just put the channel ID and then link that channel to group with the command to do so. However it is not working as it should (The same method worked for just once and was perfectly working. But not anymore). My RSS feed links are working because I'm using another bot to verify it ( @rss2tg_bot ). The chat ID is verified. The rss command is working. The RSS USER SESSIONS STRING. Database url has also been set up. All these variables have been set up and verified a million times. 

After all this and retrying thousands of times it's not working. The bot isn't even fetching the rss feeds automatically, though the /rssget particularly is working.
 
I'm attaching the logs. Thanks. 
 [           Heroku Logs
](https://pastebin.com/bdqbaem9)

**Comment by MinorX** [comment]
Please help me with this issue. 🙏

**Comment by anasty17** [comment]
RSS_USER_SESSION_STRING, issue from it. Make sure it's generated from pyrogram v2 or greater

**Comment by MinorX** [comment]
It seems to work for now 😃. Thanks 🙏👍🏻
