### ISSUE TITLE
Exclude filter for rss?

### ISSUE THREAD

**Issue by MinorX** [anasty17/mirror-leech-telegram-bot#982]
Hey Anas. 

The rss has a filter to include only those feeds which has certain words. And it's a nice feature to have.
What I was wondering is that , is there any way to exclude certain words from the RSS FEED? Like exclude XXX  💀.

THANKS 😃😃

**Comment by anasty17** [comment]
Ok but no eta

**Comment by MinorX** [comment]
Woah! Thanks man. Appreciate it. ❤️

**Comment by anasty17** [comment]
Added in to do list
