### ISSUE TITLE
Instagram ytdlp error

### ISSUE THREAD

**Issue by Aswin-coder** [anasty17/mirror-leech-telegram-bot#983]
When I try to download Instagram post it shows like
@username ERROR: [Instagram] ChG0onlKM4: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by  HTTPError 400: 'Bad Request' ); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

**Comment by anasty17** [comment]
Report to yt-dlp
