### ISSUE TITLE
Heroku alternative

### ISSUE THREAD

**Issue by elricariocco** [anasty17/mirror-leech-telegram-bot#984]
Hello Anas, this a suggestion so you consider Render.com as potential alternative to heroku. As shown in the pics below, bot can be deployed there (I deployed heroku branch). However in previous attempts account would get banned when mirroring, I have not mirrored anything this time so I can show you these pictures. Hopefully this will grab your attention and if you have time you can test and apply a bypass for this site.
This site is free https://render.com/docs/free#free-web-services   

![image](https://user-images.githubusercontent.com/91217900/186744266-0af7960a-58ff-4609-9d78-8d3950292585.png)

![image](https://user-images.githubusercontent.com/91217900/186744819-9369c237-cb5a-4230-a38b-245d3c595983.png)

**Comment by anasty17** [comment]
I guess this repository already banned lol.

**Comment by anasty17** [comment]
If u are trying with heroku branch then try to mirror

**Comment by anasty17** [comment]
I was testing from phone now, repository name is banned will get error 'there's an error above. Please fix ro continue'.
The account will get banned after deploy branch have code files like master.
The only way to ise UPSTREAM_REPO like heroku. This for now.

**Comment by anasty17** [comment]
Nuh it's shit, very slow response

**Comment by svampebobber** [comment]
why is render bad? Slow perfomance?
