### ISSUE TITLE
Deploy the bot on fly.io 

### ISSUE THREAD

**Issue by Karen-Aijo** [anasty17/mirror-leech-telegram-bot#985]
**Possible free bot implementation site.**
_I don't speak English, sorry if what I am about to say is badly explained or written._ 

But since Heroku will remove free accounts, you could create a mirror-leech-telegram-bot implementation on [fly.io](https://fly.io/) like @TheCaduceus did with his [CloneBot](https://github.com/TheCaduceus/CloneBot_V2).

A tutorial on how to implement it would also be good.

**Thank you very much for your work**

**Comment by anasty17** [comment]
Storage ? 🙃

**Comment by TheCaduceus** [comment]
@anasty17 Damn! It is not for MLTB, only ptovides 7GB Storage and 100GB Bandwidth.

**Comment by svampebobber** [comment]
1gb storage anas, it isnt worth it lol.

**Comment by idkimnoonesoignoreme** [comment]
Can't we save files directly to Google drive using [rclone mount](https://rclone.org/commands/rclone_mount/)?

**Comment by eyMarv** [comment]
> Can't we save files directly to Google drive using [rclone mount](https://rclone.org/commands/rclone_mount/)?

You're welcome to do that, if you want 2mb/s download and even worse upload speed.
