### ISSUE TITLE
Support divio.com

### ISSUE THREAD

**Issue by nodirhajiev** [anasty17/mirror-leech-telegram-bot#989]
![image](https://user-images.githubusercontent.com/38133441/186964342-c34a8fde-9baf-4d31-83bc-e3bfd1433d72.png)
Hi. Soon Heroku will close all free apps. Could you make MLTB compatible with free divio cloud. It's screenshot of bot which deployed on divio.

**Comment by SpectrexD** [comment]
![Screenshot_20220826-211402_MDGram](https://user-images.githubusercontent.com/100960266/186966748-e3740812-71e6-420b-b1cc-97d890a63188.png ??

**Comment by SpectrexD** [comment]
How you have 1 TB disk and 15gb memory

**Comment by nodirhajiev** [comment]
> ![image](https://user-images.githubusercontent.com/38133441/186964342-c34a8fde-9baf-4d31-83bc-e3bfd1433d72.png) Hi. Soon Heroku will close all free apps. Could you make MLTB compatible with free divio cloud. It's screenshot of bot which deployed on divio.

It's real ss of divio cloud

**Comment by SpectrexD** [comment]
Dude check the screen shot wen ?

**Comment by SpectrexD** [comment]
512 MB application memory

5 GB object storage

✓5 GB backup space

10 GB transfer per month

**Comment by nodirhajiev** [comment]
> 512 MB application memory
> 
> 5 GB object storage
> 
> ✓5 GB backup space
> 
> 10 GB transfer per month

I see. But try and check urself from bot

**Comment by nodirhajiev** [comment]
https://t.me/diviotestbot
