### ISSUE TITLE
Fastest way to backup Tg to Gdrive. 

### ISSUE THREAD

**Issue by ketela7** [anasty17/mirror-leech-telegram-bot#992]
I want to backup media from Telegram to Gdrive.
reply media with /cmd one by one is not good idea,
how with `/cmd start_msg_id end_msg_id` ??
I hope there is a fastest way for this, thank's

**Comment by anasty17** [comment]
Use multi link

**Comment by ketela7** [comment]
whats??
i know this leech can download with multiple links, what about the media(s) from telegram??

**Comment by anasty17** [comment]
Read i wrote link/file!
