### ISSUE TITLE
Heroku Alternatives

### ISSUE THREAD

**Issue by peru194** [anasty17/mirror-leech-telegram-bot#999]
As You Know That Heroku Is Going To Stop Free Dynos. Plz Provide Alternative Platform.

Check This Video : https://www.youtube.com/watch?v=GnoKN48PA6k

**Comment by vikas5914** [comment]
Buy a VPS

**Comment by MrZimp** [comment]
> Buy a VPS

The problem with that is you cant, they have your info i havent find one that accept crypto and finding one that allows p2p is just as hard, and..... i mean get a seedbox if you gonna pay anyway.
